
[MaskCircle90]
Shape=Ellipse 44.99999999999999,44.99999999999999,43.95833333333334 | Fill LinearGradient MyFillGradient | StrokeWidth 0
AntiAlias=1
DynamicVariables=1
UpdateDivider=-1

[MaskHexagon90]
Shape=Path Path1 | Fill LinearGradient MyFillGradient | StrokeWidth 0
Path1=83.069,66.979 | LineTo 45,88.958 | LineTo 6.931,66.979 | LineTo 6.931,23.02 | LineTo 45,1.041 | LineTo 83.069,23.02 | ClosePath 1
AntiAlias=1
DynamicVariables=1
UpdateDivider=-1

[MaskSquare90]
Shape=Path Path1 | Fill LinearGradient MyFillGradient | StrokeWidth 0
Path1=1.042,45 | LineTo 45,1.042 | LineTo 88.958,45 | LineTo 45,88.958 | LineTo 1.042,45 | ClosePath 1
AntiAlias=1
DynamicVariables=1
UpdateDivider=-1
