[Variables]

; Options
IconHeight=90
MaskWH=8100
MaskOffsetXY=45
ShapeGradientAngle=0

; ============================================================
; Adobe
; ============================================================

AfterEffectsShape=Hexagon
AfterEffectsMask=Regular Hexagon
AfterEffectsMaskBase=255,255,255
AfterEffectsShapeGradient1Base=172,77,64
AfterEffectsShapeGradient2Base=64,77,172
AfterEffectsRegularHidden=1

AnimateShape=Hexagon
AnimateMask=Regular Hexagon
AnimateMaskBase=255,255,255
AnimateShapeGradient1Base=172,77,64
AnimateShapeGradient2Base=64,77,172
AnimateRegularHidden=1

AuditionShape=Hexagon
AuditionMask=Regular Hexagon
AuditionMaskBase=255,255,255
AuditionShapeGradient1Base=172,77,64
AuditionShapeGradient2Base=64,77,172
AuditionRegularHidden=1

BridgeShape=Hexagon
BridgeMask=Regular Hexagon
BridgeMaskBase=255,255,255
BridgeShapeGradient1Base=172,77,64
BridgeShapeGradient2Base=64,77,172
BridgeRegularHidden=1

CreativeShape=Hexagon
CreativeMask=Regular Hexagon
CreativeMaskBase=255,255,255
CreativeShapeGradient1Base=172,77,64
CreativeShapeGradient2Base=64,77,172
CreativeRegularHidden=1

DreamweaverShape=Hexagon
DreamweaverMask=Regular Hexagon
DreamweaverMaskBase=255,255,255
DreamweaverShapeGradient1Base=172,77,64
DreamweaverShapeGradient2Base=64,77,172
DreamweaverRegularHidden=1

FramemakerShape=Hexagon
FramemakerMask=Regular Hexagon
FramemakerMaskBase=255,255,255
FramemakerShapeGradient1Base=172,77,64
FramemakerShapeGradient2Base=64,77,172
FramemakerRegularHidden=1

IllustratorShape=Hexagon
IllustratorMask=Regular Hexagon
IllustratorMaskBase=255,255,255
IllustratorShapeGradient1Base=172,77,64
IllustratorShapeGradient2Base=64,77,172
IllustratorRegularHidden=1

InDesignShape=Hexagon
InDesignMask=Regular Hexagon
InDesignMaskBase=255,255,255
InDesignShapeGradient1Base=172,77,64
InDesignShapeGradient2Base=64,77,172
InDesignRegularHidden=1

LightroomShape=Hexagon
LightroomMask=Regular Hexagon
LightroomMaskBase=255,255,255
LightroomShapeGradient1Base=172,77,64
LightroomShapeGradient2Base=64,77,172
LightroomRegularHidden=1

PhotoshopShape=Hexagon
PhotoshopMask=Regular Hexagon
PhotoshopMaskBase=255,255,255
PhotoshopShapeGradient1Base=172,77,64
PhotoshopShapeGradient2Base=64,77,172
PhotoshopRegularHidden=1

PremiereShape=Hexagon
PremiereMask=Regular Hexagon
PremiereMaskBase=255,255,255
PremiereShapeGradient1Base=172,77,64
PremiereShapeGradient2Base=64,77,172
PremiereRegularHidden=1

XDShape=Hexagon
XDMask=Regular Hexagon
XDMaskBase=255,255,255
XDShapeGradient1Base=172,77,64
XDShapeGradient2Base=64,77,172
XDRegularHidden=1

; ============================================================
; Browsing
; ============================================================

BraveShape=Hexagon
BraveMask=Regular Hexagon
BraveMaskBase=255,255,255
BraveShapeGradient1Base=172,77,64
BraveShapeGradient2Base=64,77,172
BraveRegularHidden=1

ChromeShape=Hexagon
ChromeMask=Regular Hexagon
ChromeMaskBase=255,255,255
ChromeShapeGradient1Base=172,77,64
ChromeShapeGradient2Base=64,77,172
ChromeRegularHidden=1

EdgeShape=Hexagon
EdgeMask=Regular Hexagon
EdgeMaskBase=255,255,255
EdgeShapeGradient1Base=172,77,64
EdgeShapeGradient2Base=64,77,172
EdgeRegularHidden=1

FirefoxShape=Hexagon
FirefoxMask=Regular Hexagon
FirefoxMaskBase=255,255,255
FirefoxShapeGradient1Base=172,77,64
FirefoxShapeGradient2Base=64,77,172
FirefoxRegularHidden=1

OperaShape=Hexagon
OperaMask=Regular Hexagon
OperaMaskBase=255,255,255
OperaShapeGradient1Base=172,77,64
OperaShapeGradient2Base=64,77,172
OperaRegularHidden=1

OperaGXShape=Hexagon
OperaGXMask=Regular Hexagon
OperaGXMaskBase=255,255,255
OperaGXShapeGradient1Base=172,77,64
OperaGXShapeGradient2Base=64,77,172
OperaGXRegularHidden=1

SafariShape=Hexagon
SafariMask=Regular Hexagon
SafariMaskBase=255,255,255
SafariShapeGradient1Base=172,77,64
SafariShapeGradient2Base=64,77,172
SafariRegularHidden=1

VivaldiShape=Hexagon
VivaldiMask=Regular Hexagon
VivaldiMaskBase=255,255,255
VivaldiShapeGradient1Base=172,77,64
VivaldiShapeGradient2Base=64,77,172
VivaldiRegularHidden=1

; ============================================================
; Elgato
; ============================================================

4KCUShape=Hexagon
4KCUMask=Regular Hexagon
4KCUMaskBase=255,255,255
4KCUShapeGradient1Base=172,77,64
4KCUShapeGradient2Base=64,77,172
4KCURegularHidden=1

CameraHubShape=Hexagon
CameraHubMask=Regular Hexagon
CameraHubMaskBase=255,255,255
CameraHubShapeGradient1Base=172,77,64
CameraHubShapeGradient2Base=64,77,172
CameraHubRegularHidden=1

ControlCenterShape=Hexagon
ControlCenterMask=Regular Hexagon
ControlCenterMaskBase=255,255,255
ControlCenterShapeGradient1Base=172,77,64
ControlCenterShapeGradient2Base=64,77,172
ControlCenterRegularHidden=1

GameCaptureShape=Hexagon
GameCaptureMask=Regular Hexagon
GameCaptureMaskBase=255,255,255
GameCaptureShapeGradient1Base=172,77,64
GameCaptureShapeGradient2Base=64,77,172
GameCaptureRegularHidden=1

StreamDeckShape=Hexagon
StreamDeckMask=Regular Hexagon
StreamDeckMaskBase=255,255,255
StreamDeckShapeGradient1Base=172,77,64
StreamDeckShapeGradient2Base=64,77,172
StreamDeckRegularHidden=1

VideoCaptureShape=Hexagon
VideoCaptureMask=Regular Hexagon
VideoCaptureMaskBase=255,255,255
VideoCaptureShapeGradient1Base=172,77,64
VideoCaptureShapeGradient2Base=64,77,172
VideoCaptureRegularHidden=1

WaveLinkShape=Hexagon
WaveLinkMask=Regular Hexagon
WaveLinkMaskBase=255,255,255
WaveLinkShapeGradient1Base=172,77,64
WaveLinkShapeGradient2Base=64,77,172
WaveLinkRegularHidden=1

; ============================================================
; Emulator
; ============================================================

BlueStacksShape=Hexagon
BlueStacksMask=Regular Hexagon
BlueStacksMaskBase=255,255,255
BlueStacksShapeGradient1Base=172,77,64
BlueStacksShapeGradient2Base=64,77,172
BlueStacksRegularHidden=1

CemuShape=Hexagon
CemuMask=Regular Hexagon
CemuMaskBase=255,255,255
CemuShapeGradient1Base=172,77,64
CemuShapeGradient2Base=64,77,172
CemuRegularHidden=1

CitraShape=Hexagon
CitraMask=Regular Hexagon
CitraMaskBase=255,255,255
CitraShapeGradient1Base=172,77,64
CitraShapeGradient2Base=64,77,172
CitraRegularHidden=1

DeSmuMEShape=Hexagon
DeSmuMEMask=Regular Hexagon
DeSmuMEMaskBase=255,255,255
DeSmuMEShapeGradient1Base=172,77,64
DeSmuMEShapeGradient2Base=64,77,172
DeSmuMERegularHidden=1

DolphinShape=Hexagon
DolphinMask=Regular Hexagon
DolphinMaskBase=255,255,255
DolphinShapeGradient1Base=172,77,64
DolphinShapeGradient2Base=64,77,172
DolphinRegularHidden=1

DuckStationShape=Hexagon
DuckStationMask=Regular Hexagon
DuckStationMaskBase=255,255,255
DuckStationShapeGradient1Base=172,77,64
DuckStationShapeGradient2Base=64,77,172
DuckStationRegularHidden=1

PCSX2Shape=Hexagon
PCSX2Mask=Regular Hexagon
PCSX2MaskBase=255,255,255
PCSX2ShapeGradient1Base=172,77,64
PCSX2ShapeGradient2Base=64,77,172
PCSX2RegularHidden=1

PPSSPPShape=Hexagon
PPSSPPMask=Regular Hexagon
PPSSPPMaskBase=255,255,255
PPSSPPShapeGradient1Base=172,77,64
PPSSPPShapeGradient2Base=64,77,172
PPSSPPRegularHidden=1

RPCS3Shape=Hexagon
RPCS3Mask=Regular Hexagon
RPCS3MaskBase=255,255,255
RPCS3ShapeGradient1Base=172,77,64
RPCS3ShapeGradient2Base=64,77,172
RPCS3RegularHidden=1

Vita3KShape=Hexagon
Vita3KMask=Regular Hexagon
Vita3KMaskBase=255,255,255
Vita3KShapeGradient1Base=172,77,64
Vita3KShapeGradient2Base=64,77,172
Vita3KRegularHidden=1

XeniaShape=Hexagon
XeniaMask=Regular Hexagon
XeniaMaskBase=255,255,255
XeniaShapeGradient1Base=172,77,64
XeniaShapeGradient2Base=64,77,172
XeniaRegularHidden=1

; ============================================================
; Gaming
; ============================================================

AmongUsShape=Hexagon
AmongUsMask=Regular Hexagon
AmongUsMaskBase=255,255,255
AmongUsShapeGradient1Base=172,77,64
AmongUsShapeGradient2Base=64,77,172
AmongUsRegularHidden=1

ApexShape=Hexagon
ApexMask=Regular Hexagon
ApexMaskBase=255,255,255
ApexShapeGradient1Base=172,77,64
ApexShapeGradient2Base=64,77,172
ApexRegularHidden=1

ArkShape=Hexagon
ArkMask=Regular Hexagon
ArkMaskBase=255,255,255
ArkShapeGradient1Base=172,77,64
ArkShapeGradient2Base=64,77,172
ArkRegularHidden=1

AssettoShape=Hexagon
AssettoMask=Regular Hexagon
AssettoMaskBase=255,255,255
AssettoShapeGradient1Base=172,77,64
AssettoShapeGradient2Base=64,77,172
AssettoRegularHidden=1

BadlionShape=Hexagon
BadlionMask=Regular Hexagon
BadlionMaskBase=255,255,255
BadlionShapeGradient1Base=172,77,64
BadlionShapeGradient2Base=64,77,172
BadlionRegularHidden=1

BattleNetShape=Hexagon
BattleNetMask=Regular Hexagon
BattleNetMaskBase=255,255,255
BattleNetShapeGradient1Base=172,77,64
BattleNetShapeGradient2Base=64,77,172
BattleNetRegularHidden=1

BF1Shape=Hexagon
BF1Mask=Regular Hexagon
BF1MaskBase=255,255,255
BF1ShapeGradient1Base=172,77,64
BF1ShapeGradient2Base=64,77,172
BF1RegularHidden=1

BF4Shape=Hexagon
BF4Mask=Regular Hexagon
BF4MaskBase=255,255,255
BF4ShapeGradient1Base=172,77,64
BF4ShapeGradient2Base=64,77,172
BF4RegularHidden=1

BF2042Shape=Hexagon
BF2042Mask=Regular Hexagon
BF2042MaskBase=255,255,255
BF2042ShapeGradient1Base=172,77,64
BF2042ShapeGradient2Base=64,77,172
BF2042RegularHidden=1

BFVShape=Hexagon
BFVMask=Regular Hexagon
BFVMaskBase=255,255,255
BFVShapeGradient1Base=172,77,64
BFVShapeGradient2Base=64,77,172
BFVRegularHidden=1

BethesdaShape=Hexagon
BethesdaMask=Regular Hexagon
BethesdaMaskBase=255,255,255
BethesdaShapeGradient1Base=172,77,64
BethesdaShapeGradient2Base=64,77,172
BethesdaRegularHidden=1

BDOShape=Hexagon
BDOMask=Regular Hexagon
BDOMaskBase=255,255,255
BDOShapeGradient1Base=172,77,64
BDOShapeGradient2Base=64,77,172
BDORegularHidden=1

BTD6Shape=Hexagon
BTD6Mask=Regular Hexagon
BTD6MaskBase=255,255,255
BTD6ShapeGradient1Base=172,77,64
BTD6ShapeGradient2Base=64,77,172
BTD6RegularHidden=1

CODMWShape=Hexagon
CODMWMask=Regular Hexagon
CODMWMaskBase=255,255,255
CODMWShapeGradient1Base=172,77,64
CODMWShapeGradient2Base=64,77,172
CODMWRegularHidden=1

CODVanguardShape=Hexagon
CODVanguardMask=Regular Hexagon
CODVanguardMaskBase=255,255,255
CODVanguardShapeGradient1Base=172,77,64
CODVanguardShapeGradient2Base=64,77,172
CODVanguardRegularHidden=1

CloneHeroShape=Hexagon
CloneHeroMask=Regular Hexagon
CloneHeroMaskBase=255,255,255
CloneHeroShapeGradient1Base=172,77,64
CloneHeroShapeGradient2Base=64,77,172
CloneHeroRegularHidden=1

CSGOShape=Hexagon
CSGOMask=Regular Hexagon
CSGOMaskBase=255,255,255
CSGOShapeGradient1Base=172,77,64
CSGOShapeGradient2Base=64,77,172
CSGORegularHidden=1

CyberpunkShape=Hexagon
CyberpunkMask=Regular Hexagon
CyberpunkMaskBase=255,255,255
CyberpunkShapeGradient1Base=172,77,64
CyberpunkShapeGradient2Base=64,77,172
CyberpunkRegularHidden=1

DauntlessShape=Hexagon
DauntlessMask=Regular Hexagon
DauntlessMaskBase=255,255,255
DauntlessShapeGradient1Base=172,77,64
DauntlessShapeGradient2Base=64,77,172
DauntlessRegularHidden=1

DBDShape=Hexagon
DBDMask=Regular Hexagon
DBDMaskBase=255,255,255
DBDShapeGradient1Base=172,77,64
DBDShapeGradient2Base=64,77,172
DBDRegularHidden=1

Destiny2Shape=Hexagon
Destiny2Mask=Regular Hexagon
Destiny2MaskBase=255,255,255
Destiny2ShapeGradient1Base=172,77,64
Destiny2ShapeGradient2Base=64,77,172
Destiny2RegularHidden=1

DOOMShape=Hexagon
DOOMMask=Regular Hexagon
DOOMMaskBase=255,255,255
DOOMShapeGradient1Base=172,77,64
DOOMShapeGradient2Base=64,77,172
DOOMRegularHidden=1

DOOMEternalShape=Hexagon
DOOMEternalMask=Regular Hexagon
DOOMEternalMaskBase=255,255,255
DOOMEternalShapeGradient1Base=172,77,64
DOOMEternalShapeGradient2Base=64,77,172
DOOMEternalRegularHidden=1

DotaShape=Hexagon
DotaMask=Regular Hexagon
DotaMaskBase=255,255,255
DotaShapeGradient1Base=172,77,64
DotaShapeGradient2Base=64,77,172
DotaRegularHidden=1

EFTShape=Hexagon
EFTMask=Regular Hexagon
EFTMaskBase=255,255,255
EFTShapeGradient1Base=172,77,64
EFTShapeGradient2Base=64,77,172
EFTRegularHidden=1

EGStoreShape=Hexagon
EGStoreMask=Regular Hexagon
EGStoreMaskBase=255,255,255
EGStoreShapeGradient1Base=172,77,64
EGStoreShapeGradient2Base=64,77,172
EGStoreRegularHidden=1

ESOShape=Hexagon
ESOMask=Regular Hexagon
ESOMaskBase=255,255,255
ESOShapeGradient1Base=172,77,64
ESOShapeGradient2Base=64,77,172
ESORegularHidden=1

ESVSkyrimShape=Hexagon
ESVSkyrimMask=Regular Hexagon
ESVSkyrimMaskBase=255,255,255
ESVSkyrimShapeGradient1Base=172,77,64
ESVSkyrimShapeGradient2Base=64,77,172
ESVSkyrimRegularHidden=1

FactorioShape=Hexagon
FactorioMask=Regular Hexagon
FactorioMaskBase=255,255,255
FactorioShapeGradient1Base=172,77,64
FactorioShapeGradient2Base=64,77,172
FactorioRegularHidden=1

FallGuysShape=Hexagon
FallGuysMask=Regular Hexagon
FallGuysMaskBase=255,255,255
FallGuysShapeGradient1Base=172,77,64
FallGuysShapeGradient2Base=64,77,172
FallGuysRegularHidden=1

FFXIVShape=Hexagon
FFXIVMask=Regular Hexagon
FFXIVMaskBase=255,255,255
FFXIVShapeGradient1Base=172,77,64
FFXIVShapeGradient2Base=64,77,172
FFXIVRegularHidden=1

FNFShape=Hexagon
FNFMask=Regular Hexagon
FNFMaskBase=255,255,255
FNFShapeGradient1Base=172,77,64
FNFShapeGradient2Base=64,77,172
FNFRegularHidden=1

FortniteShape=Hexagon
FortniteMask=Regular Hexagon
FortniteMaskBase=255,255,255
FortniteShapeGradient1Base=172,77,64
FortniteShapeGradient2Base=64,77,172
FortniteRegularHidden=1

FH4Shape=Hexagon
FH4Mask=Regular Hexagon
FH4MaskBase=255,255,255
FH4ShapeGradient1Base=172,77,64
FH4ShapeGradient2Base=64,77,172
FH4RegularHidden=1

FH5Shape=Hexagon
FH5Mask=Regular Hexagon
FH5MaskBase=255,255,255
FH5ShapeGradient1Base=172,77,64
FH5ShapeGradient2Base=64,77,172
FH5RegularHidden=1

GameLibrariesShape=Hexagon
GameLibrariesMask=Regular Hexagon
GameLibrariesMaskBase=255,255,255
GameLibrariesShapeGradient1Base=172,77,64
GameLibrariesShapeGradient2Base=64,77,172
GameLibrariesRegularHidden=1

GameHUB2Shape=Hexagon
GameHUB2Mask=Regular Hexagon
GameHUB2MaskBase=255,255,255
GameHUB2ShapeGradient1Base=172,77,64
GameHUB2ShapeGradient2Base=64,77,172
GameHUB2RegularHidden=1

GModShape=Hexagon
GModMask=Regular Hexagon
GModMaskBase=255,255,255
GModShapeGradient1Base=172,77,64
GModShapeGradient2Base=64,77,172
GModRegularHidden=1

GenshinShape=Hexagon
GenshinMask=Regular Hexagon
GenshinMaskBase=255,255,255
GenshinShapeGradient1Base=172,77,64
GenshinShapeGradient2Base=64,77,172
GenshinRegularHidden=1

GhostrunnerShape=Hexagon
GhostrunnerMask=Regular Hexagon
GhostrunnerMaskBase=255,255,255
GhostrunnerShapeGradient1Base=172,77,64
GhostrunnerShapeGradient2Base=64,77,172
GhostrunnerRegularHidden=1

GodfallShape=Hexagon
GodfallMask=Regular Hexagon
GodfallMaskBase=255,255,255
GodfallShapeGradient1Base=172,77,64
GodfallShapeGradient2Base=64,77,172
GodfallRegularHidden=1

GOGShape=Hexagon
GOGMask=Regular Hexagon
GOGMaskBase=255,255,255
GOGShapeGradient1Base=172,77,64
GOGShapeGradient2Base=64,77,172
GOGRegularHidden=1

GTAVShape=Hexagon
GTAVMask=Regular Hexagon
GTAVMaskBase=255,255,255
GTAVShapeGradient1Base=172,77,64
GTAVShapeGradient2Base=64,77,172
GTAVRegularHidden=1

GuiltyGearShape=Hexagon
GuiltyGearMask=Regular Hexagon
GuiltyGearMaskBase=255,255,255
GuiltyGearShapeGradient1Base=172,77,64
GuiltyGearShapeGradient2Base=64,77,172
GuiltyGearRegularHidden=1

GW2Shape=Hexagon
GW2Mask=Regular Hexagon
GW2MaskBase=255,255,255
GW2ShapeGradient1Base=172,77,64
GW2ShapeGradient2Base=64,77,172
GW2RegularHidden=1

HaloInfiniteShape=Hexagon
HaloInfiniteMask=Regular Hexagon
HaloInfiniteMaskBase=255,255,255
HaloInfiniteShapeGradient1Base=172,77,64
HaloInfiniteShapeGradient2Base=64,77,172
HaloInfiniteRegularHidden=1

HearthstoneShape=Hexagon
HearthstoneMask=Regular Hexagon
HearthstoneMaskBase=255,255,255
HearthstoneShapeGradient1Base=172,77,64
HearthstoneShapeGradient2Base=64,77,172
HearthstoneRegularHidden=1

HOI4Shape=Hexagon
HOI4Mask=Regular Hexagon
HOI4MaskBase=255,255,255
HOI4ShapeGradient1Base=172,77,64
HOI4ShapeGradient2Base=64,77,172
HOI4RegularHidden=1

HOTSShape=Hexagon
HOTSMask=Regular Hexagon
HOTSMaskBase=255,255,255
HOTSShapeGradient1Base=172,77,64
HOTSShapeGradient2Base=64,77,172
HOTSRegularHidden=1

HonkaiShape=Hexagon
HonkaiMask=Regular Hexagon
HonkaiMaskBase=255,255,255
HonkaiShapeGradient1Base=172,77,64
HonkaiShapeGradient2Base=64,77,172
HonkaiRegularHidden=1

HuntShowdownShape=Hexagon
HuntShowdownMask=Regular Hexagon
HuntShowdownMaskBase=255,255,255
HuntShowdownShapeGradient1Base=172,77,64
HuntShowdownShapeGradient2Base=64,77,172
HuntShowdownRegularHidden=1

LOLShape=Hexagon
LOLMask=Regular Hexagon
LOLMaskBase=255,255,255
LOLShapeGradient1Base=172,77,64
LOLShapeGradient2Base=64,77,172
LOLRegularHidden=1

LORShape=Hexagon
LORMask=Regular Hexagon
LORMaskBase=255,255,255
LORShapeGradient1Base=172,77,64
LORShapeGradient2Base=64,77,172
LORRegularHidden=1

LunarShape=Hexagon
LunarMask=Regular Hexagon
LunarMaskBase=255,255,255
LunarShapeGradient1Base=172,77,64
LunarShapeGradient2Base=64,77,172
LunarRegularHidden=1

MinecraftShape=Hexagon
MinecraftMask=Regular Hexagon
MinecraftMaskBase=255,255,255
MinecraftShapeGradient1Base=172,77,64
MinecraftShapeGradient2Base=64,77,172
MinecraftRegularHidden=1

MHWorldShape=Hexagon
MHWorldMask=Regular Hexagon
MHWorldMaskBase=255,255,255
MHWorldShapeGradient1Base=172,77,64
MHWorldShapeGradient2Base=64,77,172
MHWorldRegularHidden=1

NarakaShape=Hexagon
NarakaMask=Regular Hexagon
NarakaMaskBase=255,255,255
NarakaShapeGradient1Base=172,77,64
NarakaShapeGradient2Base=64,77,172
NarakaRegularHidden=1

NierAutomataShape=Hexagon
NierAutomataMask=Regular Hexagon
NierAutomataMaskBase=255,255,255
NierAutomataShapeGradient1Base=172,77,64
NierAutomataShapeGradient2Base=64,77,172
NierAutomataRegularHidden=1

NMSShape=Hexagon
NMSMask=Regular Hexagon
NMSMaskBase=255,255,255
NMSShapeGradient1Base=172,77,64
NMSShapeGradient2Base=64,77,172
NMSRegularHidden=1

OriginShape=Hexagon
OriginMask=Regular Hexagon
OriginMaskBase=255,255,255
OriginShapeGradient1Base=172,77,64
OriginShapeGradient2Base=64,77,172
OriginRegularHidden=1

OriBFShape=Hexagon
OriBFMask=Regular Hexagon
OriBFMaskBase=255,255,255
OriBFShapeGradient1Base=172,77,64
OriBFShapeGradient2Base=64,77,172
OriBFRegularHidden=1

OriWWShape=Hexagon
OriWWMask=Regular Hexagon
OriWWMaskBase=255,255,255
OriWWShapeGradient1Base=172,77,64
OriWWShapeGradient2Base=64,77,172
OriWWRegularHidden=1

OsuShape=Hexagon
OsuMask=Regular Hexagon
OsuMaskBase=255,255,255
OsuShapeGradient1Base=172,77,64
OsuShapeGradient2Base=64,77,172
OsuRegularHidden=1

OutridersShape=Hexagon
OutridersMask=Regular Hexagon
OutridersMaskBase=255,255,255
OutridersShapeGradient1Base=172,77,64
OutridersShapeGradient2Base=64,77,172
OutridersRegularHidden=1

OverwatchShape=Hexagon
OverwatchMask=Regular Hexagon
OverwatchMaskBase=255,255,255
OverwatchShapeGradient1Base=172,77,64
OverwatchShapeGradient2Base=64,77,172
OverwatchRegularHidden=1

PaladinsShape=Hexagon
PaladinsMask=Regular Hexagon
PaladinsMaskBase=255,255,255
PaladinsShapeGradient1Base=172,77,64
PaladinsShapeGradient2Base=64,77,172
PaladinsRegularHidden=1

POEShape=Hexagon
POEMask=Regular Hexagon
POEMaskBase=255,255,255
POEShapeGradient1Base=172,77,64
POEShapeGradient2Base=64,77,172
POERegularHidden=1

PUBGShape=Hexagon
PUBGMask=Regular Hexagon
PUBGMaskBase=255,255,255
PUBGShapeGradient1Base=172,77,64
PUBGShapeGradient2Base=64,77,172
PUBGRegularHidden=1

RSSiegeShape=Hexagon
RSSiegeMask=Regular Hexagon
RSSiegeMaskBase=255,255,255
RSSiegeShapeGradient1Base=172,77,64
RSSiegeShapeGradient2Base=64,77,172
RSSiegeRegularHidden=1

RecRoomShape=Hexagon
RecRoomMask=Regular Hexagon
RecRoomMaskBase=255,255,255
RecRoomShapeGradient1Base=172,77,64
RecRoomShapeGradient2Base=64,77,172
RecRoomRegularHidden=1

RiotShape=Hexagon
RiotMask=Regular Hexagon
RiotMaskBase=255,255,255
RiotShapeGradient1Base=172,77,64
RiotShapeGradient2Base=64,77,172
RiotRegularHidden=1

RobloxStudioShape=Hexagon
RobloxStudioMask=Regular Hexagon
RobloxStudioMaskBase=255,255,255
RobloxStudioShapeGradient1Base=172,77,64
RobloxStudioShapeGradient2Base=64,77,172
RobloxStudioRegularHidden=1

RobloxShape=Hexagon
RobloxMask=Regular Hexagon
RobloxMaskBase=255,255,255
RobloxShapeGradient1Base=172,77,64
RobloxShapeGradient2Base=64,77,172
RobloxRegularHidden=1

RocketLeagueShape=Hexagon
RocketLeagueMask=Regular Hexagon
RocketLeagueMaskBase=255,255,255
RocketLeagueShapeGradient1Base=172,77,64
RocketLeagueShapeGradient2Base=64,77,172
RocketLeagueRegularHidden=1

RockstarShape=Hexagon
RockstarMask=Regular Hexagon
RockstarMaskBase=255,255,255
RockstarShapeGradient1Base=172,77,64
RockstarShapeGradient2Base=64,77,172
RockstarRegularHidden=1

RSIShape=Hexagon
RSIMask=Regular Hexagon
RSIMaskBase=255,255,255
RSIShapeGradient1Base=172,77,64
RSIShapeGradient2Base=64,77,172
RSIRegularHidden=1

RuneScapeShape=Hexagon
RuneScapeMask=Regular Hexagon
RuneScapeMaskBase=255,255,255
RuneScapeShapeGradient1Base=172,77,64
RuneScapeShapeGradient2Base=64,77,172
RuneScapeRegularHidden=1

RustShape=Hexagon
RustMask=Regular Hexagon
RustMaskBase=255,255,255
RustShapeGradient1Base=172,77,64
RustShapeGradient2Base=64,77,172
RustRegularHidden=1

SatisfactoryShape=Hexagon
SatisfactoryMask=Regular Hexagon
SatisfactoryMaskBase=255,255,255
SatisfactoryShapeGradient1Base=172,77,64
SatisfactoryShapeGradient2Base=64,77,172
SatisfactoryRegularHidden=1

SoTShape=Hexagon
SoTMask=Regular Hexagon
SoTMaskBase=255,255,255
SoTShapeGradient1Base=172,77,64
SoTShapeGradient2Base=64,77,172
SoTRegularHidden=1

StSShape=Hexagon
StSMask=Regular Hexagon
StSMaskBase=255,255,255
StSShapeGradient1Base=172,77,64
StSShapeGradient2Base=64,77,172
StSRegularHidden=1

SmiteShape=Hexagon
SmiteMask=Regular Hexagon
SmiteMaskBase=255,255,255
SmiteShapeGradient1Base=172,77,64
SmiteShapeGradient2Base=64,77,172
SmiteRegularHidden=1

StarCitizenShape=Hexagon
StarCitizenMask=Regular Hexagon
StarCitizenMaskBase=255,255,255
StarCitizenShapeGradient1Base=172,77,64
StarCitizenShapeGradient2Base=64,77,172
StarCitizenRegularHidden=1

SteamShape=Hexagon
SteamMask=Regular Hexagon
SteamMaskBase=255,255,255
SteamShapeGradient1Base=172,77,64
SteamShapeGradient2Base=64,77,172
SteamRegularHidden=1

SAPShape=Hexagon
SAPMask=Regular Hexagon
SAPMaskBase=255,255,255
SAPShapeGradient1Base=172,77,64
SAPShapeGradient2Base=64,77,172
SAPRegularHidden=1

TF2Shape=Hexagon
TF2Mask=Regular Hexagon
TF2MaskBase=255,255,255
TF2ShapeGradient1Base=172,77,64
TF2ShapeGradient2Base=64,77,172
TF2RegularHidden=1

TW3Shape=Hexagon
TW3Mask=Regular Hexagon
TW3MaskBase=255,255,255
TW3ShapeGradient1Base=172,77,64
TW3ShapeGradient2Base=64,77,172
TW3RegularHidden=1

UbisoftShape=Hexagon
UbisoftMask=Regular Hexagon
UbisoftMaskBase=255,255,255
UbisoftShapeGradient1Base=172,77,64
UbisoftShapeGradient2Base=64,77,172
UbisoftRegularHidden=1

ValorantShape=Hexagon
ValorantMask=Regular Hexagon
ValorantMaskBase=255,255,255
ValorantShapeGradient1Base=172,77,64
ValorantShapeGradient2Base=64,77,172
ValorantRegularHidden=1

VortexShape=Hexagon
VortexMask=Regular Hexagon
VortexMaskBase=255,255,255
VortexShapeGradient1Base=172,77,64
VortexShapeGradient2Base=64,77,172
VortexRegularHidden=1

WarThunderShape=Hexagon
WarThunderMask=Regular Hexagon
WarThunderMaskBase=255,255,255
WarThunderShapeGradient1Base=172,77,64
WarThunderShapeGradient2Base=64,77,172
WarThunderRegularHidden=1

WarframeShape=Hexagon
WarframeMask=Regular Hexagon
WarframeMaskBase=255,255,255
WarframeShapeGradient1Base=172,77,64
WarframeShapeGradient2Base=64,77,172
WarframeRegularHidden=1

WOTanksShape=Hexagon
WOTanksMask=Regular Hexagon
WOTanksMaskBase=255,255,255
WOTanksShapeGradient1Base=172,77,64
WOTanksShapeGradient2Base=64,77,172
WOTanksRegularHidden=1

WOWShape=Hexagon
WOWMask=Regular Hexagon
WOWMaskBase=255,255,255
WOWShapeGradient1Base=172,77,64
WOWShapeGradient2Base=64,77,172
WOWRegularHidden=1

WOWarshipsShape=Hexagon
WOWarshipsMask=Regular Hexagon
WOWarshipsMaskBase=255,255,255
WOWarshipsShapeGradient1Base=172,77,64
WOWarshipsShapeGradient2Base=64,77,172
WOWarshipsRegularHidden=1

XboxShape=Hexagon
XboxMask=Regular Hexagon
XboxMaskBase=255,255,255
XboxShapeGradient1Base=172,77,64
XboxShapeGradient2Base=64,77,172
XboxRegularHidden=1

; ============================================================
; Media
; ============================================================

AIMPShape=Hexagon
AIMPMask=Regular Hexagon
AIMPMaskBase=255,255,255
AIMPShapeGradient1Base=172,77,64
AIMPShapeGradient2Base=64,77,172
AIMPRegularHidden=1

AmazonMusicShape=Hexagon
AmazonMusicMask=Regular Hexagon
AmazonMusicMaskBase=255,255,255
AmazonMusicShapeGradient1Base=172,77,64
AmazonMusicShapeGradient2Base=64,77,172
AmazonMusicRegularHidden=1

AudibleShape=Hexagon
AudibleMask=Regular Hexagon
AudibleMaskBase=255,255,255
AudibleShapeGradient1Base=172,77,64
AudibleShapeGradient2Base=64,77,172
AudibleRegularHidden=1

DisneyPlusShape=Hexagon
DisneyPlusMask=Regular Hexagon
DisneyPlusMaskBase=255,255,255
DisneyPlusShapeGradient1Base=172,77,64
DisneyPlusShapeGradient2Base=64,77,172
DisneyPlusRegularHidden=1

FoobarShape=Hexagon
FoobarMask=Regular Hexagon
FoobarMaskBase=255,255,255
FoobarShapeGradient1Base=172,77,64
FoobarShapeGradient2Base=64,77,172
FoobarRegularHidden=1

GPMShape=Hexagon
GPMMask=Regular Hexagon
GPMMaskBase=255,255,255
GPMShapeGradient1Base=172,77,64
GPMShapeGradient2Base=64,77,172
GPMRegularHidden=1

HuluShape=Hexagon
HuluMask=Regular Hexagon
HuluMaskBase=255,255,255
HuluShapeGradient1Base=172,77,64
HuluShapeGradient2Base=64,77,172
HuluRegularHidden=1

iTunesShape=Hexagon
iTunesMask=Regular Hexagon
iTunesMaskBase=255,255,255
iTunesShapeGradient1Base=172,77,64
iTunesShapeGradient2Base=64,77,172
iTunesRegularHidden=1

KodiShape=Hexagon
KodiMask=Regular Hexagon
KodiMaskBase=255,255,255
KodiShapeGradient1Base=172,77,64
KodiShapeGradient2Base=64,77,172
KodiRegularHidden=1

MusicBeeShape=Hexagon
MusicBeeMask=Regular Hexagon
MusicBeeMaskBase=255,255,255
MusicBeeShapeGradient1Base=172,77,64
MusicBeeShapeGradient2Base=64,77,172
MusicBeeRegularHidden=1

NetflixShape=Hexagon
NetflixMask=Regular Hexagon
NetflixMaskBase=255,255,255
NetflixShapeGradient1Base=172,77,64
NetflixShapeGradient2Base=64,77,172
NetflixRegularHidden=1

PlexShape=Hexagon
PlexMask=Regular Hexagon
PlexMaskBase=255,255,255
PlexShapeGradient1Base=172,77,64
PlexShapeGradient2Base=64,77,172
PlexRegularHidden=1

SpotifyShape=Hexagon
SpotifyMask=Regular Hexagon
SpotifyMaskBase=255,255,255
SpotifyShapeGradient1Base=172,77,64
SpotifyShapeGradient2Base=64,77,172
SpotifyRegularHidden=1

TwitchShape=Hexagon
TwitchMask=Regular Hexagon
TwitchMaskBase=255,255,255
TwitchShapeGradient1Base=172,77,64
TwitchShapeGradient2Base=64,77,172
TwitchRegularHidden=1

VLCShape=Hexagon
VLCMask=Regular Hexagon
VLCMaskBase=255,255,255
VLCShapeGradient1Base=172,77,64
VLCShapeGradient2Base=64,77,172
VLCRegularHidden=1

WakanimShape=Hexagon
WakanimMask=Regular Hexagon
WakanimMaskBase=255,255,255
WakanimShapeGradient1Base=172,77,64
WakanimShapeGradient2Base=64,77,172
WakanimRegularHidden=1

WinampShape=Hexagon
WinampMask=Regular Hexagon
WinampMaskBase=255,255,255
WinampShapeGradient1Base=172,77,64
WinampShapeGradient2Base=64,77,172
WinampRegularHidden=1

YouTubeShape=Hexagon
YouTubeMask=Regular Hexagon
YouTubeMaskBase=255,255,255
YouTubeShapeGradient1Base=172,77,64
YouTubeShapeGradient2Base=64,77,172
YouTubeRegularHidden=1

; ============================================================
; Office
; ============================================================

ExcelShape=Hexagon
ExcelMask=Regular Hexagon
ExcelMaskBase=255,255,255
ExcelShapeGradient1Base=172,77,64
ExcelShapeGradient2Base=64,77,172
ExcelRegularHidden=1

OneNoteShape=Hexagon
OneNoteMask=Regular Hexagon
OneNoteMaskBase=255,255,255
OneNoteShapeGradient1Base=172,77,64
OneNoteShapeGradient2Base=64,77,172
OneNoteRegularHidden=1

OutlookShape=Hexagon
OutlookMask=Regular Hexagon
OutlookMaskBase=255,255,255
OutlookShapeGradient1Base=172,77,64
OutlookShapeGradient2Base=64,77,172
OutlookRegularHidden=1

PowerPointShape=Hexagon
PowerPointMask=Regular Hexagon
PowerPointMaskBase=255,255,255
PowerPointShapeGradient1Base=172,77,64
PowerPointShapeGradient2Base=64,77,172
PowerPointRegularHidden=1

SharePointShape=Hexagon
SharePointMask=Regular Hexagon
SharePointMaskBase=255,255,255
SharePointShapeGradient1Base=172,77,64
SharePointShapeGradient2Base=64,77,172
SharePointRegularHidden=1

TeamsShape=Hexagon
TeamsMask=Regular Hexagon
TeamsMaskBase=255,255,255
TeamsShapeGradient1Base=172,77,64
TeamsShapeGradient2Base=64,77,172
TeamsRegularHidden=1

WordShape=Hexagon
WordMask=Regular Hexagon
WordMaskBase=255,255,255
WordShapeGradient1Base=172,77,64
WordShapeGradient2Base=64,77,172
WordRegularHidden=1

YammerShape=Hexagon
YammerMask=Regular Hexagon
YammerMaskBase=255,255,255
YammerShapeGradient1Base=172,77,64
YammerShapeGradient2Base=64,77,172
YammerRegularHidden=1

; ============================================================
; Social
; ============================================================

DiscordShape=Hexagon
DiscordMask=Regular Hexagon
DiscordMaskBase=255,255,255
DiscordShapeGradient1Base=172,77,64
DiscordShapeGradient2Base=64,77,172
DiscordRegularHidden=1

GuildedShape=Hexagon
GuildedMask=Regular Hexagon
GuildedMaskBase=255,255,255
GuildedShapeGradient1Base=172,77,64
GuildedShapeGradient2Base=64,77,172
GuildedRegularHidden=1

RedditShape=Hexagon
RedditMask=Regular Hexagon
RedditMaskBase=255,255,255
RedditShapeGradient1Base=172,77,64
RedditShapeGradient2Base=64,77,172
RedditRegularHidden=1

SignalShape=Hexagon
SignalMask=Regular Hexagon
SignalMaskBase=255,255,255
SignalShapeGradient1Base=172,77,64
SignalShapeGradient2Base=64,77,172
SignalRegularHidden=1

TeamSpeakShape=Hexagon
TeamSpeakMask=Regular Hexagon
TeamSpeakMaskBase=255,255,255
TeamSpeakShapeGradient1Base=172,77,64
TeamSpeakShapeGradient2Base=64,77,172
TeamSpeakRegularHidden=1

TelegramShape=Hexagon
TelegramMask=Regular Hexagon
TelegramMaskBase=255,255,255
TelegramShapeGradient1Base=172,77,64
TelegramShapeGradient2Base=64,77,172
TelegramRegularHidden=1

TwitterShape=Hexagon
TwitterMask=Regular Hexagon
TwitterMaskBase=255,255,255
TwitterShapeGradient1Base=172,77,64
TwitterShapeGradient2Base=64,77,172
TwitterRegularHidden=1

WhatsAppShape=Hexagon
WhatsAppMask=Regular Hexagon
WhatsAppMaskBase=255,255,255
WhatsAppShapeGradient1Base=172,77,64
WhatsAppShapeGradient2Base=64,77,172
WhatsAppRegularHidden=1

WebExShape=Hexagon
WebExMask=Regular Hexagon
WebExMaskBase=255,255,255
WebExShapeGradient1Base=172,77,64
WebExShapeGradient2Base=64,77,172
WebExRegularHidden=1

ZoomShape=Hexagon
ZoomMask=Regular Hexagon
ZoomMaskBase=255,255,255
ZoomShapeGradient1Base=172,77,64
ZoomShapeGradient2Base=64,77,172
ZoomRegularHidden=1

; ============================================================
; Other
; ============================================================

AbletonShape=Hexagon
AbletonMask=Regular Hexagon
AbletonMaskBase=255,255,255
AbletonShapeGradient1Base=172,77,64
AbletonShapeGradient2Base=64,77,172
AbletonRegularHidden=1

AMDShape=Hexagon
AMDMask=Regular Hexagon
AMDMaskBase=255,255,255
AMDShapeGradient1Base=172,77,64
AMDShapeGradient2Base=64,77,172
AMDRegularHidden=1

AMDRyzenShape=Hexagon
AMDRyzenMask=Regular Hexagon
AMDRyzenMaskBase=255,255,255
AMDRyzenShapeGradient1Base=172,77,64
AMDRyzenShapeGradient2Base=64,77,172
AMDRyzenRegularHidden=1

AnkiShape=Hexagon
AnkiMask=Regular Hexagon
AnkiMaskBase=255,255,255
AnkiShapeGradient1Base=172,77,64
AnkiShapeGradient2Base=64,77,172
AnkiRegularHidden=1

BitDefenderShape=Hexagon
BitDefenderMask=Regular Hexagon
BitDefenderMaskBase=255,255,255
BitDefenderShapeGradient1Base=172,77,64
BitDefenderShapeGradient2Base=64,77,172
BitDefenderRegularHidden=1

BitwardenShape=Hexagon
BitwardenMask=Regular Hexagon
BitwardenMaskBase=255,255,255
BitwardenShapeGradient1Base=172,77,64
BitwardenShapeGradient2Base=64,77,172
BitwardenRegularHidden=1

BlenderShape=Hexagon
BlenderMask=Regular Hexagon
BlenderMaskBase=255,255,255
BlenderShapeGradient1Base=172,77,64
BlenderShapeGradient2Base=64,77,172
BlenderRegularHidden=1

CSPShape=Hexagon
CSPMask=Regular Hexagon
CSPMaskBase=255,255,255
CSPShapeGradient1Base=172,77,64
CSPShapeGradient2Base=64,77,172
CSPRegularHidden=1

CorsairShape=Hexagon
CorsairMask=Regular Hexagon
CorsairMaskBase=255,255,255
CorsairShapeGradient1Base=172,77,64
CorsairShapeGradient2Base=64,77,172
CorsairRegularHidden=1

DaVinciShape=Hexagon
DaVinciMask=Regular Hexagon
DaVinciMaskBase=255,255,255
DaVinciShapeGradient1Base=172,77,64
DaVinciShapeGradient2Base=64,77,172
DaVinciRegularHidden=1

DeviantArtShape=Hexagon
DeviantArtMask=Regular Hexagon
DeviantArtMaskBase=255,255,255
DeviantArtShapeGradient1Base=172,77,64
DeviantArtShapeGradient2Base=64,77,172
DeviantArtRegularHidden=1

EvernoteShape=Hexagon
EvernoteMask=Regular Hexagon
EvernoteMaskBase=255,255,255
EvernoteShapeGradient1Base=172,77,64
EvernoteShapeGradient2Base=64,77,172
EvernoteRegularHidden=1

EVGAShape=Hexagon
EVGAMask=Regular Hexagon
EVGAMaskBase=255,255,255
EVGAShapeGradient1Base=172,77,64
EVGAShapeGradient2Base=64,77,172
EVGARegularHidden=1

FLStudioShape=Hexagon
FLStudioMask=Regular Hexagon
FLStudioMaskBase=255,255,255
FLStudioShapeGradient1Base=172,77,64
FLStudioShapeGradient2Base=64,77,172
FLStudioRegularHidden=1

GIMPShape=Hexagon
GIMPMask=Regular Hexagon
GIMPMaskBase=255,255,255
GIMPShapeGradient1Base=172,77,64
GIMPShapeGradient2Base=64,77,172
GIMPRegularHidden=1

KritaShape=Hexagon
KritaMask=Regular Hexagon
KritaMaskBase=255,255,255
KritaShapeGradient1Base=172,77,64
KritaShapeGradient2Base=64,77,172
KritaRegularHidden=1

LibrariesShape=Hexagon
LibrariesMask=Regular Hexagon
LibrariesMaskBase=255,255,255
LibrariesShapeGradient1Base=172,77,64
LibrariesShapeGradient2Base=64,77,172
LibrariesRegularHidden=1

LogitechShape=Hexagon
LogitechMask=Regular Hexagon
LogitechMaskBase=255,255,255
LogitechShapeGradient1Base=172,77,64
LogitechShapeGradient2Base=64,77,172
LogitechRegularHidden=1

ManageRainmeterShape=Hexagon
ManageRainmeterMask=Regular Hexagon
ManageRainmeterMaskBase=255,255,255
ManageRainmeterShapeGradient1Base=172,77,64
ManageRainmeterShapeGradient2Base=64,77,172
ManageRainmeterRegularHidden=1

MSIShape=Hexagon
MSIMask=Regular Hexagon
MSIMaskBase=255,255,255
MSIShapeGradient1Base=172,77,64
MSIShapeGradient2Base=64,77,172
MSIRegularHidden=1

NotepadPPShape=Hexagon
NotepadPPMask=Regular Hexagon
NotepadPPMaskBase=255,255,255
NotepadPPShapeGradient1Base=172,77,64
NotepadPPShapeGradient2Base=64,77,172
NotepadPPRegularHidden=1

NVIDIAShape=Hexagon
NVIDIAMask=Regular Hexagon
NVIDIAMaskBase=255,255,255
NVIDIAShapeGradient1Base=172,77,64
NVIDIAShapeGradient2Base=64,77,172
NVIDIARegularHidden=1

OBSShape=Hexagon
OBSMask=Regular Hexagon
OBSMaskBase=255,255,255
OBSShapeGradient1Base=172,77,64
OBSShapeGradient2Base=64,77,172
OBSRegularHidden=1

OculusShape=Hexagon
OculusMask=Regular Hexagon
OculusMaskBase=255,255,255
OculusShapeGradient1Base=172,77,64
OculusShapeGradient2Base=64,77,172
OculusRegularHidden=1

OutplayedShape=Hexagon
OutplayedMask=Regular Hexagon
OutplayedMaskBase=255,255,255
OutplayedShapeGradient1Base=172,77,64
OutplayedShapeGradient2Base=64,77,172
OutplayedRegularHidden=1

ProtonVPNShape=Hexagon
ProtonVPNMask=Regular Hexagon
ProtonVPNMaskBase=255,255,255
ProtonVPNShapeGradient1Base=172,77,64
ProtonVPNShapeGradient2Base=64,77,172
ProtonVPNRegularHidden=1

RazerShape=Hexagon
RazerMask=Regular Hexagon
RazerMaskBase=255,255,255
RazerShapeGradient1Base=172,77,64
RazerShapeGradient2Base=64,77,172
RazerRegularHidden=1

SlackShape=Hexagon
SlackMask=Regular Hexagon
SlackMaskBase=255,255,255
SlackShapeGradient1Base=172,77,64
SlackShapeGradient2Base=64,77,172
SlackRegularHidden=1

SoulseekQtShape=Hexagon
SoulseekQtMask=Regular Hexagon
SoulseekQtMaskBase=255,255,255
SoulseekQtShapeGradient1Base=172,77,64
SoulseekQtShapeGradient2Base=64,77,172
SoulseekQtRegularHidden=1

SpaceSnifferShape=Hexagon
SpaceSnifferMask=Regular Hexagon
SpaceSnifferMaskBase=255,255,255
SpaceSnifferShapeGradient1Base=172,77,64
SpaceSnifferShapeGradient2Base=64,77,172
SpaceSnifferRegularHidden=1

StreamLabsShape=Hexagon
StreamLabsMask=Regular Hexagon
StreamLabsMaskBase=255,255,255
StreamLabsShapeGradient1Base=172,77,64
StreamLabsShapeGradient2Base=64,77,172
StreamLabsRegularHidden=1

ThisPCShape=Hexagon
ThisPCMask=Regular Hexagon
ThisPCMaskBase=255,255,255
ThisPCShapeGradient1Base=172,77,64
ThisPCShapeGradient2Base=64,77,172
ThisPCRegularHidden=1

ThunderbirdShape=Hexagon
ThunderbirdMask=Regular Hexagon
ThunderbirdMaskBase=255,255,255
ThunderbirdShapeGradient1Base=172,77,64
ThunderbirdShapeGradient2Base=64,77,172
ThunderbirdRegularHidden=1

UnityShape=Hexagon
UnityMask=Regular Hexagon
UnityMaskBase=255,255,255
UnityShapeGradient1Base=172,77,64
UnityShapeGradient2Base=64,77,172
UnityRegularHidden=1

UnrealShape=Hexagon
UnrealMask=Regular Hexagon
UnrealMaskBase=255,255,255
UnrealShapeGradient1Base=172,77,64
UnrealShapeGradient2Base=64,77,172
UnrealRegularHidden=1

VisualStudioCodeShape=Hexagon
VisualStudioCodeMask=Regular Hexagon
VisualStudioCodeMaskBase=255,255,255
VisualStudioCodeShapeGradient1Base=172,77,64
VisualStudioCodeShapeGradient2Base=64,77,172
VisualStudioCodeRegularHidden=1

VisualStudioShape=Hexagon
VisualStudioMask=Regular Hexagon
VisualStudioMaskBase=255,255,255
VisualStudioShapeGradient1Base=172,77,64
VisualStudioShapeGradient2Base=64,77,172
VisualStudioRegularHidden=1

VMwareShape=Hexagon
VMwareMask=Regular Hexagon
VMwareMaskBase=255,255,255
VMwareShapeGradient1Base=172,77,64
VMwareShapeGradient2Base=64,77,172
VMwareRegularHidden=1

WallpaperEngineShape=Hexagon
WallpaperEngineMask=Regular Hexagon
WallpaperEngineMaskBase=255,255,255
WallpaperEngineShapeGradient1Base=172,77,64
WallpaperEngineShapeGradient2Base=64,77,172
WallpaperEngineRegularHidden=1

ZbrushShape=Hexagon
ZbrushMask=Regular Hexagon
ZbrushMaskBase=255,255,255
ZbrushShapeGradient1Base=172,77,64
ZbrushShapeGradient2Base=64,77,172
ZbrushRegularHidden=1
