[Variables]

SetUpdateDivider=1

; Options
IconHeight=90
ShapeGradientAngle=0
ChromePFText=x64
ChromePF=Program Files
GamingPG1Hidden=0
GamingPG2Hidden=1

; Masks
NameCategoryMask=Adobe
NameIconMask=Acrobat

; Faders
FadeActiveToggle1=Active
FadeActiveToggle2=NotActive
FadeTextPM=255,215,0
FadeTextMP=255,255,255

; ============================================================
; Adobe
; ============================================================

AcrobatShape=Hexagon
AcrobatMaskMeter=Shape
AcrobatMask=Regular Hexagon
AcrobatMaskStyle=Blank
AcrobatMaskBase=255,255,255
AcrobatShapeGradient1Base=225,65,105
AcrobatShapeGradient2Base=65,105,225
AcrobatRegularHidden=1

AfterEffectsShape=Hexagon
AfterEffectsMaskMeter=Shape
AfterEffectsMask=Regular Hexagon
AfterEffectsMaskStyle=Blank
AfterEffectsMaskBase=255,255,255
AfterEffectsShapeGradient1Base=225,65,105
AfterEffectsShapeGradient2Base=65,105,225
AfterEffectsRegularHidden=1

AnimateShape=Hexagon
AnimateMaskMeter=Shape
AnimateMask=Regular Hexagon
AnimateMaskStyle=Blank
AnimateMaskBase=255,255,255
AnimateShapeGradient1Base=225,65,105
AnimateShapeGradient2Base=65,105,225
AnimateRegularHidden=1

AuditionShape=Hexagon
AuditionMaskMeter=Shape
AuditionMask=Regular Hexagon
AuditionMaskStyle=Blank
AuditionMaskBase=255,255,255
AuditionShapeGradient1Base=225,65,105
AuditionShapeGradient2Base=65,105,225
AuditionRegularHidden=1

BridgeShape=Hexagon
BridgeMaskMeter=Shape
BridgeMask=Regular Hexagon
BridgeMaskStyle=Blank
BridgeMaskBase=255,255,255
BridgeShapeGradient1Base=225,65,105
BridgeShapeGradient2Base=65,105,225
BridgeRegularHidden=1

CharacterAnimatorShape=Hexagon
CharacterAnimatorMaskMeter=Shape
CharacterAnimatorMask=Regular Hexagon
CharacterAnimatorMaskStyle=Blank
CharacterAnimatorMaskBase=255,255,255
CharacterAnimatorShapeGradient1Base=225,65,105
CharacterAnimatorShapeGradient2Base=65,105,225
CharacterAnimatorRegularHidden=1

CreativeShape=Hexagon
CreativeMaskMeter=Shape
CreativeMask=Regular Hexagon
CreativeMaskStyle=Blank
CreativeMaskBase=255,255,255
CreativeShapeGradient1Base=225,65,105
CreativeShapeGradient2Base=65,105,225
CreativeRegularHidden=1

DreamweaverShape=Hexagon
DreamweaverMaskMeter=Shape
DreamweaverMask=Regular Hexagon
DreamweaverMaskStyle=Blank
DreamweaverMaskBase=255,255,255
DreamweaverShapeGradient1Base=225,65,105
DreamweaverShapeGradient2Base=65,105,225
DreamweaverRegularHidden=1

FramemakerShape=Hexagon
FramemakerMaskMeter=Shape
FramemakerMask=Regular Hexagon
FramemakerMaskStyle=Blank
FramemakerMaskBase=255,255,255
FramemakerShapeGradient1Base=225,65,105
FramemakerShapeGradient2Base=65,105,225
FramemakerRegularHidden=1

FrescoShape=Hexagon
FrescoMaskMeter=Shape
FrescoMask=Regular Hexagon
FrescoMaskStyle=Blank
FrescoMaskBase=255,255,255
FrescoShapeGradient1Base=225,65,105
FrescoShapeGradient2Base=65,105,225
FrescoRegularHidden=1

IllustratorShape=Hexagon
IllustratorMaskMeter=Shape
IllustratorMask=Regular Hexagon
IllustratorMaskStyle=Blank
IllustratorMaskBase=255,255,255
IllustratorShapeGradient1Base=225,65,105
IllustratorShapeGradient2Base=65,105,225
IllustratorRegularHidden=1

InCopyShape=Hexagon
InCopyMaskMeter=Shape
InCopyMask=Regular Hexagon
InCopyMaskStyle=Blank
InCopyMaskBase=255,255,255
InCopyShapeGradient1Base=225,65,105
InCopyShapeGradient2Base=65,105,225
InCopyRegularHidden=1

InDesignShape=Hexagon
InDesignMaskMeter=Shape
InDesignMask=Regular Hexagon
InDesignMaskStyle=Blank
InDesignMaskBase=255,255,255
InDesignShapeGradient1Base=225,65,105
InDesignShapeGradient2Base=65,105,225
InDesignRegularHidden=1

LightroomShape=Hexagon
LightroomMaskMeter=Shape
LightroomMask=Regular Hexagon
LightroomMaskStyle=Blank
LightroomMaskBase=255,255,255
LightroomShapeGradient1Base=225,65,105
LightroomShapeGradient2Base=65,105,225
LightroomRegularHidden=1

MediaEncoderShape=Hexagon
MediaEncoderMaskMeter=Shape
MediaEncoderMask=Regular Hexagon
MediaEncoderMaskStyle=Blank
MediaEncoderMaskBase=255,255,255
MediaEncoderShapeGradient1Base=225,65,105
MediaEncoderShapeGradient2Base=65,105,225
MediaEncoderRegularHidden=1

PhotoshopShape=Hexagon
PhotoshopMaskMeter=Shape
PhotoshopMask=Regular Hexagon
PhotoshopMaskStyle=Blank
PhotoshopMaskBase=255,255,255
PhotoshopShapeGradient1Base=225,65,105
PhotoshopShapeGradient2Base=65,105,225
PhotoshopRegularHidden=1

PremiereShape=Hexagon
PremiereMaskMeter=Shape
PremiereMask=Regular Hexagon
PremiereMaskStyle=Blank
PremiereMaskBase=255,255,255
PremiereShapeGradient1Base=225,65,105
PremiereShapeGradient2Base=65,105,225
PremiereRegularHidden=1

S3DDesignerShape=Hexagon
S3DDesignerMaskMeter=Shape
S3DDesignerMask=Regular Hexagon
S3DDesignerMaskStyle=Blank
S3DDesignerMaskBase=255,255,255
S3DDesignerShapeGradient1Base=225,65,105
S3DDesignerShapeGradient2Base=65,105,225
S3DDesignerRegularHidden=1

S3DPainterShape=Hexagon
S3DPainterMaskMeter=Shape
S3DPainterMask=Regular Hexagon
S3DPainterMaskStyle=Blank
S3DPainterMaskBase=255,255,255
S3DPainterShapeGradient1Base=225,65,105
S3DPainterShapeGradient2Base=65,105,225
S3DPainterRegularHidden=1

S3DSamplerShape=Hexagon
S3DSamplerMaskMeter=Shape
S3DSamplerMask=Regular Hexagon
S3DSamplerMaskStyle=Blank
S3DSamplerMaskBase=255,255,255
S3DSamplerShapeGradient1Base=225,65,105
S3DSamplerShapeGradient2Base=65,105,225
S3DSamplerRegularHidden=1

S3DStagerShape=Hexagon
S3DStagerMaskMeter=Shape
S3DStagerMask=Regular Hexagon
S3DStagerMaskStyle=Blank
S3DStagerMaskBase=255,255,255
S3DStagerShapeGradient1Base=225,65,105
S3DStagerShapeGradient2Base=65,105,225
S3DStagerRegularHidden=1

XDShape=Hexagon
XDMaskMeter=Shape
XDMask=Regular Hexagon
XDMaskStyle=Blank
XDMaskBase=255,255,255
XDShapeGradient1Base=225,65,105
XDShapeGradient2Base=65,105,225
XDRegularHidden=1

; ============================================================
; Assassin's Creed
; ============================================================

AssassinsCreedShape=Hexagon
AssassinsCreedMaskMeter=Shape
AssassinsCreedMask=Regular Hexagon
AssassinsCreedMaskStyle=Blank
AssassinsCreedMaskBase=255,255,255
AssassinsCreedShapeGradient1Base=225,65,105
AssassinsCreedShapeGradient2Base=65,105,225
AssassinsCreedRegularHidden=1

ACRevelationsShape=Hexagon
ACRevelationsMaskMeter=Shape
ACRevelationsMask=Regular Hexagon
ACRevelationsMaskStyle=Blank
ACRevelationsMaskBase=255,255,255
ACRevelationsShapeGradient1Base=225,65,105
ACRevelationsShapeGradient2Base=65,105,225
ACRevelationsRegularHidden=1

AC3Shape=Hexagon
AC3MaskMeter=Shape
AC3Mask=Regular Hexagon
AC3MaskStyle=Blank
AC3MaskBase=255,255,255
AC3ShapeGradient1Base=225,65,105
AC3ShapeGradient2Base=65,105,225
AC3RegularHidden=1

ACRogueShape=Hexagon
ACRogueMaskMeter=Shape
ACRogueMask=Regular Hexagon
ACRogueMaskStyle=Blank
ACRogueMaskBase=255,255,255
ACRogueShapeGradient1Base=225,65,105
ACRogueShapeGradient2Base=65,105,225
ACRogueRegularHidden=1

AC4BlackFlagShape=Hexagon
AC4BlackFlagMaskMeter=Shape
AC4BlackFlagMask=Regular Hexagon
AC4BlackFlagMaskStyle=Blank
AC4BlackFlagMaskBase=255,255,255
AC4BlackFlagShapeGradient1Base=225,65,105
AC4BlackFlagShapeGradient2Base=65,105,225
AC4BlackFlagRegularHidden=1

ACUnityShape=Hexagon
ACUnityMaskMeter=Shape
ACUnityMask=Regular Hexagon
ACUnityMaskStyle=Blank
ACUnityMaskBase=255,255,255
ACUnityShapeGradient1Base=225,65,105
ACUnityShapeGradient2Base=65,105,225
ACUnityRegularHidden=1

ACSyndicateShape=Hexagon
ACSyndicateMaskMeter=Shape
ACSyndicateMask=Regular Hexagon
ACSyndicateMaskStyle=Blank
ACSyndicateMaskBase=255,255,255
ACSyndicateShapeGradient1Base=225,65,105
ACSyndicateShapeGradient2Base=65,105,225
ACSyndicateRegularHidden=1

ACOriginsShape=Hexagon
ACOriginsMaskMeter=Shape
ACOriginsMask=Regular Hexagon
ACOriginsMaskStyle=Blank
ACOriginsMaskBase=255,255,255
ACOriginsShapeGradient1Base=225,65,105
ACOriginsShapeGradient2Base=65,105,225
ACOriginsRegularHidden=1

ACOdysseyShape=Hexagon
ACOdysseyMaskMeter=Shape
ACOdysseyMask=Regular Hexagon
ACOdysseyMaskStyle=Blank
ACOdysseyMaskBase=255,255,255
ACOdysseyShapeGradient1Base=225,65,105
ACOdysseyShapeGradient2Base=65,105,225
ACOdysseyRegularHidden=1

ACValhallaShape=Hexagon
ACValhallaMaskMeter=Shape
ACValhallaMask=Regular Hexagon
ACValhallaMaskStyle=Blank
ACValhallaMaskBase=255,255,255
ACValhallaShapeGradient1Base=225,65,105
ACValhallaShapeGradient2Base=65,105,225
ACValhallaRegularHidden=1

; ============================================================
; Browsing
; ============================================================

BraveShape=Hexagon
BraveMaskMeter=Shape
BraveMask=Regular Hexagon
BraveMaskStyle=Blank
BraveMaskBase=255,255,255
BraveShapeGradient1Base=225,65,105
BraveShapeGradient2Base=65,105,225
BraveRegularHidden=1

ChromeShape=Hexagon
ChromeMaskMeter=Shape
ChromeMask=Regular Hexagon
ChromeMaskStyle=Blank
ChromeMaskBase=255,255,255
ChromeShapeGradient1Base=225,65,105
ChromeShapeGradient2Base=65,105,225
ChromeRegularHidden=1

EdgeShape=Hexagon
EdgeMaskMeter=Shape
EdgeMask=Regular Hexagon
EdgeMaskStyle=Blank
EdgeMaskBase=255,255,255
EdgeShapeGradient1Base=225,65,105
EdgeShapeGradient2Base=65,105,225
EdgeRegularHidden=1

FirefoxShape=Hexagon
FirefoxMaskMeter=Shape
FirefoxMask=Regular Hexagon
FirefoxMaskStyle=Blank
FirefoxMaskBase=255,255,255
FirefoxShapeGradient1Base=225,65,105
FirefoxShapeGradient2Base=65,105,225
FirefoxRegularHidden=1

OperaShape=Hexagon
OperaMaskMeter=Shape
OperaMask=Regular Hexagon
OperaMaskStyle=Blank
OperaMaskBase=255,255,255
OperaShapeGradient1Base=225,65,105
OperaShapeGradient2Base=65,105,225
OperaRegularHidden=1

OperaGXShape=Hexagon
OperaGXMaskMeter=Shape
OperaGXMask=Regular Hexagon
OperaGXMaskStyle=Blank
OperaGXMaskBase=255,255,255
OperaGXShapeGradient1Base=225,65,105
OperaGXShapeGradient2Base=65,105,225
OperaGXRegularHidden=1

SafariShape=Hexagon
SafariMaskMeter=Shape
SafariMask=Regular Hexagon
SafariMaskStyle=Blank
SafariMaskBase=255,255,255
SafariShapeGradient1Base=225,65,105
SafariShapeGradient2Base=65,105,225
SafariRegularHidden=1

TorShape=Hexagon
TorMaskMeter=Shape
TorMask=Regular Hexagon
TorMaskStyle=Blank
TorMaskBase=255,255,255
TorShapeGradient1Base=225,65,105
TorShapeGradient2Base=65,105,225
TorRegularHidden=1

VivaldiShape=Hexagon
VivaldiMaskMeter=Shape
VivaldiMask=Regular Hexagon
VivaldiMaskStyle=Blank
VivaldiMaskBase=255,255,255
VivaldiShapeGradient1Base=225,65,105
VivaldiShapeGradient2Base=65,105,225
VivaldiRegularHidden=1

; ============================================================
; Disk
; ============================================================

DiskAShape=Hexagon
DiskAMaskMeter=Shape
DiskAMask=Regular Hexagon
DiskAMaskStyle=Blank
DiskAMaskBase=255,255,255
DiskAShapeGradient1Base=225,65,105
DiskAShapeGradient2Base=65,105,225
DiskARegularHidden=1

DiskBShape=Hexagon
DiskBMaskMeter=Shape
DiskBMask=Regular Hexagon
DiskBMaskStyle=Blank
DiskBMaskBase=255,255,255
DiskBShapeGradient1Base=225,65,105
DiskBShapeGradient2Base=65,105,225
DiskBRegularHidden=1

DiskCShape=Hexagon
DiskCMaskMeter=Shape
DiskCMask=Regular Hexagon
DiskCMaskStyle=Blank
DiskCMaskBase=255,255,255
DiskCShapeGradient1Base=225,65,105
DiskCShapeGradient2Base=65,105,225
DiskCRegularHidden=1

DiskDShape=Hexagon
DiskDMaskMeter=Shape
DiskDMask=Regular Hexagon
DiskDMaskStyle=Blank
DiskDMaskBase=255,255,255
DiskDShapeGradient1Base=225,65,105
DiskDShapeGradient2Base=65,105,225
DiskDRegularHidden=1

DiskEShape=Hexagon
DiskEMaskMeter=Shape
DiskEMask=Regular Hexagon
DiskEMaskStyle=Blank
DiskEMaskBase=255,255,255
DiskEShapeGradient1Base=225,65,105
DiskEShapeGradient2Base=65,105,225
DiskERegularHidden=1

DiskFShape=Hexagon
DiskFMaskMeter=Shape
DiskFMask=Regular Hexagon
DiskFMaskStyle=Blank
DiskFMaskBase=255,255,255
DiskFShapeGradient1Base=225,65,105
DiskFShapeGradient2Base=65,105,225
DiskFRegularHidden=1

DiskGShape=Hexagon
DiskGMaskMeter=Shape
DiskGMask=Regular Hexagon
DiskGMaskStyle=Blank
DiskGMaskBase=255,255,255
DiskGShapeGradient1Base=225,65,105
DiskGShapeGradient2Base=65,105,225
DiskGRegularHidden=1

DiskHShape=Hexagon
DiskHMaskMeter=Shape
DiskHMask=Regular Hexagon
DiskHMaskStyle=Blank
DiskHMaskBase=255,255,255
DiskHShapeGradient1Base=225,65,105
DiskHShapeGradient2Base=65,105,225
DiskHRegularHidden=1

DiskIShape=Hexagon
DiskIMaskMeter=Shape
DiskIMask=Regular Hexagon
DiskIMaskStyle=Blank
DiskIMaskBase=255,255,255
DiskIShapeGradient1Base=225,65,105
DiskIShapeGradient2Base=65,105,225
DiskIRegularHidden=1

DiskJShape=Hexagon
DiskJMaskMeter=Shape
DiskJMask=Regular Hexagon
DiskJMaskStyle=Blank
DiskJMaskBase=255,255,255
DiskJShapeGradient1Base=225,65,105
DiskJShapeGradient2Base=65,105,225
DiskJRegularHidden=1

DiskKShape=Hexagon
DiskKMaskMeter=Shape
DiskKMask=Regular Hexagon
DiskKMaskStyle=Blank
DiskKMaskBase=255,255,255
DiskKShapeGradient1Base=225,65,105
DiskKShapeGradient2Base=65,105,225
DiskKRegularHidden=1

DiskLShape=Hexagon
DiskLMaskMeter=Shape
DiskLMask=Regular Hexagon
DiskLMaskStyle=Blank
DiskLMaskBase=255,255,255
DiskLShapeGradient1Base=225,65,105
DiskLShapeGradient2Base=65,105,225
DiskLRegularHidden=1

DiskMShape=Hexagon
DiskMMaskMeter=Shape
DiskMMask=Regular Hexagon
DiskMMaskStyle=Blank
DiskMMaskBase=255,255,255
DiskMShapeGradient1Base=225,65,105
DiskMShapeGradient2Base=65,105,225
DiskMRegularHidden=1

DiskNShape=Hexagon
DiskNMaskMeter=Shape
DiskNMask=Regular Hexagon
DiskNMaskStyle=Blank
DiskNMaskBase=255,255,255
DiskNShapeGradient1Base=225,65,105
DiskNShapeGradient2Base=65,105,225
DiskNRegularHidden=1

DiskOShape=Hexagon
DiskOMaskMeter=Shape
DiskOMask=Regular Hexagon
DiskOMaskStyle=Blank
DiskOMaskBase=255,255,255
DiskOShapeGradient1Base=225,65,105
DiskOShapeGradient2Base=65,105,225
DiskORegularHidden=1

DiskPShape=Hexagon
DiskPMaskMeter=Shape
DiskPMask=Regular Hexagon
DiskPMaskStyle=Blank
DiskPMaskBase=255,255,255
DiskPShapeGradient1Base=225,65,105
DiskPShapeGradient2Base=65,105,225
DiskPRegularHidden=1

DiskQShape=Hexagon
DiskQMaskMeter=Shape
DiskQMask=Regular Hexagon
DiskQMaskStyle=Blank
DiskQMaskBase=255,255,255
DiskQShapeGradient1Base=225,65,105
DiskQShapeGradient2Base=65,105,225
DiskQRegularHidden=1

DiskRShape=Hexagon
DiskRMaskMeter=Shape
DiskRMask=Regular Hexagon
DiskRMaskStyle=Blank
DiskRMaskBase=255,255,255
DiskRShapeGradient1Base=225,65,105
DiskRShapeGradient2Base=65,105,225
DiskRRegularHidden=1

DiskSShape=Hexagon
DiskSMaskMeter=Shape
DiskSMask=Regular Hexagon
DiskSMaskStyle=Blank
DiskSMaskBase=255,255,255
DiskSShapeGradient1Base=225,65,105
DiskSShapeGradient2Base=65,105,225
DiskSRegularHidden=1

DiskTShape=Hexagon
DiskTMaskMeter=Shape
DiskTMask=Regular Hexagon
DiskTMaskStyle=Blank
DiskTMaskBase=255,255,255
DiskTShapeGradient1Base=225,65,105
DiskTShapeGradient2Base=65,105,225
DiskTRegularHidden=1

DiskUShape=Hexagon
DiskUMaskMeter=Shape
DiskUMask=Regular Hexagon
DiskUMaskStyle=Blank
DiskUMaskBase=255,255,255
DiskUShapeGradient1Base=225,65,105
DiskUShapeGradient2Base=65,105,225
DiskURegularHidden=1

DiskVShape=Hexagon
DiskVMaskMeter=Shape
DiskVMask=Regular Hexagon
DiskVMaskStyle=Blank
DiskVMaskBase=255,255,255
DiskVShapeGradient1Base=225,65,105
DiskVShapeGradient2Base=65,105,225
DiskVRegularHidden=1

DiskWShape=Hexagon
DiskWMaskMeter=Shape
DiskWMask=Regular Hexagon
DiskWMaskStyle=Blank
DiskWMaskBase=255,255,255
DiskWShapeGradient1Base=225,65,105
DiskWShapeGradient2Base=65,105,225
DiskWRegularHidden=1

DiskXShape=Hexagon
DiskXMaskMeter=Shape
DiskXMask=Regular Hexagon
DiskXMaskStyle=Blank
DiskXMaskBase=255,255,255
DiskXShapeGradient1Base=225,65,105
DiskXShapeGradient2Base=65,105,225
DiskXRegularHidden=1

DiskYShape=Hexagon
DiskYMaskMeter=Shape
DiskYMask=Regular Hexagon
DiskYMaskStyle=Blank
DiskYMaskBase=255,255,255
DiskYShapeGradient1Base=225,65,105
DiskYShapeGradient2Base=65,105,225
DiskYRegularHidden=1

DiskZShape=Hexagon
DiskZMaskMeter=Shape
DiskZMask=Regular Hexagon
DiskZMaskStyle=Blank
DiskZMaskBase=255,255,255
DiskZShapeGradient1Base=225,65,105
DiskZShapeGradient2Base=65,105,225
DiskZRegularHidden=1

; ============================================================
; Elgato
; ============================================================

4KCUShape=Hexagon
4KCUMaskMeter=Shape
4KCUMask=Regular Hexagon
4KCUMaskStyle=Blank
4KCUMaskBase=255,255,255
4KCUShapeGradient1Base=225,65,105
4KCUShapeGradient2Base=65,105,225
4KCURegularHidden=1

CameraHubShape=Hexagon
CameraHubMaskMeter=Shape
CameraHubMask=Regular Hexagon
CameraHubMaskStyle=Blank
CameraHubMaskBase=255,255,255
CameraHubShapeGradient1Base=225,65,105
CameraHubShapeGradient2Base=65,105,225
CameraHubRegularHidden=1

ControlCenterShape=Hexagon
ControlCenterMaskMeter=Shape
ControlCenterMask=Regular Hexagon
ControlCenterMaskStyle=Blank
ControlCenterMaskBase=255,255,255
ControlCenterShapeGradient1Base=225,65,105
ControlCenterShapeGradient2Base=65,105,225
ControlCenterRegularHidden=1

GameCaptureShape=Hexagon
GameCaptureMaskMeter=Shape
GameCaptureMask=Regular Hexagon
GameCaptureMaskStyle=Blank
GameCaptureMaskBase=255,255,255
GameCaptureShapeGradient1Base=225,65,105
GameCaptureShapeGradient2Base=65,105,225
GameCaptureRegularHidden=1

StreamDeckShape=Hexagon
StreamDeckMaskMeter=Shape
StreamDeckMask=Regular Hexagon
StreamDeckMaskStyle=Blank
StreamDeckMaskBase=255,255,255
StreamDeckShapeGradient1Base=225,65,105
StreamDeckShapeGradient2Base=65,105,225
StreamDeckRegularHidden=1

VideoCaptureShape=Hexagon
VideoCaptureMaskMeter=Shape
VideoCaptureMask=Regular Hexagon
VideoCaptureMaskStyle=Blank
VideoCaptureMaskBase=255,255,255
VideoCaptureShapeGradient1Base=225,65,105
VideoCaptureShapeGradient2Base=65,105,225
VideoCaptureRegularHidden=1

WaveLinkShape=Hexagon
WaveLinkMaskMeter=Shape
WaveLinkMask=Regular Hexagon
WaveLinkMaskStyle=Blank
WaveLinkMaskBase=255,255,255
WaveLinkShapeGradient1Base=225,65,105
WaveLinkShapeGradient2Base=65,105,225
WaveLinkRegularHidden=1

; ============================================================
; Emulator
; ============================================================

BlueStacksShape=Hexagon
BlueStacksMaskMeter=Shape
BlueStacksMask=Regular Hexagon
BlueStacksMaskStyle=Blank
BlueStacksMaskBase=255,255,255
BlueStacksShapeGradient1Base=225,65,105
BlueStacksShapeGradient2Base=65,105,225
BlueStacksRegularHidden=1

BlueStacksXShape=Hexagon
BlueStacksXMaskMeter=Shape
BlueStacksXMask=Regular Hexagon
BlueStacksXMaskStyle=Blank
BlueStacksXMaskBase=255,255,255
BlueStacksXShapeGradient1Base=225,65,105
BlueStacksXShapeGradient2Base=65,105,225
BlueStacksXRegularHidden=1

CemuShape=Hexagon
CemuMaskMeter=Shape
CemuMask=Regular Hexagon
CemuMaskStyle=Blank
CemuMaskBase=255,255,255
CemuShapeGradient1Base=225,65,105
CemuShapeGradient2Base=65,105,225
CemuRegularHidden=1

CitraShape=Hexagon
CitraMaskMeter=Shape
CitraMask=Regular Hexagon
CitraMaskStyle=Blank
CitraMaskBase=255,255,255
CitraShapeGradient1Base=225,65,105
CitraShapeGradient2Base=65,105,225
CitraRegularHidden=1

DeSmuMEShape=Hexagon
DeSmuMEMaskMeter=Shape
DeSmuMEMask=Regular Hexagon
DeSmuMEMaskStyle=Blank
DeSmuMEMaskBase=255,255,255
DeSmuMEShapeGradient1Base=225,65,105
DeSmuMEShapeGradient2Base=65,105,225
DeSmuMERegularHidden=1

DolphinShape=Hexagon
DolphinMaskMeter=Shape
DolphinMask=Regular Hexagon
DolphinMaskStyle=Blank
DolphinMaskBase=255,255,255
DolphinShapeGradient1Base=225,65,105
DolphinShapeGradient2Base=65,105,225
DolphinRegularHidden=1

DuckStationShape=Hexagon
DuckStationMaskMeter=Shape
DuckStationMask=Regular Hexagon
DuckStationMaskStyle=Blank
DuckStationMaskBase=255,255,255
DuckStationShapeGradient1Base=225,65,105
DuckStationShapeGradient2Base=65,105,225
DuckStationRegularHidden=1

LaunchBoxShape=Hexagon
LaunchBoxMaskMeter=Shape
LaunchBoxMask=Regular Hexagon
LaunchBoxMaskStyle=Blank
LaunchBoxMaskBase=255,255,255
LaunchBoxShapeGradient1Base=225,65,105
LaunchBoxShapeGradient2Base=65,105,225
LaunchBoxRegularHidden=1

PCSX2Shape=Hexagon
PCSX2MaskMeter=Shape
PCSX2Mask=Regular Hexagon
PCSX2MaskStyle=Blank
PCSX2MaskBase=255,255,255
PCSX2ShapeGradient1Base=225,65,105
PCSX2ShapeGradient2Base=65,105,225
PCSX2RegularHidden=1

PPSSPPShape=Hexagon
PPSSPPMaskMeter=Shape
PPSSPPMask=Regular Hexagon
PPSSPPMaskStyle=Blank
PPSSPPMaskBase=255,255,255
PPSSPPShapeGradient1Base=225,65,105
PPSSPPShapeGradient2Base=65,105,225
PPSSPPRegularHidden=1

RPCS3Shape=Hexagon
RPCS3MaskMeter=Shape
RPCS3Mask=Regular Hexagon
RPCS3MaskStyle=Blank
RPCS3MaskBase=255,255,255
RPCS3ShapeGradient1Base=225,65,105
RPCS3ShapeGradient2Base=65,105,225
RPCS3RegularHidden=1

Vita3KShape=Hexagon
Vita3KMaskMeter=Shape
Vita3KMask=Regular Hexagon
Vita3KMaskStyle=Blank
Vita3KMaskBase=255,255,255
Vita3KShapeGradient1Base=225,65,105
Vita3KShapeGradient2Base=65,105,225
Vita3KRegularHidden=1

XeniaShape=Hexagon
XeniaMaskMeter=Shape
XeniaMask=Regular Hexagon
XeniaMaskStyle=Blank
XeniaMaskBase=255,255,255
XeniaShapeGradient1Base=225,65,105
XeniaShapeGradient2Base=65,105,225
XeniaRegularHidden=1

YuzuShape=Hexagon
YuzuMaskMeter=Shape
YuzuMask=Regular Hexagon
YuzuMaskStyle=Blank
YuzuMaskBase=255,255,255
YuzuShapeGradient1Base=225,65,105
YuzuShapeGradient2Base=65,105,225
YuzuRegularHidden=1

; ============================================================
; Gaming
; ============================================================

ADFIShape=Hexagon
ADFIMaskMeter=Shape
ADFIMask=Regular Hexagon
ADFIMaskStyle=Blank
ADFIMaskBase=255,255,255
ADFIShapeGradient1Base=225,65,105
ADFIShapeGradient2Base=65,105,225
ADFIRegularHidden=1

AimlabShape=Hexagon
AimlabMaskMeter=Shape
AimlabMask=Regular Hexagon
AimlabMaskStyle=Blank
AimlabMaskBase=255,255,255
AimlabShapeGradient1Base=225,65,105
AimlabShapeGradient2Base=65,105,225
AimlabRegularHidden=1

AmongUsShape=Hexagon
AmongUsMaskMeter=Shape
AmongUsMask=Regular Hexagon
AmongUsMaskStyle=Blank
AmongUsMaskBase=255,255,255
AmongUsShapeGradient1Base=225,65,105
AmongUsShapeGradient2Base=65,105,225
AmongUsRegularHidden=1

ApexShape=Hexagon
ApexMaskMeter=Shape
ApexMask=Regular Hexagon
ApexMaskStyle=Blank
ApexMaskBase=255,255,255
ApexShapeGradient1Base=225,65,105
ApexShapeGradient2Base=65,105,225
ApexRegularHidden=1

ArkShape=Hexagon
ArkMaskMeter=Shape
ArkMask=Regular Hexagon
ArkMaskStyle=Blank
ArkMaskBase=255,255,255
ArkShapeGradient1Base=225,65,105
ArkShapeGradient2Base=65,105,225
ArkRegularHidden=1

AssettoShape=Hexagon
AssettoMaskMeter=Shape
AssettoMask=Regular Hexagon
AssettoMaskStyle=Blank
AssettoMaskBase=255,255,255
AssettoShapeGradient1Base=225,65,105
AssettoShapeGradient2Base=65,105,225
AssettoRegularHidden=1

AvenColonyShape=Hexagon
AvenColonyMaskMeter=Shape
AvenColonyMask=Regular Hexagon
AvenColonyMaskStyle=Blank
AvenColonyMaskBase=255,255,255
AvenColonyShapeGradient1Base=225,65,105
AvenColonyShapeGradient2Base=65,105,225
AvenColonyRegularHidden=1

BattleNetShape=Hexagon
BattleNetMaskMeter=Shape
BattleNetMask=Regular Hexagon
BattleNetMaskStyle=Blank
BattleNetMaskBase=255,255,255
BattleNetShapeGradient1Base=225,65,105
BattleNetShapeGradient2Base=65,105,225
BattleNetRegularHidden=1

BF1Shape=Hexagon
BF1MaskMeter=Shape
BF1Mask=Regular Hexagon
BF1MaskStyle=Blank
BF1MaskBase=255,255,255
BF1ShapeGradient1Base=225,65,105
BF1ShapeGradient2Base=65,105,225
BF1RegularHidden=1

BF4Shape=Hexagon
BF4MaskMeter=Shape
BF4Mask=Regular Hexagon
BF4MaskStyle=Blank
BF4MaskBase=255,255,255
BF4ShapeGradient1Base=225,65,105
BF4ShapeGradient2Base=65,105,225
BF4RegularHidden=1

BF2042Shape=Hexagon
BF2042MaskMeter=Shape
BF2042Mask=Regular Hexagon
BF2042MaskStyle=Blank
BF2042MaskBase=255,255,255
BF2042ShapeGradient1Base=225,65,105
BF2042ShapeGradient2Base=65,105,225
BF2042RegularHidden=1

BFVShape=Hexagon
BFVMaskMeter=Shape
BFVMask=Regular Hexagon
BFVMaskStyle=Blank
BFVMaskBase=255,255,255
BFVShapeGradient1Base=225,65,105
BFVShapeGradient2Base=65,105,225
BFVRegularHidden=1

BDOShape=Hexagon
BDOMaskMeter=Shape
BDOMask=Regular Hexagon
BDOMaskStyle=Blank
BDOMaskBase=255,255,255
BDOShapeGradient1Base=225,65,105
BDOShapeGradient2Base=65,105,225
BDORegularHidden=1

BTD6Shape=Hexagon
BTD6MaskMeter=Shape
BTD6Mask=Regular Hexagon
BTD6MaskStyle=Blank
BTD6MaskBase=255,255,255
BTD6ShapeGradient1Base=225,65,105
BTD6ShapeGradient2Base=65,105,225
BTD6RegularHidden=1

Borderlands3Shape=Hexagon
Borderlands3MaskMeter=Shape
Borderlands3Mask=Regular Hexagon
Borderlands3MaskStyle=Blank
Borderlands3MaskBase=255,255,255
Borderlands3ShapeGradient1Base=225,65,105
Borderlands3ShapeGradient2Base=65,105,225
Borderlands3RegularHidden=1

CODMWShape=Hexagon
CODMWMaskMeter=Shape
CODMWMask=Regular Hexagon
CODMWMaskStyle=Blank
CODMWMaskBase=255,255,255
CODMWShapeGradient1Base=225,65,105
CODMWShapeGradient2Base=65,105,225
CODMWRegularHidden=1

CODVanguardShape=Hexagon
CODVanguardMaskMeter=Shape
CODVanguardMask=Regular Hexagon
CODVanguardMaskStyle=Blank
CODVanguardMaskBase=255,255,255
CODVanguardShapeGradient1Base=225,65,105
CODVanguardShapeGradient2Base=65,105,225
CODVanguardRegularHidden=1

CelesteShape=Hexagon
CelesteMaskMeter=Shape
CelesteMask=Regular Hexagon
CelesteMaskStyle=Blank
CelesteMaskBase=255,255,255
CelesteShapeGradient1Base=225,65,105
CelesteShapeGradient2Base=65,105,225
CelesteRegularHidden=1

CloneHeroShape=Hexagon
CloneHeroMaskMeter=Shape
CloneHeroMask=Regular Hexagon
CloneHeroMaskStyle=Blank
CloneHeroMaskBase=255,255,255
CloneHeroShapeGradient1Base=225,65,105
CloneHeroShapeGradient2Base=65,105,225
CloneHeroRegularHidden=1

CoreGamesShape=Hexagon
CoreGamesMaskMeter=Shape
CoreGamesMask=Regular Hexagon
CoreGamesMaskStyle=Blank
CoreGamesMaskBase=255,255,255
CoreGamesShapeGradient1Base=225,65,105
CoreGamesShapeGradient2Base=65,105,225
CoreGamesRegularHidden=1

CSGOShape=Hexagon
CSGOMaskMeter=Shape
CSGOMask=Regular Hexagon
CSGOMaskStyle=Blank
CSGOMaskBase=255,255,255
CSGOShapeGradient1Base=225,65,105
CSGOShapeGradient2Base=65,105,225
CSGORegularHidden=1

COTLShape=Hexagon
COTLMaskMeter=Shape
COTLMask=Regular Hexagon
COTLMaskStyle=Blank
COTLMaskBase=255,255,255
COTLShapeGradient1Base=225,65,105
COTLShapeGradient2Base=65,105,225
COTLRegularHidden=1

CyberpunkShape=Hexagon
CyberpunkMaskMeter=Shape
CyberpunkMask=Regular Hexagon
CyberpunkMaskStyle=Blank
CyberpunkMaskBase=255,255,255
CyberpunkShapeGradient1Base=225,65,105
CyberpunkShapeGradient2Base=65,105,225
CyberpunkRegularHidden=1

DauntlessShape=Hexagon
DauntlessMaskMeter=Shape
DauntlessMask=Regular Hexagon
DauntlessMaskStyle=Blank
DauntlessMaskBase=255,255,255
DauntlessShapeGradient1Base=225,65,105
DauntlessShapeGradient2Base=65,105,225
DauntlessRegularHidden=1

DBDShape=Hexagon
DBDMaskMeter=Shape
DBDMask=Regular Hexagon
DBDMaskStyle=Blank
DBDMaskBase=255,255,255
DBDShapeGradient1Base=225,65,105
DBDShapeGradient2Base=65,105,225
DBDRegularHidden=1

DeathloopShape=Hexagon
DeathloopMaskMeter=Shape
DeathloopMask=Regular Hexagon
DeathloopMaskStyle=Blank
DeathloopMaskBase=255,255,255
DeathloopShapeGradient1Base=225,65,105
DeathloopShapeGradient2Base=65,105,225
DeathloopRegularHidden=1

Destiny2Shape=Hexagon
Destiny2MaskMeter=Shape
Destiny2Mask=Regular Hexagon
Destiny2MaskStyle=Blank
Destiny2MaskBase=255,255,255
Destiny2ShapeGradient1Base=225,65,105
Destiny2ShapeGradient2Base=65,105,225
Destiny2RegularHidden=1

DOOMShape=Hexagon
DOOMMaskMeter=Shape
DOOMMask=Regular Hexagon
DOOMMaskStyle=Blank
DOOMMaskBase=255,255,255
DOOMShapeGradient1Base=225,65,105
DOOMShapeGradient2Base=65,105,225
DOOMRegularHidden=1

DOOMEternalShape=Hexagon
DOOMEternalMaskMeter=Shape
DOOMEternalMask=Regular Hexagon
DOOMEternalMaskStyle=Blank
DOOMEternalMaskBase=255,255,255
DOOMEternalShapeGradient1Base=225,65,105
DOOMEternalShapeGradient2Base=65,105,225
DOOMEternalRegularHidden=1

DotaShape=Hexagon
DotaMaskMeter=Shape
DotaMask=Regular Hexagon
DotaMaskStyle=Blank
DotaMaskBase=255,255,255
DotaShapeGradient1Base=225,65,105
DotaShapeGradient2Base=65,105,225
DotaRegularHidden=1

DRGShape=Hexagon
DRGMaskMeter=Shape
DRGMask=Regular Hexagon
DRGMaskStyle=Blank
DRGMaskBase=255,255,255
DRGShapeGradient1Base=225,65,105
DRGShapeGradient2Base=65,105,225
DRGRegularHidden=1

EldenRingShape=Hexagon
EldenRingMaskMeter=Shape
EldenRingMask=Regular Hexagon
EldenRingMaskStyle=Blank
EldenRingMaskBase=255,255,255
EldenRingShapeGradient1Base=225,65,105
EldenRingShapeGradient2Base=65,105,225
EldenRingRegularHidden=1

EFTShape=Hexagon
EFTMaskMeter=Shape
EFTMask=Regular Hexagon
EFTMaskStyle=Blank
EFTMaskBase=255,255,255
EFTShapeGradient1Base=225,65,105
EFTShapeGradient2Base=65,105,225
EFTRegularHidden=1

EGLauncherShape=Hexagon
EGLauncherMaskMeter=Shape
EGLauncherMask=Regular Hexagon
EGLauncherMaskStyle=Blank
EGLauncherMaskBase=255,255,255
EGLauncherShapeGradient1Base=225,65,105
EGLauncherShapeGradient2Base=65,105,225
EGLauncherRegularHidden=1

ESOShape=Hexagon
ESOMaskMeter=Shape
ESOMask=Regular Hexagon
ESOMaskStyle=Blank
ESOMaskBase=255,255,255
ESOShapeGradient1Base=225,65,105
ESOShapeGradient2Base=65,105,225
ESORegularHidden=1

ESVSkyrimShape=Hexagon
ESVSkyrimMaskMeter=Shape
ESVSkyrimMask=Regular Hexagon
ESVSkyrimMaskStyle=Blank
ESVSkyrimMaskBase=255,255,255
ESVSkyrimShapeGradient1Base=225,65,105
ESVSkyrimShapeGradient2Base=65,105,225
ESVSkyrimRegularHidden=1

FactorioShape=Hexagon
FactorioMaskMeter=Shape
FactorioMask=Regular Hexagon
FactorioMaskStyle=Blank
FactorioMaskBase=255,255,255
FactorioShapeGradient1Base=225,65,105
FactorioShapeGradient2Base=65,105,225
FactorioRegularHidden=1

FallGuysShape=Hexagon
FallGuysMaskMeter=Shape
FallGuysMask=Regular Hexagon
FallGuysMaskStyle=Blank
FallGuysMaskBase=255,255,255
FallGuysShapeGradient1Base=225,65,105
FallGuysShapeGradient2Base=65,105,225
FallGuysRegularHidden=1

FC3Shape=Hexagon
FC3MaskMeter=Shape
FC3Mask=Regular Hexagon
FC3MaskStyle=Blank
FC3MaskBase=255,255,255
FC3ShapeGradient1Base=225,65,105
FC3ShapeGradient2Base=65,105,225
FC3RegularHidden=1

FC3BDShape=Hexagon
FC3BDMaskMeter=Shape
FC3BDMask=Regular Hexagon
FC3BDMaskStyle=Blank
FC3BDMaskBase=255,255,255
FC3BDShapeGradient1Base=225,65,105
FC3BDShapeGradient2Base=65,105,225
FC3BDRegularHidden=1

FNAFSBShape=Hexagon
FNAFSBMaskMeter=Shape
FNAFSBMask=Regular Hexagon
FNAFSBMaskStyle=Blank
FNAFSBMaskBase=255,255,255
FNAFSBShapeGradient1Base=225,65,105
FNAFSBShapeGradient2Base=65,105,225
FNAFSBRegularHidden=1

FFXIVShape=Hexagon
FFXIVMaskMeter=Shape
FFXIVMask=Regular Hexagon
FFXIVMaskStyle=Blank
FFXIVMaskBase=255,255,255
FFXIVShapeGradient1Base=225,65,105
FFXIVShapeGradient2Base=65,105,225
FFXIVRegularHidden=1

FNFShape=Hexagon
FNFMaskMeter=Shape
FNFMask=Regular Hexagon
FNFMaskStyle=Blank
FNFMaskBase=255,255,255
FNFShapeGradient1Base=225,65,105
FNFShapeGradient2Base=65,105,225
FNFRegularHidden=1

FortniteShape=Hexagon
FortniteMaskMeter=Shape
FortniteMask=Regular Hexagon
FortniteMaskStyle=Blank
FortniteMaskBase=255,255,255
FortniteShapeGradient1Base=225,65,105
FortniteShapeGradient2Base=65,105,225
FortniteRegularHidden=1

FH3Shape=Hexagon
FH3MaskMeter=Shape
FH3Mask=Regular Hexagon
FH3MaskStyle=Blank
FH3MaskBase=255,255,255
FH3ShapeGradient1Base=225,65,105
FH3ShapeGradient2Base=65,105,225
FH3RegularHidden=1

FH4Shape=Hexagon
FH4MaskMeter=Shape
FH4Mask=Regular Hexagon
FH4MaskStyle=Blank
FH4MaskBase=255,255,255
FH4ShapeGradient1Base=225,65,105
FH4ShapeGradient2Base=65,105,225
FH4RegularHidden=1

FH5Shape=Hexagon
FH5MaskMeter=Shape
FH5Mask=Regular Hexagon
FH5MaskStyle=Blank
FH5MaskBase=255,255,255
FH5ShapeGradient1Base=225,65,105
FH5ShapeGradient2Base=65,105,225
FH5RegularHidden=1

FM7Shape=Hexagon
FM7MaskMeter=Shape
FM7Mask=Regular Hexagon
FM7MaskStyle=Blank
FM7MaskBase=255,255,255
FM7ShapeGradient1Base=225,65,105
FM7ShapeGradient2Base=65,105,225
FM7RegularHidden=1

GameLibrariesShape=Hexagon
GameLibrariesMaskMeter=Shape
GameLibrariesMask=Regular Hexagon
GameLibrariesMaskStyle=Blank
GameLibrariesMaskBase=255,255,255
GameLibrariesShapeGradient1Base=225,65,105
GameLibrariesShapeGradient2Base=65,105,225
GameLibrariesRegularHidden=1

GameHUB2Shape=Hexagon
GameHUB2MaskMeter=Shape
GameHUB2Mask=Regular Hexagon
GameHUB2MaskStyle=Blank
GameHUB2MaskBase=255,255,255
GameHUB2ShapeGradient1Base=225,65,105
GameHUB2ShapeGradient2Base=65,105,225
GameHUB2RegularHidden=1

GModShape=Hexagon
GModMaskMeter=Shape
GModMask=Regular Hexagon
GModMaskStyle=Blank
GModMaskBase=255,255,255
GModShapeGradient1Base=225,65,105
GModShapeGradient2Base=65,105,225
GModRegularHidden=1

GenshinShape=Hexagon
GenshinMaskMeter=Shape
GenshinMask=Regular Hexagon
GenshinMaskStyle=Blank
GenshinMaskBase=255,255,255
GenshinShapeGradient1Base=225,65,105
GenshinShapeGradient2Base=65,105,225
GenshinRegularHidden=1

GhostrunnerShape=Hexagon
GhostrunnerMaskMeter=Shape
GhostrunnerMask=Regular Hexagon
GhostrunnerMaskStyle=Blank
GhostrunnerMaskBase=255,255,255
GhostrunnerShapeGradient1Base=225,65,105
GhostrunnerShapeGradient2Base=65,105,225
GhostrunnerRegularHidden=1

GOWShape=Hexagon
GOWMaskMeter=Shape
GOWMask=Regular Hexagon
GOWMaskStyle=Blank
GOWMaskBase=255,255,255
GOWShapeGradient1Base=225,65,105
GOWShapeGradient2Base=65,105,225
GOWRegularHidden=1

GodfallShape=Hexagon
GodfallMaskMeter=Shape
GodfallMask=Regular Hexagon
GodfallMaskStyle=Blank
GodfallMaskBase=255,255,255
GodfallShapeGradient1Base=225,65,105
GodfallShapeGradient2Base=65,105,225
GodfallRegularHidden=1

GOGShape=Hexagon
GOGMaskMeter=Shape
GOGMask=Regular Hexagon
GOGMaskStyle=Blank
GOGMaskBase=255,255,255
GOGShapeGradient1Base=225,65,105
GOGShapeGradient2Base=65,105,225
GOGRegularHidden=1

GPGamesShape=Hexagon
GPGamesMaskMeter=Shape
GPGamesMask=Regular Hexagon
GPGamesMaskStyle=Blank
GPGamesMaskBase=255,255,255
GPGamesShapeGradient1Base=225,65,105
GPGamesShapeGradient2Base=65,105,225
GPGamesRegularHidden=1

GTAVShape=Hexagon
GTAVMaskMeter=Shape
GTAVMask=Regular Hexagon
GTAVMaskStyle=Blank
GTAVMaskBase=255,255,255
GTAVShapeGradient1Base=225,65,105
GTAVShapeGradient2Base=65,105,225
GTAVRegularHidden=1

GuiltyGearShape=Hexagon
GuiltyGearMaskMeter=Shape
GuiltyGearMask=Regular Hexagon
GuiltyGearMaskStyle=Blank
GuiltyGearMaskBase=255,255,255
GuiltyGearShapeGradient1Base=225,65,105
GuiltyGearShapeGradient2Base=65,105,225
GuiltyGearRegularHidden=1

GW2Shape=Hexagon
GW2MaskMeter=Shape
GW2Mask=Regular Hexagon
GW2MaskStyle=Blank
GW2MaskBase=255,255,255
GW2ShapeGradient1Base=225,65,105
GW2ShapeGradient2Base=65,105,225
GW2RegularHidden=1

HaloInfiniteShape=Hexagon
HaloInfiniteMaskMeter=Shape
HaloInfiniteMask=Regular Hexagon
HaloInfiniteMaskStyle=Blank
HaloInfiniteMaskBase=255,255,255
HaloInfiniteShapeGradient1Base=225,65,105
HaloInfiniteShapeGradient2Base=65,105,225
HaloInfiniteRegularHidden=1

HearthstoneShape=Hexagon
HearthstoneMaskMeter=Shape
HearthstoneMask=Regular Hexagon
HearthstoneMaskStyle=Blank
HearthstoneMaskBase=255,255,255
HearthstoneShapeGradient1Base=225,65,105
HearthstoneShapeGradient2Base=65,105,225
HearthstoneRegularHidden=1

HOI4Shape=Hexagon
HOI4MaskMeter=Shape
HOI4Mask=Regular Hexagon
HOI4MaskStyle=Blank
HOI4MaskBase=255,255,255
HOI4ShapeGradient1Base=225,65,105
HOI4ShapeGradient2Base=65,105,225
HOI4RegularHidden=1

HOTSShape=Hexagon
HOTSMaskMeter=Shape
HOTSMask=Regular Hexagon
HOTSMaskStyle=Blank
HOTSMaskBase=255,255,255
HOTSShapeGradient1Base=225,65,105
HOTSShapeGradient2Base=65,105,225
HOTSRegularHidden=1

HollowKnightShape=Hexagon
HollowKnightMaskMeter=Shape
HollowKnightMask=Regular Hexagon
HollowKnightMaskStyle=Blank
HollowKnightMaskBase=255,255,255
HollowKnightShapeGradient1Base=225,65,105
HollowKnightShapeGradient2Base=65,105,225
HollowKnightRegularHidden=1

HonkaiImpactShape=Hexagon
HonkaiImpactMaskMeter=Shape
HonkaiImpactMask=Regular Hexagon
HonkaiImpactMaskStyle=Blank
HonkaiImpactMaskBase=255,255,255
HonkaiImpactShapeGradient1Base=225,65,105
HonkaiImpactShapeGradient2Base=65,105,225
HonkaiImpactRegularHidden=1

HuntShowdownShape=Hexagon
HuntShowdownMaskMeter=Shape
HuntShowdownMask=Regular Hexagon
HuntShowdownMaskStyle=Blank
HuntShowdownMaskBase=255,255,255
HuntShowdownShapeGradient1Base=225,65,105
HuntShowdownShapeGradient2Base=65,105,225
HuntShowdownRegularHidden=1

JWEvolutionShape=Hexagon
JWEvolutionMaskMeter=Shape
JWEvolutionMask=Regular Hexagon
JWEvolutionMaskStyle=Blank
JWEvolutionMaskBase=255,255,255
JWEvolutionShapeGradient1Base=225,65,105
JWEvolutionShapeGradient2Base=65,105,225
JWEvolutionRegularHidden=1

JWEvolution2Shape=Hexagon
JWEvolution2MaskMeter=Shape
JWEvolution2Mask=Regular Hexagon
JWEvolution2MaskStyle=Blank
JWEvolution2MaskBase=255,255,255
JWEvolution2ShapeGradient1Base=225,65,105
JWEvolution2ShapeGradient2Base=65,105,225
JWEvolution2RegularHidden=1

KovaakShape=Hexagon
KovaakMaskMeter=Shape
KovaakMask=Regular Hexagon
KovaakMaskStyle=Blank
KovaakMaskBase=255,255,255
KovaakShapeGradient1Base=225,65,105
KovaakShapeGradient2Base=65,105,225
KovaakRegularHidden=1

LOLShape=Hexagon
LOLMaskMeter=Shape
LOLMask=Regular Hexagon
LOLMaskStyle=Blank
LOLMaskBase=255,255,255
LOLShapeGradient1Base=225,65,105
LOLShapeGradient2Base=65,105,225
LOLRegularHidden=1

L4D2Shape=Hexagon
L4D2MaskMeter=Shape
L4D2Mask=Regular Hexagon
L4D2MaskStyle=Blank
L4D2MaskBase=255,255,255
L4D2ShapeGradient1Base=225,65,105
L4D2ShapeGradient2Base=65,105,225
L4D2RegularHidden=1

LORShape=Hexagon
LORMaskMeter=Shape
LORMask=Regular Hexagon
LORMaskStyle=Blank
LORMaskBase=255,255,255
LORShapeGradient1Base=225,65,105
LORShapeGradient2Base=65,105,225
LORRegularHidden=1

LostArkShape=Hexagon
LostArkMaskMeter=Shape
LostArkMask=Regular Hexagon
LostArkMaskStyle=Blank
LostArkMaskBase=255,255,255
LostArkShapeGradient1Base=225,65,105
LostArkShapeGradient2Base=65,105,225
LostArkRegularHidden=1

ManeaterShape=Hexagon
ManeaterMaskMeter=Shape
ManeaterMask=Regular Hexagon
ManeaterMaskStyle=Blank
ManeaterMaskBase=255,255,255
ManeaterShapeGradient1Base=225,65,105
ManeaterShapeGradient2Base=65,105,225
ManeaterRegularHidden=1

MassEffectLEShape=Hexagon
MassEffectLEMaskMeter=Shape
MassEffectLEMask=Regular Hexagon
MassEffectLEMaskStyle=Blank
MassEffectLEMaskBase=255,255,255
MassEffectLEShapeGradient1Base=225,65,105
MassEffectLEShapeGradient2Base=65,105,225
MassEffectLERegularHidden=1

MHWorldShape=Hexagon
MHWorldMaskMeter=Shape
MHWorldMask=Regular Hexagon
MHWorldMaskStyle=Blank
MHWorldMaskBase=255,255,255
MHWorldShapeGradient1Base=225,65,105
MHWorldShapeGradient2Base=65,105,225
MHWorldRegularHidden=1

MultiVersusShape=Hexagon
MultiVersusMaskMeter=Shape
MultiVersusMask=Regular Hexagon
MultiVersusMaskStyle=Blank
MultiVersusMaskBase=255,255,255
MultiVersusShapeGradient1Base=225,65,105
MultiVersusShapeGradient2Base=65,105,225
MultiVersusRegularHidden=1

MuseDashShape=Hexagon
MuseDashMaskMeter=Shape
MuseDashMask=Regular Hexagon
MuseDashMaskStyle=Blank
MuseDashMaskBase=255,255,255
MuseDashShapeGradient1Base=225,65,105
MuseDashShapeGradient2Base=65,105,225
MuseDashRegularHidden=1

NarakaShape=Hexagon
NarakaMaskMeter=Shape
NarakaMask=Regular Hexagon
NarakaMaskStyle=Blank
NarakaMaskBase=255,255,255
NarakaShapeGradient1Base=225,65,105
NarakaShapeGradient2Base=65,105,225
NarakaRegularHidden=1

NewWorldShape=Hexagon
NewWorldMaskMeter=Shape
NewWorldMask=Regular Hexagon
NewWorldMaskStyle=Blank
NewWorldMaskBase=255,255,255
NewWorldShapeGradient1Base=225,65,105
NewWorldShapeGradient2Base=65,105,225
NewWorldRegularHidden=1

NierAutomataShape=Hexagon
NierAutomataMaskMeter=Shape
NierAutomataMask=Regular Hexagon
NierAutomataMaskStyle=Blank
NierAutomataMaskBase=255,255,255
NierAutomataShapeGradient1Base=225,65,105
NierAutomataShapeGradient2Base=65,105,225
NierAutomataRegularHidden=1

NMSShape=Hexagon
NMSMaskMeter=Shape
NMSMask=Regular Hexagon
NMSMaskStyle=Blank
NMSMaskBase=255,255,255
NMSShapeGradient1Base=225,65,105
NMSShapeGradient2Base=65,105,225
NMSRegularHidden=1

OriginShape=Hexagon
OriginMaskMeter=Shape
OriginMask=Regular Hexagon
OriginMaskStyle=Blank
OriginMaskBase=255,255,255
OriginShapeGradient1Base=225,65,105
OriginShapeGradient2Base=65,105,225
OriginRegularHidden=1

OlympusShape=Hexagon
OlympusMaskMeter=Shape
OlympusMask=Regular Hexagon
OlympusMaskStyle=Blank
OlympusMaskBase=255,255,255
OlympusShapeGradient1Base=225,65,105
OlympusShapeGradient2Base=65,105,225
OlympusRegularHidden=1

OriBFShape=Hexagon
OriBFMaskMeter=Shape
OriBFMask=Regular Hexagon
OriBFMaskStyle=Blank
OriBFMaskBase=255,255,255
OriBFShapeGradient1Base=225,65,105
OriBFShapeGradient2Base=65,105,225
OriBFRegularHidden=1

OriWWShape=Hexagon
OriWWMaskMeter=Shape
OriWWMask=Regular Hexagon
OriWWMaskStyle=Blank
OriWWMaskBase=255,255,255
OriWWShapeGradient1Base=225,65,105
OriWWShapeGradient2Base=65,105,225
OriWWRegularHidden=1

OsuShape=Hexagon
OsuMaskMeter=Shape
OsuMask=Regular Hexagon
OsuMaskStyle=Blank
OsuMaskBase=255,255,255
OsuShapeGradient1Base=225,65,105
OsuShapeGradient2Base=65,105,225
OsuRegularHidden=1

OutridersShape=Hexagon
OutridersMaskMeter=Shape
OutridersMask=Regular Hexagon
OutridersMaskStyle=Blank
OutridersMaskBase=255,255,255
OutridersShapeGradient1Base=225,65,105
OutridersShapeGradient2Base=65,105,225
OutridersRegularHidden=1

OverwatchShape=Hexagon
OverwatchMaskMeter=Shape
OverwatchMask=Regular Hexagon
OverwatchMaskStyle=Blank
OverwatchMaskBase=255,255,255
OverwatchShapeGradient1Base=225,65,105
OverwatchShapeGradient2Base=65,105,225
OverwatchRegularHidden=1

Overwatch2Shape=Hexagon
Overwatch2MaskMeter=Shape
Overwatch2Mask=Regular Hexagon
Overwatch2MaskStyle=Blank
Overwatch2MaskBase=255,255,255
Overwatch2ShapeGradient1Base=225,65,105
Overwatch2ShapeGradient2Base=65,105,225
Overwatch2RegularHidden=1

PaladinsShape=Hexagon
PaladinsMaskMeter=Shape
PaladinsMask=Regular Hexagon
PaladinsMaskStyle=Blank
PaladinsMaskBase=255,255,255
PaladinsShapeGradient1Base=225,65,105
PaladinsShapeGradient2Base=65,105,225
PaladinsRegularHidden=1

POEShape=Hexagon
POEMaskMeter=Shape
POEMask=Regular Hexagon
POEMaskStyle=Blank
POEMaskBase=255,255,255
POEShapeGradient1Base=225,65,105
POEShapeGradient2Base=65,105,225
POERegularHidden=1

Pico8Shape=Hexagon
Pico8MaskMeter=Shape
Pico8Mask=Regular Hexagon
Pico8MaskStyle=Blank
Pico8MaskBase=255,255,255
Pico8ShapeGradient1Base=225,65,105
Pico8ShapeGradient2Base=65,105,225
Pico8RegularHidden=1

PUBGShape=Hexagon
PUBGMaskMeter=Shape
PUBGMask=Regular Hexagon
PUBGMaskStyle=Blank
PUBGMaskBase=255,255,255
PUBGShapeGradient1Base=225,65,105
PUBGShapeGradient2Base=65,105,225
PUBGRegularHidden=1

ProjectZomboidShape=Hexagon
ProjectZomboidMaskMeter=Shape
ProjectZomboidMask=Regular Hexagon
ProjectZomboidMaskStyle=Blank
ProjectZomboidMaskBase=255,255,255
ProjectZomboidShapeGradient1Base=225,65,105
ProjectZomboidShapeGradient2Base=65,105,225
ProjectZomboidRegularHidden=1

RSExtractionShape=Hexagon
RSExtractionMaskMeter=Shape
RSExtractionMask=Regular Hexagon
RSExtractionMaskStyle=Blank
RSExtractionMaskBase=255,255,255
RSExtractionShapeGradient1Base=225,65,105
RSExtractionShapeGradient2Base=65,105,225
RSExtractionRegularHidden=1

RSSiegeShape=Hexagon
RSSiegeMaskMeter=Shape
RSSiegeMask=Regular Hexagon
RSSiegeMaskStyle=Blank
RSSiegeMaskBase=255,255,255
RSSiegeShapeGradient1Base=225,65,105
RSSiegeShapeGradient2Base=65,105,225
RSSiegeRegularHidden=1

RecRoomShape=Hexagon
RecRoomMaskMeter=Shape
RecRoomMask=Regular Hexagon
RecRoomMaskStyle=Blank
RecRoomMaskBase=255,255,255
RecRoomShapeGradient1Base=225,65,105
RecRoomShapeGradient2Base=65,105,225
RecRoomRegularHidden=1

REVillageShape=Hexagon
REVillageMaskMeter=Shape
REVillageMask=Regular Hexagon
REVillageMaskStyle=Blank
REVillageMaskBase=255,255,255
REVillageShapeGradient1Base=225,65,105
REVillageShapeGradient2Base=65,105,225
REVillageRegularHidden=1

RiotShape=Hexagon
RiotMaskMeter=Shape
RiotMask=Regular Hexagon
RiotMaskStyle=Blank
RiotMaskBase=255,255,255
RiotShapeGradient1Base=225,65,105
RiotShapeGradient2Base=65,105,225
RiotRegularHidden=1

RobloxShape=Hexagon
RobloxMaskMeter=Shape
RobloxMask=Regular Hexagon
RobloxMaskStyle=Blank
RobloxMaskBase=255,255,255
RobloxShapeGradient1Base=225,65,105
RobloxShapeGradient2Base=65,105,225
RobloxRegularHidden=1

RobloxStudioShape=Hexagon
RobloxStudioMaskMeter=Shape
RobloxStudioMask=Regular Hexagon
RobloxStudioMaskStyle=Blank
RobloxStudioMaskBase=255,255,255
RobloxStudioShapeGradient1Base=225,65,105
RobloxStudioShapeGradient2Base=65,105,225
RobloxStudioRegularHidden=1

RocketLeagueShape=Hexagon
RocketLeagueMaskMeter=Shape
RocketLeagueMask=Regular Hexagon
RocketLeagueMaskStyle=Blank
RocketLeagueMaskBase=255,255,255
RocketLeagueShapeGradient1Base=225,65,105
RocketLeagueShapeGradient2Base=65,105,225
RocketLeagueRegularHidden=1

RockstarShape=Hexagon
RockstarMaskMeter=Shape
RockstarMask=Regular Hexagon
RockstarMaskStyle=Blank
RockstarMaskBase=255,255,255
RockstarShapeGradient1Base=225,65,105
RockstarShapeGradient2Base=65,105,225
RockstarRegularHidden=1

RollerChampionsShape=Hexagon
RollerChampionsMaskMeter=Shape
RollerChampionsMask=Regular Hexagon
RollerChampionsMaskStyle=Blank
RollerChampionsMaskBase=255,255,255
RollerChampionsShapeGradient1Base=225,65,105
RollerChampionsShapeGradient2Base=65,105,225
RollerChampionsRegularHidden=1

RSIShape=Hexagon
RSIMaskMeter=Shape
RSIMask=Regular Hexagon
RSIMaskStyle=Blank
RSIMaskBase=255,255,255
RSIShapeGradient1Base=225,65,105
RSIShapeGradient2Base=65,105,225
RSIRegularHidden=1

RuneScapeShape=Hexagon
RuneScapeMaskMeter=Shape
RuneScapeMask=Regular Hexagon
RuneScapeMaskStyle=Blank
RuneScapeMaskBase=255,255,255
RuneScapeShapeGradient1Base=225,65,105
RuneScapeShapeGradient2Base=65,105,225
RuneScapeRegularHidden=1

RustShape=Hexagon
RustMaskMeter=Shape
RustMask=Regular Hexagon
RustMaskStyle=Blank
RustMaskBase=255,255,255
RustShapeGradient1Base=225,65,105
RustShapeGradient2Base=65,105,225
RustRegularHidden=1

SaintsRowShape=Hexagon
SaintsRowMaskMeter=Shape
SaintsRowMask=Regular Hexagon
SaintsRowMaskStyle=Blank
SaintsRowMaskBase=255,255,255
SaintsRowShapeGradient1Base=225,65,105
SaintsRowShapeGradient2Base=65,105,225
SaintsRowRegularHidden=1

SatisfactoryShape=Hexagon
SatisfactoryMaskMeter=Shape
SatisfactoryMask=Regular Hexagon
SatisfactoryMaskStyle=Blank
SatisfactoryMaskBase=255,255,255
SatisfactoryShapeGradient1Base=225,65,105
SatisfactoryShapeGradient2Base=65,105,225
SatisfactoryRegularHidden=1

SoTShape=Hexagon
SoTMaskMeter=Shape
SoTMask=Regular Hexagon
SoTMaskStyle=Blank
SoTMaskBase=255,255,255
SoTShapeGradient1Base=225,65,105
SoTShapeGradient2Base=65,105,225
SoTRegularHidden=1

StSShape=Hexagon
StSMaskMeter=Shape
StSMask=Regular Hexagon
StSMaskStyle=Blank
StSMaskBase=255,255,255
StSShapeGradient1Base=225,65,105
StSShapeGradient2Base=65,105,225
StSRegularHidden=1

SmiteShape=Hexagon
SmiteMaskMeter=Shape
SmiteMask=Regular Hexagon
SmiteMaskStyle=Blank
SmiteMaskBase=255,255,255
SmiteShapeGradient1Base=225,65,105
SmiteShapeGradient2Base=65,105,225
SmiteRegularHidden=1

SCBlacklistShape=Hexagon
SCBlacklistMaskMeter=Shape
SCBlacklistMask=Regular Hexagon
SCBlacklistMaskStyle=Blank
SCBlacklistMaskBase=255,255,255
SCBlacklistShapeGradient1Base=225,65,105
SCBlacklistShapeGradient2Base=65,105,225
SCBlacklistRegularHidden=1

StarCitizenShape=Hexagon
StarCitizenMaskMeter=Shape
StarCitizenMask=Regular Hexagon
StarCitizenMaskStyle=Blank
StarCitizenMaskBase=255,255,255
StarCitizenShapeGradient1Base=225,65,105
StarCitizenShapeGradient2Base=65,105,225
StarCitizenRegularHidden=1

SteamShape=Hexagon
SteamMaskMeter=Shape
SteamMask=Regular Hexagon
SteamMaskStyle=Blank
SteamMaskBase=255,255,255
SteamShapeGradient1Base=225,65,105
SteamShapeGradient2Base=65,105,225
SteamRegularHidden=1

StrayShape=Hexagon
StrayMaskMeter=Shape
StrayMask=Regular Hexagon
StrayMaskStyle=Blank
StrayMaskBase=255,255,255
StrayShapeGradient1Base=225,65,105
StrayShapeGradient2Base=65,105,225
StrayRegularHidden=1

SAPShape=Hexagon
SAPMaskMeter=Shape
SAPMask=Regular Hexagon
SAPMaskStyle=Blank
SAPMaskBase=255,255,255
SAPShapeGradient1Base=225,65,105
SAPShapeGradient2Base=65,105,225
SAPRegularHidden=1

TF2Shape=Hexagon
TF2MaskMeter=Shape
TF2Mask=Regular Hexagon
TF2MaskStyle=Blank
TF2MaskBase=255,255,255
TF2ShapeGradient1Base=225,65,105
TF2ShapeGradient2Base=65,105,225
TF2RegularHidden=1

TemtemShape=Hexagon
TemtemMaskMeter=Shape
TemtemMask=Regular Hexagon
TemtemMaskStyle=Blank
TemtemMaskBase=255,255,255
TemtemShapeGradient1Base=225,65,105
TemtemShapeGradient2Base=65,105,225
TemtemRegularHidden=1

TerrariaShape=Hexagon
TerrariaMaskMeter=Shape
TerrariaMask=Regular Hexagon
TerrariaMaskStyle=Blank
TerrariaMaskBase=255,255,255
TerrariaShapeGradient1Base=225,65,105
TerrariaShapeGradient2Base=65,105,225
TerrariaRegularHidden=1

TETRIOShape=Hexagon
TETRIOMaskMeter=Shape
TETRIOMask=Regular Hexagon
TETRIOMaskStyle=Blank
TETRIOMaskBase=255,255,255
TETRIOShapeGradient1Base=225,65,105
TETRIOShapeGradient2Base=65,105,225
TETRIORegularHidden=1

TCFShape=Hexagon
TCFMaskMeter=Shape
TCFMask=Regular Hexagon
TCFMaskStyle=Blank
TCFMaskBase=255,255,255
TCFShapeGradient1Base=225,65,105
TCFShapeGradient2Base=65,105,225
TCFRegularHidden=1

TW3Shape=Hexagon
TW3MaskMeter=Shape
TW3Mask=Regular Hexagon
TW3MaskStyle=Blank
TW3MaskBase=255,255,255
TW3ShapeGradient1Base=225,65,105
TW3ShapeGradient2Base=65,105,225
TW3RegularHidden=1

UbisoftShape=Hexagon
UbisoftMaskMeter=Shape
UbisoftMask=Regular Hexagon
UbisoftMaskStyle=Blank
UbisoftMaskBase=255,255,255
UbisoftShapeGradient1Base=225,65,105
UbisoftShapeGradient2Base=65,105,225
UbisoftRegularHidden=1

UltrakillShape=Hexagon
UltrakillMaskMeter=Shape
UltrakillMask=Regular Hexagon
UltrakillMaskStyle=Blank
UltrakillMaskBase=255,255,255
UltrakillShapeGradient1Base=225,65,105
UltrakillShapeGradient2Base=65,105,225
UltrakillRegularHidden=1

UnrailedShape=Hexagon
UnrailedMaskMeter=Shape
UnrailedMask=Regular Hexagon
UnrailedMaskStyle=Blank
UnrailedMaskBase=255,255,255
UnrailedShapeGradient1Base=225,65,105
UnrailedShapeGradient2Base=65,105,225
UnrailedRegularHidden=1

VRisingShape=Hexagon
VRisingMaskMeter=Shape
VRisingMask=Regular Hexagon
VRisingMaskStyle=Blank
VRisingMaskBase=255,255,255
VRisingShapeGradient1Base=225,65,105
VRisingShapeGradient2Base=65,105,225
VRisingRegularHidden=1

ValorantShape=Hexagon
ValorantMaskMeter=Shape
ValorantMask=Regular Hexagon
ValorantMaskStyle=Blank
ValorantMaskBase=255,255,255
ValorantShapeGradient1Base=225,65,105
ValorantShapeGradient2Base=65,105,225
ValorantRegularHidden=1

VampireSurvivorsShape=Hexagon
VampireSurvivorsMaskMeter=Shape
VampireSurvivorsMask=Regular Hexagon
VampireSurvivorsMaskStyle=Blank
VampireSurvivorsMaskBase=255,255,255
VampireSurvivorsShapeGradient1Base=225,65,105
VampireSurvivorsShapeGradient2Base=65,105,225
VampireSurvivorsRegularHidden=1

VortexShape=Hexagon
VortexMaskMeter=Shape
VortexMask=Regular Hexagon
VortexMaskStyle=Blank
VortexMaskBase=255,255,255
VortexShapeGradient1Base=225,65,105
VortexShapeGradient2Base=65,105,225
VortexRegularHidden=1

VoxatronShape=Hexagon
VoxatronMaskMeter=Shape
VoxatronMask=Regular Hexagon
VoxatronMaskStyle=Blank
VoxatronMaskBase=255,255,255
VoxatronShapeGradient1Base=225,65,105
VoxatronShapeGradient2Base=65,105,225
VoxatronRegularHidden=1

VRChatShape=Hexagon
VRChatMaskMeter=Shape
VRChatMask=Regular Hexagon
VRChatMaskStyle=Blank
VRChatMaskBase=255,255,255
VRChatShapeGradient1Base=225,65,105
VRChatShapeGradient2Base=65,105,225
VRChatRegularHidden=1

WarThunderShape=Hexagon
WarThunderMaskMeter=Shape
WarThunderMask=Regular Hexagon
WarThunderMaskStyle=Blank
WarThunderMaskBase=255,255,255
WarThunderShapeGradient1Base=225,65,105
WarThunderShapeGradient2Base=65,105,225
WarThunderRegularHidden=1

WarframeShape=Hexagon
WarframeMaskMeter=Shape
WarframeMask=Regular Hexagon
WarframeMaskStyle=Blank
WarframeMaskBase=255,255,255
WarframeShapeGradient1Base=225,65,105
WarframeShapeGradient2Base=65,105,225
WarframeRegularHidden=1

WOTanksShape=Hexagon
WOTanksMaskMeter=Shape
WOTanksMask=Regular Hexagon
WOTanksMaskStyle=Blank
WOTanksMaskBase=255,255,255
WOTanksShapeGradient1Base=225,65,105
WOTanksShapeGradient2Base=65,105,225
WOTanksRegularHidden=1

WOWShape=Hexagon
WOWMaskMeter=Shape
WOWMask=Regular Hexagon
WOWMaskStyle=Blank
WOWMaskBase=255,255,255
WOWShapeGradient1Base=225,65,105
WOWShapeGradient2Base=65,105,225
WOWRegularHidden=1

WOWarshipsShape=Hexagon
WOWarshipsMaskMeter=Shape
WOWarshipsMask=Regular Hexagon
WOWarshipsMaskStyle=Blank
WOWarshipsMaskBase=255,255,255
WOWarshipsShapeGradient1Base=225,65,105
WOWarshipsShapeGradient2Base=65,105,225
WOWarshipsRegularHidden=1

XboxShape=Hexagon
XboxMaskMeter=Shape
XboxMask=Regular Hexagon
XboxMaskStyle=Blank
XboxMaskBase=255,255,255
XboxShapeGradient1Base=225,65,105
XboxShapeGradient2Base=65,105,225
XboxRegularHidden=1

; ============================================================
; Google
; ============================================================

DocsShape=Hexagon
DocsMaskMeter=Shape
DocsMask=Regular Hexagon
DocsMaskStyle=Blank
DocsMaskBase=255,255,255
DocsShapeGradient1Base=225,65,105
DocsShapeGradient2Base=65,105,225
DocsRegularHidden=1

DriveShape=Hexagon
DriveMaskMeter=Shape
DriveMask=Regular Hexagon
DriveMaskStyle=Blank
DriveMaskBase=255,255,255
DriveShapeGradient1Base=225,65,105
DriveShapeGradient2Base=65,105,225
DriveRegularHidden=1

GmailShape=Hexagon
GmailMaskMeter=Shape
GmailMask=Regular Hexagon
GmailMaskStyle=Blank
GmailMaskBase=255,255,255
GmailShapeGradient1Base=225,65,105
GmailShapeGradient2Base=65,105,225
GmailRegularHidden=1

MapsShape=Hexagon
MapsMaskMeter=Shape
MapsMask=Regular Hexagon
MapsMaskStyle=Blank
MapsMaskBase=255,255,255
MapsShapeGradient1Base=225,65,105
MapsShapeGradient2Base=65,105,225
MapsRegularHidden=1

PhotosShape=Hexagon
PhotosMaskMeter=Shape
PhotosMask=Regular Hexagon
PhotosMaskStyle=Blank
PhotosMaskBase=255,255,255
PhotosShapeGradient1Base=225,65,105
PhotosShapeGradient2Base=65,105,225
PhotosRegularHidden=1

SheetsShape=Hexagon
SheetsMaskMeter=Shape
SheetsMask=Regular Hexagon
SheetsMaskStyle=Blank
SheetsMaskBase=255,255,255
SheetsShapeGradient1Base=225,65,105
SheetsShapeGradient2Base=65,105,225
SheetsRegularHidden=1

SlidesShape=Hexagon
SlidesMaskMeter=Shape
SlidesMask=Regular Hexagon
SlidesMaskStyle=Blank
SlidesMaskBase=255,255,255
SlidesShapeGradient1Base=225,65,105
SlidesShapeGradient2Base=65,105,225
SlidesRegularHidden=1

; ============================================================
; LibreOffice
; ============================================================

BaseShape=Hexagon
BaseMaskMeter=Shape
BaseMask=Regular Hexagon
BaseMaskStyle=Blank
BaseMaskBase=255,255,255
BaseShapeGradient1Base=225,65,105
BaseShapeGradient2Base=65,105,225
BaseRegularHidden=1

CalcShape=Hexagon
CalcMaskMeter=Shape
CalcMask=Regular Hexagon
CalcMaskStyle=Blank
CalcMaskBase=255,255,255
CalcShapeGradient1Base=225,65,105
CalcShapeGradient2Base=65,105,225
CalcRegularHidden=1

DrawShape=Hexagon
DrawMaskMeter=Shape
DrawMask=Regular Hexagon
DrawMaskStyle=Blank
DrawMaskBase=255,255,255
DrawShapeGradient1Base=225,65,105
DrawShapeGradient2Base=65,105,225
DrawRegularHidden=1

ImpressShape=Hexagon
ImpressMaskMeter=Shape
ImpressMask=Regular Hexagon
ImpressMaskStyle=Blank
ImpressMaskBase=255,255,255
ImpressShapeGradient1Base=225,65,105
ImpressShapeGradient2Base=65,105,225
ImpressRegularHidden=1

MathShape=Hexagon
MathMaskMeter=Shape
MathMask=Regular Hexagon
MathMaskStyle=Blank
MathMaskBase=255,255,255
MathShapeGradient1Base=225,65,105
MathShapeGradient2Base=65,105,225
MathRegularHidden=1

WriterShape=Hexagon
WriterMaskMeter=Shape
WriterMask=Regular Hexagon
WriterMaskStyle=Blank
WriterMaskBase=255,255,255
WriterShapeGradient1Base=225,65,105
WriterShapeGradient2Base=65,105,225
WriterRegularHidden=1

; ============================================================
; Minecraft
; ============================================================

MinecraftBedrockShape=Hexagon
MinecraftBedrockMaskMeter=Shape
MinecraftBedrockMask=Regular Hexagon
MinecraftBedrockMaskStyle=Blank
MinecraftBedrockMaskBase=255,255,255
MinecraftBedrockShapeGradient1Base=225,65,105
MinecraftBedrockShapeGradient2Base=65,105,225
MinecraftBedrockRegularHidden=1

MinecraftJavaShape=Hexagon
MinecraftJavaMaskMeter=Shape
MinecraftJavaMask=Regular Hexagon
MinecraftJavaMaskStyle=Blank
MinecraftJavaMaskBase=255,255,255
MinecraftJavaShapeGradient1Base=225,65,105
MinecraftJavaShapeGradient2Base=65,105,225
MinecraftJavaRegularHidden=1

MinecraftDungeonsShape=Hexagon
MinecraftDungeonsMaskMeter=Shape
MinecraftDungeonsMask=Regular Hexagon
MinecraftDungeonsMaskStyle=Blank
MinecraftDungeonsMaskBase=255,255,255
MinecraftDungeonsShapeGradient1Base=225,65,105
MinecraftDungeonsShapeGradient2Base=65,105,225
MinecraftDungeonsRegularHidden=1

BadlionShape=Hexagon
BadlionMaskMeter=Shape
BadlionMask=Regular Hexagon
BadlionMaskStyle=Blank
BadlionMaskBase=255,255,255
BadlionShapeGradient1Base=225,65,105
BadlionShapeGradient2Base=65,105,225
BadlionRegularHidden=1

BatmodShape=Hexagon
BatmodMaskMeter=Shape
BatmodMask=Regular Hexagon
BatmodMaskStyle=Blank
BatmodMaskBase=255,255,255
BatmodShapeGradient1Base=225,65,105
BatmodShapeGradient2Base=65,105,225
BatmodRegularHidden=1

BetterMinecraftShape=Hexagon
BetterMinecraftMaskMeter=Shape
BetterMinecraftMask=Regular Hexagon
BetterMinecraftMaskStyle=Blank
BetterMinecraftMaskBase=255,255,255
BetterMinecraftShapeGradient1Base=225,65,105
BetterMinecraftShapeGradient2Base=65,105,225
BetterMinecraftRegularHidden=1

CosmicShape=Hexagon
CosmicMaskMeter=Shape
CosmicMask=Regular Hexagon
CosmicMaskStyle=Blank
CosmicMaskBase=255,255,255
CosmicShapeGradient1Base=225,65,105
CosmicShapeGradient2Base=65,105,225
CosmicRegularHidden=1

LabyModShape=Hexagon
LabyModMaskMeter=Shape
LabyModMask=Regular Hexagon
LabyModMaskStyle=Blank
LabyModMaskBase=255,255,255
LabyModShapeGradient1Base=225,65,105
LabyModShapeGradient2Base=65,105,225
LabyModRegularHidden=1

LunarShape=Hexagon
LunarMaskMeter=Shape
LunarMask=Regular Hexagon
LunarMaskStyle=Blank
LunarMaskBase=255,255,255
LunarShapeGradient1Base=225,65,105
LunarShapeGradient2Base=65,105,225
LunarRegularHidden=1

MultiMCShape=Hexagon
MultiMCMaskMeter=Shape
MultiMCMask=Regular Hexagon
MultiMCMaskStyle=Blank
MultiMCMaskBase=255,255,255
MultiMCShapeGradient1Base=225,65,105
MultiMCShapeGradient2Base=65,105,225
MultiMCRegularHidden=1

PixelmonShape=Hexagon
PixelmonMaskMeter=Shape
PixelmonMask=Regular Hexagon
PixelmonMaskStyle=Blank
PixelmonMaskBase=255,255,255
PixelmonShapeGradient1Base=225,65,105
PixelmonShapeGradient2Base=65,105,225
PixelmonRegularHidden=1

PvPLoungeShape=Hexagon
PvPLoungeMaskMeter=Shape
PvPLoungeMask=Regular Hexagon
PvPLoungeMaskStyle=Blank
PvPLoungeMaskBase=255,255,255
PvPLoungeShapeGradient1Base=225,65,105
PvPLoungeShapeGradient2Base=65,105,225
PvPLoungeRegularHidden=1

RLCraftShape=Hexagon
RLCraftMaskMeter=Shape
RLCraftMask=Regular Hexagon
RLCraftMaskStyle=Blank
RLCraftMaskBase=255,255,255
RLCraftShapeGradient1Base=225,65,105
RLCraftShapeGradient2Base=65,105,225
RLCraftRegularHidden=1

ValhelsiaShape=Hexagon
ValhelsiaMaskMeter=Shape
ValhelsiaMask=Regular Hexagon
ValhelsiaMaskStyle=Blank
ValhelsiaMaskBase=255,255,255
ValhelsiaShapeGradient1Base=225,65,105
ValhelsiaShapeGradient2Base=65,105,225
ValhelsiaRegularHidden=1

; ============================================================
; Media
; ============================================================

AIMPShape=Hexagon
AIMPMaskMeter=Shape
AIMPMask=Regular Hexagon
AIMPMaskStyle=Blank
AIMPMaskBase=255,255,255
AIMPShapeGradient1Base=225,65,105
AIMPShapeGradient2Base=65,105,225
AIMPRegularHidden=1

AmazonMusicShape=Hexagon
AmazonMusicMaskMeter=Shape
AmazonMusicMask=Regular Hexagon
AmazonMusicMaskStyle=Blank
AmazonMusicMaskBase=255,255,255
AmazonMusicShapeGradient1Base=225,65,105
AmazonMusicShapeGradient2Base=65,105,225
AmazonMusicRegularHidden=1

AudibleShape=Hexagon
AudibleMaskMeter=Shape
AudibleMask=Regular Hexagon
AudibleMaskStyle=Blank
AudibleMaskBase=255,255,255
AudibleShapeGradient1Base=225,65,105
AudibleShapeGradient2Base=65,105,225
AudibleRegularHidden=1

DisneyPlusShape=Hexagon
DisneyPlusMaskMeter=Shape
DisneyPlusMask=Regular Hexagon
DisneyPlusMaskStyle=Blank
DisneyPlusMaskBase=255,255,255
DisneyPlusShapeGradient1Base=225,65,105
DisneyPlusShapeGradient2Base=65,105,225
DisneyPlusRegularHidden=1

FoobarShape=Hexagon
FoobarMaskMeter=Shape
FoobarMask=Regular Hexagon
FoobarMaskStyle=Blank
FoobarMaskBase=255,255,255
FoobarShapeGradient1Base=225,65,105
FoobarShapeGradient2Base=65,105,225
FoobarRegularHidden=1

GPMusicShape=Hexagon
GPMusicMaskMeter=Shape
GPMusicMask=Regular Hexagon
GPMusicMaskStyle=Blank
GPMusicMaskBase=255,255,255
GPMusicShapeGradient1Base=225,65,105
GPMusicShapeGradient2Base=65,105,225
GPMusicRegularHidden=1

HuluShape=Hexagon
HuluMaskMeter=Shape
HuluMask=Regular Hexagon
HuluMaskStyle=Blank
HuluMaskBase=255,255,255
HuluShapeGradient1Base=225,65,105
HuluShapeGradient2Base=65,105,225
HuluRegularHidden=1

iTunesShape=Hexagon
iTunesMaskMeter=Shape
iTunesMask=Regular Hexagon
iTunesMaskStyle=Blank
iTunesMaskBase=255,255,255
iTunesShapeGradient1Base=225,65,105
iTunesShapeGradient2Base=65,105,225
iTunesRegularHidden=1

KodiShape=Hexagon
KodiMaskMeter=Shape
KodiMask=Regular Hexagon
KodiMaskStyle=Blank
KodiMaskBase=255,255,255
KodiShapeGradient1Base=225,65,105
KodiShapeGradient2Base=65,105,225
KodiRegularHidden=1

MusicBeeShape=Hexagon
MusicBeeMaskMeter=Shape
MusicBeeMask=Regular Hexagon
MusicBeeMaskStyle=Blank
MusicBeeMaskBase=255,255,255
MusicBeeShapeGradient1Base=225,65,105
MusicBeeShapeGradient2Base=65,105,225
MusicBeeRegularHidden=1

NetflixShape=Hexagon
NetflixMaskMeter=Shape
NetflixMask=Regular Hexagon
NetflixMaskStyle=Blank
NetflixMaskBase=255,255,255
NetflixShapeGradient1Base=225,65,105
NetflixShapeGradient2Base=65,105,225
NetflixRegularHidden=1

PlexShape=Hexagon
PlexMaskMeter=Shape
PlexMask=Regular Hexagon
PlexMaskStyle=Blank
PlexMaskBase=255,255,255
PlexShapeGradient1Base=225,65,105
PlexShapeGradient2Base=65,105,225
PlexRegularHidden=1

SpotifyShape=Hexagon
SpotifyMaskMeter=Shape
SpotifyMask=Regular Hexagon
SpotifyMaskStyle=Blank
SpotifyMaskBase=255,255,255
SpotifyShapeGradient1Base=225,65,105
SpotifyShapeGradient2Base=65,105,225
SpotifyRegularHidden=1

TwitchShape=Hexagon
TwitchMaskMeter=Shape
TwitchMask=Regular Hexagon
TwitchMaskStyle=Blank
TwitchMaskBase=255,255,255
TwitchShapeGradient1Base=225,65,105
TwitchShapeGradient2Base=65,105,225
TwitchRegularHidden=1

VLCShape=Hexagon
VLCMaskMeter=Shape
VLCMask=Regular Hexagon
VLCMaskStyle=Blank
VLCMaskBase=255,255,255
VLCShapeGradient1Base=225,65,105
VLCShapeGradient2Base=65,105,225
VLCRegularHidden=1

WakanimShape=Hexagon
WakanimMaskMeter=Shape
WakanimMask=Regular Hexagon
WakanimMaskStyle=Blank
WakanimMaskBase=255,255,255
WakanimShapeGradient1Base=225,65,105
WakanimShapeGradient2Base=65,105,225
WakanimRegularHidden=1

WinampShape=Hexagon
WinampMaskMeter=Shape
WinampMask=Regular Hexagon
WinampMaskStyle=Blank
WinampMaskBase=255,255,255
WinampShapeGradient1Base=225,65,105
WinampShapeGradient2Base=65,105,225
WinampRegularHidden=1

YouTubeShape=Hexagon
YouTubeMaskMeter=Shape
YouTubeMask=Regular Hexagon
YouTubeMaskStyle=Blank
YouTubeMaskBase=255,255,255
YouTubeShapeGradient1Base=225,65,105
YouTubeShapeGradient2Base=65,105,225
YouTubeRegularHidden=1

; ============================================================
; Office
; ============================================================

ExcelShape=Hexagon
ExcelMaskMeter=Shape
ExcelMask=Regular Hexagon
ExcelMaskStyle=Blank
ExcelMaskBase=255,255,255
ExcelShapeGradient1Base=225,65,105
ExcelShapeGradient2Base=65,105,225
ExcelRegularHidden=1

OneDriveShape=Hexagon
OneDriveMaskMeter=Shape
OneDriveMask=Regular Hexagon
OneDriveMaskStyle=Blank
OneDriveMaskBase=255,255,255
OneDriveShapeGradient1Base=225,65,105
OneDriveShapeGradient2Base=65,105,225
OneDriveRegularHidden=1

OneNoteShape=Hexagon
OneNoteMaskMeter=Shape
OneNoteMask=Regular Hexagon
OneNoteMaskStyle=Blank
OneNoteMaskBase=255,255,255
OneNoteShapeGradient1Base=225,65,105
OneNoteShapeGradient2Base=65,105,225
OneNoteRegularHidden=1

OutlookShape=Hexagon
OutlookMaskMeter=Shape
OutlookMask=Regular Hexagon
OutlookMaskStyle=Blank
OutlookMaskBase=255,255,255
OutlookShapeGradient1Base=225,65,105
OutlookShapeGradient2Base=65,105,225
OutlookRegularHidden=1

PowerPointShape=Hexagon
PowerPointMaskMeter=Shape
PowerPointMask=Regular Hexagon
PowerPointMaskStyle=Blank
PowerPointMaskBase=255,255,255
PowerPointShapeGradient1Base=225,65,105
PowerPointShapeGradient2Base=65,105,225
PowerPointRegularHidden=1

SharePointShape=Hexagon
SharePointMaskMeter=Shape
SharePointMask=Regular Hexagon
SharePointMaskStyle=Blank
SharePointMaskBase=255,255,255
SharePointShapeGradient1Base=225,65,105
SharePointShapeGradient2Base=65,105,225
SharePointRegularHidden=1

TeamsShape=Hexagon
TeamsMaskMeter=Shape
TeamsMask=Regular Hexagon
TeamsMaskStyle=Blank
TeamsMaskBase=255,255,255
TeamsShapeGradient1Base=225,65,105
TeamsShapeGradient2Base=65,105,225
TeamsRegularHidden=1

WordShape=Hexagon
WordMaskMeter=Shape
WordMask=Regular Hexagon
WordMaskStyle=Blank
WordMaskBase=255,255,255
WordShapeGradient1Base=225,65,105
WordShapeGradient2Base=65,105,225
WordRegularHidden=1

YammerShape=Hexagon
YammerMaskMeter=Shape
YammerMask=Regular Hexagon
YammerMaskStyle=Blank
YammerMaskBase=255,255,255
YammerShapeGradient1Base=225,65,105
YammerShapeGradient2Base=65,105,225
YammerRegularHidden=1

; ============================================================
; Social
; ============================================================

DiscordShape=Hexagon
DiscordMaskMeter=Shape
DiscordMask=Regular Hexagon
DiscordMaskStyle=Blank
DiscordMaskBase=255,255,255
DiscordShapeGradient1Base=225,65,105
DiscordShapeGradient2Base=65,105,225
DiscordRegularHidden=1

GuildedShape=Hexagon
GuildedMaskMeter=Shape
GuildedMask=Regular Hexagon
GuildedMaskStyle=Blank
GuildedMaskBase=255,255,255
GuildedShapeGradient1Base=225,65,105
GuildedShapeGradient2Base=65,105,225
GuildedRegularHidden=1

MetaMessengerShape=Hexagon
MetaMessengerMaskMeter=Shape
MetaMessengerMask=Regular Hexagon
MetaMessengerMaskStyle=Blank
MetaMessengerMaskBase=255,255,255
MetaMessengerShapeGradient1Base=225,65,105
MetaMessengerShapeGradient2Base=65,105,225
MetaMessengerRegularHidden=1

RedditShape=Hexagon
RedditMaskMeter=Shape
RedditMask=Regular Hexagon
RedditMaskStyle=Blank
RedditMaskBase=255,255,255
RedditShapeGradient1Base=225,65,105
RedditShapeGradient2Base=65,105,225
RedditRegularHidden=1

SignalShape=Hexagon
SignalMaskMeter=Shape
SignalMask=Regular Hexagon
SignalMaskStyle=Blank
SignalMaskBase=255,255,255
SignalShapeGradient1Base=225,65,105
SignalShapeGradient2Base=65,105,225
SignalRegularHidden=1

TeamSpeakShape=Hexagon
TeamSpeakMaskMeter=Shape
TeamSpeakMask=Regular Hexagon
TeamSpeakMaskStyle=Blank
TeamSpeakMaskBase=255,255,255
TeamSpeakShapeGradient1Base=225,65,105
TeamSpeakShapeGradient2Base=65,105,225
TeamSpeakRegularHidden=1

TelegramShape=Hexagon
TelegramMaskMeter=Shape
TelegramMask=Regular Hexagon
TelegramMaskStyle=Blank
TelegramMaskBase=255,255,255
TelegramShapeGradient1Base=225,65,105
TelegramShapeGradient2Base=65,105,225
TelegramRegularHidden=1

TwitterShape=Hexagon
TwitterMaskMeter=Shape
TwitterMask=Regular Hexagon
TwitterMaskStyle=Blank
TwitterMaskBase=255,255,255
TwitterShapeGradient1Base=225,65,105
TwitterShapeGradient2Base=65,105,225
TwitterRegularHidden=1

WhatsAppShape=Hexagon
WhatsAppMaskMeter=Shape
WhatsAppMask=Regular Hexagon
WhatsAppMaskStyle=Blank
WhatsAppMaskBase=255,255,255
WhatsAppShapeGradient1Base=225,65,105
WhatsAppShapeGradient2Base=65,105,225
WhatsAppRegularHidden=1

WebExShape=Hexagon
WebExMaskMeter=Shape
WebExMask=Regular Hexagon
WebExMaskStyle=Blank
WebExMaskBase=255,255,255
WebExShapeGradient1Base=225,65,105
WebExShapeGradient2Base=65,105,225
WebExRegularHidden=1

ZoomShape=Hexagon
ZoomMaskMeter=Shape
ZoomMask=Regular Hexagon
ZoomMaskStyle=Blank
ZoomMaskBase=255,255,255
ZoomShapeGradient1Base=225,65,105
ZoomShapeGradient2Base=65,105,225
ZoomRegularHidden=1

; ============================================================
; Other
; ============================================================

AbletonShape=Hexagon
AbletonMaskMeter=Shape
AbletonMask=Regular Hexagon
AbletonMaskStyle=Blank
AbletonMaskBase=255,255,255
AbletonShapeGradient1Base=225,65,105
AbletonShapeGradient2Base=65,105,225
AbletonRegularHidden=1

AffinityDesignerShape=Hexagon
AffinityDesignerMaskMeter=Shape
AffinityDesignerMask=Regular Hexagon
AffinityDesignerMaskStyle=Blank
AffinityDesignerMaskBase=255,255,255
AffinityDesignerShapeGradient1Base=225,65,105
AffinityDesignerShapeGradient2Base=65,105,225
AffinityDesignerRegularHidden=1

AffinityPhotoShape=Hexagon
AffinityPhotoMaskMeter=Shape
AffinityPhotoMask=Regular Hexagon
AffinityPhotoMaskStyle=Blank
AffinityPhotoMaskBase=255,255,255
AffinityPhotoShapeGradient1Base=225,65,105
AffinityPhotoShapeGradient2Base=65,105,225
AffinityPhotoRegularHidden=1

AffinityPublisherShape=Hexagon
AffinityPublisherMaskMeter=Shape
AffinityPublisherMask=Regular Hexagon
AffinityPublisherMaskStyle=Blank
AffinityPublisherMaskBase=255,255,255
AffinityPublisherShapeGradient1Base=225,65,105
AffinityPublisherShapeGradient2Base=65,105,225
AffinityPublisherRegularHidden=1

AMDRadeonShape=Hexagon
AMDRadeonMaskMeter=Shape
AMDRadeonMask=Regular Hexagon
AMDRadeonMaskStyle=Blank
AMDRadeonMaskBase=255,255,255
AMDRadeonShapeGradient1Base=225,65,105
AMDRadeonShapeGradient2Base=65,105,225
AMDRadeonRegularHidden=1

AMDRyzenShape=Hexagon
AMDRyzenMaskMeter=Shape
AMDRyzenMask=Regular Hexagon
AMDRyzenMaskStyle=Blank
AMDRyzenMaskBase=255,255,255
AMDRyzenShapeGradient1Base=225,65,105
AMDRyzenShapeGradient2Base=65,105,225
AMDRyzenRegularHidden=1

AnacondaShape=Hexagon
AnacondaMaskMeter=Shape
AnacondaMask=Regular Hexagon
AnacondaMaskStyle=Blank
AnacondaMaskBase=255,255,255
AnacondaShapeGradient1Base=225,65,105
AnacondaShapeGradient2Base=65,105,225
AnacondaRegularHidden=1

AnkiShape=Hexagon
AnkiMaskMeter=Shape
AnkiMask=Regular Hexagon
AnkiMaskStyle=Blank
AnkiMaskBase=255,255,255
AnkiShapeGradient1Base=225,65,105
AnkiShapeGradient2Base=65,105,225
AnkiRegularHidden=1

AsepriteShape=Hexagon
AsepriteMaskMeter=Shape
AsepriteMask=Regular Hexagon
AsepriteMaskStyle=Blank
AsepriteMaskBase=255,255,255
AsepriteShapeGradient1Base=225,65,105
AsepriteShapeGradient2Base=65,105,225
AsepriteRegularHidden=1

Autodesk3dsMaxShape=Hexagon
Autodesk3dsMaxMaskMeter=Shape
Autodesk3dsMaxMask=Regular Hexagon
Autodesk3dsMaxMaskStyle=Blank
Autodesk3dsMaxMaskBase=255,255,255
Autodesk3dsMaxShapeGradient1Base=225,65,105
Autodesk3dsMaxShapeGradient2Base=65,105,225
Autodesk3dsMaxRegularHidden=1

AutodeskMayaShape=Hexagon
AutodeskMayaMaskMeter=Shape
AutodeskMayaMask=Regular Hexagon
AutodeskMayaMaskStyle=Blank
AutodeskMayaMaskBase=255,255,255
AutodeskMayaShapeGradient1Base=225,65,105
AutodeskMayaShapeGradient2Base=65,105,225
AutodeskMayaRegularHidden=1

BitDefenderShape=Hexagon
BitDefenderMaskMeter=Shape
BitDefenderMask=Regular Hexagon
BitDefenderMaskStyle=Blank
BitDefenderMaskBase=255,255,255
BitDefenderShapeGradient1Base=225,65,105
BitDefenderShapeGradient2Base=65,105,225
BitDefenderRegularHidden=1

BitwardenShape=Hexagon
BitwardenMaskMeter=Shape
BitwardenMask=Regular Hexagon
BitwardenMaskStyle=Blank
BitwardenMaskBase=255,255,255
BitwardenShapeGradient1Base=225,65,105
BitwardenShapeGradient2Base=65,105,225
BitwardenRegularHidden=1

BlenderShape=Hexagon
BlenderMaskMeter=Shape
BlenderMask=Regular Hexagon
BlenderMaskStyle=Blank
BlenderMaskBase=255,255,255
BlenderShapeGradient1Base=225,65,105
BlenderShapeGradient2Base=65,105,225
BlenderRegularHidden=1

CSPShape=Hexagon
CSPMaskMeter=Shape
CSPMask=Regular Hexagon
CSPMaskStyle=Blank
CSPMaskBase=255,255,255
CSPShapeGradient1Base=225,65,105
CSPShapeGradient2Base=65,105,225
CSPRegularHidden=1

ClipchampShape=Hexagon
ClipchampMaskMeter=Shape
ClipchampMask=Regular Hexagon
ClipchampMaskStyle=Blank
ClipchampMaskBase=255,255,255
ClipchampShapeGradient1Base=225,65,105
ClipchampShapeGradient2Base=65,105,225
ClipchampRegularHidden=1

CorsairShape=Hexagon
CorsairMaskMeter=Shape
CorsairMask=Regular Hexagon
CorsairMaskStyle=Blank
CorsairMaskBase=255,255,255
CorsairShapeGradient1Base=225,65,105
CorsairShapeGradient2Base=65,105,225
CorsairRegularHidden=1

DaVinciShape=Hexagon
DaVinciMaskMeter=Shape
DaVinciMask=Regular Hexagon
DaVinciMaskStyle=Blank
DaVinciMaskBase=255,255,255
DaVinciShapeGradient1Base=225,65,105
DaVinciShapeGradient2Base=65,105,225
DaVinciRegularHidden=1

DeviantArtShape=Hexagon
DeviantArtMaskMeter=Shape
DeviantArtMask=Regular Hexagon
DeviantArtMaskStyle=Blank
DeviantArtMaskBase=255,255,255
DeviantArtShapeGradient1Base=225,65,105
DeviantArtShapeGradient2Base=65,105,225
DeviantArtRegularHidden=1

EvernoteShape=Hexagon
EvernoteMaskMeter=Shape
EvernoteMask=Regular Hexagon
EvernoteMaskStyle=Blank
EvernoteMaskBase=255,255,255
EvernoteShapeGradient1Base=225,65,105
EvernoteShapeGradient2Base=65,105,225
EvernoteRegularHidden=1

EVGAShape=Hexagon
EVGAMaskMeter=Shape
EVGAMask=Regular Hexagon
EVGAMaskStyle=Blank
EVGAMaskBase=255,255,255
EVGAShapeGradient1Base=225,65,105
EVGAShapeGradient2Base=65,105,225
EVGARegularHidden=1

FilmoraXShape=Hexagon
FilmoraXMaskMeter=Shape
FilmoraXMask=Regular Hexagon
FilmoraXMaskStyle=Blank
FilmoraXMaskBase=255,255,255
FilmoraXShapeGradient1Base=225,65,105
FilmoraXShapeGradient2Base=65,105,225
FilmoraXRegularHidden=1

FLStudioShape=Hexagon
FLStudioMaskMeter=Shape
FLStudioMask=Regular Hexagon
FLStudioMaskStyle=Blank
FLStudioMaskBase=255,255,255
FLStudioShapeGradient1Base=225,65,105
FLStudioShapeGradient2Base=65,105,225
FLStudioRegularHidden=1

FlowLauncherShape=Hexagon
FlowLauncherMaskMeter=Shape
FlowLauncherMask=Regular Hexagon
FlowLauncherMaskStyle=Blank
FlowLauncherMaskBase=255,255,255
FlowLauncherShapeGradient1Base=225,65,105
FlowLauncherShapeGradient2Base=65,105,225
FlowLauncherRegularHidden=1

GIMPShape=Hexagon
GIMPMaskMeter=Shape
GIMPMask=Regular Hexagon
GIMPMaskStyle=Blank
GIMPMaskBase=255,255,255
GIMPShapeGradient1Base=225,65,105
GIMPShapeGradient2Base=65,105,225
GIMPRegularHidden=1

HandBrakeShape=Hexagon
HandBrakeMaskMeter=Shape
HandBrakeMask=Regular Hexagon
HandBrakeMaskStyle=Blank
HandBrakeMaskBase=255,255,255
HandBrakeShapeGradient1Base=225,65,105
HandBrakeShapeGradient2Base=65,105,225
HandBrakeRegularHidden=1

InkscapeShape=Hexagon
InkscapeMaskMeter=Shape
InkscapeMask=Regular Hexagon
InkscapeMaskStyle=Blank
InkscapeMaskBase=255,255,255
InkscapeShapeGradient1Base=225,65,105
InkscapeShapeGradient2Base=65,105,225
InkscapeRegularHidden=1

JBPyCharmShape=Hexagon
JBPyCharmMaskMeter=Shape
JBPyCharmMask=Regular Hexagon
JBPyCharmMaskStyle=Blank
JBPyCharmMaskBase=255,255,255
JBPyCharmShapeGradient1Base=225,65,105
JBPyCharmShapeGradient2Base=65,105,225
JBPyCharmRegularHidden=1

JBRiderShape=Hexagon
JBRiderMaskMeter=Shape
JBRiderMask=Regular Hexagon
JBRiderMaskStyle=Blank
JBRiderMaskBase=255,255,255
JBRiderShapeGradient1Base=225,65,105
JBRiderShapeGradient2Base=65,105,225
JBRiderRegularHidden=1

KritaShape=Hexagon
KritaMaskMeter=Shape
KritaMask=Regular Hexagon
KritaMaskStyle=Blank
KritaMaskBase=255,255,255
KritaShapeGradient1Base=225,65,105
KritaShapeGradient2Base=65,105,225
KritaRegularHidden=1

LibrariesShape=Hexagon
LibrariesMaskMeter=Shape
LibrariesMask=Regular Hexagon
LibrariesMaskStyle=Blank
LibrariesMaskBase=255,255,255
LibrariesShapeGradient1Base=225,65,105
LibrariesShapeGradient2Base=65,105,225
LibrariesRegularHidden=1

LogitechShape=Hexagon
LogitechMaskMeter=Shape
LogitechMask=Regular Hexagon
LogitechMaskStyle=Blank
LogitechMaskBase=255,255,255
LogitechShapeGradient1Base=225,65,105
LogitechShapeGradient2Base=65,105,225
LogitechRegularHidden=1

ManageRainmeterShape=Hexagon
ManageRainmeterMaskMeter=Shape
ManageRainmeterMask=Regular Hexagon
ManageRainmeterMaskStyle=Blank
ManageRainmeterMaskBase=255,255,255
ManageRainmeterShapeGradient1Base=225,65,105
ManageRainmeterShapeGradient2Base=65,105,225
ManageRainmeterRegularHidden=1

MatlabShape=Hexagon
MatlabMaskMeter=Shape
MatlabMask=Regular Hexagon
MatlabMaskStyle=Blank
MatlabMaskBase=255,255,255
MatlabShapeGradient1Base=225,65,105
MatlabShapeGradient2Base=65,105,225
MatlabRegularHidden=1

MedalShape=Hexagon
MedalMaskMeter=Shape
MedalMask=Regular Hexagon
MedalMaskStyle=Blank
MedalMaskBase=255,255,255
MedalShapeGradient1Base=225,65,105
MedalShapeGradient2Base=65,105,225
MedalRegularHidden=1

MicrosoftStoreShape=Hexagon
MicrosoftStoreMaskMeter=Shape
MicrosoftStoreMask=Regular Hexagon
MicrosoftStoreMaskStyle=Blank
MicrosoftStoreMaskBase=255,255,255
MicrosoftStoreShapeGradient1Base=225,65,105
MicrosoftStoreShapeGradient2Base=65,105,225
MicrosoftStoreRegularHidden=1

MindomoShape=Hexagon
MindomoMaskMeter=Shape
MindomoMask=Regular Hexagon
MindomoMaskStyle=Blank
MindomoMaskBase=255,255,255
MindomoShapeGradient1Base=225,65,105
MindomoShapeGradient2Base=65,105,225
MindomoRegularHidden=1

MSIShape=Hexagon
MSIMaskMeter=Shape
MSIMask=Regular Hexagon
MSIMaskStyle=Blank
MSIMaskBase=255,255,255
MSIShapeGradient1Base=225,65,105
MSIShapeGradient2Base=65,105,225
MSIRegularHidden=1

MyPhoneExplorerShape=Hexagon
MyPhoneExplorerMaskMeter=Shape
MyPhoneExplorerMask=Regular Hexagon
MyPhoneExplorerMaskStyle=Blank
MyPhoneExplorerMaskBase=255,255,255
MyPhoneExplorerShapeGradient1Base=225,65,105
MyPhoneExplorerShapeGradient2Base=65,105,225
MyPhoneExplorerRegularHidden=1

NiceHashShape=Hexagon
NiceHashMaskMeter=Shape
NiceHashMask=Regular Hexagon
NiceHashMaskStyle=Blank
NiceHashMaskBase=255,255,255
NiceHashShapeGradient1Base=225,65,105
NiceHashShapeGradient2Base=65,105,225
NiceHashRegularHidden=1

NotepadPPShape=Hexagon
NotepadPPMaskMeter=Shape
NotepadPPMask=Regular Hexagon
NotepadPPMaskStyle=Blank
NotepadPPMaskBase=255,255,255
NotepadPPShapeGradient1Base=225,65,105
NotepadPPShapeGradient2Base=65,105,225
NotepadPPRegularHidden=1

NotionShape=Hexagon
NotionMaskMeter=Shape
NotionMask=Regular Hexagon
NotionMaskStyle=Blank
NotionMaskBase=255,255,255
NotionShapeGradient1Base=225,65,105
NotionShapeGradient2Base=65,105,225
NotionRegularHidden=1

NVIDIAShape=Hexagon
NVIDIAMaskMeter=Shape
NVIDIAMask=Regular Hexagon
NVIDIAMaskStyle=Blank
NVIDIAMaskBase=255,255,255
NVIDIAShapeGradient1Base=225,65,105
NVIDIAShapeGradient2Base=65,105,225
NVIDIARegularHidden=1

OBSShape=Hexagon
OBSMaskMeter=Shape
OBSMask=Regular Hexagon
OBSMaskStyle=Blank
OBSMaskBase=255,255,255
OBSShapeGradient1Base=225,65,105
OBSShapeGradient2Base=65,105,225
OBSRegularHidden=1

ObsidianShape=Hexagon
ObsidianMaskMeter=Shape
ObsidianMask=Regular Hexagon
ObsidianMaskStyle=Blank
ObsidianMaskBase=255,255,255
ObsidianShapeGradient1Base=225,65,105
ObsidianShapeGradient2Base=65,105,225
ObsidianRegularHidden=1

OculusShape=Hexagon
OculusMaskMeter=Shape
OculusMask=Regular Hexagon
OculusMaskStyle=Blank
OculusMaskBase=255,255,255
OculusShapeGradient1Base=225,65,105
OculusShapeGradient2Base=65,105,225
OculusRegularHidden=1

OutplayedShape=Hexagon
OutplayedMaskMeter=Shape
OutplayedMask=Regular Hexagon
OutplayedMaskStyle=Blank
OutplayedMaskBase=255,255,255
OutplayedShapeGradient1Base=225,65,105
OutplayedShapeGradient2Base=65,105,225
OutplayedRegularHidden=1

ProtonCalendarShape=Hexagon
ProtonCalendarMaskMeter=Shape
ProtonCalendarMask=Regular Hexagon
ProtonCalendarMaskStyle=Blank
ProtonCalendarMaskBase=255,255,255
ProtonCalendarShapeGradient1Base=225,65,105
ProtonCalendarShapeGradient2Base=65,105,225
ProtonCalendarRegularHidden=1

ProtonMailShape=Hexagon
ProtonMailMaskMeter=Shape
ProtonMailMask=Regular Hexagon
ProtonMailMaskStyle=Blank
ProtonMailMaskBase=255,255,255
ProtonMailShapeGradient1Base=225,65,105
ProtonMailShapeGradient2Base=65,105,225
ProtonMailRegularHidden=1

ProtonVPNShape=Hexagon
ProtonVPNMaskMeter=Shape
ProtonVPNMask=Regular Hexagon
ProtonVPNMaskStyle=Blank
ProtonVPNMaskBase=255,255,255
ProtonVPNShapeGradient1Base=225,65,105
ProtonVPNShapeGradient2Base=65,105,225
ProtonVPNRegularHidden=1

RazerCortexShape=Hexagon
RazerCortexMaskMeter=Shape
RazerCortexMask=Regular Hexagon
RazerCortexMaskStyle=Blank
RazerCortexMaskBase=255,255,255
RazerCortexShapeGradient1Base=225,65,105
RazerCortexShapeGradient2Base=65,105,225
RazerCortexRegularHidden=1

RazerSynapseShape=Hexagon
RazerSynapseMaskMeter=Shape
RazerSynapseMask=Regular Hexagon
RazerSynapseMaskStyle=Blank
RazerSynapseMaskBase=255,255,255
RazerSynapseShapeGradient1Base=225,65,105
RazerSynapseShapeGradient2Base=65,105,225
RazerSynapseRegularHidden=1

RecycleBinShape=Hexagon
RecycleBinMaskMeter=Shape
RecycleBinMask=Regular Hexagon
RecycleBinMaskStyle=Blank
RecycleBinMaskBase=255,255,255
RecycleBinShapeGradient1Base=225,65,105
RecycleBinShapeGradient2Base=65,105,225
RecycleBinRegularHidden=1

RemNoteShape=Hexagon
RemNoteMaskMeter=Shape
RemNoteMask=Regular Hexagon
RemNoteMaskStyle=Blank
RemNoteMaskBase=255,255,255
RemNoteShapeGradient1Base=225,65,105
RemNoteShapeGradient2Base=65,105,225
RemNoteRegularHidden=1

ScrivenerShape=Hexagon
ScrivenerMaskMeter=Shape
ScrivenerMask=Regular Hexagon
ScrivenerMaskStyle=Blank
ScrivenerMaskBase=255,255,255
ScrivenerShapeGradient1Base=225,65,105
ScrivenerShapeGradient2Base=65,105,225
ScrivenerRegularHidden=1

SlackShape=Hexagon
SlackMaskMeter=Shape
SlackMask=Regular Hexagon
SlackMaskStyle=Blank
SlackMaskBase=255,255,255
SlackShapeGradient1Base=225,65,105
SlackShapeGradient2Base=65,105,225
SlackRegularHidden=1

SoulseekQtShape=Hexagon
SoulseekQtMaskMeter=Shape
SoulseekQtMask=Regular Hexagon
SoulseekQtMaskStyle=Blank
SoulseekQtMaskBase=255,255,255
SoulseekQtShapeGradient1Base=225,65,105
SoulseekQtShapeGradient2Base=65,105,225
SoulseekQtRegularHidden=1

SpaceSnifferShape=Hexagon
SpaceSnifferMaskMeter=Shape
SpaceSnifferMask=Regular Hexagon
SpaceSnifferMaskStyle=Blank
SpaceSnifferMaskBase=255,255,255
SpaceSnifferShapeGradient1Base=225,65,105
SpaceSnifferShapeGradient2Base=65,105,225
SpaceSnifferRegularHidden=1

StreamLabsShape=Hexagon
StreamLabsMaskMeter=Shape
StreamLabsMask=Regular Hexagon
StreamLabsMaskStyle=Blank
StreamLabsMaskBase=255,255,255
StreamLabsShapeGradient1Base=225,65,105
StreamLabsShapeGradient2Base=65,105,225
StreamLabsRegularHidden=1

TeamViewerShape=Hexagon
TeamViewerMaskMeter=Shape
TeamViewerMask=Regular Hexagon
TeamViewerMaskStyle=Blank
TeamViewerMaskBase=255,255,255
TeamViewerShapeGradient1Base=225,65,105
TeamViewerShapeGradient2Base=65,105,225
TeamViewerRegularHidden=1

ThisPCShape=Hexagon
ThisPCMaskMeter=Shape
ThisPCMask=Regular Hexagon
ThisPCMaskStyle=Blank
ThisPCMaskBase=255,255,255
ThisPCShapeGradient1Base=225,65,105
ThisPCShapeGradient2Base=65,105,225
ThisPCRegularHidden=1

ThunderbirdShape=Hexagon
ThunderbirdMaskMeter=Shape
ThunderbirdMask=Regular Hexagon
ThunderbirdMaskStyle=Blank
ThunderbirdMaskBase=255,255,255
ThunderbirdShapeGradient1Base=225,65,105
ThunderbirdShapeGradient2Base=65,105,225
ThunderbirdRegularHidden=1

UnityShape=Hexagon
UnityMaskMeter=Shape
UnityMask=Regular Hexagon
UnityMaskStyle=Blank
UnityMaskBase=255,255,255
UnityShapeGradient1Base=225,65,105
UnityShapeGradient2Base=65,105,225
UnityRegularHidden=1

UnrealShape=Hexagon
UnrealMaskMeter=Shape
UnrealMask=Regular Hexagon
UnrealMaskStyle=Blank
UnrealMaskBase=255,255,255
UnrealShapeGradient1Base=225,65,105
UnrealShapeGradient2Base=65,105,225
UnrealRegularHidden=1

VirtualBoxShape=Hexagon
VirtualBoxMaskMeter=Shape
VirtualBoxMask=Regular Hexagon
VirtualBoxMaskStyle=Blank
VirtualBoxMaskBase=255,255,255
VirtualBoxShapeGradient1Base=225,65,105
VirtualBoxShapeGradient2Base=65,105,225
VirtualBoxRegularHidden=1

VisualStudioShape=Hexagon
VisualStudioMaskMeter=Shape
VisualStudioMask=Regular Hexagon
VisualStudioMaskStyle=Blank
VisualStudioMaskBase=255,255,255
VisualStudioShapeGradient1Base=225,65,105
VisualStudioShapeGradient2Base=65,105,225
VisualStudioRegularHidden=1

VSCodeShape=Hexagon
VSCodeMaskMeter=Shape
VSCodeMask=Regular Hexagon
VSCodeMaskStyle=Blank
VSCodeMaskBase=255,255,255
VSCodeShapeGradient1Base=225,65,105
VSCodeShapeGradient2Base=65,105,225
VSCodeRegularHidden=1

VMwareShape=Hexagon
VMwareMaskMeter=Shape
VMwareMask=Regular Hexagon
VMwareMaskStyle=Blank
VMwareMaskBase=255,255,255
VMwareShapeGradient1Base=225,65,105
VMwareShapeGradient2Base=65,105,225
VMwareRegularHidden=1

VTEverythingShape=Hexagon
VTEverythingMaskMeter=Shape
VTEverythingMask=Regular Hexagon
VTEverythingMaskStyle=Blank
VTEverythingMaskBase=255,255,255
VTEverythingShapeGradient1Base=225,65,105
VTEverythingShapeGradient2Base=65,105,225
VTEverythingRegularHidden=1

WallpaperEngineShape=Hexagon
WallpaperEngineMaskMeter=Shape
WallpaperEngineMask=Regular Hexagon
WallpaperEngineMaskStyle=Blank
WallpaperEngineMaskBase=255,255,255
WallpaperEngineShapeGradient1Base=225,65,105
WallpaperEngineShapeGradient2Base=65,105,225
WallpaperEngineRegularHidden=1

WindowsOSKShape=Hexagon
WindowsOSKMaskMeter=Shape
WindowsOSKMask=Regular Hexagon
WindowsOSKMaskStyle=Blank
WindowsOSKMaskBase=255,255,255
WindowsOSKShapeGradient1Base=225,65,105
WindowsOSKShapeGradient2Base=65,105,225
WindowsOSKRegularHidden=1

WindowsTerminalShape=Hexagon
WindowsTerminalMaskMeter=Shape
WindowsTerminalMask=Regular Hexagon
WindowsTerminalMaskStyle=Blank
WindowsTerminalMaskBase=255,255,255
WindowsTerminalShapeGradient1Base=225,65,105
WindowsTerminalShapeGradient2Base=65,105,225
WindowsTerminalRegularHidden=1

WPSShape=Hexagon
WPSMaskMeter=Shape
WPSMask=Regular Hexagon
WPSMaskStyle=Blank
WPSMaskBase=255,255,255
WPSShapeGradient1Base=225,65,105
WPSShapeGradient2Base=65,105,225
WPSRegularHidden=1

ZbrushShape=Hexagon
ZbrushMaskMeter=Shape
ZbrushMask=Regular Hexagon
ZbrushMaskStyle=Blank
ZbrushMaskBase=255,255,255
ZbrushShapeGradient1Base=225,65,105
ZbrushShapeGradient2Base=65,105,225
ZbrushRegularHidden=1
NameIconMC=Destiny2
