; =============================================================
; Chameleon Plugin
; =============================================================

[ChameleonDesktop]
Measure=Plugin
Plugin=Chameleon
Type=Desktop

[DesktopAvg]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Average

[DesktopFG1]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Foreground1

[DesktopFG2]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Foreground2

[DesktopBG1]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Background1

[DesktopBG2]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Background2

; =============================================================
; Chameleon Icon
; =============================================================

[AvgImageStyle]
ImageTint=[DesktopAvg]FF
AntiAlias=1
DynamicVariables=1

[FG1ImageStyle]
ImageTint=[DesktopFG1]FF
AntiAlias=1
DynamicVariables=1

[FG2ImageStyle]
ImageTint=[DesktopFG2]FF
AntiAlias=1
DynamicVariables=1

[BG1ImageStyle]
ImageTint=[DesktopBG1]FF
AntiAlias=1
DynamicVariables=1

[BG2ImageStyle]
ImageTint=[DesktopBG2]FF
AntiAlias=1
DynamicVariables=1

; =============================================================
; Chameleon Special Mask Shapes
; =============================================================

[SpecialChameleonAlterHexagonAvgStyle]
ImageName=#@#Image Shapes\Mask\90\Alter Hexagon.png
ImageTint=[DesktopAvg]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAlterHexagonFG1Style]
ImageName=#@#Image Shapes\Mask\90\Alter Hexagon.png
ImageTint=[DesktopFG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAlterHexagonFG2Style]
ImageName=#@#Image Shapes\Mask\90\Alter Hexagon.png
ImageTint=[DesktopFG2]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAlterHexagonBG1Style]
ImageName=#@#Image Shapes\Mask\90\Alter Hexagon.png
ImageTint=[DesktopBG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAlterHexagonBG2Style]
ImageName=#@#Image Shapes\Mask\90\Alter Hexagon.png
ImageTint=[DesktopBG2]FF
AntiAlias=1
DynamicVariables=1

; =============================================================

[SpecialChameleonAlterHexagonV2AvgStyle]
ImageName=#@#Image Shapes\Mask\90\Alter Hexagon V2.png
ImageTint=[DesktopAvg]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAlterHexagonV2FG1Style]
ImageName=#@#Image Shapes\Mask\90\Alter Hexagon V2.png
ImageTint=[DesktopFG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAlterHexagonV2FG2Style]
ImageName=#@#Image Shapes\Mask\90\Alter Hexagon V2.png
ImageTint=[DesktopFG2]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAlterHexagonV2BG1Style]
ImageName=#@#Image Shapes\Mask\90\Alter Hexagon V2.png
ImageTint=[DesktopBG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAlterHexagonV2BG2Style]
ImageName=#@#Image Shapes\Mask\90\Alter Hexagon V2.png
ImageTint=[DesktopBG2]FF
AntiAlias=1
DynamicVariables=1

; =============================================================

[SpecialChameleonDashedHexagonAvgStyle]
ImageName=#@#Image Shapes\Mask\90\Dashed Hexagon.png
ImageTint=[DesktopAvg]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonDashedHexagonFG1Style]
ImageName=#@#Image Shapes\Mask\90\Dashed Hexagon.png
ImageTint=[DesktopFG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonDashedHexagonFG2Style]
ImageName=#@#Image Shapes\Mask\90\Dashed Hexagon.png
ImageTint=[DesktopFG2]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonDashedHexagonBG1Style]
ImageName=#@#Image Shapes\Mask\90\Dashed Hexagon.png
ImageTint=[DesktopBG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonDashedHexagonBG2Style]
ImageName=#@#Image Shapes\Mask\90\Dashed Hexagon.png
ImageTint=[DesktopBG2]FF
AntiAlias=1
DynamicVariables=1

; =============================================================

[SpecialChameleonInlineHexagonAvgStyle]
ImageName=#@#Image Shapes\Mask\90\Inline Hexagon.png
ImageTint=[DesktopAvg]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonInlineHexagonFG1Style]
ImageName=#@#Image Shapes\Mask\90\Inline Hexagon.png
ImageTint=[DesktopFG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonInlineHexagonFG2Style]
ImageName=#@#Image Shapes\Mask\90\Inline Hexagon.png
ImageTint=[DesktopFG2]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonInlineHexagonBG1Style]
ImageName=#@#Image Shapes\Mask\90\Inline Hexagon.png
ImageTint=[DesktopBG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonInlineHexagonBG2Style]
ImageName=#@#Image Shapes\Mask\90\Inline Hexagon.png
ImageTint=[DesktopBG2]FF
AntiAlias=1
DynamicVariables=1

; =============================================================

[SpecialChameleonRegularHexagonAvgStyle]
ImageName=#@#Image Shapes\Mask\90\Regular Hexagon.png
ImageTint=[DesktopAvg]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonRegularHexagonFG1Style]
ImageName=#@#Image Shapes\Mask\90\Regular Hexagon.png
ImageTint=[DesktopFG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonRegularHexagonFG2Style]
ImageName=#@#Image Shapes\Mask\90\Regular Hexagon.png
ImageTint=[DesktopFG2]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonRegularHexagonBG1Style]
ImageName=#@#Image Shapes\Mask\90\Regular Hexagon.png
ImageTint=[DesktopBG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonRegularHexagonBG2Style]
ImageName=#@#Image Shapes\Mask\90\Regular Hexagon.png
ImageTint=[DesktopBG2]FF
AntiAlias=1
DynamicVariables=1

; =============================================================

[SpecialChameleonAlterSquareAvgStyle]
ImageName=#@#Image Shapes\Mask\90\Alter Square.png
ImageTint=[DesktopAvg]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAlterSquareFG1Style]
ImageName=#@#Image Shapes\Mask\90\Alter Square.png
ImageTint=[DesktopFG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAlterSquareFG2Style]
ImageName=#@#Image Shapes\Mask\90\Alter Square.png
ImageTint=[DesktopFG2]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAlterSquareBG1Style]
ImageName=#@#Image Shapes\Mask\90\Alter Square.png
ImageTint=[DesktopBG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAlterSquareBG2Style]
ImageName=#@#Image Shapes\Mask\90\Alter Square.png
ImageTint=[DesktopBG2]FF
AntiAlias=1
DynamicVariables=1

; =============================================================

[SpecialChameleonAlterSquareV2AvgStyle]
ImageName=#@#Image Shapes\Mask\90\Alter Square V2.png
ImageTint=[DesktopAvg]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAlterSquareV2FG1Style]
ImageName=#@#Image Shapes\Mask\90\Alter Square V2.png
ImageTint=[DesktopFG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAlterSquareV2FG2Style]
ImageName=#@#Image Shapes\Mask\90\Alter Square V2.png
ImageTint=[DesktopFG2]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAlterSquareV2BG1Style]
ImageName=#@#Image Shapes\Mask\90\Alter Square V2.png
ImageTint=[DesktopBG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAlterSquareV2BG2Style]
ImageName=#@#Image Shapes\Mask\90\Alter Square V2.png
ImageTint=[DesktopBG2]FF
AntiAlias=1
DynamicVariables=1

; =============================================================

[SpecialChameleonInlineSquareAvgStyle]
ImageName=#@#Image Shapes\Mask\90\Inline Square.png
ImageTint=[DesktopAvg]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonInlineSquareFG1Style]
ImageName=#@#Image Shapes\Mask\90\Inline Square.png
ImageTint=[DesktopFG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonInlineSquareFG2Style]
ImageName=#@#Image Shapes\Mask\90\Inline Square.png
ImageTint=[DesktopFG2]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonInlineSquareBG1Style]
ImageName=#@#Image Shapes\Mask\90\Inline Square.png
ImageTint=[DesktopBG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonInlineSquareBG2Style]
ImageName=#@#Image Shapes\Mask\90\Inline Square.png
ImageTint=[DesktopBG2]FF
AntiAlias=1
DynamicVariables=1

; =============================================================

[SpecialChameleonRegularSquareAvgStyle]
ImageName=#@#Image Shapes\Mask\90\Regular Square.png
ImageTint=[DesktopAvg]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonRegularSquareFG1Style]
ImageName=#@#Image Shapes\Mask\90\Regular Square.png
ImageTint=[DesktopFG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonRegularSquareFG2Style]
ImageName=#@#Image Shapes\Mask\90\Regular Square.png
ImageTint=[DesktopFG2]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonRegularSquareBG1Style]
ImageName=#@#Image Shapes\Mask\90\Regular Square.png
ImageTint=[DesktopBG1]FF
AntiAlias=1
DynamicVariables=1

[SpecialChameleonRegularSquareBG2Style]
ImageName=#@#Image Shapes\Mask\90\Regular Square.png
ImageTint=[DesktopBG2]FF
AntiAlias=1
DynamicVariables=1

; =============================================================
; Chameleon Special Icon
; =============================================================

[SpecialChameleonAdobeAvgStyle]
ImagePath=#@#Image Shapes\Settings\Icon\Adobe
ImageTint=[DesktopAvg]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAdobeFG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Adobe
ImageTint=[DesktopFG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAdobeFG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Adobe
ImageTint=[DesktopFG2]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAdobeBG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Adobe
ImageTint=[DesktopBG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonAdobeBG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Adobe
ImageTint=[DesktopBG2]FF
H=90
AntiAlias=1
DynamicVariables=1

; =============================================================

[SpecialChameleonBrowsingAvgStyle]
ImagePath=#@#Image Shapes\Settings\Icon\Browsing
ImageTint=[DesktopAvg]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonBrowsingFG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Browsing
ImageTint=[DesktopFG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonBrowsingFG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Browsing
ImageTint=[DesktopFG2]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonBrowsingBG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Browsing
ImageTint=[DesktopBG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonBrowsingBG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Browsing
ImageTint=[DesktopBG2]FF
H=90
AntiAlias=1
DynamicVariables=1

; =============================================================

[SpecialChameleonEmulatorAvgStyle]
ImagePath=#@#Image Shapes\Settings\Icon\Emulator
ImageTint=[DesktopAvg]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonEmulatorFG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Emulator
ImageTint=[DesktopFG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonEmulatorFG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Emulator
ImageTint=[DesktopFG2]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonEmulatorBG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Emulator
ImageTint=[DesktopBG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonEmulatorBG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Emulator
ImageTint=[DesktopBG2]FF
H=90
AntiAlias=1
DynamicVariables=1

; =============================================================

[SpecialChameleonGamingAvgStyle]
ImagePath=#@#Image Shapes\Settings\Icon\Gaming
ImageTint=[DesktopAvg]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonGamingFG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Gaming
ImageTint=[DesktopFG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonGamingFG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Gaming
ImageTint=[DesktopFG2]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonGamingBG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Gaming
ImageTint=[DesktopBG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonGamingBG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Gaming
ImageTint=[DesktopBG2]FF
H=90
AntiAlias=1
DynamicVariables=1

; =============================================================

[SpecialChameleonMediaAvgStyle]
ImagePath=#@#Image Shapes\Settings\Icon\Media
ImageTint=[DesktopAvg]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonMediaFG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Media
ImageTint=[DesktopFG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonMediaFG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Media
ImageTint=[DesktopFG2]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonMediaBG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Media
ImageTint=[DesktopBG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonMediaBG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Media
ImageTint=[DesktopBG2]FF
H=90
AntiAlias=1
DynamicVariables=1

; =============================================================

[SpecialChameleonOfficeAvgStyle]
ImagePath=#@#Image Shapes\Settings\Icon\Office
ImageTint=[DesktopAvg]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonOfficeFG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Office
ImageTint=[DesktopFG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonOfficeFG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Office
ImageTint=[DesktopFG2]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonOfficeBG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Office
ImageTint=[DesktopBG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonOfficeBG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Office
ImageTint=[DesktopBG2]FF
H=90
AntiAlias=1
DynamicVariables=1

; =============================================================

[SpecialChameleonSocialAvgStyle]
ImagePath=#@#Image Shapes\Settings\Icon\Social
ImageTint=[DesktopAvg]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonSocialFG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Social
ImageTint=[DesktopFG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonSocialFG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Social
ImageTint=[DesktopFG2]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonSocialBG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Social
ImageTint=[DesktopBG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonSocialBG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Social
ImageTint=[DesktopBG2]FF
H=90
AntiAlias=1
DynamicVariables=1

; =============================================================

[SpecialChameleonOtherAvgStyle]
ImagePath=#@#Image Shapes\Settings\Icon\Other
ImageTint=[DesktopAvg]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonOtherFG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Other
ImageTint=[DesktopFG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonOtherFG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Other
ImageTint=[DesktopFG2]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonOtherBG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Other
ImageTint=[DesktopBG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonOtherBG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Other
ImageTint=[DesktopBG2]FF
H=90
AntiAlias=1
DynamicVariables=1

; =============================================================

[SpecialChameleonBlankAvgStyle]
ImagePath=#@#Image Shapes\Settings\Icon\Blank
ImageTint=[DesktopAvg]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonBlankFG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Blank
ImageTint=[DesktopFG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonBlankFG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Blank
ImageTint=[DesktopFG2]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonBlankBG1Style]
ImagePath=#@#Image Shapes\Settings\Icon\Blank
ImageTint=[DesktopBG1]FF
H=90
AntiAlias=1
DynamicVariables=1

[SpecialChameleonBlankBG2Style]
ImagePath=#@#Image Shapes\Settings\Icon\Blank
ImageTint=[DesktopBG2]FF
H=90
AntiAlias=1
DynamicVariables=1
