[Variables]

; Category
PageCategory=Info
CategoryPage1=0
CategoryPage2=1
NameIcon=Info
HiddenLineInfo=1

; Option Page
OptionPage1=0
OptionPage2=1

; Adobe Page
AdobePage1=0
AdobePage2=1

; Browsing Page
; N/A

; Emulator Page
EmulatorPage1=0
EmulatorPage2=1

; Gaming Page
GamingPage1=1
GamingPage2=1
GamingPage3=1
GamingPage4=1
GamingPage5=1
GamingPage6=1
GamingPage7=1
GamingPage8=1
GamingPage9=1
GamingPage10=0
GamingPage11=1
GamingPage12=1

; Media Page
MediaPage1=0
MediaPage2=1
MediaPage3=1

; Office Page
; N/A

; Social Page
SocialPage1=0
SocialPage2=1

; Other Page
OtherPage1=0
OtherPage2=1
OtherPage3=1
OtherPage4=1
OtherPage5=1
