[Variables]

NameShape=Alter Hexagon
NumShape=3
IconNum=1

SpecNameShape=AlterHexagon
SpecNumShape=3
SpecIconNum=1
SpecSetIconShapeNum=1

; ============================================================
; ============================================================

Special3Icon1CategoryAlterHexagonNo1=Blank
Special3Icon1CategoryAlterHexagonNo2=Blank
Special3Icon1CategoryAlterHexagonNo3=Blank

Special3Icon2CategoryAlterHexagonNo1=Blank
Special3Icon2CategoryAlterHexagonNo2=Blank
Special3Icon2CategoryAlterHexagonNo3=Blank

Special3Icon3CategoryAlterHexagonNo1=Blank
Special3Icon3CategoryAlterHexagonNo2=Blank
Special3Icon3CategoryAlterHexagonNo3=Blank

Special3Icon4CategoryAlterHexagonNo1=Blank
Special3Icon4CategoryAlterHexagonNo2=Blank
Special3Icon4CategoryAlterHexagonNo3=Blank

Special3Icon5CategoryAlterHexagonNo1=Blank
Special3Icon5CategoryAlterHexagonNo2=Blank
Special3Icon5CategoryAlterHexagonNo3=Blank

Special3Icon1AlterHexagonNo1=Blank
Special3Icon1AlterHexagonNo2=Blank
Special3Icon1AlterHexagonNo3=Blank

Special3Icon2AlterHexagonNo1=Blank
Special3Icon2AlterHexagonNo2=Blank
Special3Icon2AlterHexagonNo3=Blank

Special3Icon3AlterHexagonNo1=Blank
Special3Icon3AlterHexagonNo2=Blank
Special3Icon3AlterHexagonNo3=Blank

Special3Icon4AlterHexagonNo1=Blank
Special3Icon4AlterHexagonNo2=Blank
Special3Icon4AlterHexagonNo3=Blank

Special3Icon5AlterHexagonNo1=Blank
Special3Icon5AlterHexagonNo2=Blank
Special3Icon5AlterHexagonNo3=Blank

Special3Icon1URLAlterHexagonNo1=Blank
Special3Icon1URLAlterHexagonNo2=Blank
Special3Icon1URLAlterHexagonNo3=Blank

Special3Icon2URLAlterHexagonNo1=Blank
Special3Icon2URLAlterHexagonNo2=Blank
Special3Icon2URLAlterHexagonNo3=Blank

Special3Icon3URLAlterHexagonNo1=Blank
Special3Icon3URLAlterHexagonNo2=Blank
Special3Icon3URLAlterHexagonNo3=Blank

Special3Icon4URLAlterHexagonNo1=Blank
Special3Icon4URLAlterHexagonNo2=Blank
Special3Icon4URLAlterHexagonNo3=Blank

Special3Icon5URLAlterHexagonNo1=Blank
Special3Icon5URLAlterHexagonNo2=Blank
Special3Icon5URLAlterHexagonNo3=Blank

Special3Icon1AlterHexagonCode=Base
Special3Icon1AlterHexagonColorType=Base
Special3Icon1AlterHexagonChameleonName=Foreground 1
Special3Icon1AlterHexagonChameleonHidden=1
Special3Icon1AlterHexagonBase=255,255,255
Special3Icon1AlterHexagonBaseHidden=0

Special3Icon2AlterHexagonCode=Base
Special3Icon2AlterHexagonColorType=Base
Special3Icon2AlterHexagonChameleonName=Foreground 1
Special3Icon2AlterHexagonChameleonHidden=1
Special3Icon2AlterHexagonBase=255,255,255
Special3Icon2AlterHexagonBaseHidden=0

Special3Icon3AlterHexagonCode=Base
Special3Icon3AlterHexagonColorType=Base
Special3Icon3AlterHexagonChameleonName=Foreground 1
Special3Icon3AlterHexagonChameleonHidden=1
Special3Icon3AlterHexagonBase=255,255,255
Special3Icon3AlterHexagonBaseHidden=0

Special3Icon4AlterHexagonCode=Base
Special3Icon4AlterHexagonColorType=Base
Special3Icon4AlterHexagonChameleonName=Foreground 1
Special3Icon4AlterHexagonChameleonHidden=1
Special3Icon4AlterHexagonBase=255,255,255
Special3Icon4AlterHexagonBaseHidden=0

Special3Icon5AlterHexagonCode=Base
Special3Icon5AlterHexagonColorType=Base
Special3Icon5AlterHexagonChameleonName=Foreground 1
Special3Icon5AlterHexagonChameleonHidden=1
Special3Icon5AlterHexagonBase=255,255,255
Special3Icon5AlterHexagonBaseHidden=0

; ============================================================
; ============================================================

Special4Icon1CategoryAlterHexagonNo1=Blank
Special4Icon1CategoryAlterHexagonNo2=Blank
Special4Icon1CategoryAlterHexagonNo3=Blank
Special4Icon1CategoryAlterHexagonNo4=Blank

Special4Icon2CategoryAlterHexagonNo1=Blank
Special4Icon2CategoryAlterHexagonNo2=Blank
Special4Icon2CategoryAlterHexagonNo3=Blank
Special4Icon2CategoryAlterHexagonNo4=Blank

Special4Icon3CategoryAlterHexagonNo1=Blank
Special4Icon3CategoryAlterHexagonNo2=Blank
Special4Icon3CategoryAlterHexagonNo3=Blank
Special4Icon3CategoryAlterHexagonNo4=Blank

Special4Icon4CategoryAlterHexagonNo1=Blank
Special4Icon4CategoryAlterHexagonNo2=Blank
Special4Icon4CategoryAlterHexagonNo3=Blank
Special4Icon4CategoryAlterHexagonNo4=Blank

Special4Icon5CategoryAlterHexagonNo1=Blank
Special4Icon5CategoryAlterHexagonNo2=Blank
Special4Icon5CategoryAlterHexagonNo3=Blank
Special4Icon5CategoryAlterHexagonNo4=Blank

Special4Icon1AlterHexagonNo1=Blank
Special4Icon1AlterHexagonNo2=Blank
Special4Icon1AlterHexagonNo3=Blank
Special4Icon1AlterHexagonNo4=Blank

Special4Icon2AlterHexagonNo1=Blank
Special4Icon2AlterHexagonNo2=Blank
Special4Icon2AlterHexagonNo3=Blank
Special4Icon2AlterHexagonNo4=Blank

Special4Icon3AlterHexagonNo1=Blank
Special4Icon3AlterHexagonNo2=Blank
Special4Icon3AlterHexagonNo3=Blank
Special4Icon3AlterHexagonNo4=Blank

Special4Icon4AlterHexagonNo1=Blank
Special4Icon4AlterHexagonNo2=Blank
Special4Icon4AlterHexagonNo3=Blank
Special4Icon4AlterHexagonNo4=Blank

Special4Icon5AlterHexagonNo1=Blank
Special4Icon5AlterHexagonNo2=Blank
Special4Icon5AlterHexagonNo3=Blank
Special4Icon5AlterHexagonNo4=Blank

Special4Icon1URLAlterHexagonNo1=Blank
Special4Icon1URLAlterHexagonNo2=Blank
Special4Icon1URLAlterHexagonNo3=Blank
Special4Icon1URLAlterHexagonNo4=Blank

Special4Icon2URLAlterHexagonNo1=Blank
Special4Icon2URLAlterHexagonNo2=Blank
Special4Icon2URLAlterHexagonNo3=Blank
Special4Icon2URLAlterHexagonNo4=Blank

Special4Icon3URLAlterHexagonNo1=Blank
Special4Icon3URLAlterHexagonNo2=Blank
Special4Icon3URLAlterHexagonNo3=Blank
Special4Icon3URLAlterHexagonNo4=Blank

Special4Icon4URLAlterHexagonNo1=Blank
Special4Icon4URLAlterHexagonNo2=Blank
Special4Icon4URLAlterHexagonNo3=Blank
Special4Icon4URLAlterHexagonNo4=Blank

Special4Icon5URLAlterHexagonNo1=Blank
Special4Icon5URLAlterHexagonNo2=Blank
Special4Icon5URLAlterHexagonNo3=Blank
Special4Icon5URLAlterHexagonNo4=Blank

Special4Icon1AlterHexagonCode=Base
Special4Icon1AlterHexagonColorType=Base
Special4Icon1AlterHexagonChameleonName=Foreground 1
Special4Icon1AlterHexagonChameleonHidden=1
Special4Icon1AlterHexagonBase=255,255,255
Special4Icon1AlterHexagonBaseHidden=0

Special4Icon2AlterHexagonCode=Base
Special4Icon2AlterHexagonColorType=Base
Special4Icon2AlterHexagonChameleonName=Foreground 1
Special4Icon2AlterHexagonChameleonHidden=1
Special4Icon2AlterHexagonBase=255,255,255
Special4Icon2AlterHexagonBaseHidden=0

Special4Icon3AlterHexagonCode=Base
Special4Icon3AlterHexagonColorType=Base
Special4Icon3AlterHexagonChameleonName=Foreground 1
Special4Icon3AlterHexagonChameleonHidden=1
Special4Icon3AlterHexagonBase=255,255,255
Special4Icon3AlterHexagonBaseHidden=0

Special4Icon4AlterHexagonCode=Base
Special4Icon4AlterHexagonColorType=Base
Special4Icon4AlterHexagonChameleonName=Foreground 1
Special4Icon4AlterHexagonChameleonHidden=1
Special4Icon4AlterHexagonBase=255,255,255
Special4Icon4AlterHexagonBaseHidden=0

Special4Icon5AlterHexagonCode=Base
Special4Icon5AlterHexagonColorType=Base
Special4Icon5AlterHexagonChameleonName=Foreground 1
Special4Icon5AlterHexagonChameleonHidden=1
Special4Icon5AlterHexagonBase=255,255,255
Special4Icon5AlterHexagonBaseHidden=0

; ============================================================
; ============================================================

Special5Icon1CategoryAlterHexagonNo1=Blank
Special5Icon1CategoryAlterHexagonNo2=Blank
Special5Icon1CategoryAlterHexagonNo3=Blank
Special5Icon1CategoryAlterHexagonNo4=Blank
Special5Icon1CategoryAlterHexagonNo5=Blank

Special5Icon2CategoryAlterHexagonNo1=Blank
Special5Icon2CategoryAlterHexagonNo2=Blank
Special5Icon2CategoryAlterHexagonNo3=Blank
Special5Icon2CategoryAlterHexagonNo4=Blank
Special5Icon2CategoryAlterHexagonNo5=Blank

Special5Icon3CategoryAlterHexagonNo1=Blank
Special5Icon3CategoryAlterHexagonNo2=Blank
Special5Icon3CategoryAlterHexagonNo3=Blank
Special5Icon3CategoryAlterHexagonNo4=Blank
Special5Icon3CategoryAlterHexagonNo5=Blank

Special5Icon4CategoryAlterHexagonNo1=Blank
Special5Icon4CategoryAlterHexagonNo2=Blank
Special5Icon4CategoryAlterHexagonNo3=Blank
Special5Icon4CategoryAlterHexagonNo4=Blank
Special5Icon4CategoryAlterHexagonNo5=Blank

Special5Icon5CategoryAlterHexagonNo1=Blank
Special5Icon5CategoryAlterHexagonNo2=Blank
Special5Icon5CategoryAlterHexagonNo3=Blank
Special5Icon5CategoryAlterHexagonNo4=Blank
Special5Icon5CategoryAlterHexagonNo5=Blank

Special5Icon1AlterHexagonNo1=Blank
Special5Icon1AlterHexagonNo2=Blank
Special5Icon1AlterHexagonNo3=Blank
Special5Icon1AlterHexagonNo4=Blank
Special5Icon1AlterHexagonNo5=Blank

Special5Icon2AlterHexagonNo1=Blank
Special5Icon2AlterHexagonNo2=Blank
Special5Icon2AlterHexagonNo3=Blank
Special5Icon2AlterHexagonNo4=Blank
Special5Icon2AlterHexagonNo5=Blank

Special5Icon3AlterHexagonNo1=Blank
Special5Icon3AlterHexagonNo2=Blank
Special5Icon3AlterHexagonNo3=Blank
Special5Icon3AlterHexagonNo4=Blank
Special5Icon3AlterHexagonNo5=Blank

Special5Icon4AlterHexagonNo1=Blank
Special5Icon4AlterHexagonNo2=Blank
Special5Icon4AlterHexagonNo3=Blank
Special5Icon4AlterHexagonNo4=Blank
Special5Icon4AlterHexagonNo5=Blank

Special5Icon5AlterHexagonNo1=Blank
Special5Icon5AlterHexagonNo2=Blank
Special5Icon5AlterHexagonNo3=Blank
Special5Icon5AlterHexagonNo4=Blank
Special5Icon5AlterHexagonNo5=Blank

Special5Icon1URLAlterHexagonNo1=Blank
Special5Icon1URLAlterHexagonNo2=Blank
Special5Icon1URLAlterHexagonNo3=Blank
Special5Icon1URLAlterHexagonNo4=Blank
Special5Icon1URLAlterHexagonNo5=Blank

Special5Icon2URLAlterHexagonNo1=Blank
Special5Icon2URLAlterHexagonNo2=Blank
Special5Icon2URLAlterHexagonNo3=Blank
Special5Icon2URLAlterHexagonNo4=Blank
Special5Icon2URLAlterHexagonNo5=Blank

Special5Icon3URLAlterHexagonNo1=Blank
Special5Icon3URLAlterHexagonNo2=Blank
Special5Icon3URLAlterHexagonNo3=Blank
Special5Icon3URLAlterHexagonNo4=Blank
Special5Icon3URLAlterHexagonNo5=Blank

Special5Icon4URLAlterHexagonNo1=Blank
Special5Icon4URLAlterHexagonNo2=Blank
Special5Icon4URLAlterHexagonNo3=Blank
Special5Icon4URLAlterHexagonNo4=Blank
Special5Icon4URLAlterHexagonNo5=Blank

Special5Icon5URLAlterHexagonNo1=Blank
Special5Icon5URLAlterHexagonNo2=Blank
Special5Icon5URLAlterHexagonNo3=Blank
Special5Icon5URLAlterHexagonNo4=Blank
Special5Icon5URLAlterHexagonNo5=Blank

Special5Icon1AlterHexagonCode=Base
Special5Icon1AlterHexagonColorType=Base
Special5Icon1AlterHexagonChameleonName=Foreground 1
Special5Icon1AlterHexagonChameleonHidden=1
Special5Icon1AlterHexagonBase=255,255,255
Special5Icon1AlterHexagonBaseHidden=0

Special5Icon2AlterHexagonCode=Base
Special5Icon2AlterHexagonColorType=Base
Special5Icon2AlterHexagonChameleonName=Foreground 1
Special5Icon2AlterHexagonChameleonHidden=1
Special5Icon2AlterHexagonBase=255,255,255
Special5Icon2AlterHexagonBaseHidden=0

Special5Icon3AlterHexagonCode=Base
Special5Icon3AlterHexagonColorType=Base
Special5Icon3AlterHexagonChameleonName=Foreground 1
Special5Icon3AlterHexagonChameleonHidden=1
Special5Icon3AlterHexagonBase=255,255,255
Special5Icon3AlterHexagonBaseHidden=0

Special5Icon4AlterHexagonCode=Base
Special5Icon4AlterHexagonColorType=Base
Special5Icon4AlterHexagonChameleonName=Foreground 1
Special5Icon4AlterHexagonChameleonHidden=1
Special5Icon4AlterHexagonBase=255,255,255
Special5Icon4AlterHexagonBaseHidden=0

Special5Icon5AlterHexagonCode=Base
Special5Icon5AlterHexagonColorType=Base
Special5Icon5AlterHexagonChameleonName=Foreground 1
Special5Icon5AlterHexagonChameleonHidden=1
Special5Icon5AlterHexagonBase=255,255,255
Special5Icon5AlterHexagonBaseHidden=0

; ============================================================
; ============================================================

Special7Icon1CategoryAlterHexagonNo1=Blank
Special7Icon1CategoryAlterHexagonNo2=Blank
Special7Icon1CategoryAlterHexagonNo3=Blank
Special7Icon1CategoryAlterHexagonNo4=Blank
Special7Icon1CategoryAlterHexagonNo5=Blank
Special7Icon1CategoryAlterHexagonNo6=Blank
Special7Icon1CategoryAlterHexagonNo7=Blank

Special7Icon2CategoryAlterHexagonNo1=Blank
Special7Icon2CategoryAlterHexagonNo2=Blank
Special7Icon2CategoryAlterHexagonNo3=Blank
Special7Icon2CategoryAlterHexagonNo4=Blank
Special7Icon2CategoryAlterHexagonNo5=Blank
Special7Icon2CategoryAlterHexagonNo6=Blank
Special7Icon2CategoryAlterHexagonNo7=Blank

Special7Icon3CategoryAlterHexagonNo1=Blank
Special7Icon3CategoryAlterHexagonNo2=Blank
Special7Icon3CategoryAlterHexagonNo3=Blank
Special7Icon3CategoryAlterHexagonNo4=Blank
Special7Icon3CategoryAlterHexagonNo5=Blank
Special7Icon3CategoryAlterHexagonNo6=Blank
Special7Icon3CategoryAlterHexagonNo7=Blank

Special7Icon4CategoryAlterHexagonNo1=Blank
Special7Icon4CategoryAlterHexagonNo2=Blank
Special7Icon4CategoryAlterHexagonNo3=Blank
Special7Icon4CategoryAlterHexagonNo4=Blank
Special7Icon4CategoryAlterHexagonNo5=Blank
Special7Icon4CategoryAlterHexagonNo6=Blank
Special7Icon4CategoryAlterHexagonNo7=Blank

Special7Icon5CategoryAlterHexagonNo1=Blank
Special7Icon5CategoryAlterHexagonNo2=Blank
Special7Icon5CategoryAlterHexagonNo3=Blank
Special7Icon5CategoryAlterHexagonNo4=Blank
Special7Icon5CategoryAlterHexagonNo5=Blank
Special7Icon5CategoryAlterHexagonNo6=Blank
Special7Icon5CategoryAlterHexagonNo7=Blank

Special7Icon1AlterHexagonNo1=Blank
Special7Icon1AlterHexagonNo2=Blank
Special7Icon1AlterHexagonNo3=Blank
Special7Icon1AlterHexagonNo4=Blank
Special7Icon1AlterHexagonNo5=Blank
Special7Icon1AlterHexagonNo6=Blank
Special7Icon1AlterHexagonNo7=Blank

Special7Icon2AlterHexagonNo1=Blank
Special7Icon2AlterHexagonNo2=Blank
Special7Icon2AlterHexagonNo3=Blank
Special7Icon2AlterHexagonNo4=Blank
Special7Icon2AlterHexagonNo5=Blank
Special7Icon2AlterHexagonNo6=Blank
Special7Icon2AlterHexagonNo7=Blank

Special7Icon3AlterHexagonNo1=Blank
Special7Icon3AlterHexagonNo2=Blank
Special7Icon3AlterHexagonNo3=Blank
Special7Icon3AlterHexagonNo4=Blank
Special7Icon3AlterHexagonNo5=Blank
Special7Icon3AlterHexagonNo6=Blank
Special7Icon3AlterHexagonNo7=Blank

Special7Icon4AlterHexagonNo1=Blank
Special7Icon4AlterHexagonNo2=Blank
Special7Icon4AlterHexagonNo3=Blank
Special7Icon4AlterHexagonNo4=Blank
Special7Icon4AlterHexagonNo5=Blank
Special7Icon4AlterHexagonNo6=Blank
Special7Icon4AlterHexagonNo7=Blank

Special7Icon5AlterHexagonNo1=Blank
Special7Icon5AlterHexagonNo2=Blank
Special7Icon5AlterHexagonNo3=Blank
Special7Icon5AlterHexagonNo4=Blank
Special7Icon5AlterHexagonNo5=Blank
Special7Icon5AlterHexagonNo6=Blank
Special7Icon5AlterHexagonNo7=Blank

Special7Icon1URLAlterHexagonNo1=Blank
Special7Icon1URLAlterHexagonNo2=Blank
Special7Icon1URLAlterHexagonNo3=Blank
Special7Icon1URLAlterHexagonNo4=Blank
Special7Icon1URLAlterHexagonNo5=Blank
Special7Icon1URLAlterHexagonNo6=Blank
Special7Icon1URLAlterHexagonNo7=Blank

Special7Icon2URLAlterHexagonNo1=Blank
Special7Icon2URLAlterHexagonNo2=Blank
Special7Icon2URLAlterHexagonNo3=Blank
Special7Icon2URLAlterHexagonNo4=Blank
Special7Icon2URLAlterHexagonNo5=Blank
Special7Icon2URLAlterHexagonNo6=Blank
Special7Icon2URLAlterHexagonNo7=Blank

Special7Icon3URLAlterHexagonNo1=Blank
Special7Icon3URLAlterHexagonNo2=Blank
Special7Icon3URLAlterHexagonNo3=Blank
Special7Icon3URLAlterHexagonNo4=Blank
Special7Icon3URLAlterHexagonNo5=Blank
Special7Icon3URLAlterHexagonNo6=Blank
Special7Icon3URLAlterHexagonNo7=Blank

Special7Icon4URLAlterHexagonNo1=Blank
Special7Icon4URLAlterHexagonNo2=Blank
Special7Icon4URLAlterHexagonNo3=Blank
Special7Icon4URLAlterHexagonNo4=Blank
Special7Icon4URLAlterHexagonNo5=Blank
Special7Icon4URLAlterHexagonNo6=Blank
Special7Icon4URLAlterHexagonNo7=Blank

Special7Icon5URLAlterHexagonNo1=Blank
Special7Icon5URLAlterHexagonNo2=Blank
Special7Icon5URLAlterHexagonNo3=Blank
Special7Icon5URLAlterHexagonNo4=Blank
Special7Icon5URLAlterHexagonNo5=Blank
Special7Icon5URLAlterHexagonNo6=Blank
Special7Icon5URLAlterHexagonNo7=Blank

Special7Icon1AlterHexagonCode=Base
Special7Icon1AlterHexagonColorType=Base
Special7Icon1AlterHexagonChameleonName=Foreground 1
Special7Icon1AlterHexagonChameleonHidden=1
Special7Icon1AlterHexagonBase=255,255,255
Special7Icon1AlterHexagonBaseHidden=0

Special7Icon2AlterHexagonCode=Base
Special7Icon2AlterHexagonColorType=Base
Special7Icon2AlterHexagonChameleonName=Foreground 1
Special7Icon2AlterHexagonChameleonHidden=1
Special7Icon2AlterHexagonBase=255,255,255
Special7Icon2AlterHexagonBaseHidden=0

Special7Icon3AlterHexagonCode=Base
Special7Icon3AlterHexagonColorType=Base
Special7Icon3AlterHexagonChameleonName=Foreground 1
Special7Icon3AlterHexagonChameleonHidden=1
Special7Icon3AlterHexagonBase=255,255,255
Special7Icon3AlterHexagonBaseHidden=0

Special7Icon4AlterHexagonCode=Base
Special7Icon4AlterHexagonColorType=Base
Special7Icon4AlterHexagonChameleonName=Foreground 1
Special7Icon4AlterHexagonChameleonHidden=1
Special7Icon4AlterHexagonBase=255,255,255
Special7Icon4AlterHexagonBaseHidden=0

Special7Icon5AlterHexagonCode=Base
Special7Icon5AlterHexagonColorType=Base
Special7Icon5AlterHexagonChameleonName=Foreground 1
Special7Icon5AlterHexagonChameleonHidden=1
Special7Icon5AlterHexagonBase=255,255,255
Special7Icon5AlterHexagonBaseHidden=0

; ============================================================
; ============================================================
; ============================================================
; ============================================================

Special3Icon1CategoryAlterHexagonV2No1=Blank
Special3Icon1CategoryAlterHexagonV2No2=Blank
Special3Icon1CategoryAlterHexagonV2No3=Blank

Special3Icon2CategoryAlterHexagonV2No1=Blank
Special3Icon2CategoryAlterHexagonV2No2=Blank
Special3Icon2CategoryAlterHexagonV2No3=Blank

Special3Icon3CategoryAlterHexagonV2No1=Blank
Special3Icon3CategoryAlterHexagonV2No2=Blank
Special3Icon3CategoryAlterHexagonV2No3=Blank

Special3Icon4CategoryAlterHexagonV2No1=Blank
Special3Icon4CategoryAlterHexagonV2No2=Blank
Special3Icon4CategoryAlterHexagonV2No3=Blank

Special3Icon5CategoryAlterHexagonV2No1=Blank
Special3Icon5CategoryAlterHexagonV2No2=Blank
Special3Icon5CategoryAlterHexagonV2No3=Blank

Special3Icon1AlterHexagonV2No1=Blank
Special3Icon1AlterHexagonV2No2=Blank
Special3Icon1AlterHexagonV2No3=Blank

Special3Icon2AlterHexagonV2No1=Blank
Special3Icon2AlterHexagonV2No2=Blank
Special3Icon2AlterHexagonV2No3=Blank

Special3Icon3AlterHexagonV2No1=Blank
Special3Icon3AlterHexagonV2No2=Blank
Special3Icon3AlterHexagonV2No3=Blank

Special3Icon4AlterHexagonV2No1=Blank
Special3Icon4AlterHexagonV2No2=Blank
Special3Icon4AlterHexagonV2No3=Blank

Special3Icon5AlterHexagonV2No1=Blank
Special3Icon5AlterHexagonV2No2=Blank
Special3Icon5AlterHexagonV2No3=Blank

Special3Icon1URLAlterHexagonV2No1=Blank
Special3Icon1URLAlterHexagonV2No2=Blank
Special3Icon1URLAlterHexagonV2No3=Blank

Special3Icon2URLAlterHexagonV2No1=Blank
Special3Icon2URLAlterHexagonV2No2=Blank
Special3Icon2URLAlterHexagonV2No3=Blank

Special3Icon3URLAlterHexagonV2No1=Blank
Special3Icon3URLAlterHexagonV2No2=Blank
Special3Icon3URLAlterHexagonV2No3=Blank

Special3Icon4URLAlterHexagonV2No1=Blank
Special3Icon4URLAlterHexagonV2No2=Blank
Special3Icon4URLAlterHexagonV2No3=Blank

Special3Icon5URLAlterHexagonV2No1=Blank
Special3Icon5URLAlterHexagonV2No2=Blank
Special3Icon5URLAlterHexagonV2No3=Blank

Special3Icon1AlterHexagonV2Code=Base
Special3Icon1AlterHexagonV2ColorType=Base
Special3Icon1AlterHexagonV2ChameleonName=Foreground 1
Special3Icon1AlterHexagonV2ChameleonHidden=1
Special3Icon1AlterHexagonV2Base=255,255,255
Special3Icon1AlterHexagonV2BaseHidden=0

Special3Icon2AlterHexagonV2Code=Base
Special3Icon2AlterHexagonV2ColorType=Base
Special3Icon2AlterHexagonV2ChameleonName=Foreground 1
Special3Icon2AlterHexagonV2ChameleonHidden=1
Special3Icon2AlterHexagonV2Base=255,255,255
Special3Icon2AlterHexagonV2BaseHidden=0

Special3Icon3AlterHexagonV2Code=Base
Special3Icon3AlterHexagonV2ColorType=Base
Special3Icon3AlterHexagonV2ChameleonName=Foreground 1
Special3Icon3AlterHexagonV2ChameleonHidden=1
Special3Icon3AlterHexagonV2Base=255,255,255
Special3Icon3AlterHexagonV2BaseHidden=0

Special3Icon4AlterHexagonV2Code=Base
Special3Icon4AlterHexagonV2ColorType=Base
Special3Icon4AlterHexagonV2ChameleonName=Foreground 1
Special3Icon4AlterHexagonV2ChameleonHidden=1
Special3Icon4AlterHexagonV2Base=255,255,255
Special3Icon4AlterHexagonV2BaseHidden=0

Special3Icon5AlterHexagonV2Code=Base
Special3Icon5AlterHexagonV2ColorType=Base
Special3Icon5AlterHexagonV2ChameleonName=Foreground 1
Special3Icon5AlterHexagonV2ChameleonHidden=1
Special3Icon5AlterHexagonV2Base=255,255,255
Special3Icon5AlterHexagonV2BaseHidden=0

; ============================================================
; ============================================================

Special4Icon1CategoryAlterHexagonV2No1=Blank
Special4Icon1CategoryAlterHexagonV2No2=Blank
Special4Icon1CategoryAlterHexagonV2No3=Blank
Special4Icon1CategoryAlterHexagonV2No4=Blank

Special4Icon2CategoryAlterHexagonV2No1=Blank
Special4Icon2CategoryAlterHexagonV2No2=Blank
Special4Icon2CategoryAlterHexagonV2No3=Blank
Special4Icon2CategoryAlterHexagonV2No4=Blank

Special4Icon3CategoryAlterHexagonV2No1=Blank
Special4Icon3CategoryAlterHexagonV2No2=Blank
Special4Icon3CategoryAlterHexagonV2No3=Blank
Special4Icon3CategoryAlterHexagonV2No4=Blank

Special4Icon4CategoryAlterHexagonV2No1=Blank
Special4Icon4CategoryAlterHexagonV2No2=Blank
Special4Icon4CategoryAlterHexagonV2No3=Blank
Special4Icon4CategoryAlterHexagonV2No4=Blank

Special4Icon5CategoryAlterHexagonV2No1=Blank
Special4Icon5CategoryAlterHexagonV2No2=Blank
Special4Icon5CategoryAlterHexagonV2No3=Blank
Special4Icon5CategoryAlterHexagonV2No4=Blank

Special4Icon1AlterHexagonV2No1=Blank
Special4Icon1AlterHexagonV2No2=Blank
Special4Icon1AlterHexagonV2No3=Blank
Special4Icon1AlterHexagonV2No4=Blank

Special4Icon2AlterHexagonV2No1=Blank
Special4Icon2AlterHexagonV2No2=Blank
Special4Icon2AlterHexagonV2No3=Blank
Special4Icon2AlterHexagonV2No4=Blank

Special4Icon3AlterHexagonV2No1=Blank
Special4Icon3AlterHexagonV2No2=Blank
Special4Icon3AlterHexagonV2No3=Blank
Special4Icon3AlterHexagonV2No4=Blank

Special4Icon4AlterHexagonV2No1=Blank
Special4Icon4AlterHexagonV2No2=Blank
Special4Icon4AlterHexagonV2No3=Blank
Special4Icon4AlterHexagonV2No4=Blank

Special4Icon5AlterHexagonV2No1=Blank
Special4Icon5AlterHexagonV2No2=Blank
Special4Icon5AlterHexagonV2No3=Blank
Special4Icon5AlterHexagonV2No4=Blank

Special4Icon1URLAlterHexagonV2No1=Blank
Special4Icon1URLAlterHexagonV2No2=Blank
Special4Icon1URLAlterHexagonV2No3=Blank
Special4Icon1URLAlterHexagonV2No4=Blank

Special4Icon2URLAlterHexagonV2No1=Blank
Special4Icon2URLAlterHexagonV2No2=Blank
Special4Icon2URLAlterHexagonV2No3=Blank
Special4Icon2URLAlterHexagonV2No4=Blank

Special4Icon3URLAlterHexagonV2No1=Blank
Special4Icon3URLAlterHexagonV2No2=Blank
Special4Icon3URLAlterHexagonV2No3=Blank
Special4Icon3URLAlterHexagonV2No4=Blank

Special4Icon4URLAlterHexagonV2No1=Blank
Special4Icon4URLAlterHexagonV2No2=Blank
Special4Icon4URLAlterHexagonV2No3=Blank
Special4Icon4URLAlterHexagonV2No4=Blank

Special4Icon5URLAlterHexagonV2No1=Blank
Special4Icon5URLAlterHexagonV2No2=Blank
Special4Icon5URLAlterHexagonV2No3=Blank
Special4Icon5URLAlterHexagonV2No4=Blank

Special4Icon1AlterHexagonV2Code=Base
Special4Icon1AlterHexagonV2ColorType=Base
Special4Icon1AlterHexagonV2ChameleonName=Foreground 1
Special4Icon1AlterHexagonV2ChameleonHidden=1
Special4Icon1AlterHexagonV2Base=255,255,255
Special4Icon1AlterHexagonV2BaseHidden=0

Special4Icon2AlterHexagonV2Code=Base
Special4Icon2AlterHexagonV2ColorType=Base
Special4Icon2AlterHexagonV2ChameleonName=Foreground 1
Special4Icon2AlterHexagonV2ChameleonHidden=1
Special4Icon2AlterHexagonV2Base=255,255,255
Special4Icon2AlterHexagonV2BaseHidden=0

Special4Icon3AlterHexagonV2Code=Base
Special4Icon3AlterHexagonV2ColorType=Base
Special4Icon3AlterHexagonV2ChameleonName=Foreground 1
Special4Icon3AlterHexagonV2ChameleonHidden=1
Special4Icon3AlterHexagonV2Base=255,255,255
Special4Icon3AlterHexagonV2BaseHidden=0

Special4Icon4AlterHexagonV2Code=Base
Special4Icon4AlterHexagonV2ColorType=Base
Special4Icon4AlterHexagonV2ChameleonName=Foreground 1
Special4Icon4AlterHexagonV2ChameleonHidden=1
Special4Icon4AlterHexagonV2Base=255,255,255
Special4Icon4AlterHexagonV2BaseHidden=0

Special4Icon5AlterHexagonV2Code=Base
Special4Icon5AlterHexagonV2ColorType=Base
Special4Icon5AlterHexagonV2ChameleonName=Foreground 1
Special4Icon5AlterHexagonV2ChameleonHidden=1
Special4Icon5AlterHexagonV2Base=255,255,255
Special4Icon5AlterHexagonV2BaseHidden=0

; ============================================================
; ============================================================

Special5Icon1CategoryAlterHexagonV2No1=Blank
Special5Icon1CategoryAlterHexagonV2No2=Blank
Special5Icon1CategoryAlterHexagonV2No3=Blank
Special5Icon1CategoryAlterHexagonV2No4=Blank
Special5Icon1CategoryAlterHexagonV2No5=Blank

Special5Icon2CategoryAlterHexagonV2No1=Blank
Special5Icon2CategoryAlterHexagonV2No2=Blank
Special5Icon2CategoryAlterHexagonV2No3=Blank
Special5Icon2CategoryAlterHexagonV2No4=Blank
Special5Icon2CategoryAlterHexagonV2No5=Blank

Special5Icon3CategoryAlterHexagonV2No1=Blank
Special5Icon3CategoryAlterHexagonV2No2=Blank
Special5Icon3CategoryAlterHexagonV2No3=Blank
Special5Icon3CategoryAlterHexagonV2No4=Blank
Special5Icon3CategoryAlterHexagonV2No5=Blank

Special5Icon4CategoryAlterHexagonV2No1=Blank
Special5Icon4CategoryAlterHexagonV2No2=Blank
Special5Icon4CategoryAlterHexagonV2No3=Blank
Special5Icon4CategoryAlterHexagonV2No4=Blank
Special5Icon4CategoryAlterHexagonV2No5=Blank

Special5Icon5CategoryAlterHexagonV2No1=Blank
Special5Icon5CategoryAlterHexagonV2No2=Blank
Special5Icon5CategoryAlterHexagonV2No3=Blank
Special5Icon5CategoryAlterHexagonV2No4=Blank
Special5Icon5CategoryAlterHexagonV2No5=Blank

Special5Icon1AlterHexagonV2No1=Blank
Special5Icon1AlterHexagonV2No2=Blank
Special5Icon1AlterHexagonV2No3=Blank
Special5Icon1AlterHexagonV2No4=Blank
Special5Icon1AlterHexagonV2No5=Blank

Special5Icon2AlterHexagonV2No1=Blank
Special5Icon2AlterHexagonV2No2=Blank
Special5Icon2AlterHexagonV2No3=Blank
Special5Icon2AlterHexagonV2No4=Blank
Special5Icon2AlterHexagonV2No5=Blank

Special5Icon3AlterHexagonV2No1=Blank
Special5Icon3AlterHexagonV2No2=Blank
Special5Icon3AlterHexagonV2No3=Blank
Special5Icon3AlterHexagonV2No4=Blank
Special5Icon3AlterHexagonV2No5=Blank

Special5Icon4AlterHexagonV2No1=Blank
Special5Icon4AlterHexagonV2No2=Blank
Special5Icon4AlterHexagonV2No3=Blank
Special5Icon4AlterHexagonV2No4=Blank
Special5Icon4AlterHexagonV2No5=Blank

Special5Icon5AlterHexagonV2No1=Blank
Special5Icon5AlterHexagonV2No2=Blank
Special5Icon5AlterHexagonV2No3=Blank
Special5Icon5AlterHexagonV2No4=Blank
Special5Icon5AlterHexagonV2No5=Blank

Special5Icon1URLAlterHexagonV2No1=Blank
Special5Icon1URLAlterHexagonV2No2=Blank
Special5Icon1URLAlterHexagonV2No3=Blank
Special5Icon1URLAlterHexagonV2No4=Blank
Special5Icon1URLAlterHexagonV2No5=Blank

Special5Icon2URLAlterHexagonV2No1=Blank
Special5Icon2URLAlterHexagonV2No2=Blank
Special5Icon2URLAlterHexagonV2No3=Blank
Special5Icon2URLAlterHexagonV2No4=Blank
Special5Icon2URLAlterHexagonV2No5=Blank

Special5Icon3URLAlterHexagonV2No1=Blank
Special5Icon3URLAlterHexagonV2No2=Blank
Special5Icon3URLAlterHexagonV2No3=Blank
Special5Icon3URLAlterHexagonV2No4=Blank
Special5Icon3URLAlterHexagonV2No5=Blank

Special5Icon4URLAlterHexagonV2No1=Blank
Special5Icon4URLAlterHexagonV2No2=Blank
Special5Icon4URLAlterHexagonV2No3=Blank
Special5Icon4URLAlterHexagonV2No4=Blank
Special5Icon4URLAlterHexagonV2No5=Blank

Special5Icon5URLAlterHexagonV2No1=Blank
Special5Icon5URLAlterHexagonV2No2=Blank
Special5Icon5URLAlterHexagonV2No3=Blank
Special5Icon5URLAlterHexagonV2No4=Blank
Special5Icon5URLAlterHexagonV2No5=Blank

Special5Icon1AlterHexagonV2Code=Base
Special5Icon1AlterHexagonV2ColorType=Base
Special5Icon1AlterHexagonV2ChameleonName=Foreground 1
Special5Icon1AlterHexagonV2ChameleonHidden=1
Special5Icon1AlterHexagonV2Base=255,255,255
Special5Icon1AlterHexagonV2BaseHidden=0

Special5Icon2AlterHexagonV2Code=Base
Special5Icon2AlterHexagonV2ColorType=Base
Special5Icon2AlterHexagonV2ChameleonName=Foreground 1
Special5Icon2AlterHexagonV2ChameleonHidden=1
Special5Icon2AlterHexagonV2Base=255,255,255
Special5Icon2AlterHexagonV2BaseHidden=0

Special5Icon3AlterHexagonV2Code=Base
Special5Icon3AlterHexagonV2ColorType=Base
Special5Icon3AlterHexagonV2ChameleonName=Foreground 1
Special5Icon3AlterHexagonV2ChameleonHidden=1
Special5Icon3AlterHexagonV2Base=255,255,255
Special5Icon3AlterHexagonV2BaseHidden=0

Special5Icon4AlterHexagonV2Code=Base
Special5Icon4AlterHexagonV2ColorType=Base
Special5Icon4AlterHexagonV2ChameleonName=Foreground 1
Special5Icon4AlterHexagonV2ChameleonHidden=1
Special5Icon4AlterHexagonV2Base=255,255,255
Special5Icon4AlterHexagonV2BaseHidden=0

Special5Icon5AlterHexagonV2Code=Base
Special5Icon5AlterHexagonV2ColorType=Base
Special5Icon5AlterHexagonV2ChameleonName=Foreground 1
Special5Icon5AlterHexagonV2ChameleonHidden=1
Special5Icon5AlterHexagonV2Base=255,255,255
Special5Icon5AlterHexagonV2BaseHidden=0

; ============================================================
; ============================================================

Special7Icon1CategoryAlterHexagonV2No1=Blank
Special7Icon1CategoryAlterHexagonV2No2=Blank
Special7Icon1CategoryAlterHexagonV2No3=Blank
Special7Icon1CategoryAlterHexagonV2No4=Blank
Special7Icon1CategoryAlterHexagonV2No5=Blank
Special7Icon1CategoryAlterHexagonV2No6=Blank
Special7Icon1CategoryAlterHexagonV2No7=Blank

Special7Icon2CategoryAlterHexagonV2No1=Blank
Special7Icon2CategoryAlterHexagonV2No2=Blank
Special7Icon2CategoryAlterHexagonV2No3=Blank
Special7Icon2CategoryAlterHexagonV2No4=Blank
Special7Icon2CategoryAlterHexagonV2No5=Blank
Special7Icon2CategoryAlterHexagonV2No6=Blank
Special7Icon2CategoryAlterHexagonV2No7=Blank

Special7Icon3CategoryAlterHexagonV2No1=Blank
Special7Icon3CategoryAlterHexagonV2No2=Blank
Special7Icon3CategoryAlterHexagonV2No3=Blank
Special7Icon3CategoryAlterHexagonV2No4=Blank
Special7Icon3CategoryAlterHexagonV2No5=Blank
Special7Icon3CategoryAlterHexagonV2No6=Blank
Special7Icon3CategoryAlterHexagonV2No7=Blank

Special7Icon4CategoryAlterHexagonV2No1=Blank
Special7Icon4CategoryAlterHexagonV2No2=Blank
Special7Icon4CategoryAlterHexagonV2No3=Blank
Special7Icon4CategoryAlterHexagonV2No4=Blank
Special7Icon4CategoryAlterHexagonV2No5=Blank
Special7Icon4CategoryAlterHexagonV2No6=Blank
Special7Icon4CategoryAlterHexagonV2No7=Blank

Special7Icon5CategoryAlterHexagonV2No1=Blank
Special7Icon5CategoryAlterHexagonV2No2=Blank
Special7Icon5CategoryAlterHexagonV2No3=Blank
Special7Icon5CategoryAlterHexagonV2No4=Blank
Special7Icon5CategoryAlterHexagonV2No5=Blank
Special7Icon5CategoryAlterHexagonV2No6=Blank
Special7Icon5CategoryAlterHexagonV2No7=Blank

Special7Icon1AlterHexagonV2No1=Blank
Special7Icon1AlterHexagonV2No2=Blank
Special7Icon1AlterHexagonV2No3=Blank
Special7Icon1AlterHexagonV2No4=Blank
Special7Icon1AlterHexagonV2No5=Blank
Special7Icon1AlterHexagonV2No6=Blank
Special7Icon1AlterHexagonV2No7=Blank

Special7Icon2AlterHexagonV2No1=Blank
Special7Icon2AlterHexagonV2No2=Blank
Special7Icon2AlterHexagonV2No3=Blank
Special7Icon2AlterHexagonV2No4=Blank
Special7Icon2AlterHexagonV2No5=Blank
Special7Icon2AlterHexagonV2No6=Blank
Special7Icon2AlterHexagonV2No7=Blank

Special7Icon3AlterHexagonV2No1=Blank
Special7Icon3AlterHexagonV2No2=Blank
Special7Icon3AlterHexagonV2No3=Blank
Special7Icon3AlterHexagonV2No4=Blank
Special7Icon3AlterHexagonV2No5=Blank
Special7Icon3AlterHexagonV2No6=Blank
Special7Icon3AlterHexagonV2No7=Blank

Special7Icon4AlterHexagonV2No1=Blank
Special7Icon4AlterHexagonV2No2=Blank
Special7Icon4AlterHexagonV2No3=Blank
Special7Icon4AlterHexagonV2No4=Blank
Special7Icon4AlterHexagonV2No5=Blank
Special7Icon4AlterHexagonV2No6=Blank
Special7Icon4AlterHexagonV2No7=Blank

Special7Icon5AlterHexagonV2No1=Blank
Special7Icon5AlterHexagonV2No2=Blank
Special7Icon5AlterHexagonV2No3=Blank
Special7Icon5AlterHexagonV2No4=Blank
Special7Icon5AlterHexagonV2No5=Blank
Special7Icon5AlterHexagonV2No6=Blank
Special7Icon5AlterHexagonV2No7=Blank

Special7Icon1URLAlterHexagonV2No1=Blank
Special7Icon1URLAlterHexagonV2No2=Blank
Special7Icon1URLAlterHexagonV2No3=Blank
Special7Icon1URLAlterHexagonV2No4=Blank
Special7Icon1URLAlterHexagonV2No5=Blank
Special7Icon1URLAlterHexagonV2No6=Blank
Special7Icon1URLAlterHexagonV2No7=Blank

Special7Icon2URLAlterHexagonV2No1=Blank
Special7Icon2URLAlterHexagonV2No2=Blank
Special7Icon2URLAlterHexagonV2No3=Blank
Special7Icon2URLAlterHexagonV2No4=Blank
Special7Icon2URLAlterHexagonV2No5=Blank
Special7Icon2URLAlterHexagonV2No6=Blank
Special7Icon2URLAlterHexagonV2No7=Blank

Special7Icon3URLAlterHexagonV2No1=Blank
Special7Icon3URLAlterHexagonV2No2=Blank
Special7Icon3URLAlterHexagonV2No3=Blank
Special7Icon3URLAlterHexagonV2No4=Blank
Special7Icon3URLAlterHexagonV2No5=Blank
Special7Icon3URLAlterHexagonV2No6=Blank
Special7Icon3URLAlterHexagonV2No7=Blank

Special7Icon4URLAlterHexagonV2No1=Blank
Special7Icon4URLAlterHexagonV2No2=Blank
Special7Icon4URLAlterHexagonV2No3=Blank
Special7Icon4URLAlterHexagonV2No4=Blank
Special7Icon4URLAlterHexagonV2No5=Blank
Special7Icon4URLAlterHexagonV2No6=Blank
Special7Icon4URLAlterHexagonV2No7=Blank

Special7Icon5URLAlterHexagonV2No1=Blank
Special7Icon5URLAlterHexagonV2No2=Blank
Special7Icon5URLAlterHexagonV2No3=Blank
Special7Icon5URLAlterHexagonV2No4=Blank
Special7Icon5URLAlterHexagonV2No5=Blank
Special7Icon5URLAlterHexagonV2No6=Blank
Special7Icon5URLAlterHexagonV2No7=Blank

Special7Icon1AlterHexagonV2Code=Base
Special7Icon1AlterHexagonV2ColorType=Base
Special7Icon1AlterHexagonV2ChameleonName=Foreground 1
Special7Icon1AlterHexagonV2ChameleonHidden=1
Special7Icon1AlterHexagonV2Base=255,255,255
Special7Icon1AlterHexagonV2BaseHidden=0

Special7Icon2AlterHexagonV2Code=Base
Special7Icon2AlterHexagonV2ColorType=Base
Special7Icon2AlterHexagonV2ChameleonName=Foreground 1
Special7Icon2AlterHexagonV2ChameleonHidden=1
Special7Icon2AlterHexagonV2Base=255,255,255
Special7Icon2AlterHexagonV2BaseHidden=0

Special7Icon3AlterHexagonV2Code=Base
Special7Icon3AlterHexagonV2ColorType=Base
Special7Icon3AlterHexagonV2ChameleonName=Foreground 1
Special7Icon3AlterHexagonV2ChameleonHidden=1
Special7Icon3AlterHexagonV2Base=255,255,255
Special7Icon3AlterHexagonV2BaseHidden=0

Special7Icon4AlterHexagonV2Code=Base
Special7Icon4AlterHexagonV2ColorType=Base
Special7Icon4AlterHexagonV2ChameleonName=Foreground 1
Special7Icon4AlterHexagonV2ChameleonHidden=1
Special7Icon4AlterHexagonV2Base=255,255,255
Special7Icon4AlterHexagonV2BaseHidden=0

Special7Icon5AlterHexagonV2Code=Base
Special7Icon5AlterHexagonV2ColorType=Base
Special7Icon5AlterHexagonV2ChameleonName=Foreground 1
Special7Icon5AlterHexagonV2ChameleonHidden=1
Special7Icon5AlterHexagonV2Base=255,255,255
Special7Icon5AlterHexagonV2BaseHidden=0

; ============================================================
; ============================================================
; ============================================================
; ============================================================

Special3Icon1CategoryDashedHexagonNo1=Blank
Special3Icon1CategoryDashedHexagonNo2=Blank
Special3Icon1CategoryDashedHexagonNo3=Blank

Special3Icon2CategoryDashedHexagonNo1=Blank
Special3Icon2CategoryDashedHexagonNo2=Blank
Special3Icon2CategoryDashedHexagonNo3=Blank

Special3Icon3CategoryDashedHexagonNo1=Blank
Special3Icon3CategoryDashedHexagonNo2=Blank
Special3Icon3CategoryDashedHexagonNo3=Blank

Special3Icon4CategoryDashedHexagonNo1=Blank
Special3Icon4CategoryDashedHexagonNo2=Blank
Special3Icon4CategoryDashedHexagonNo3=Blank

Special3Icon5CategoryDashedHexagonNo1=Blank
Special3Icon5CategoryDashedHexagonNo2=Blank
Special3Icon5CategoryDashedHexagonNo3=Blank

Special3Icon1DashedHexagonNo1=Blank
Special3Icon1DashedHexagonNo2=Blank
Special3Icon1DashedHexagonNo3=Blank

Special3Icon2DashedHexagonNo1=Blank
Special3Icon2DashedHexagonNo2=Blank
Special3Icon2DashedHexagonNo3=Blank

Special3Icon3DashedHexagonNo1=Blank
Special3Icon3DashedHexagonNo2=Blank
Special3Icon3DashedHexagonNo3=Blank

Special3Icon4DashedHexagonNo1=Blank
Special3Icon4DashedHexagonNo2=Blank
Special3Icon4DashedHexagonNo3=Blank

Special3Icon5DashedHexagonNo1=Blank
Special3Icon5DashedHexagonNo2=Blank
Special3Icon5DashedHexagonNo3=Blank

Special3Icon1URLDashedHexagonNo1=Blank
Special3Icon1URLDashedHexagonNo2=Blank
Special3Icon1URLDashedHexagonNo3=Blank

Special3Icon2URLDashedHexagonNo1=Blank
Special3Icon2URLDashedHexagonNo2=Blank
Special3Icon2URLDashedHexagonNo3=Blank

Special3Icon3URLDashedHexagonNo1=Blank
Special3Icon3URLDashedHexagonNo2=Blank
Special3Icon3URLDashedHexagonNo3=Blank

Special3Icon4URLDashedHexagonNo1=Blank
Special3Icon4URLDashedHexagonNo2=Blank
Special3Icon4URLDashedHexagonNo3=Blank

Special3Icon5URLDashedHexagonNo1=Blank
Special3Icon5URLDashedHexagonNo2=Blank
Special3Icon5URLDashedHexagonNo3=Blank

Special3Icon1DashedHexagonCode=Base
Special3Icon1DashedHexagonColorType=Base
Special3Icon1DashedHexagonChameleonName=Foreground 1
Special3Icon1DashedHexagonChameleonHidden=1
Special3Icon1DashedHexagonBase=255,255,255
Special3Icon1DashedHexagonBaseHidden=0

Special3Icon2DashedHexagonCode=Base
Special3Icon2DashedHexagonColorType=Base
Special3Icon2DashedHexagonChameleonName=Foreground 1
Special3Icon2DashedHexagonChameleonHidden=1
Special3Icon2DashedHexagonBase=255,255,255
Special3Icon2DashedHexagonBaseHidden=0

Special3Icon3DashedHexagonCode=Base
Special3Icon3DashedHexagonColorType=Base
Special3Icon3DashedHexagonChameleonName=Foreground 1
Special3Icon3DashedHexagonChameleonHidden=1
Special3Icon3DashedHexagonBase=255,255,255
Special3Icon3DashedHexagonBaseHidden=0

Special3Icon4DashedHexagonCode=Base
Special3Icon4DashedHexagonColorType=Base
Special3Icon4DashedHexagonChameleonName=Foreground 1
Special3Icon4DashedHexagonChameleonHidden=1
Special3Icon4DashedHexagonBase=255,255,255
Special3Icon4DashedHexagonBaseHidden=0

Special3Icon5DashedHexagonCode=Base
Special3Icon5DashedHexagonColorType=Base
Special3Icon5DashedHexagonChameleonName=Foreground 1
Special3Icon5DashedHexagonChameleonHidden=1
Special3Icon5DashedHexagonBase=255,255,255
Special3Icon5DashedHexagonBaseHidden=0

; ============================================================
; ============================================================

Special4Icon1CategoryDashedHexagonNo1=Blank
Special4Icon1CategoryDashedHexagonNo2=Blank
Special4Icon1CategoryDashedHexagonNo3=Blank
Special4Icon1CategoryDashedHexagonNo4=Blank

Special4Icon2CategoryDashedHexagonNo1=Blank
Special4Icon2CategoryDashedHexagonNo2=Blank
Special4Icon2CategoryDashedHexagonNo3=Blank
Special4Icon2CategoryDashedHexagonNo4=Blank

Special4Icon3CategoryDashedHexagonNo1=Blank
Special4Icon3CategoryDashedHexagonNo2=Blank
Special4Icon3CategoryDashedHexagonNo3=Blank
Special4Icon3CategoryDashedHexagonNo4=Blank

Special4Icon4CategoryDashedHexagonNo1=Blank
Special4Icon4CategoryDashedHexagonNo2=Blank
Special4Icon4CategoryDashedHexagonNo3=Blank
Special4Icon4CategoryDashedHexagonNo4=Blank

Special4Icon5CategoryDashedHexagonNo1=Blank
Special4Icon5CategoryDashedHexagonNo2=Blank
Special4Icon5CategoryDashedHexagonNo3=Blank
Special4Icon5CategoryDashedHexagonNo4=Blank

Special4Icon1DashedHexagonNo1=Blank
Special4Icon1DashedHexagonNo2=Blank
Special4Icon1DashedHexagonNo3=Blank
Special4Icon1DashedHexagonNo4=Blank

Special4Icon2DashedHexagonNo1=Blank
Special4Icon2DashedHexagonNo2=Blank
Special4Icon2DashedHexagonNo3=Blank
Special4Icon2DashedHexagonNo4=Blank

Special4Icon3DashedHexagonNo1=Blank
Special4Icon3DashedHexagonNo2=Blank
Special4Icon3DashedHexagonNo3=Blank
Special4Icon3DashedHexagonNo4=Blank

Special4Icon4DashedHexagonNo1=Blank
Special4Icon4DashedHexagonNo2=Blank
Special4Icon4DashedHexagonNo3=Blank
Special4Icon4DashedHexagonNo4=Blank

Special4Icon5DashedHexagonNo1=Blank
Special4Icon5DashedHexagonNo2=Blank
Special4Icon5DashedHexagonNo3=Blank
Special4Icon5DashedHexagonNo4=Blank

Special4Icon1URLDashedHexagonNo1=Blank
Special4Icon1URLDashedHexagonNo2=Blank
Special4Icon1URLDashedHexagonNo3=Blank
Special4Icon1URLDashedHexagonNo4=Blank

Special4Icon2URLDashedHexagonNo1=Blank
Special4Icon2URLDashedHexagonNo2=Blank
Special4Icon2URLDashedHexagonNo3=Blank
Special4Icon2URLDashedHexagonNo4=Blank

Special4Icon3URLDashedHexagonNo1=Blank
Special4Icon3URLDashedHexagonNo2=Blank
Special4Icon3URLDashedHexagonNo3=Blank
Special4Icon3URLDashedHexagonNo4=Blank

Special4Icon4URLDashedHexagonNo1=Blank
Special4Icon4URLDashedHexagonNo2=Blank
Special4Icon4URLDashedHexagonNo3=Blank
Special4Icon4URLDashedHexagonNo4=Blank

Special4Icon5URLDashedHexagonNo1=Blank
Special4Icon5URLDashedHexagonNo2=Blank
Special4Icon5URLDashedHexagonNo3=Blank
Special4Icon5URLDashedHexagonNo4=Blank

Special4Icon1DashedHexagonCode=Base
Special4Icon1DashedHexagonColorType=Base
Special4Icon1DashedHexagonChameleonName=Foreground 1
Special4Icon1DashedHexagonChameleonHidden=1
Special4Icon1DashedHexagonBase=255,255,255
Special4Icon1DashedHexagonBaseHidden=0

Special4Icon2DashedHexagonCode=Base
Special4Icon2DashedHexagonColorType=Base
Special4Icon2DashedHexagonChameleonName=Foreground 1
Special4Icon2DashedHexagonChameleonHidden=1
Special4Icon2DashedHexagonBase=255,255,255
Special4Icon2DashedHexagonBaseHidden=0

Special4Icon3DashedHexagonCode=Base
Special4Icon3DashedHexagonColorType=Base
Special4Icon3DashedHexagonChameleonName=Foreground 1
Special4Icon3DashedHexagonChameleonHidden=1
Special4Icon3DashedHexagonBase=255,255,255
Special4Icon3DashedHexagonBaseHidden=0

Special4Icon4DashedHexagonCode=Base
Special4Icon4DashedHexagonColorType=Base
Special4Icon4DashedHexagonChameleonName=Foreground 1
Special4Icon4DashedHexagonChameleonHidden=1
Special4Icon4DashedHexagonBase=255,255,255
Special4Icon4DashedHexagonBaseHidden=0

Special4Icon5DashedHexagonCode=Base
Special4Icon5DashedHexagonColorType=Base
Special4Icon5DashedHexagonChameleonName=Foreground 1
Special4Icon5DashedHexagonChameleonHidden=1
Special4Icon5DashedHexagonBase=255,255,255
Special4Icon5DashedHexagonBaseHidden=0

; ============================================================
; ============================================================

Special5Icon1CategoryDashedHexagonNo1=Blank
Special5Icon1CategoryDashedHexagonNo2=Blank
Special5Icon1CategoryDashedHexagonNo3=Blank
Special5Icon1CategoryDashedHexagonNo4=Blank
Special5Icon1CategoryDashedHexagonNo5=Blank

Special5Icon2CategoryDashedHexagonNo1=Blank
Special5Icon2CategoryDashedHexagonNo2=Blank
Special5Icon2CategoryDashedHexagonNo3=Blank
Special5Icon2CategoryDashedHexagonNo4=Blank
Special5Icon2CategoryDashedHexagonNo5=Blank

Special5Icon3CategoryDashedHexagonNo1=Blank
Special5Icon3CategoryDashedHexagonNo2=Blank
Special5Icon3CategoryDashedHexagonNo3=Blank
Special5Icon3CategoryDashedHexagonNo4=Blank
Special5Icon3CategoryDashedHexagonNo5=Blank

Special5Icon4CategoryDashedHexagonNo1=Blank
Special5Icon4CategoryDashedHexagonNo2=Blank
Special5Icon4CategoryDashedHexagonNo3=Blank
Special5Icon4CategoryDashedHexagonNo4=Blank
Special5Icon4CategoryDashedHexagonNo5=Blank

Special5Icon5CategoryDashedHexagonNo1=Blank
Special5Icon5CategoryDashedHexagonNo2=Blank
Special5Icon5CategoryDashedHexagonNo3=Blank
Special5Icon5CategoryDashedHexagonNo4=Blank
Special5Icon5CategoryDashedHexagonNo5=Blank

Special5Icon1DashedHexagonNo1=Blank
Special5Icon1DashedHexagonNo2=Blank
Special5Icon1DashedHexagonNo3=Blank
Special5Icon1DashedHexagonNo4=Blank
Special5Icon1DashedHexagonNo5=Blank

Special5Icon2DashedHexagonNo1=Blank
Special5Icon2DashedHexagonNo2=Blank
Special5Icon2DashedHexagonNo3=Blank
Special5Icon2DashedHexagonNo4=Blank
Special5Icon2DashedHexagonNo5=Blank

Special5Icon3DashedHexagonNo1=Blank
Special5Icon3DashedHexagonNo2=Blank
Special5Icon3DashedHexagonNo3=Blank
Special5Icon3DashedHexagonNo4=Blank
Special5Icon3DashedHexagonNo5=Blank

Special5Icon4DashedHexagonNo1=Blank
Special5Icon4DashedHexagonNo2=Blank
Special5Icon4DashedHexagonNo3=Blank
Special5Icon4DashedHexagonNo4=Blank
Special5Icon4DashedHexagonNo5=Blank

Special5Icon5DashedHexagonNo1=Blank
Special5Icon5DashedHexagonNo2=Blank
Special5Icon5DashedHexagonNo3=Blank
Special5Icon5DashedHexagonNo4=Blank
Special5Icon5DashedHexagonNo5=Blank

Special5Icon1URLDashedHexagonNo1=Blank
Special5Icon1URLDashedHexagonNo2=Blank
Special5Icon1URLDashedHexagonNo3=Blank
Special5Icon1URLDashedHexagonNo4=Blank
Special5Icon1URLDashedHexagonNo5=Blank

Special5Icon2URLDashedHexagonNo1=Blank
Special5Icon2URLDashedHexagonNo2=Blank
Special5Icon2URLDashedHexagonNo3=Blank
Special5Icon2URLDashedHexagonNo4=Blank
Special5Icon2URLDashedHexagonNo5=Blank

Special5Icon3URLDashedHexagonNo1=Blank
Special5Icon3URLDashedHexagonNo2=Blank
Special5Icon3URLDashedHexagonNo3=Blank
Special5Icon3URLDashedHexagonNo4=Blank
Special5Icon3URLDashedHexagonNo5=Blank

Special5Icon4URLDashedHexagonNo1=Blank
Special5Icon4URLDashedHexagonNo2=Blank
Special5Icon4URLDashedHexagonNo3=Blank
Special5Icon4URLDashedHexagonNo4=Blank
Special5Icon4URLDashedHexagonNo5=Blank

Special5Icon5URLDashedHexagonNo1=Blank
Special5Icon5URLDashedHexagonNo2=Blank
Special5Icon5URLDashedHexagonNo3=Blank
Special5Icon5URLDashedHexagonNo4=Blank
Special5Icon5URLDashedHexagonNo5=Blank

Special5Icon1DashedHexagonCode=Base
Special5Icon1DashedHexagonColorType=Base
Special5Icon1DashedHexagonChameleonName=Foreground 1
Special5Icon1DashedHexagonChameleonHidden=1
Special5Icon1DashedHexagonBase=255,255,255
Special5Icon1DashedHexagonBaseHidden=0

Special5Icon2DashedHexagonCode=Base
Special5Icon2DashedHexagonColorType=Base
Special5Icon2DashedHexagonChameleonName=Foreground 1
Special5Icon2DashedHexagonChameleonHidden=1
Special5Icon2DashedHexagonBase=255,255,255
Special5Icon2DashedHexagonBaseHidden=0

Special5Icon3DashedHexagonCode=Base
Special5Icon3DashedHexagonColorType=Base
Special5Icon3DashedHexagonChameleonName=Foreground 1
Special5Icon3DashedHexagonChameleonHidden=1
Special5Icon3DashedHexagonBase=255,255,255
Special5Icon3DashedHexagonBaseHidden=0

Special5Icon4DashedHexagonCode=Base
Special5Icon4DashedHexagonColorType=Base
Special5Icon4DashedHexagonChameleonName=Foreground 1
Special5Icon4DashedHexagonChameleonHidden=1
Special5Icon4DashedHexagonBase=255,255,255
Special5Icon4DashedHexagonBaseHidden=0

Special5Icon5DashedHexagonCode=Base
Special5Icon5DashedHexagonColorType=Base
Special5Icon5DashedHexagonChameleonName=Foreground 1
Special5Icon5DashedHexagonChameleonHidden=1
Special5Icon5DashedHexagonBase=255,255,255
Special5Icon5DashedHexagonBaseHidden=0

; ============================================================
; ============================================================

Special7Icon1CategoryDashedHexagonNo1=Blank
Special7Icon1CategoryDashedHexagonNo2=Blank
Special7Icon1CategoryDashedHexagonNo3=Blank
Special7Icon1CategoryDashedHexagonNo4=Blank
Special7Icon1CategoryDashedHexagonNo5=Blank
Special7Icon1CategoryDashedHexagonNo6=Blank
Special7Icon1CategoryDashedHexagonNo7=Blank

Special7Icon2CategoryDashedHexagonNo1=Blank
Special7Icon2CategoryDashedHexagonNo2=Blank
Special7Icon2CategoryDashedHexagonNo3=Blank
Special7Icon2CategoryDashedHexagonNo4=Blank
Special7Icon2CategoryDashedHexagonNo5=Blank
Special7Icon2CategoryDashedHexagonNo6=Blank
Special7Icon2CategoryDashedHexagonNo7=Blank

Special7Icon3CategoryDashedHexagonNo1=Blank
Special7Icon3CategoryDashedHexagonNo2=Blank
Special7Icon3CategoryDashedHexagonNo3=Blank
Special7Icon3CategoryDashedHexagonNo4=Blank
Special7Icon3CategoryDashedHexagonNo5=Blank
Special7Icon3CategoryDashedHexagonNo6=Blank
Special7Icon3CategoryDashedHexagonNo7=Blank

Special7Icon4CategoryDashedHexagonNo1=Blank
Special7Icon4CategoryDashedHexagonNo2=Blank
Special7Icon4CategoryDashedHexagonNo3=Blank
Special7Icon4CategoryDashedHexagonNo4=Blank
Special7Icon4CategoryDashedHexagonNo5=Blank
Special7Icon4CategoryDashedHexagonNo6=Blank
Special7Icon4CategoryDashedHexagonNo7=Blank

Special7Icon5CategoryDashedHexagonNo1=Blank
Special7Icon5CategoryDashedHexagonNo2=Blank
Special7Icon5CategoryDashedHexagonNo3=Blank
Special7Icon5CategoryDashedHexagonNo4=Blank
Special7Icon5CategoryDashedHexagonNo5=Blank
Special7Icon5CategoryDashedHexagonNo6=Blank
Special7Icon5CategoryDashedHexagonNo7=Blank

Special7Icon1DashedHexagonNo1=Blank
Special7Icon1DashedHexagonNo2=Blank
Special7Icon1DashedHexagonNo3=Blank
Special7Icon1DashedHexagonNo4=Blank
Special7Icon1DashedHexagonNo5=Blank
Special7Icon1DashedHexagonNo6=Blank
Special7Icon1DashedHexagonNo7=Blank

Special7Icon2DashedHexagonNo1=Blank
Special7Icon2DashedHexagonNo2=Blank
Special7Icon2DashedHexagonNo3=Blank
Special7Icon2DashedHexagonNo4=Blank
Special7Icon2DashedHexagonNo5=Blank
Special7Icon2DashedHexagonNo6=Blank
Special7Icon2DashedHexagonNo7=Blank

Special7Icon3DashedHexagonNo1=Blank
Special7Icon3DashedHexagonNo2=Blank
Special7Icon3DashedHexagonNo3=Blank
Special7Icon3DashedHexagonNo4=Blank
Special7Icon3DashedHexagonNo5=Blank
Special7Icon3DashedHexagonNo6=Blank
Special7Icon3DashedHexagonNo7=Blank

Special7Icon4DashedHexagonNo1=Blank
Special7Icon4DashedHexagonNo2=Blank
Special7Icon4DashedHexagonNo3=Blank
Special7Icon4DashedHexagonNo4=Blank
Special7Icon4DashedHexagonNo5=Blank
Special7Icon4DashedHexagonNo6=Blank
Special7Icon4DashedHexagonNo7=Blank

Special7Icon5DashedHexagonNo1=Blank
Special7Icon5DashedHexagonNo2=Blank
Special7Icon5DashedHexagonNo3=Blank
Special7Icon5DashedHexagonNo4=Blank
Special7Icon5DashedHexagonNo5=Blank
Special7Icon5DashedHexagonNo6=Blank
Special7Icon5DashedHexagonNo7=Blank

Special7Icon1URLDashedHexagonNo1=Blank
Special7Icon1URLDashedHexagonNo2=Blank
Special7Icon1URLDashedHexagonNo3=Blank
Special7Icon1URLDashedHexagonNo4=Blank
Special7Icon1URLDashedHexagonNo5=Blank
Special7Icon1URLDashedHexagonNo6=Blank
Special7Icon1URLDashedHexagonNo7=Blank

Special7Icon2URLDashedHexagonNo1=Blank
Special7Icon2URLDashedHexagonNo2=Blank
Special7Icon2URLDashedHexagonNo3=Blank
Special7Icon2URLDashedHexagonNo4=Blank
Special7Icon2URLDashedHexagonNo5=Blank
Special7Icon2URLDashedHexagonNo6=Blank
Special7Icon2URLDashedHexagonNo7=Blank

Special7Icon3URLDashedHexagonNo1=Blank
Special7Icon3URLDashedHexagonNo2=Blank
Special7Icon3URLDashedHexagonNo3=Blank
Special7Icon3URLDashedHexagonNo4=Blank
Special7Icon3URLDashedHexagonNo5=Blank
Special7Icon3URLDashedHexagonNo6=Blank
Special7Icon3URLDashedHexagonNo7=Blank

Special7Icon4URLDashedHexagonNo1=Blank
Special7Icon4URLDashedHexagonNo2=Blank
Special7Icon4URLDashedHexagonNo3=Blank
Special7Icon4URLDashedHexagonNo4=Blank
Special7Icon4URLDashedHexagonNo5=Blank
Special7Icon4URLDashedHexagonNo6=Blank
Special7Icon4URLDashedHexagonNo7=Blank

Special7Icon5URLDashedHexagonNo1=Blank
Special7Icon5URLDashedHexagonNo2=Blank
Special7Icon5URLDashedHexagonNo3=Blank
Special7Icon5URLDashedHexagonNo4=Blank
Special7Icon5URLDashedHexagonNo5=Blank
Special7Icon5URLDashedHexagonNo6=Blank
Special7Icon5URLDashedHexagonNo7=Blank

Special7Icon1DashedHexagonCode=Base
Special7Icon1DashedHexagonColorType=Base
Special7Icon1DashedHexagonChameleonName=Foreground 1
Special7Icon1DashedHexagonChameleonHidden=1
Special7Icon1DashedHexagonBase=255,255,255
Special7Icon1DashedHexagonBaseHidden=0

Special7Icon2DashedHexagonCode=Base
Special7Icon2DashedHexagonColorType=Base
Special7Icon2DashedHexagonChameleonName=Foreground 1
Special7Icon2DashedHexagonChameleonHidden=1
Special7Icon2DashedHexagonBase=255,255,255
Special7Icon2DashedHexagonBaseHidden=0

Special7Icon3DashedHexagonCode=Base
Special7Icon3DashedHexagonColorType=Base
Special7Icon3DashedHexagonChameleonName=Foreground 1
Special7Icon3DashedHexagonChameleonHidden=1
Special7Icon3DashedHexagonBase=255,255,255
Special7Icon3DashedHexagonBaseHidden=0

Special7Icon4DashedHexagonCode=Base
Special7Icon4DashedHexagonColorType=Base
Special7Icon4DashedHexagonChameleonName=Foreground 1
Special7Icon4DashedHexagonChameleonHidden=1
Special7Icon4DashedHexagonBase=255,255,255
Special7Icon4DashedHexagonBaseHidden=0

Special7Icon5DashedHexagonCode=Base
Special7Icon5DashedHexagonColorType=Base
Special7Icon5DashedHexagonChameleonName=Foreground 1
Special7Icon5DashedHexagonChameleonHidden=1
Special7Icon5DashedHexagonBase=255,255,255
Special7Icon5DashedHexagonBaseHidden=0

; ============================================================
; ============================================================
; ============================================================
; ============================================================

Special3Icon1CategoryInlineHexagonNo1=Blank
Special3Icon1CategoryInlineHexagonNo2=Blank
Special3Icon1CategoryInlineHexagonNo3=Blank

Special3Icon2CategoryInlineHexagonNo1=Blank
Special3Icon2CategoryInlineHexagonNo2=Blank
Special3Icon2CategoryInlineHexagonNo3=Blank

Special3Icon3CategoryInlineHexagonNo1=Blank
Special3Icon3CategoryInlineHexagonNo2=Blank
Special3Icon3CategoryInlineHexagonNo3=Blank

Special3Icon4CategoryInlineHexagonNo1=Blank
Special3Icon4CategoryInlineHexagonNo2=Blank
Special3Icon4CategoryInlineHexagonNo3=Blank

Special3Icon5CategoryInlineHexagonNo1=Blank
Special3Icon5CategoryInlineHexagonNo2=Blank
Special3Icon5CategoryInlineHexagonNo3=Blank

Special3Icon1InlineHexagonNo1=Blank
Special3Icon1InlineHexagonNo2=Blank
Special3Icon1InlineHexagonNo3=Blank

Special3Icon2InlineHexagonNo1=Blank
Special3Icon2InlineHexagonNo2=Blank
Special3Icon2InlineHexagonNo3=Blank

Special3Icon3InlineHexagonNo1=Blank
Special3Icon3InlineHexagonNo2=Blank
Special3Icon3InlineHexagonNo3=Blank

Special3Icon4InlineHexagonNo1=Blank
Special3Icon4InlineHexagonNo2=Blank
Special3Icon4InlineHexagonNo3=Blank

Special3Icon5InlineHexagonNo1=Blank
Special3Icon5InlineHexagonNo2=Blank
Special3Icon5InlineHexagonNo3=Blank

Special3Icon1URLInlineHexagonNo1=Blank
Special3Icon1URLInlineHexagonNo2=Blank
Special3Icon1URLInlineHexagonNo3=Blank

Special3Icon2URLInlineHexagonNo1=Blank
Special3Icon2URLInlineHexagonNo2=Blank
Special3Icon2URLInlineHexagonNo3=Blank

Special3Icon3URLInlineHexagonNo1=Blank
Special3Icon3URLInlineHexagonNo2=Blank
Special3Icon3URLInlineHexagonNo3=Blank

Special3Icon4URLInlineHexagonNo1=Blank
Special3Icon4URLInlineHexagonNo2=Blank
Special3Icon4URLInlineHexagonNo3=Blank

Special3Icon5URLInlineHexagonNo1=Blank
Special3Icon5URLInlineHexagonNo2=Blank
Special3Icon5URLInlineHexagonNo3=Blank

Special3Icon1InlineHexagonCode=Base
Special3Icon1InlineHexagonColorType=Base
Special3Icon1InlineHexagonChameleonName=Foreground 1
Special3Icon1InlineHexagonChameleonHidden=1
Special3Icon1InlineHexagonBase=255,255,255
Special3Icon1InlineHexagonBaseHidden=0

Special3Icon2InlineHexagonCode=Base
Special3Icon2InlineHexagonColorType=Base
Special3Icon2InlineHexagonChameleonName=Foreground 1
Special3Icon2InlineHexagonChameleonHidden=1
Special3Icon2InlineHexagonBase=255,255,255
Special3Icon2InlineHexagonBaseHidden=0

Special3Icon3InlineHexagonCode=Base
Special3Icon3InlineHexagonColorType=Base
Special3Icon3InlineHexagonChameleonName=Foreground 1
Special3Icon3InlineHexagonChameleonHidden=1
Special3Icon3InlineHexagonBase=255,255,255
Special3Icon3InlineHexagonBaseHidden=0

Special3Icon4InlineHexagonCode=Base
Special3Icon4InlineHexagonColorType=Base
Special3Icon4InlineHexagonChameleonName=Foreground 1
Special3Icon4InlineHexagonChameleonHidden=1
Special3Icon4InlineHexagonBase=255,255,255
Special3Icon4InlineHexagonBaseHidden=0

Special3Icon5InlineHexagonCode=Base
Special3Icon5InlineHexagonColorType=Base
Special3Icon5InlineHexagonChameleonName=Foreground 1
Special3Icon5InlineHexagonChameleonHidden=1
Special3Icon5InlineHexagonBase=255,255,255
Special3Icon5InlineHexagonBaseHidden=0

; ============================================================
; ============================================================

Special4Icon1CategoryInlineHexagonNo1=Blank
Special4Icon1CategoryInlineHexagonNo2=Blank
Special4Icon1CategoryInlineHexagonNo3=Blank
Special4Icon1CategoryInlineHexagonNo4=Blank

Special4Icon2CategoryInlineHexagonNo1=Blank
Special4Icon2CategoryInlineHexagonNo2=Blank
Special4Icon2CategoryInlineHexagonNo3=Blank
Special4Icon2CategoryInlineHexagonNo4=Blank

Special4Icon3CategoryInlineHexagonNo1=Blank
Special4Icon3CategoryInlineHexagonNo2=Blank
Special4Icon3CategoryInlineHexagonNo3=Blank
Special4Icon3CategoryInlineHexagonNo4=Blank

Special4Icon4CategoryInlineHexagonNo1=Blank
Special4Icon4CategoryInlineHexagonNo2=Blank
Special4Icon4CategoryInlineHexagonNo3=Blank
Special4Icon4CategoryInlineHexagonNo4=Blank

Special4Icon5CategoryInlineHexagonNo1=Blank
Special4Icon5CategoryInlineHexagonNo2=Blank
Special4Icon5CategoryInlineHexagonNo3=Blank
Special4Icon5CategoryInlineHexagonNo4=Blank

Special4Icon1InlineHexagonNo1=Blank
Special4Icon1InlineHexagonNo2=Blank
Special4Icon1InlineHexagonNo3=Blank
Special4Icon1InlineHexagonNo4=Blank

Special4Icon2InlineHexagonNo1=Blank
Special4Icon2InlineHexagonNo2=Blank
Special4Icon2InlineHexagonNo3=Blank
Special4Icon2InlineHexagonNo4=Blank

Special4Icon3InlineHexagonNo1=Blank
Special4Icon3InlineHexagonNo2=Blank
Special4Icon3InlineHexagonNo3=Blank
Special4Icon3InlineHexagonNo4=Blank

Special4Icon4InlineHexagonNo1=Blank
Special4Icon4InlineHexagonNo2=Blank
Special4Icon4InlineHexagonNo3=Blank
Special4Icon4InlineHexagonNo4=Blank

Special4Icon5InlineHexagonNo1=Blank
Special4Icon5InlineHexagonNo2=Blank
Special4Icon5InlineHexagonNo3=Blank
Special4Icon5InlineHexagonNo4=Blank

Special4Icon1URLInlineHexagonNo1=Blank
Special4Icon1URLInlineHexagonNo2=Blank
Special4Icon1URLInlineHexagonNo3=Blank
Special4Icon1URLInlineHexagonNo4=Blank

Special4Icon2URLInlineHexagonNo1=Blank
Special4Icon2URLInlineHexagonNo2=Blank
Special4Icon2URLInlineHexagonNo3=Blank
Special4Icon2URLInlineHexagonNo4=Blank

Special4Icon3URLInlineHexagonNo1=Blank
Special4Icon3URLInlineHexagonNo2=Blank
Special4Icon3URLInlineHexagonNo3=Blank
Special4Icon3URLInlineHexagonNo4=Blank

Special4Icon4URLInlineHexagonNo1=Blank
Special4Icon4URLInlineHexagonNo2=Blank
Special4Icon4URLInlineHexagonNo3=Blank
Special4Icon4URLInlineHexagonNo4=Blank

Special4Icon5URLInlineHexagonNo1=Blank
Special4Icon5URLInlineHexagonNo2=Blank
Special4Icon5URLInlineHexagonNo3=Blank
Special4Icon5URLInlineHexagonNo4=Blank

Special4Icon1InlineHexagonCode=Base
Special4Icon1InlineHexagonColorType=Base
Special4Icon1InlineHexagonChameleonName=Foreground 1
Special4Icon1InlineHexagonChameleonHidden=1
Special4Icon1InlineHexagonBase=255,255,255
Special4Icon1InlineHexagonBaseHidden=0

Special4Icon2InlineHexagonCode=Base
Special4Icon2InlineHexagonColorType=Base
Special4Icon2InlineHexagonChameleonName=Foreground 1
Special4Icon2InlineHexagonChameleonHidden=1
Special4Icon2InlineHexagonBase=255,255,255
Special4Icon2InlineHexagonBaseHidden=0

Special4Icon3InlineHexagonCode=Base
Special4Icon3InlineHexagonColorType=Base
Special4Icon3InlineHexagonChameleonName=Foreground 1
Special4Icon3InlineHexagonChameleonHidden=1
Special4Icon3InlineHexagonBase=255,255,255
Special4Icon3InlineHexagonBaseHidden=0

Special4Icon4InlineHexagonCode=Base
Special4Icon4InlineHexagonColorType=Base
Special4Icon4InlineHexagonChameleonName=Foreground 1
Special4Icon4InlineHexagonChameleonHidden=1
Special4Icon4InlineHexagonBase=255,255,255
Special4Icon4InlineHexagonBaseHidden=0

Special4Icon5InlineHexagonCode=Base
Special4Icon5InlineHexagonColorType=Base
Special4Icon5InlineHexagonChameleonName=Foreground 1
Special4Icon5InlineHexagonChameleonHidden=1
Special4Icon5InlineHexagonBase=255,255,255
Special4Icon5InlineHexagonBaseHidden=0

; ============================================================
; ============================================================

Special5Icon1CategoryInlineHexagonNo1=Blank
Special5Icon1CategoryInlineHexagonNo2=Blank
Special5Icon1CategoryInlineHexagonNo3=Blank
Special5Icon1CategoryInlineHexagonNo4=Blank
Special5Icon1CategoryInlineHexagonNo5=Blank

Special5Icon2CategoryInlineHexagonNo1=Blank
Special5Icon2CategoryInlineHexagonNo2=Blank
Special5Icon2CategoryInlineHexagonNo3=Blank
Special5Icon2CategoryInlineHexagonNo4=Blank
Special5Icon2CategoryInlineHexagonNo5=Blank

Special5Icon3CategoryInlineHexagonNo1=Blank
Special5Icon3CategoryInlineHexagonNo2=Blank
Special5Icon3CategoryInlineHexagonNo3=Blank
Special5Icon3CategoryInlineHexagonNo4=Blank
Special5Icon3CategoryInlineHexagonNo5=Blank

Special5Icon4CategoryInlineHexagonNo1=Blank
Special5Icon4CategoryInlineHexagonNo2=Blank
Special5Icon4CategoryInlineHexagonNo3=Blank
Special5Icon4CategoryInlineHexagonNo4=Blank
Special5Icon4CategoryInlineHexagonNo5=Blank

Special5Icon5CategoryInlineHexagonNo1=Blank
Special5Icon5CategoryInlineHexagonNo2=Blank
Special5Icon5CategoryInlineHexagonNo3=Blank
Special5Icon5CategoryInlineHexagonNo4=Blank
Special5Icon5CategoryInlineHexagonNo5=Blank

Special5Icon1InlineHexagonNo1=Blank
Special5Icon1InlineHexagonNo2=Blank
Special5Icon1InlineHexagonNo3=Blank
Special5Icon1InlineHexagonNo4=Blank
Special5Icon1InlineHexagonNo5=Blank

Special5Icon2InlineHexagonNo1=Blank
Special5Icon2InlineHexagonNo2=Blank
Special5Icon2InlineHexagonNo3=Blank
Special5Icon2InlineHexagonNo4=Blank
Special5Icon2InlineHexagonNo5=Blank

Special5Icon3InlineHexagonNo1=Blank
Special5Icon3InlineHexagonNo2=Blank
Special5Icon3InlineHexagonNo3=Blank
Special5Icon3InlineHexagonNo4=Blank
Special5Icon3InlineHexagonNo5=Blank

Special5Icon4InlineHexagonNo1=Blank
Special5Icon4InlineHexagonNo2=Blank
Special5Icon4InlineHexagonNo3=Blank
Special5Icon4InlineHexagonNo4=Blank
Special5Icon4InlineHexagonNo5=Blank

Special5Icon5InlineHexagonNo1=Blank
Special5Icon5InlineHexagonNo2=Blank
Special5Icon5InlineHexagonNo3=Blank
Special5Icon5InlineHexagonNo4=Blank
Special5Icon5InlineHexagonNo5=Blank

Special5Icon1URLInlineHexagonNo1=Blank
Special5Icon1URLInlineHexagonNo2=Blank
Special5Icon1URLInlineHexagonNo3=Blank
Special5Icon1URLInlineHexagonNo4=Blank
Special5Icon1URLInlineHexagonNo5=Blank

Special5Icon2URLInlineHexagonNo1=Blank
Special5Icon2URLInlineHexagonNo2=Blank
Special5Icon2URLInlineHexagonNo3=Blank
Special5Icon2URLInlineHexagonNo4=Blank
Special5Icon2URLInlineHexagonNo5=Blank

Special5Icon3URLInlineHexagonNo1=Blank
Special5Icon3URLInlineHexagonNo2=Blank
Special5Icon3URLInlineHexagonNo3=Blank
Special5Icon3URLInlineHexagonNo4=Blank
Special5Icon3URLInlineHexagonNo5=Blank

Special5Icon4URLInlineHexagonNo1=Blank
Special5Icon4URLInlineHexagonNo2=Blank
Special5Icon4URLInlineHexagonNo3=Blank
Special5Icon4URLInlineHexagonNo4=Blank
Special5Icon4URLInlineHexagonNo5=Blank

Special5Icon5URLInlineHexagonNo1=Blank
Special5Icon5URLInlineHexagonNo2=Blank
Special5Icon5URLInlineHexagonNo3=Blank
Special5Icon5URLInlineHexagonNo4=Blank
Special5Icon5URLInlineHexagonNo5=Blank

Special5Icon1InlineHexagonCode=Base
Special5Icon1InlineHexagonColorType=Base
Special5Icon1InlineHexagonChameleonName=Foreground 1
Special5Icon1InlineHexagonChameleonHidden=1
Special5Icon1InlineHexagonBase=255,255,255
Special5Icon1InlineHexagonBaseHidden=0

Special5Icon2InlineHexagonCode=Base
Special5Icon2InlineHexagonColorType=Base
Special5Icon2InlineHexagonChameleonName=Foreground 1
Special5Icon2InlineHexagonChameleonHidden=1
Special5Icon2InlineHexagonBase=255,255,255
Special5Icon2InlineHexagonBaseHidden=0

Special5Icon3InlineHexagonCode=Base
Special5Icon3InlineHexagonColorType=Base
Special5Icon3InlineHexagonChameleonName=Foreground 1
Special5Icon3InlineHexagonChameleonHidden=1
Special5Icon3InlineHexagonBase=255,255,255
Special5Icon3InlineHexagonBaseHidden=0

Special5Icon4InlineHexagonCode=Base
Special5Icon4InlineHexagonColorType=Base
Special5Icon4InlineHexagonChameleonName=Foreground 1
Special5Icon4InlineHexagonChameleonHidden=1
Special5Icon4InlineHexagonBase=255,255,255
Special5Icon4InlineHexagonBaseHidden=0

Special5Icon5InlineHexagonCode=Base
Special5Icon5InlineHexagonColorType=Base
Special5Icon5InlineHexagonChameleonName=Foreground 1
Special5Icon5InlineHexagonChameleonHidden=1
Special5Icon5InlineHexagonBase=255,255,255
Special5Icon5InlineHexagonBaseHidden=0

; ============================================================
; ============================================================

Special7Icon1CategoryInlineHexagonNo1=Blank
Special7Icon1CategoryInlineHexagonNo2=Blank
Special7Icon1CategoryInlineHexagonNo3=Blank
Special7Icon1CategoryInlineHexagonNo4=Blank
Special7Icon1CategoryInlineHexagonNo5=Blank
Special7Icon1CategoryInlineHexagonNo6=Blank
Special7Icon1CategoryInlineHexagonNo7=Blank

Special7Icon2CategoryInlineHexagonNo1=Blank
Special7Icon2CategoryInlineHexagonNo2=Blank
Special7Icon2CategoryInlineHexagonNo3=Blank
Special7Icon2CategoryInlineHexagonNo4=Blank
Special7Icon2CategoryInlineHexagonNo5=Blank
Special7Icon2CategoryInlineHexagonNo6=Blank
Special7Icon2CategoryInlineHexagonNo7=Blank

Special7Icon3CategoryInlineHexagonNo1=Blank
Special7Icon3CategoryInlineHexagonNo2=Blank
Special7Icon3CategoryInlineHexagonNo3=Blank
Special7Icon3CategoryInlineHexagonNo4=Blank
Special7Icon3CategoryInlineHexagonNo5=Blank
Special7Icon3CategoryInlineHexagonNo6=Blank
Special7Icon3CategoryInlineHexagonNo7=Blank

Special7Icon4CategoryInlineHexagonNo1=Blank
Special7Icon4CategoryInlineHexagonNo2=Blank
Special7Icon4CategoryInlineHexagonNo3=Blank
Special7Icon4CategoryInlineHexagonNo4=Blank
Special7Icon4CategoryInlineHexagonNo5=Blank
Special7Icon4CategoryInlineHexagonNo6=Blank
Special7Icon4CategoryInlineHexagonNo7=Blank

Special7Icon5CategoryInlineHexagonNo1=Blank
Special7Icon5CategoryInlineHexagonNo2=Blank
Special7Icon5CategoryInlineHexagonNo3=Blank
Special7Icon5CategoryInlineHexagonNo4=Blank
Special7Icon5CategoryInlineHexagonNo5=Blank
Special7Icon5CategoryInlineHexagonNo6=Blank
Special7Icon5CategoryInlineHexagonNo7=Blank

Special7Icon1InlineHexagonNo1=Blank
Special7Icon1InlineHexagonNo2=Blank
Special7Icon1InlineHexagonNo3=Blank
Special7Icon1InlineHexagonNo4=Blank
Special7Icon1InlineHexagonNo5=Blank
Special7Icon1InlineHexagonNo6=Blank
Special7Icon1InlineHexagonNo7=Blank

Special7Icon2InlineHexagonNo1=Blank
Special7Icon2InlineHexagonNo2=Blank
Special7Icon2InlineHexagonNo3=Blank
Special7Icon2InlineHexagonNo4=Blank
Special7Icon2InlineHexagonNo5=Blank
Special7Icon2InlineHexagonNo6=Blank
Special7Icon2InlineHexagonNo7=Blank

Special7Icon3InlineHexagonNo1=Blank
Special7Icon3InlineHexagonNo2=Blank
Special7Icon3InlineHexagonNo3=Blank
Special7Icon3InlineHexagonNo4=Blank
Special7Icon3InlineHexagonNo5=Blank
Special7Icon3InlineHexagonNo6=Blank
Special7Icon3InlineHexagonNo7=Blank

Special7Icon4InlineHexagonNo1=Blank
Special7Icon4InlineHexagonNo2=Blank
Special7Icon4InlineHexagonNo3=Blank
Special7Icon4InlineHexagonNo4=Blank
Special7Icon4InlineHexagonNo5=Blank
Special7Icon4InlineHexagonNo6=Blank
Special7Icon4InlineHexagonNo7=Blank

Special7Icon5InlineHexagonNo1=Blank
Special7Icon5InlineHexagonNo2=Blank
Special7Icon5InlineHexagonNo3=Blank
Special7Icon5InlineHexagonNo4=Blank
Special7Icon5InlineHexagonNo5=Blank
Special7Icon5InlineHexagonNo6=Blank
Special7Icon5InlineHexagonNo7=Blank

Special7Icon1URLInlineHexagonNo1=Blank
Special7Icon1URLInlineHexagonNo2=Blank
Special7Icon1URLInlineHexagonNo3=Blank
Special7Icon1URLInlineHexagonNo4=Blank
Special7Icon1URLInlineHexagonNo5=Blank
Special7Icon1URLInlineHexagonNo6=Blank
Special7Icon1URLInlineHexagonNo7=Blank

Special7Icon2URLInlineHexagonNo1=Blank
Special7Icon2URLInlineHexagonNo2=Blank
Special7Icon2URLInlineHexagonNo3=Blank
Special7Icon2URLInlineHexagonNo4=Blank
Special7Icon2URLInlineHexagonNo5=Blank
Special7Icon2URLInlineHexagonNo6=Blank
Special7Icon2URLInlineHexagonNo7=Blank

Special7Icon3URLInlineHexagonNo1=Blank
Special7Icon3URLInlineHexagonNo2=Blank
Special7Icon3URLInlineHexagonNo3=Blank
Special7Icon3URLInlineHexagonNo4=Blank
Special7Icon3URLInlineHexagonNo5=Blank
Special7Icon3URLInlineHexagonNo6=Blank
Special7Icon3URLInlineHexagonNo7=Blank

Special7Icon4URLInlineHexagonNo1=Blank
Special7Icon4URLInlineHexagonNo2=Blank
Special7Icon4URLInlineHexagonNo3=Blank
Special7Icon4URLInlineHexagonNo4=Blank
Special7Icon4URLInlineHexagonNo5=Blank
Special7Icon4URLInlineHexagonNo6=Blank
Special7Icon4URLInlineHexagonNo7=Blank

Special7Icon5URLInlineHexagonNo1=Blank
Special7Icon5URLInlineHexagonNo2=Blank
Special7Icon5URLInlineHexagonNo3=Blank
Special7Icon5URLInlineHexagonNo4=Blank
Special7Icon5URLInlineHexagonNo5=Blank
Special7Icon5URLInlineHexagonNo6=Blank
Special7Icon5URLInlineHexagonNo7=Blank

Special7Icon1InlineHexagonCode=Base
Special7Icon1InlineHexagonColorType=Base
Special7Icon1InlineHexagonChameleonName=Foreground 1
Special7Icon1InlineHexagonChameleonHidden=1
Special7Icon1InlineHexagonBase=255,255,255
Special7Icon1InlineHexagonBaseHidden=0

Special7Icon2InlineHexagonCode=Base
Special7Icon2InlineHexagonColorType=Base
Special7Icon2InlineHexagonChameleonName=Foreground 1
Special7Icon2InlineHexagonChameleonHidden=1
Special7Icon2InlineHexagonBase=255,255,255
Special7Icon2InlineHexagonBaseHidden=0

Special7Icon3InlineHexagonCode=Base
Special7Icon3InlineHexagonColorType=Base
Special7Icon3InlineHexagonChameleonName=Foreground 1
Special7Icon3InlineHexagonChameleonHidden=1
Special7Icon3InlineHexagonBase=255,255,255
Special7Icon3InlineHexagonBaseHidden=0

Special7Icon4InlineHexagonCode=Base
Special7Icon4InlineHexagonColorType=Base
Special7Icon4InlineHexagonChameleonName=Foreground 1
Special7Icon4InlineHexagonChameleonHidden=1
Special7Icon4InlineHexagonBase=255,255,255
Special7Icon4InlineHexagonBaseHidden=0

Special7Icon5InlineHexagonCode=Base
Special7Icon5InlineHexagonColorType=Base
Special7Icon5InlineHexagonChameleonName=Foreground 1
Special7Icon5InlineHexagonChameleonHidden=1
Special7Icon5InlineHexagonBase=255,255,255
Special7Icon5InlineHexagonBaseHidden=0

; ============================================================
; ============================================================
; ============================================================
; ============================================================

Special3Icon1CategoryRegularHexagonNo1=Blank
Special3Icon1CategoryRegularHexagonNo2=Blank
Special3Icon1CategoryRegularHexagonNo3=Blank

Special3Icon2CategoryRegularHexagonNo1=Blank
Special3Icon2CategoryRegularHexagonNo2=Blank
Special3Icon2CategoryRegularHexagonNo3=Blank

Special3Icon3CategoryRegularHexagonNo1=Blank
Special3Icon3CategoryRegularHexagonNo2=Blank
Special3Icon3CategoryRegularHexagonNo3=Blank

Special3Icon4CategoryRegularHexagonNo1=Blank
Special3Icon4CategoryRegularHexagonNo2=Blank
Special3Icon4CategoryRegularHexagonNo3=Blank

Special3Icon5CategoryRegularHexagonNo1=Blank
Special3Icon5CategoryRegularHexagonNo2=Blank
Special3Icon5CategoryRegularHexagonNo3=Blank

Special3Icon1RegularHexagonNo1=Blank
Special3Icon1RegularHexagonNo2=Blank
Special3Icon1RegularHexagonNo3=Blank

Special3Icon2RegularHexagonNo1=Blank
Special3Icon2RegularHexagonNo2=Blank
Special3Icon2RegularHexagonNo3=Blank

Special3Icon3RegularHexagonNo1=Blank
Special3Icon3RegularHexagonNo2=Blank
Special3Icon3RegularHexagonNo3=Blank

Special3Icon4RegularHexagonNo1=Blank
Special3Icon4RegularHexagonNo2=Blank
Special3Icon4RegularHexagonNo3=Blank

Special3Icon5RegularHexagonNo1=Blank
Special3Icon5RegularHexagonNo2=Blank
Special3Icon5RegularHexagonNo3=Blank

Special3Icon1URLRegularHexagonNo1=Blank
Special3Icon1URLRegularHexagonNo2=Blank
Special3Icon1URLRegularHexagonNo3=Blank

Special3Icon2URLRegularHexagonNo1=Blank
Special3Icon2URLRegularHexagonNo2=Blank
Special3Icon2URLRegularHexagonNo3=Blank

Special3Icon3URLRegularHexagonNo1=Blank
Special3Icon3URLRegularHexagonNo2=Blank
Special3Icon3URLRegularHexagonNo3=Blank

Special3Icon4URLRegularHexagonNo1=Blank
Special3Icon4URLRegularHexagonNo2=Blank
Special3Icon4URLRegularHexagonNo3=Blank

Special3Icon5URLRegularHexagonNo1=Blank
Special3Icon5URLRegularHexagonNo2=Blank
Special3Icon5URLRegularHexagonNo3=Blank

Special3Icon1RegularHexagonCode=Base
Special3Icon1RegularHexagonColorType=Base
Special3Icon1RegularHexagonChameleonName=Foreground 1
Special3Icon1RegularHexagonChameleonHidden=1
Special3Icon1RegularHexagonBase=255,255,255
Special3Icon1RegularHexagonBaseHidden=0

Special3Icon2RegularHexagonCode=Base
Special3Icon2RegularHexagonColorType=Base
Special3Icon2RegularHexagonChameleonName=Foreground 1
Special3Icon2RegularHexagonChameleonHidden=1
Special3Icon2RegularHexagonBase=255,255,255
Special3Icon2RegularHexagonBaseHidden=0

Special3Icon3RegularHexagonCode=Base
Special3Icon3RegularHexagonColorType=Base
Special3Icon3RegularHexagonChameleonName=Foreground 1
Special3Icon3RegularHexagonChameleonHidden=1
Special3Icon3RegularHexagonBase=255,255,255
Special3Icon3RegularHexagonBaseHidden=0

Special3Icon4RegularHexagonCode=Base
Special3Icon4RegularHexagonColorType=Base
Special3Icon4RegularHexagonChameleonName=Foreground 1
Special3Icon4RegularHexagonChameleonHidden=1
Special3Icon4RegularHexagonBase=255,255,255
Special3Icon4RegularHexagonBaseHidden=0

Special3Icon5RegularHexagonCode=Base
Special3Icon5RegularHexagonColorType=Base
Special3Icon5RegularHexagonChameleonName=Foreground 1
Special3Icon5RegularHexagonChameleonHidden=1
Special3Icon5RegularHexagonBase=255,255,255
Special3Icon5RegularHexagonBaseHidden=0

; ============================================================
; ============================================================

Special4Icon1CategoryRegularHexagonNo1=Blank
Special4Icon1CategoryRegularHexagonNo2=Blank
Special4Icon1CategoryRegularHexagonNo3=Blank
Special4Icon1CategoryRegularHexagonNo4=Blank

Special4Icon2CategoryRegularHexagonNo1=Blank
Special4Icon2CategoryRegularHexagonNo2=Blank
Special4Icon2CategoryRegularHexagonNo3=Blank
Special4Icon2CategoryRegularHexagonNo4=Blank

Special4Icon3CategoryRegularHexagonNo1=Blank
Special4Icon3CategoryRegularHexagonNo2=Blank
Special4Icon3CategoryRegularHexagonNo3=Blank
Special4Icon3CategoryRegularHexagonNo4=Blank

Special4Icon4CategoryRegularHexagonNo1=Blank
Special4Icon4CategoryRegularHexagonNo2=Blank
Special4Icon4CategoryRegularHexagonNo3=Blank
Special4Icon4CategoryRegularHexagonNo4=Blank

Special4Icon5CategoryRegularHexagonNo1=Blank
Special4Icon5CategoryRegularHexagonNo2=Blank
Special4Icon5CategoryRegularHexagonNo3=Blank
Special4Icon5CategoryRegularHexagonNo4=Blank

Special4Icon1RegularHexagonNo1=Blank
Special4Icon1RegularHexagonNo2=Blank
Special4Icon1RegularHexagonNo3=Blank
Special4Icon1RegularHexagonNo4=Blank

Special4Icon2RegularHexagonNo1=Blank
Special4Icon2RegularHexagonNo2=Blank
Special4Icon2RegularHexagonNo3=Blank
Special4Icon2RegularHexagonNo4=Blank

Special4Icon3RegularHexagonNo1=Blank
Special4Icon3RegularHexagonNo2=Blank
Special4Icon3RegularHexagonNo3=Blank
Special4Icon3RegularHexagonNo4=Blank

Special4Icon4RegularHexagonNo1=Blank
Special4Icon4RegularHexagonNo2=Blank
Special4Icon4RegularHexagonNo3=Blank
Special4Icon4RegularHexagonNo4=Blank

Special4Icon5RegularHexagonNo1=Blank
Special4Icon5RegularHexagonNo2=Blank
Special4Icon5RegularHexagonNo3=Blank
Special4Icon5RegularHexagonNo4=Blank

Special4Icon1URLRegularHexagonNo1=Blank
Special4Icon1URLRegularHexagonNo2=Blank
Special4Icon1URLRegularHexagonNo3=Blank
Special4Icon1URLRegularHexagonNo4=Blank

Special4Icon2URLRegularHexagonNo1=Blank
Special4Icon2URLRegularHexagonNo2=Blank
Special4Icon2URLRegularHexagonNo3=Blank
Special4Icon2URLRegularHexagonNo4=Blank

Special4Icon3URLRegularHexagonNo1=Blank
Special4Icon3URLRegularHexagonNo2=Blank
Special4Icon3URLRegularHexagonNo3=Blank
Special4Icon3URLRegularHexagonNo4=Blank

Special4Icon4URLRegularHexagonNo1=Blank
Special4Icon4URLRegularHexagonNo2=Blank
Special4Icon4URLRegularHexagonNo3=Blank
Special4Icon4URLRegularHexagonNo4=Blank

Special4Icon5URLRegularHexagonNo1=Blank
Special4Icon5URLRegularHexagonNo2=Blank
Special4Icon5URLRegularHexagonNo3=Blank
Special4Icon5URLRegularHexagonNo4=Blank

Special4Icon1RegularHexagonCode=Base
Special4Icon1RegularHexagonColorType=Base
Special4Icon1RegularHexagonChameleonName=Foreground 1
Special4Icon1RegularHexagonChameleonHidden=1
Special4Icon1RegularHexagonBase=255,255,255
Special4Icon1RegularHexagonBaseHidden=0

Special4Icon2RegularHexagonCode=Base
Special4Icon2RegularHexagonColorType=Base
Special4Icon2RegularHexagonChameleonName=Foreground 1
Special4Icon2RegularHexagonChameleonHidden=1
Special4Icon2RegularHexagonBase=255,255,255
Special4Icon2RegularHexagonBaseHidden=0

Special4Icon3RegularHexagonCode=Base
Special4Icon3RegularHexagonColorType=Base
Special4Icon3RegularHexagonChameleonName=Foreground 1
Special4Icon3RegularHexagonChameleonHidden=1
Special4Icon3RegularHexagonBase=255,255,255
Special4Icon3RegularHexagonBaseHidden=0

Special4Icon4RegularHexagonCode=Base
Special4Icon4RegularHexagonColorType=Base
Special4Icon4RegularHexagonChameleonName=Foreground 1
Special4Icon4RegularHexagonChameleonHidden=1
Special4Icon4RegularHexagonBase=255,255,255
Special4Icon4RegularHexagonBaseHidden=0

Special4Icon5RegularHexagonCode=Base
Special4Icon5RegularHexagonColorType=Base
Special4Icon5RegularHexagonChameleonName=Foreground 1
Special4Icon5RegularHexagonChameleonHidden=1
Special4Icon5RegularHexagonBase=255,255,255
Special4Icon5RegularHexagonBaseHidden=0

; ============================================================
; ============================================================

Special5Icon1CategoryRegularHexagonNo1=Blank
Special5Icon1CategoryRegularHexagonNo2=Blank
Special5Icon1CategoryRegularHexagonNo3=Blank
Special5Icon1CategoryRegularHexagonNo4=Blank
Special5Icon1CategoryRegularHexagonNo5=Blank

Special5Icon2CategoryRegularHexagonNo1=Blank
Special5Icon2CategoryRegularHexagonNo2=Blank
Special5Icon2CategoryRegularHexagonNo3=Blank
Special5Icon2CategoryRegularHexagonNo4=Blank
Special5Icon2CategoryRegularHexagonNo5=Blank

Special5Icon3CategoryRegularHexagonNo1=Blank
Special5Icon3CategoryRegularHexagonNo2=Blank
Special5Icon3CategoryRegularHexagonNo3=Blank
Special5Icon3CategoryRegularHexagonNo4=Blank
Special5Icon3CategoryRegularHexagonNo5=Blank

Special5Icon4CategoryRegularHexagonNo1=Blank
Special5Icon4CategoryRegularHexagonNo2=Blank
Special5Icon4CategoryRegularHexagonNo3=Blank
Special5Icon4CategoryRegularHexagonNo4=Blank
Special5Icon4CategoryRegularHexagonNo5=Blank

Special5Icon5CategoryRegularHexagonNo1=Blank
Special5Icon5CategoryRegularHexagonNo2=Blank
Special5Icon5CategoryRegularHexagonNo3=Blank
Special5Icon5CategoryRegularHexagonNo4=Blank
Special5Icon5CategoryRegularHexagonNo5=Blank

Special5Icon1RegularHexagonNo1=Blank
Special5Icon1RegularHexagonNo2=Blank
Special5Icon1RegularHexagonNo3=Blank
Special5Icon1RegularHexagonNo4=Blank
Special5Icon1RegularHexagonNo5=Blank

Special5Icon2RegularHexagonNo1=Blank
Special5Icon2RegularHexagonNo2=Blank
Special5Icon2RegularHexagonNo3=Blank
Special5Icon2RegularHexagonNo4=Blank
Special5Icon2RegularHexagonNo5=Blank

Special5Icon3RegularHexagonNo1=Blank
Special5Icon3RegularHexagonNo2=Blank
Special5Icon3RegularHexagonNo3=Blank
Special5Icon3RegularHexagonNo4=Blank
Special5Icon3RegularHexagonNo5=Blank

Special5Icon4RegularHexagonNo1=Blank
Special5Icon4RegularHexagonNo2=Blank
Special5Icon4RegularHexagonNo3=Blank
Special5Icon4RegularHexagonNo4=Blank
Special5Icon4RegularHexagonNo5=Blank

Special5Icon5RegularHexagonNo1=Blank
Special5Icon5RegularHexagonNo2=Blank
Special5Icon5RegularHexagonNo3=Blank
Special5Icon5RegularHexagonNo4=Blank
Special5Icon5RegularHexagonNo5=Blank

Special5Icon1URLRegularHexagonNo1=Blank
Special5Icon1URLRegularHexagonNo2=Blank
Special5Icon1URLRegularHexagonNo3=Blank
Special5Icon1URLRegularHexagonNo4=Blank
Special5Icon1URLRegularHexagonNo5=Blank

Special5Icon2URLRegularHexagonNo1=Blank
Special5Icon2URLRegularHexagonNo2=Blank
Special5Icon2URLRegularHexagonNo3=Blank
Special5Icon2URLRegularHexagonNo4=Blank
Special5Icon2URLRegularHexagonNo5=Blank

Special5Icon3URLRegularHexagonNo1=Blank
Special5Icon3URLRegularHexagonNo2=Blank
Special5Icon3URLRegularHexagonNo3=Blank
Special5Icon3URLRegularHexagonNo4=Blank
Special5Icon3URLRegularHexagonNo5=Blank

Special5Icon4URLRegularHexagonNo1=Blank
Special5Icon4URLRegularHexagonNo2=Blank
Special5Icon4URLRegularHexagonNo3=Blank
Special5Icon4URLRegularHexagonNo4=Blank
Special5Icon4URLRegularHexagonNo5=Blank

Special5Icon5URLRegularHexagonNo1=Blank
Special5Icon5URLRegularHexagonNo2=Blank
Special5Icon5URLRegularHexagonNo3=Blank
Special5Icon5URLRegularHexagonNo4=Blank
Special5Icon5URLRegularHexagonNo5=Blank

Special5Icon1RegularHexagonCode=Base
Special5Icon1RegularHexagonColorType=Base
Special5Icon1RegularHexagonChameleonName=Foreground 1
Special5Icon1RegularHexagonChameleonHidden=1
Special5Icon1RegularHexagonBase=255,255,255
Special5Icon1RegularHexagonBaseHidden=0

Special5Icon2RegularHexagonCode=Base
Special5Icon2RegularHexagonColorType=Base
Special5Icon2RegularHexagonChameleonName=Foreground 1
Special5Icon2RegularHexagonChameleonHidden=1
Special5Icon2RegularHexagonBase=255,255,255
Special5Icon2RegularHexagonBaseHidden=0

Special5Icon3RegularHexagonCode=Base
Special5Icon3RegularHexagonColorType=Base
Special5Icon3RegularHexagonChameleonName=Foreground 1
Special5Icon3RegularHexagonChameleonHidden=1
Special5Icon3RegularHexagonBase=255,255,255
Special5Icon3RegularHexagonBaseHidden=0

Special5Icon4RegularHexagonCode=Base
Special5Icon4RegularHexagonColorType=Base
Special5Icon4RegularHexagonChameleonName=Foreground 1
Special5Icon4RegularHexagonChameleonHidden=1
Special5Icon4RegularHexagonBase=255,255,255
Special5Icon4RegularHexagonBaseHidden=0

Special5Icon5RegularHexagonCode=Base
Special5Icon5RegularHexagonColorType=Base
Special5Icon5RegularHexagonChameleonName=Foreground 1
Special5Icon5RegularHexagonChameleonHidden=1
Special5Icon5RegularHexagonBase=255,255,255
Special5Icon5RegularHexagonBaseHidden=0

; ============================================================
; ============================================================

Special7Icon1CategoryRegularHexagonNo1=Blank
Special7Icon1CategoryRegularHexagonNo2=Blank
Special7Icon1CategoryRegularHexagonNo3=Blank
Special7Icon1CategoryRegularHexagonNo4=Blank
Special7Icon1CategoryRegularHexagonNo5=Blank
Special7Icon1CategoryRegularHexagonNo6=Blank
Special7Icon1CategoryRegularHexagonNo7=Blank

Special7Icon2CategoryRegularHexagonNo1=Blank
Special7Icon2CategoryRegularHexagonNo2=Blank
Special7Icon2CategoryRegularHexagonNo3=Blank
Special7Icon2CategoryRegularHexagonNo4=Blank
Special7Icon2CategoryRegularHexagonNo5=Blank
Special7Icon2CategoryRegularHexagonNo6=Blank
Special7Icon2CategoryRegularHexagonNo7=Blank

Special7Icon3CategoryRegularHexagonNo1=Blank
Special7Icon3CategoryRegularHexagonNo2=Blank
Special7Icon3CategoryRegularHexagonNo3=Blank
Special7Icon3CategoryRegularHexagonNo4=Blank
Special7Icon3CategoryRegularHexagonNo5=Blank
Special7Icon3CategoryRegularHexagonNo6=Blank
Special7Icon3CategoryRegularHexagonNo7=Blank

Special7Icon4CategoryRegularHexagonNo1=Blank
Special7Icon4CategoryRegularHexagonNo2=Blank
Special7Icon4CategoryRegularHexagonNo3=Blank
Special7Icon4CategoryRegularHexagonNo4=Blank
Special7Icon4CategoryRegularHexagonNo5=Blank
Special7Icon4CategoryRegularHexagonNo6=Blank
Special7Icon4CategoryRegularHexagonNo7=Blank

Special7Icon5CategoryRegularHexagonNo1=Blank
Special7Icon5CategoryRegularHexagonNo2=Blank
Special7Icon5CategoryRegularHexagonNo3=Blank
Special7Icon5CategoryRegularHexagonNo4=Blank
Special7Icon5CategoryRegularHexagonNo5=Blank
Special7Icon5CategoryRegularHexagonNo6=Blank
Special7Icon5CategoryRegularHexagonNo7=Blank

Special7Icon1RegularHexagonNo1=Blank
Special7Icon1RegularHexagonNo2=Blank
Special7Icon1RegularHexagonNo3=Blank
Special7Icon1RegularHexagonNo4=Blank
Special7Icon1RegularHexagonNo5=Blank
Special7Icon1RegularHexagonNo6=Blank
Special7Icon1RegularHexagonNo7=Blank

Special7Icon2RegularHexagonNo1=Blank
Special7Icon2RegularHexagonNo2=Blank
Special7Icon2RegularHexagonNo3=Blank
Special7Icon2RegularHexagonNo4=Blank
Special7Icon2RegularHexagonNo5=Blank
Special7Icon2RegularHexagonNo6=Blank
Special7Icon2RegularHexagonNo7=Blank

Special7Icon3RegularHexagonNo1=Blank
Special7Icon3RegularHexagonNo2=Blank
Special7Icon3RegularHexagonNo3=Blank
Special7Icon3RegularHexagonNo4=Blank
Special7Icon3RegularHexagonNo5=Blank
Special7Icon3RegularHexagonNo6=Blank
Special7Icon3RegularHexagonNo7=Blank

Special7Icon4RegularHexagonNo1=Blank
Special7Icon4RegularHexagonNo2=Blank
Special7Icon4RegularHexagonNo3=Blank
Special7Icon4RegularHexagonNo4=Blank
Special7Icon4RegularHexagonNo5=Blank
Special7Icon4RegularHexagonNo6=Blank
Special7Icon4RegularHexagonNo7=Blank

Special7Icon5RegularHexagonNo1=Blank
Special7Icon5RegularHexagonNo2=Blank
Special7Icon5RegularHexagonNo3=Blank
Special7Icon5RegularHexagonNo4=Blank
Special7Icon5RegularHexagonNo5=Blank
Special7Icon5RegularHexagonNo6=Blank
Special7Icon5RegularHexagonNo7=Blank

Special7Icon1URLRegularHexagonNo1=Blank
Special7Icon1URLRegularHexagonNo2=Blank
Special7Icon1URLRegularHexagonNo3=Blank
Special7Icon1URLRegularHexagonNo4=Blank
Special7Icon1URLRegularHexagonNo5=Blank
Special7Icon1URLRegularHexagonNo6=Blank
Special7Icon1URLRegularHexagonNo7=Blank

Special7Icon2URLRegularHexagonNo1=Blank
Special7Icon2URLRegularHexagonNo2=Blank
Special7Icon2URLRegularHexagonNo3=Blank
Special7Icon2URLRegularHexagonNo4=Blank
Special7Icon2URLRegularHexagonNo5=Blank
Special7Icon2URLRegularHexagonNo6=Blank
Special7Icon2URLRegularHexagonNo7=Blank

Special7Icon3URLRegularHexagonNo1=Blank
Special7Icon3URLRegularHexagonNo2=Blank
Special7Icon3URLRegularHexagonNo3=Blank
Special7Icon3URLRegularHexagonNo4=Blank
Special7Icon3URLRegularHexagonNo5=Blank
Special7Icon3URLRegularHexagonNo6=Blank
Special7Icon3URLRegularHexagonNo7=Blank

Special7Icon4URLRegularHexagonNo1=Blank
Special7Icon4URLRegularHexagonNo2=Blank
Special7Icon4URLRegularHexagonNo3=Blank
Special7Icon4URLRegularHexagonNo4=Blank
Special7Icon4URLRegularHexagonNo5=Blank
Special7Icon4URLRegularHexagonNo6=Blank
Special7Icon4URLRegularHexagonNo7=Blank

Special7Icon5URLRegularHexagonNo1=Blank
Special7Icon5URLRegularHexagonNo2=Blank
Special7Icon5URLRegularHexagonNo3=Blank
Special7Icon5URLRegularHexagonNo4=Blank
Special7Icon5URLRegularHexagonNo5=Blank
Special7Icon5URLRegularHexagonNo6=Blank
Special7Icon5URLRegularHexagonNo7=Blank

Special7Icon1RegularHexagonCode=Base
Special7Icon1RegularHexagonColorType=Base
Special7Icon1RegularHexagonChameleonName=Foreground 1
Special7Icon1RegularHexagonChameleonHidden=1
Special7Icon1RegularHexagonBase=255,255,255
Special7Icon1RegularHexagonBaseHidden=0

Special7Icon2RegularHexagonCode=Base
Special7Icon2RegularHexagonColorType=Base
Special7Icon2RegularHexagonChameleonName=Foreground 1
Special7Icon2RegularHexagonChameleonHidden=1
Special7Icon2RegularHexagonBase=255,255,255
Special7Icon2RegularHexagonBaseHidden=0

Special7Icon3RegularHexagonCode=Base
Special7Icon3RegularHexagonColorType=Base
Special7Icon3RegularHexagonChameleonName=Foreground 1
Special7Icon3RegularHexagonChameleonHidden=1
Special7Icon3RegularHexagonBase=255,255,255
Special7Icon3RegularHexagonBaseHidden=0

Special7Icon4RegularHexagonCode=Base
Special7Icon4RegularHexagonColorType=Base
Special7Icon4RegularHexagonChameleonName=Foreground 1
Special7Icon4RegularHexagonChameleonHidden=1
Special7Icon4RegularHexagonBase=255,255,255
Special7Icon4RegularHexagonBaseHidden=0

Special7Icon5RegularHexagonCode=Base
Special7Icon5RegularHexagonColorType=Base
Special7Icon5RegularHexagonChameleonName=Foreground 1
Special7Icon5RegularHexagonChameleonHidden=1
Special7Icon5RegularHexagonBase=255,255,255
Special7Icon5RegularHexagonBaseHidden=0

; ============================================================
; ============================================================
; ============================================================
; ============================================================

Special3Icon1CategoryAlterSquareNo1=Blank
Special3Icon1CategoryAlterSquareNo2=Blank
Special3Icon1CategoryAlterSquareNo3=Blank

Special3Icon2CategoryAlterSquareNo1=Blank
Special3Icon2CategoryAlterSquareNo2=Blank
Special3Icon2CategoryAlterSquareNo3=Blank

Special3Icon3CategoryAlterSquareNo1=Blank
Special3Icon3CategoryAlterSquareNo2=Blank
Special3Icon3CategoryAlterSquareNo3=Blank

Special3Icon4CategoryAlterSquareNo1=Blank
Special3Icon4CategoryAlterSquareNo2=Blank
Special3Icon4CategoryAlterSquareNo3=Blank

Special3Icon5CategoryAlterSquareNo1=Blank
Special3Icon5CategoryAlterSquareNo2=Blank
Special3Icon5CategoryAlterSquareNo3=Blank

Special3Icon1AlterSquareNo1=Blank
Special3Icon1AlterSquareNo2=Blank
Special3Icon1AlterSquareNo3=Blank

Special3Icon2AlterSquareNo1=Blank
Special3Icon2AlterSquareNo2=Blank
Special3Icon2AlterSquareNo3=Blank

Special3Icon3AlterSquareNo1=Blank
Special3Icon3AlterSquareNo2=Blank
Special3Icon3AlterSquareNo3=Blank

Special3Icon4AlterSquareNo1=Blank
Special3Icon4AlterSquareNo2=Blank
Special3Icon4AlterSquareNo3=Blank

Special3Icon5AlterSquareNo1=Blank
Special3Icon5AlterSquareNo2=Blank
Special3Icon5AlterSquareNo3=Blank

Special3Icon1URLAlterSquareNo1=Blank
Special3Icon1URLAlterSquareNo2=Blank
Special3Icon1URLAlterSquareNo3=Blank

Special3Icon2URLAlterSquareNo1=Blank
Special3Icon2URLAlterSquareNo2=Blank
Special3Icon2URLAlterSquareNo3=Blank

Special3Icon3URLAlterSquareNo1=Blank
Special3Icon3URLAlterSquareNo2=Blank
Special3Icon3URLAlterSquareNo3=Blank

Special3Icon4URLAlterSquareNo1=Blank
Special3Icon4URLAlterSquareNo2=Blank
Special3Icon4URLAlterSquareNo3=Blank

Special3Icon5URLAlterSquareNo1=Blank
Special3Icon5URLAlterSquareNo2=Blank
Special3Icon5URLAlterSquareNo3=Blank

Special3Icon1AlterSquareCode=Base
Special3Icon1AlterSquareColorType=Base
Special3Icon1AlterSquareChameleonName=Foreground 1
Special3Icon1AlterSquareChameleonHidden=1
Special3Icon1AlterSquareBase=255,255,255
Special3Icon1AlterSquareBaseHidden=0

Special3Icon2AlterSquareCode=Base
Special3Icon2AlterSquareColorType=Base
Special3Icon2AlterSquareChameleonName=Foreground 1
Special3Icon2AlterSquareChameleonHidden=1
Special3Icon2AlterSquareBase=255,255,255
Special3Icon2AlterSquareBaseHidden=0

Special3Icon3AlterSquareCode=Base
Special3Icon3AlterSquareColorType=Base
Special3Icon3AlterSquareChameleonName=Foreground 1
Special3Icon3AlterSquareChameleonHidden=1
Special3Icon3AlterSquareBase=255,255,255
Special3Icon3AlterSquareBaseHidden=0

Special3Icon4AlterSquareCode=Base
Special3Icon4AlterSquareColorType=Base
Special3Icon4AlterSquareChameleonName=Foreground 1
Special3Icon4AlterSquareChameleonHidden=1
Special3Icon4AlterSquareBase=255,255,255
Special3Icon4AlterSquareBaseHidden=0

Special3Icon5AlterSquareCode=Base
Special3Icon5AlterSquareColorType=Base
Special3Icon5AlterSquareChameleonName=Foreground 1
Special3Icon5AlterSquareChameleonHidden=1
Special3Icon5AlterSquareBase=255,255,255
Special3Icon5AlterSquareBaseHidden=0

; ============================================================
; ============================================================

Special4Icon1CategoryAlterSquareNo1=Blank
Special4Icon1CategoryAlterSquareNo2=Blank
Special4Icon1CategoryAlterSquareNo3=Blank
Special4Icon1CategoryAlterSquareNo4=Blank

Special4Icon2CategoryAlterSquareNo1=Blank
Special4Icon2CategoryAlterSquareNo2=Blank
Special4Icon2CategoryAlterSquareNo3=Blank
Special4Icon2CategoryAlterSquareNo4=Blank

Special4Icon3CategoryAlterSquareNo1=Blank
Special4Icon3CategoryAlterSquareNo2=Blank
Special4Icon3CategoryAlterSquareNo3=Blank
Special4Icon3CategoryAlterSquareNo4=Blank

Special4Icon4CategoryAlterSquareNo1=Blank
Special4Icon4CategoryAlterSquareNo2=Blank
Special4Icon4CategoryAlterSquareNo3=Blank
Special4Icon4CategoryAlterSquareNo4=Blank

Special4Icon5CategoryAlterSquareNo1=Blank
Special4Icon5CategoryAlterSquareNo2=Blank
Special4Icon5CategoryAlterSquareNo3=Blank
Special4Icon5CategoryAlterSquareNo4=Blank

Special4Icon1AlterSquareNo1=Blank
Special4Icon1AlterSquareNo2=Blank
Special4Icon1AlterSquareNo3=Blank
Special4Icon1AlterSquareNo4=Blank

Special4Icon2AlterSquareNo1=Blank
Special4Icon2AlterSquareNo2=Blank
Special4Icon2AlterSquareNo3=Blank
Special4Icon2AlterSquareNo4=Blank

Special4Icon3AlterSquareNo1=Blank
Special4Icon3AlterSquareNo2=Blank
Special4Icon3AlterSquareNo3=Blank
Special4Icon3AlterSquareNo4=Blank

Special4Icon4AlterSquareNo1=Blank
Special4Icon4AlterSquareNo2=Blank
Special4Icon4AlterSquareNo3=Blank
Special4Icon4AlterSquareNo4=Blank

Special4Icon5AlterSquareNo1=Blank
Special4Icon5AlterSquareNo2=Blank
Special4Icon5AlterSquareNo3=Blank
Special4Icon5AlterSquareNo4=Blank

Special4Icon1URLAlterSquareNo1=Blank
Special4Icon1URLAlterSquareNo2=Blank
Special4Icon1URLAlterSquareNo3=Blank
Special4Icon1URLAlterSquareNo4=Blank

Special4Icon2URLAlterSquareNo1=Blank
Special4Icon2URLAlterSquareNo2=Blank
Special4Icon2URLAlterSquareNo3=Blank
Special4Icon2URLAlterSquareNo4=Blank

Special4Icon3URLAlterSquareNo1=Blank
Special4Icon3URLAlterSquareNo2=Blank
Special4Icon3URLAlterSquareNo3=Blank
Special4Icon3URLAlterSquareNo4=Blank

Special4Icon4URLAlterSquareNo1=Blank
Special4Icon4URLAlterSquareNo2=Blank
Special4Icon4URLAlterSquareNo3=Blank
Special4Icon4URLAlterSquareNo4=Blank

Special4Icon5URLAlterSquareNo1=Blank
Special4Icon5URLAlterSquareNo2=Blank
Special4Icon5URLAlterSquareNo3=Blank
Special4Icon5URLAlterSquareNo4=Blank

Special4Icon1AlterSquareCode=Base
Special4Icon1AlterSquareColorType=Base
Special4Icon1AlterSquareChameleonName=Foreground 1
Special4Icon1AlterSquareChameleonHidden=1
Special4Icon1AlterSquareBase=255,255,255
Special4Icon1AlterSquareBaseHidden=0

Special4Icon2AlterSquareCode=Base
Special4Icon2AlterSquareColorType=Base
Special4Icon2AlterSquareChameleonName=Foreground 1
Special4Icon2AlterSquareChameleonHidden=1
Special4Icon2AlterSquareBase=255,255,255
Special4Icon2AlterSquareBaseHidden=0

Special4Icon3AlterSquareCode=Base
Special4Icon3AlterSquareColorType=Base
Special4Icon3AlterSquareChameleonName=Foreground 1
Special4Icon3AlterSquareChameleonHidden=1
Special4Icon3AlterSquareBase=255,255,255
Special4Icon3AlterSquareBaseHidden=0

Special4Icon4AlterSquareCode=Base
Special4Icon4AlterSquareColorType=Base
Special4Icon4AlterSquareChameleonName=Foreground 1
Special4Icon4AlterSquareChameleonHidden=1
Special4Icon4AlterSquareBase=255,255,255
Special4Icon4AlterSquareBaseHidden=0

Special4Icon5AlterSquareCode=Base
Special4Icon5AlterSquareColorType=Base
Special4Icon5AlterSquareChameleonName=Foreground 1
Special4Icon5AlterSquareChameleonHidden=1
Special4Icon5AlterSquareBase=255,255,255
Special4Icon5AlterSquareBaseHidden=0

; ============================================================
; ============================================================

Special5Icon1CategoryAlterSquareNo1=Blank
Special5Icon1CategoryAlterSquareNo2=Blank
Special5Icon1CategoryAlterSquareNo3=Blank
Special5Icon1CategoryAlterSquareNo4=Blank
Special5Icon1CategoryAlterSquareNo5=Blank

Special5Icon2CategoryAlterSquareNo1=Blank
Special5Icon2CategoryAlterSquareNo2=Blank
Special5Icon2CategoryAlterSquareNo3=Blank
Special5Icon2CategoryAlterSquareNo4=Blank
Special5Icon2CategoryAlterSquareNo5=Blank

Special5Icon3CategoryAlterSquareNo1=Blank
Special5Icon3CategoryAlterSquareNo2=Blank
Special5Icon3CategoryAlterSquareNo3=Blank
Special5Icon3CategoryAlterSquareNo4=Blank
Special5Icon3CategoryAlterSquareNo5=Blank

Special5Icon4CategoryAlterSquareNo1=Blank
Special5Icon4CategoryAlterSquareNo2=Blank
Special5Icon4CategoryAlterSquareNo3=Blank
Special5Icon4CategoryAlterSquareNo4=Blank
Special5Icon4CategoryAlterSquareNo5=Blank

Special5Icon5CategoryAlterSquareNo1=Blank
Special5Icon5CategoryAlterSquareNo2=Blank
Special5Icon5CategoryAlterSquareNo3=Blank
Special5Icon5CategoryAlterSquareNo4=Blank
Special5Icon5CategoryAlterSquareNo5=Blank

Special5Icon1AlterSquareNo1=Blank
Special5Icon1AlterSquareNo2=Blank
Special5Icon1AlterSquareNo3=Blank
Special5Icon1AlterSquareNo4=Blank
Special5Icon1AlterSquareNo5=Blank

Special5Icon2AlterSquareNo1=Blank
Special5Icon2AlterSquareNo2=Blank
Special5Icon2AlterSquareNo3=Blank
Special5Icon2AlterSquareNo4=Blank
Special5Icon2AlterSquareNo5=Blank

Special5Icon3AlterSquareNo1=Blank
Special5Icon3AlterSquareNo2=Blank
Special5Icon3AlterSquareNo3=Blank
Special5Icon3AlterSquareNo4=Blank
Special5Icon3AlterSquareNo5=Blank

Special5Icon4AlterSquareNo1=Blank
Special5Icon4AlterSquareNo2=Blank
Special5Icon4AlterSquareNo3=Blank
Special5Icon4AlterSquareNo4=Blank
Special5Icon4AlterSquareNo5=Blank

Special5Icon5AlterSquareNo1=Blank
Special5Icon5AlterSquareNo2=Blank
Special5Icon5AlterSquareNo3=Blank
Special5Icon5AlterSquareNo4=Blank
Special5Icon5AlterSquareNo5=Blank

Special5Icon1URLAlterSquareNo1=Blank
Special5Icon1URLAlterSquareNo2=Blank
Special5Icon1URLAlterSquareNo3=Blank
Special5Icon1URLAlterSquareNo4=Blank
Special5Icon1URLAlterSquareNo5=Blank

Special5Icon2URLAlterSquareNo1=Blank
Special5Icon2URLAlterSquareNo2=Blank
Special5Icon2URLAlterSquareNo3=Blank
Special5Icon2URLAlterSquareNo4=Blank
Special5Icon2URLAlterSquareNo5=Blank

Special5Icon3URLAlterSquareNo1=Blank
Special5Icon3URLAlterSquareNo2=Blank
Special5Icon3URLAlterSquareNo3=Blank
Special5Icon3URLAlterSquareNo4=Blank
Special5Icon3URLAlterSquareNo5=Blank

Special5Icon4URLAlterSquareNo1=Blank
Special5Icon4URLAlterSquareNo2=Blank
Special5Icon4URLAlterSquareNo3=Blank
Special5Icon4URLAlterSquareNo4=Blank
Special5Icon4URLAlterSquareNo5=Blank

Special5Icon5URLAlterSquareNo1=Blank
Special5Icon5URLAlterSquareNo2=Blank
Special5Icon5URLAlterSquareNo3=Blank
Special5Icon5URLAlterSquareNo4=Blank
Special5Icon5URLAlterSquareNo5=Blank

Special5Icon1AlterSquareCode=Base
Special5Icon1AlterSquareColorType=Base
Special5Icon1AlterSquareChameleonName=Foreground 1
Special5Icon1AlterSquareChameleonHidden=1
Special5Icon1AlterSquareBase=255,255,255
Special5Icon1AlterSquareBaseHidden=0

Special5Icon2AlterSquareCode=Base
Special5Icon2AlterSquareColorType=Base
Special5Icon2AlterSquareChameleonName=Foreground 1
Special5Icon2AlterSquareChameleonHidden=1
Special5Icon2AlterSquareBase=255,255,255
Special5Icon2AlterSquareBaseHidden=0

Special5Icon3AlterSquareCode=Base
Special5Icon3AlterSquareColorType=Base
Special5Icon3AlterSquareChameleonName=Foreground 1
Special5Icon3AlterSquareChameleonHidden=1
Special5Icon3AlterSquareBase=255,255,255
Special5Icon3AlterSquareBaseHidden=0

Special5Icon4AlterSquareCode=Base
Special5Icon4AlterSquareColorType=Base
Special5Icon4AlterSquareChameleonName=Foreground 1
Special5Icon4AlterSquareChameleonHidden=1
Special5Icon4AlterSquareBase=255,255,255
Special5Icon4AlterSquareBaseHidden=0

Special5Icon5AlterSquareCode=Base
Special5Icon5AlterSquareColorType=Base
Special5Icon5AlterSquareChameleonName=Foreground 1
Special5Icon5AlterSquareChameleonHidden=1
Special5Icon5AlterSquareBase=255,255,255
Special5Icon5AlterSquareBaseHidden=0

; ============================================================
; ============================================================
; ============================================================
; ============================================================

Special3Icon1CategoryAlterSquareV2No1=Blank
Special3Icon1CategoryAlterSquareV2No2=Blank
Special3Icon1CategoryAlterSquareV2No3=Blank

Special3Icon2CategoryAlterSquareV2No1=Blank
Special3Icon2CategoryAlterSquareV2No2=Blank
Special3Icon2CategoryAlterSquareV2No3=Blank

Special3Icon3CategoryAlterSquareV2No1=Blank
Special3Icon3CategoryAlterSquareV2No2=Blank
Special3Icon3CategoryAlterSquareV2No3=Blank

Special3Icon4CategoryAlterSquareV2No1=Blank
Special3Icon4CategoryAlterSquareV2No2=Blank
Special3Icon4CategoryAlterSquareV2No3=Blank

Special3Icon5CategoryAlterSquareV2No1=Blank
Special3Icon5CategoryAlterSquareV2No2=Blank
Special3Icon5CategoryAlterSquareV2No3=Blank

Special3Icon1AlterSquareV2No1=Blank
Special3Icon1AlterSquareV2No2=Blank
Special3Icon1AlterSquareV2No3=Blank

Special3Icon2AlterSquareV2No1=Blank
Special3Icon2AlterSquareV2No2=Blank
Special3Icon2AlterSquareV2No3=Blank

Special3Icon3AlterSquareV2No1=Blank
Special3Icon3AlterSquareV2No2=Blank
Special3Icon3AlterSquareV2No3=Blank

Special3Icon4AlterSquareV2No1=Blank
Special3Icon4AlterSquareV2No2=Blank
Special3Icon4AlterSquareV2No3=Blank

Special3Icon5AlterSquareV2No1=Blank
Special3Icon5AlterSquareV2No2=Blank
Special3Icon5AlterSquareV2No3=Blank

Special3Icon1URLAlterSquareV2No1=Blank
Special3Icon1URLAlterSquareV2No2=Blank
Special3Icon1URLAlterSquareV2No3=Blank

Special3Icon2URLAlterSquareV2No1=Blank
Special3Icon2URLAlterSquareV2No2=Blank
Special3Icon2URLAlterSquareV2No3=Blank

Special3Icon3URLAlterSquareV2No1=Blank
Special3Icon3URLAlterSquareV2No2=Blank
Special3Icon3URLAlterSquareV2No3=Blank

Special3Icon4URLAlterSquareV2No1=Blank
Special3Icon4URLAlterSquareV2No2=Blank
Special3Icon4URLAlterSquareV2No3=Blank

Special3Icon5URLAlterSquareV2No1=Blank
Special3Icon5URLAlterSquareV2No2=Blank
Special3Icon5URLAlterSquareV2No3=Blank

Special3Icon1AlterSquareV2Code=Base
Special3Icon1AlterSquareV2ColorType=Base
Special3Icon1AlterSquareV2ChameleonName=Foreground 1
Special3Icon1AlterSquareV2ChameleonHidden=1
Special3Icon1AlterSquareV2Base=255,255,255
Special3Icon1AlterSquareV2BaseHidden=0

Special3Icon2AlterSquareV2Code=Base
Special3Icon2AlterSquareV2ColorType=Base
Special3Icon2AlterSquareV2ChameleonName=Foreground 1
Special3Icon2AlterSquareV2ChameleonHidden=1
Special3Icon2AlterSquareV2Base=255,255,255
Special3Icon2AlterSquareV2BaseHidden=0

Special3Icon3AlterSquareV2Code=Base
Special3Icon3AlterSquareV2ColorType=Base
Special3Icon3AlterSquareV2ChameleonName=Foreground 1
Special3Icon3AlterSquareV2ChameleonHidden=1
Special3Icon3AlterSquareV2Base=255,255,255
Special3Icon3AlterSquareV2BaseHidden=0

Special3Icon4AlterSquareV2Code=Base
Special3Icon4AlterSquareV2ColorType=Base
Special3Icon4AlterSquareV2ChameleonName=Foreground 1
Special3Icon4AlterSquareV2ChameleonHidden=1
Special3Icon4AlterSquareV2Base=255,255,255
Special3Icon4AlterSquareV2BaseHidden=0

Special3Icon5AlterSquareV2Code=Base
Special3Icon5AlterSquareV2ColorType=Base
Special3Icon5AlterSquareV2ChameleonName=Foreground 1
Special3Icon5AlterSquareV2ChameleonHidden=1
Special3Icon5AlterSquareV2Base=255,255,255
Special3Icon5AlterSquareV2BaseHidden=0

; ============================================================
; ============================================================

Special4Icon1CategoryAlterSquareV2No1=Blank
Special4Icon1CategoryAlterSquareV2No2=Blank
Special4Icon1CategoryAlterSquareV2No3=Blank
Special4Icon1CategoryAlterSquareV2No4=Blank

Special4Icon2CategoryAlterSquareV2No1=Blank
Special4Icon2CategoryAlterSquareV2No2=Blank
Special4Icon2CategoryAlterSquareV2No3=Blank
Special4Icon2CategoryAlterSquareV2No4=Blank

Special4Icon3CategoryAlterSquareV2No1=Blank
Special4Icon3CategoryAlterSquareV2No2=Blank
Special4Icon3CategoryAlterSquareV2No3=Blank
Special4Icon3CategoryAlterSquareV2No4=Blank

Special4Icon4CategoryAlterSquareV2No1=Blank
Special4Icon4CategoryAlterSquareV2No2=Blank
Special4Icon4CategoryAlterSquareV2No3=Blank
Special4Icon4CategoryAlterSquareV2No4=Blank

Special4Icon5CategoryAlterSquareV2No1=Blank
Special4Icon5CategoryAlterSquareV2No2=Blank
Special4Icon5CategoryAlterSquareV2No3=Blank
Special4Icon5CategoryAlterSquareV2No4=Blank

Special4Icon1AlterSquareV2No1=Blank
Special4Icon1AlterSquareV2No2=Blank
Special4Icon1AlterSquareV2No3=Blank
Special4Icon1AlterSquareV2No4=Blank

Special4Icon2AlterSquareV2No1=Blank
Special4Icon2AlterSquareV2No2=Blank
Special4Icon2AlterSquareV2No3=Blank
Special4Icon2AlterSquareV2No4=Blank

Special4Icon3AlterSquareV2No1=Blank
Special4Icon3AlterSquareV2No2=Blank
Special4Icon3AlterSquareV2No3=Blank
Special4Icon3AlterSquareV2No4=Blank

Special4Icon4AlterSquareV2No1=Blank
Special4Icon4AlterSquareV2No2=Blank
Special4Icon4AlterSquareV2No3=Blank
Special4Icon4AlterSquareV2No4=Blank

Special4Icon5AlterSquareV2No1=Blank
Special4Icon5AlterSquareV2No2=Blank
Special4Icon5AlterSquareV2No3=Blank
Special4Icon5AlterSquareV2No4=Blank

Special4Icon1URLAlterSquareV2No1=Blank
Special4Icon1URLAlterSquareV2No2=Blank
Special4Icon1URLAlterSquareV2No3=Blank
Special4Icon1URLAlterSquareV2No4=Blank

Special4Icon2URLAlterSquareV2No1=Blank
Special4Icon2URLAlterSquareV2No2=Blank
Special4Icon2URLAlterSquareV2No3=Blank
Special4Icon2URLAlterSquareV2No4=Blank

Special4Icon3URLAlterSquareV2No1=Blank
Special4Icon3URLAlterSquareV2No2=Blank
Special4Icon3URLAlterSquareV2No3=Blank
Special4Icon3URLAlterSquareV2No4=Blank

Special4Icon4URLAlterSquareV2No1=Blank
Special4Icon4URLAlterSquareV2No2=Blank
Special4Icon4URLAlterSquareV2No3=Blank
Special4Icon4URLAlterSquareV2No4=Blank

Special4Icon5URLAlterSquareV2No1=Blank
Special4Icon5URLAlterSquareV2No2=Blank
Special4Icon5URLAlterSquareV2No3=Blank
Special4Icon5URLAlterSquareV2No4=Blank

Special4Icon1AlterSquareV2Code=Base
Special4Icon1AlterSquareV2ColorType=Base
Special4Icon1AlterSquareV2ChameleonName=Foreground 1
Special4Icon1AlterSquareV2ChameleonHidden=1
Special4Icon1AlterSquareV2Base=255,255,255
Special4Icon1AlterSquareV2BaseHidden=0

Special4Icon2AlterSquareV2Code=Base
Special4Icon2AlterSquareV2ColorType=Base
Special4Icon2AlterSquareV2ChameleonName=Foreground 1
Special4Icon2AlterSquareV2ChameleonHidden=1
Special4Icon2AlterSquareV2Base=255,255,255
Special4Icon2AlterSquareV2BaseHidden=0

Special4Icon3AlterSquareV2Code=Base
Special4Icon3AlterSquareV2ColorType=Base
Special4Icon3AlterSquareV2ChameleonName=Foreground 1
Special4Icon3AlterSquareV2ChameleonHidden=1
Special4Icon3AlterSquareV2Base=255,255,255
Special4Icon3AlterSquareV2BaseHidden=0

Special4Icon4AlterSquareV2Code=Base
Special4Icon4AlterSquareV2ColorType=Base
Special4Icon4AlterSquareV2ChameleonName=Foreground 1
Special4Icon4AlterSquareV2ChameleonHidden=1
Special4Icon4AlterSquareV2Base=255,255,255
Special4Icon4AlterSquareV2BaseHidden=0

Special4Icon5AlterSquareV2Code=Base
Special4Icon5AlterSquareV2ColorType=Base
Special4Icon5AlterSquareV2ChameleonName=Foreground 1
Special4Icon5AlterSquareV2ChameleonHidden=1
Special4Icon5AlterSquareV2Base=255,255,255
Special4Icon5AlterSquareV2BaseHidden=0

; ============================================================
; ============================================================

Special5Icon1CategoryAlterSquareV2No1=Blank
Special5Icon1CategoryAlterSquareV2No2=Blank
Special5Icon1CategoryAlterSquareV2No3=Blank
Special5Icon1CategoryAlterSquareV2No4=Blank
Special5Icon1CategoryAlterSquareV2No5=Blank

Special5Icon2CategoryAlterSquareV2No1=Blank
Special5Icon2CategoryAlterSquareV2No2=Blank
Special5Icon2CategoryAlterSquareV2No3=Blank
Special5Icon2CategoryAlterSquareV2No4=Blank
Special5Icon2CategoryAlterSquareV2No5=Blank

Special5Icon3CategoryAlterSquareV2No1=Blank
Special5Icon3CategoryAlterSquareV2No2=Blank
Special5Icon3CategoryAlterSquareV2No3=Blank
Special5Icon3CategoryAlterSquareV2No4=Blank
Special5Icon3CategoryAlterSquareV2No5=Blank

Special5Icon4CategoryAlterSquareV2No1=Blank
Special5Icon4CategoryAlterSquareV2No2=Blank
Special5Icon4CategoryAlterSquareV2No3=Blank
Special5Icon4CategoryAlterSquareV2No4=Blank
Special5Icon4CategoryAlterSquareV2No5=Blank

Special5Icon5CategoryAlterSquareV2No1=Blank
Special5Icon5CategoryAlterSquareV2No2=Blank
Special5Icon5CategoryAlterSquareV2No3=Blank
Special5Icon5CategoryAlterSquareV2No4=Blank
Special5Icon5CategoryAlterSquareV2No5=Blank

Special5Icon1AlterSquareV2No1=Blank
Special5Icon1AlterSquareV2No2=Blank
Special5Icon1AlterSquareV2No3=Blank
Special5Icon1AlterSquareV2No4=Blank
Special5Icon1AlterSquareV2No5=Blank

Special5Icon2AlterSquareV2No1=Blank
Special5Icon2AlterSquareV2No2=Blank
Special5Icon2AlterSquareV2No3=Blank
Special5Icon2AlterSquareV2No4=Blank
Special5Icon2AlterSquareV2No5=Blank

Special5Icon3AlterSquareV2No1=Blank
Special5Icon3AlterSquareV2No2=Blank
Special5Icon3AlterSquareV2No3=Blank
Special5Icon3AlterSquareV2No4=Blank
Special5Icon3AlterSquareV2No5=Blank

Special5Icon4AlterSquareV2No1=Blank
Special5Icon4AlterSquareV2No2=Blank
Special5Icon4AlterSquareV2No3=Blank
Special5Icon4AlterSquareV2No4=Blank
Special5Icon4AlterSquareV2No5=Blank

Special5Icon5AlterSquareV2No1=Blank
Special5Icon5AlterSquareV2No2=Blank
Special5Icon5AlterSquareV2No3=Blank
Special5Icon5AlterSquareV2No4=Blank
Special5Icon5AlterSquareV2No5=Blank

Special5Icon1URLAlterSquareV2No1=Blank
Special5Icon1URLAlterSquareV2No2=Blank
Special5Icon1URLAlterSquareV2No3=Blank
Special5Icon1URLAlterSquareV2No4=Blank
Special5Icon1URLAlterSquareV2No5=Blank

Special5Icon2URLAlterSquareV2No1=Blank
Special5Icon2URLAlterSquareV2No2=Blank
Special5Icon2URLAlterSquareV2No3=Blank
Special5Icon2URLAlterSquareV2No4=Blank
Special5Icon2URLAlterSquareV2No5=Blank

Special5Icon3URLAlterSquareV2No1=Blank
Special5Icon3URLAlterSquareV2No2=Blank
Special5Icon3URLAlterSquareV2No3=Blank
Special5Icon3URLAlterSquareV2No4=Blank
Special5Icon3URLAlterSquareV2No5=Blank

Special5Icon4URLAlterSquareV2No1=Blank
Special5Icon4URLAlterSquareV2No2=Blank
Special5Icon4URLAlterSquareV2No3=Blank
Special5Icon4URLAlterSquareV2No4=Blank
Special5Icon4URLAlterSquareV2No5=Blank

Special5Icon5URLAlterSquareV2No1=Blank
Special5Icon5URLAlterSquareV2No2=Blank
Special5Icon5URLAlterSquareV2No3=Blank
Special5Icon5URLAlterSquareV2No4=Blank
Special5Icon5URLAlterSquareV2No5=Blank

Special5Icon1AlterSquareV2Code=Base
Special5Icon1AlterSquareV2ColorType=Base
Special5Icon1AlterSquareV2ChameleonName=Foreground 1
Special5Icon1AlterSquareV2ChameleonHidden=1
Special5Icon1AlterSquareV2Base=255,255,255
Special5Icon1AlterSquareV2BaseHidden=0

Special5Icon2AlterSquareV2Code=Base
Special5Icon2AlterSquareV2ColorType=Base
Special5Icon2AlterSquareV2ChameleonName=Foreground 1
Special5Icon2AlterSquareV2ChameleonHidden=1
Special5Icon2AlterSquareV2Base=255,255,255
Special5Icon2AlterSquareV2BaseHidden=0

Special5Icon3AlterSquareV2Code=Base
Special5Icon3AlterSquareV2ColorType=Base
Special5Icon3AlterSquareV2ChameleonName=Foreground 1
Special5Icon3AlterSquareV2ChameleonHidden=1
Special5Icon3AlterSquareV2Base=255,255,255
Special5Icon3AlterSquareV2BaseHidden=0

Special5Icon4AlterSquareV2Code=Base
Special5Icon4AlterSquareV2ColorType=Base
Special5Icon4AlterSquareV2ChameleonName=Foreground 1
Special5Icon4AlterSquareV2ChameleonHidden=1
Special5Icon4AlterSquareV2Base=255,255,255
Special5Icon4AlterSquareV2BaseHidden=0

Special5Icon5AlterSquareV2Code=Base
Special5Icon5AlterSquareV2ColorType=Base
Special5Icon5AlterSquareV2ChameleonName=Foreground 1
Special5Icon5AlterSquareV2ChameleonHidden=1
Special5Icon5AlterSquareV2Base=255,255,255
Special5Icon5AlterSquareV2BaseHidden=0

; ============================================================
; ============================================================
; ============================================================
; ============================================================

Special3Icon1CategoryInlineSquareNo1=Blank
Special3Icon1CategoryInlineSquareNo2=Blank
Special3Icon1CategoryInlineSquareNo3=Blank

Special3Icon2CategoryInlineSquareNo1=Blank
Special3Icon2CategoryInlineSquareNo2=Blank
Special3Icon2CategoryInlineSquareNo3=Blank

Special3Icon3CategoryInlineSquareNo1=Blank
Special3Icon3CategoryInlineSquareNo2=Blank
Special3Icon3CategoryInlineSquareNo3=Blank

Special3Icon4CategoryInlineSquareNo1=Blank
Special3Icon4CategoryInlineSquareNo2=Blank
Special3Icon4CategoryInlineSquareNo3=Blank

Special3Icon5CategoryInlineSquareNo1=Blank
Special3Icon5CategoryInlineSquareNo2=Blank
Special3Icon5CategoryInlineSquareNo3=Blank

Special3Icon1InlineSquareNo1=Blank
Special3Icon1InlineSquareNo2=Blank
Special3Icon1InlineSquareNo3=Blank

Special3Icon2InlineSquareNo1=Blank
Special3Icon2InlineSquareNo2=Blank
Special3Icon2InlineSquareNo3=Blank

Special3Icon3InlineSquareNo1=Blank
Special3Icon3InlineSquareNo2=Blank
Special3Icon3InlineSquareNo3=Blank

Special3Icon4InlineSquareNo1=Blank
Special3Icon4InlineSquareNo2=Blank
Special3Icon4InlineSquareNo3=Blank

Special3Icon5InlineSquareNo1=Blank
Special3Icon5InlineSquareNo2=Blank
Special3Icon5InlineSquareNo3=Blank

Special3Icon1URLInlineSquareNo1=Blank
Special3Icon1URLInlineSquareNo2=Blank
Special3Icon1URLInlineSquareNo3=Blank

Special3Icon2URLInlineSquareNo1=Blank
Special3Icon2URLInlineSquareNo2=Blank
Special3Icon2URLInlineSquareNo3=Blank

Special3Icon3URLInlineSquareNo1=Blank
Special3Icon3URLInlineSquareNo2=Blank
Special3Icon3URLInlineSquareNo3=Blank

Special3Icon4URLInlineSquareNo1=Blank
Special3Icon4URLInlineSquareNo2=Blank
Special3Icon4URLInlineSquareNo3=Blank

Special3Icon5URLInlineSquareNo1=Blank
Special3Icon5URLInlineSquareNo2=Blank
Special3Icon5URLInlineSquareNo3=Blank

Special3Icon1InlineSquareCode=Base
Special3Icon1InlineSquareColorType=Base
Special3Icon1InlineSquareChameleonName=Foreground 1
Special3Icon1InlineSquareChameleonHidden=1
Special3Icon1InlineSquareBase=255,255,255
Special3Icon1InlineSquareBaseHidden=0

Special3Icon2InlineSquareCode=Base
Special3Icon2InlineSquareColorType=Base
Special3Icon2InlineSquareChameleonName=Foreground 1
Special3Icon2InlineSquareChameleonHidden=1
Special3Icon2InlineSquareBase=255,255,255
Special3Icon2InlineSquareBaseHidden=0

Special3Icon3InlineSquareCode=Base
Special3Icon3InlineSquareColorType=Base
Special3Icon3InlineSquareChameleonName=Foreground 1
Special3Icon3InlineSquareChameleonHidden=1
Special3Icon3InlineSquareBase=255,255,255
Special3Icon3InlineSquareBaseHidden=0

Special3Icon4InlineSquareCode=Base
Special3Icon4InlineSquareColorType=Base
Special3Icon4InlineSquareChameleonName=Foreground 1
Special3Icon4InlineSquareChameleonHidden=1
Special3Icon4InlineSquareBase=255,255,255
Special3Icon4InlineSquareBaseHidden=0

Special3Icon5InlineSquareCode=Base
Special3Icon5InlineSquareColorType=Base
Special3Icon5InlineSquareChameleonName=Foreground 1
Special3Icon5InlineSquareChameleonHidden=1
Special3Icon5InlineSquareBase=255,255,255
Special3Icon5InlineSquareBaseHidden=0

; ============================================================
; ============================================================

Special4Icon1CategoryInlineSquareNo1=Blank
Special4Icon1CategoryInlineSquareNo2=Blank
Special4Icon1CategoryInlineSquareNo3=Blank
Special4Icon1CategoryInlineSquareNo4=Blank

Special4Icon2CategoryInlineSquareNo1=Blank
Special4Icon2CategoryInlineSquareNo2=Blank
Special4Icon2CategoryInlineSquareNo3=Blank
Special4Icon2CategoryInlineSquareNo4=Blank

Special4Icon3CategoryInlineSquareNo1=Blank
Special4Icon3CategoryInlineSquareNo2=Blank
Special4Icon3CategoryInlineSquareNo3=Blank
Special4Icon3CategoryInlineSquareNo4=Blank

Special4Icon4CategoryInlineSquareNo1=Blank
Special4Icon4CategoryInlineSquareNo2=Blank
Special4Icon4CategoryInlineSquareNo3=Blank
Special4Icon4CategoryInlineSquareNo4=Blank

Special4Icon5CategoryInlineSquareNo1=Blank
Special4Icon5CategoryInlineSquareNo2=Blank
Special4Icon5CategoryInlineSquareNo3=Blank
Special4Icon5CategoryInlineSquareNo4=Blank

Special4Icon1InlineSquareNo1=Blank
Special4Icon1InlineSquareNo2=Blank
Special4Icon1InlineSquareNo3=Blank
Special4Icon1InlineSquareNo4=Blank

Special4Icon2InlineSquareNo1=Blank
Special4Icon2InlineSquareNo2=Blank
Special4Icon2InlineSquareNo3=Blank
Special4Icon2InlineSquareNo4=Blank

Special4Icon3InlineSquareNo1=Blank
Special4Icon3InlineSquareNo2=Blank
Special4Icon3InlineSquareNo3=Blank
Special4Icon3InlineSquareNo4=Blank

Special4Icon4InlineSquareNo1=Blank
Special4Icon4InlineSquareNo2=Blank
Special4Icon4InlineSquareNo3=Blank
Special4Icon4InlineSquareNo4=Blank

Special4Icon5InlineSquareNo1=Blank
Special4Icon5InlineSquareNo2=Blank
Special4Icon5InlineSquareNo3=Blank
Special4Icon5InlineSquareNo4=Blank

Special4Icon1URLInlineSquareNo1=Blank
Special4Icon1URLInlineSquareNo2=Blank
Special4Icon1URLInlineSquareNo3=Blank
Special4Icon1URLInlineSquareNo4=Blank

Special4Icon2URLInlineSquareNo1=Blank
Special4Icon2URLInlineSquareNo2=Blank
Special4Icon2URLInlineSquareNo3=Blank
Special4Icon2URLInlineSquareNo4=Blank

Special4Icon3URLInlineSquareNo1=Blank
Special4Icon3URLInlineSquareNo2=Blank
Special4Icon3URLInlineSquareNo3=Blank
Special4Icon3URLInlineSquareNo4=Blank

Special4Icon4URLInlineSquareNo1=Blank
Special4Icon4URLInlineSquareNo2=Blank
Special4Icon4URLInlineSquareNo3=Blank
Special4Icon4URLInlineSquareNo4=Blank

Special4Icon5URLInlineSquareNo1=Blank
Special4Icon5URLInlineSquareNo2=Blank
Special4Icon5URLInlineSquareNo3=Blank
Special4Icon5URLInlineSquareNo4=Blank

Special4Icon1InlineSquareCode=Base
Special4Icon1InlineSquareColorType=Base
Special4Icon1InlineSquareChameleonName=Foreground 1
Special4Icon1InlineSquareChameleonHidden=1
Special4Icon1InlineSquareBase=255,255,255
Special4Icon1InlineSquareBaseHidden=0

Special4Icon2InlineSquareCode=Base
Special4Icon2InlineSquareColorType=Base
Special4Icon2InlineSquareChameleonName=Foreground 1
Special4Icon2InlineSquareChameleonHidden=1
Special4Icon2InlineSquareBase=255,255,255
Special4Icon2InlineSquareBaseHidden=0

Special4Icon3InlineSquareCode=Base
Special4Icon3InlineSquareColorType=Base
Special4Icon3InlineSquareChameleonName=Foreground 1
Special4Icon3InlineSquareChameleonHidden=1
Special4Icon3InlineSquareBase=255,255,255
Special4Icon3InlineSquareBaseHidden=0

Special4Icon4InlineSquareCode=Base
Special4Icon4InlineSquareColorType=Base
Special4Icon4InlineSquareChameleonName=Foreground 1
Special4Icon4InlineSquareChameleonHidden=1
Special4Icon4InlineSquareBase=255,255,255
Special4Icon4InlineSquareBaseHidden=0

Special4Icon5InlineSquareCode=Base
Special4Icon5InlineSquareColorType=Base
Special4Icon5InlineSquareChameleonName=Foreground 1
Special4Icon5InlineSquareChameleonHidden=1
Special4Icon5InlineSquareBase=255,255,255
Special4Icon5InlineSquareBaseHidden=0

; ============================================================
; ============================================================

Special5Icon1CategoryInlineSquareNo1=Blank
Special5Icon1CategoryInlineSquareNo2=Blank
Special5Icon1CategoryInlineSquareNo3=Blank
Special5Icon1CategoryInlineSquareNo4=Blank
Special5Icon1CategoryInlineSquareNo5=Blank

Special5Icon2CategoryInlineSquareNo1=Blank
Special5Icon2CategoryInlineSquareNo2=Blank
Special5Icon2CategoryInlineSquareNo3=Blank
Special5Icon2CategoryInlineSquareNo4=Blank
Special5Icon2CategoryInlineSquareNo5=Blank

Special5Icon3CategoryInlineSquareNo1=Blank
Special5Icon3CategoryInlineSquareNo2=Blank
Special5Icon3CategoryInlineSquareNo3=Blank
Special5Icon3CategoryInlineSquareNo4=Blank
Special5Icon3CategoryInlineSquareNo5=Blank

Special5Icon4CategoryInlineSquareNo1=Blank
Special5Icon4CategoryInlineSquareNo2=Blank
Special5Icon4CategoryInlineSquareNo3=Blank
Special5Icon4CategoryInlineSquareNo4=Blank
Special5Icon4CategoryInlineSquareNo5=Blank

Special5Icon5CategoryInlineSquareNo1=Blank
Special5Icon5CategoryInlineSquareNo2=Blank
Special5Icon5CategoryInlineSquareNo3=Blank
Special5Icon5CategoryInlineSquareNo4=Blank
Special5Icon5CategoryInlineSquareNo5=Blank

Special5Icon1InlineSquareNo1=Blank
Special5Icon1InlineSquareNo2=Blank
Special5Icon1InlineSquareNo3=Blank
Special5Icon1InlineSquareNo4=Blank
Special5Icon1InlineSquareNo5=Blank

Special5Icon2InlineSquareNo1=Blank
Special5Icon2InlineSquareNo2=Blank
Special5Icon2InlineSquareNo3=Blank
Special5Icon2InlineSquareNo4=Blank
Special5Icon2InlineSquareNo5=Blank

Special5Icon3InlineSquareNo1=Blank
Special5Icon3InlineSquareNo2=Blank
Special5Icon3InlineSquareNo3=Blank
Special5Icon3InlineSquareNo4=Blank
Special5Icon3InlineSquareNo5=Blank

Special5Icon4InlineSquareNo1=Blank
Special5Icon4InlineSquareNo2=Blank
Special5Icon4InlineSquareNo3=Blank
Special5Icon4InlineSquareNo4=Blank
Special5Icon4InlineSquareNo5=Blank

Special5Icon5InlineSquareNo1=Blank
Special5Icon5InlineSquareNo2=Blank
Special5Icon5InlineSquareNo3=Blank
Special5Icon5InlineSquareNo4=Blank
Special5Icon5InlineSquareNo5=Blank

Special5Icon1URLInlineSquareNo1=Blank
Special5Icon1URLInlineSquareNo2=Blank
Special5Icon1URLInlineSquareNo3=Blank
Special5Icon1URLInlineSquareNo4=Blank
Special5Icon1URLInlineSquareNo5=Blank

Special5Icon2URLInlineSquareNo1=Blank
Special5Icon2URLInlineSquareNo2=Blank
Special5Icon2URLInlineSquareNo3=Blank
Special5Icon2URLInlineSquareNo4=Blank
Special5Icon2URLInlineSquareNo5=Blank

Special5Icon3URLInlineSquareNo1=Blank
Special5Icon3URLInlineSquareNo2=Blank
Special5Icon3URLInlineSquareNo3=Blank
Special5Icon3URLInlineSquareNo4=Blank
Special5Icon3URLInlineSquareNo5=Blank

Special5Icon4URLInlineSquareNo1=Blank
Special5Icon4URLInlineSquareNo2=Blank
Special5Icon4URLInlineSquareNo3=Blank
Special5Icon4URLInlineSquareNo4=Blank
Special5Icon4URLInlineSquareNo5=Blank

Special5Icon5URLInlineSquareNo1=Blank
Special5Icon5URLInlineSquareNo2=Blank
Special5Icon5URLInlineSquareNo3=Blank
Special5Icon5URLInlineSquareNo4=Blank
Special5Icon5URLInlineSquareNo5=Blank

Special5Icon1InlineSquareCode=Base
Special5Icon1InlineSquareColorType=Base
Special5Icon1InlineSquareChameleonName=Foreground 1
Special5Icon1InlineSquareChameleonHidden=1
Special5Icon1InlineSquareBase=255,255,255
Special5Icon1InlineSquareBaseHidden=0

Special5Icon2InlineSquareCode=Base
Special5Icon2InlineSquareColorType=Base
Special5Icon2InlineSquareChameleonName=Foreground 1
Special5Icon2InlineSquareChameleonHidden=1
Special5Icon2InlineSquareBase=255,255,255
Special5Icon2InlineSquareBaseHidden=0

Special5Icon3InlineSquareCode=Base
Special5Icon3InlineSquareColorType=Base
Special5Icon3InlineSquareChameleonName=Foreground 1
Special5Icon3InlineSquareChameleonHidden=1
Special5Icon3InlineSquareBase=255,255,255
Special5Icon3InlineSquareBaseHidden=0

Special5Icon4InlineSquareCode=Base
Special5Icon4InlineSquareColorType=Base
Special5Icon4InlineSquareChameleonName=Foreground 1
Special5Icon4InlineSquareChameleonHidden=1
Special5Icon4InlineSquareBase=255,255,255
Special5Icon4InlineSquareBaseHidden=0

Special5Icon5InlineSquareCode=Base
Special5Icon5InlineSquareColorType=Base
Special5Icon5InlineSquareChameleonName=Foreground 1
Special5Icon5InlineSquareChameleonHidden=1
Special5Icon5InlineSquareBase=255,255,255
Special5Icon5InlineSquareBaseHidden=0

; ============================================================
; ============================================================
; ============================================================
; ============================================================

Special3Icon1CategoryRegularSquareNo1=Blank
Special3Icon1CategoryRegularSquareNo2=Blank
Special3Icon1CategoryRegularSquareNo3=Blank

Special3Icon2CategoryRegularSquareNo1=Blank
Special3Icon2CategoryRegularSquareNo2=Blank
Special3Icon2CategoryRegularSquareNo3=Blank

Special3Icon3CategoryRegularSquareNo1=Blank
Special3Icon3CategoryRegularSquareNo2=Blank
Special3Icon3CategoryRegularSquareNo3=Blank

Special3Icon4CategoryRegularSquareNo1=Blank
Special3Icon4CategoryRegularSquareNo2=Blank
Special3Icon4CategoryRegularSquareNo3=Blank

Special3Icon5CategoryRegularSquareNo1=Blank
Special3Icon5CategoryRegularSquareNo2=Blank
Special3Icon5CategoryRegularSquareNo3=Blank

Special3Icon1RegularSquareNo1=Blank
Special3Icon1RegularSquareNo2=Blank
Special3Icon1RegularSquareNo3=Blank

Special3Icon2RegularSquareNo1=Blank
Special3Icon2RegularSquareNo2=Blank
Special3Icon2RegularSquareNo3=Blank

Special3Icon3RegularSquareNo1=Blank
Special3Icon3RegularSquareNo2=Blank
Special3Icon3RegularSquareNo3=Blank

Special3Icon4RegularSquareNo1=Blank
Special3Icon4RegularSquareNo2=Blank
Special3Icon4RegularSquareNo3=Blank

Special3Icon5RegularSquareNo1=Blank
Special3Icon5RegularSquareNo2=Blank
Special3Icon5RegularSquareNo3=Blank

Special3Icon1URLRegularSquareNo1=Blank
Special3Icon1URLRegularSquareNo2=Blank
Special3Icon1URLRegularSquareNo3=Blank

Special3Icon2URLRegularSquareNo1=Blank
Special3Icon2URLRegularSquareNo2=Blank
Special3Icon2URLRegularSquareNo3=Blank

Special3Icon3URLRegularSquareNo1=Blank
Special3Icon3URLRegularSquareNo2=Blank
Special3Icon3URLRegularSquareNo3=Blank

Special3Icon4URLRegularSquareNo1=Blank
Special3Icon4URLRegularSquareNo2=Blank
Special3Icon4URLRegularSquareNo3=Blank

Special3Icon5URLRegularSquareNo1=Blank
Special3Icon5URLRegularSquareNo2=Blank
Special3Icon5URLRegularSquareNo3=Blank

Special3Icon1RegularSquareCode=Base
Special3Icon1RegularSquareColorType=Base
Special3Icon1RegularSquareChameleonName=Foreground 1
Special3Icon1RegularSquareChameleonHidden=1
Special3Icon1RegularSquareBase=255,255,255
Special3Icon1RegularSquareBaseHidden=0

Special3Icon2RegularSquareCode=Base
Special3Icon2RegularSquareColorType=Base
Special3Icon2RegularSquareChameleonName=Foreground 1
Special3Icon2RegularSquareChameleonHidden=1
Special3Icon2RegularSquareBase=255,255,255
Special3Icon2RegularSquareBaseHidden=0

Special3Icon3RegularSquareCode=Base
Special3Icon3RegularSquareColorType=Base
Special3Icon3RegularSquareChameleonName=Foreground 1
Special3Icon3RegularSquareChameleonHidden=1
Special3Icon3RegularSquareBase=255,255,255
Special3Icon3RegularSquareBaseHidden=0

Special3Icon4RegularSquareCode=Base
Special3Icon4RegularSquareColorType=Base
Special3Icon4RegularSquareChameleonName=Foreground 1
Special3Icon4RegularSquareChameleonHidden=1
Special3Icon4RegularSquareBase=255,255,255
Special3Icon4RegularSquareBaseHidden=0

Special3Icon5RegularSquareCode=Base
Special3Icon5RegularSquareColorType=Base
Special3Icon5RegularSquareChameleonName=Foreground 1
Special3Icon5RegularSquareChameleonHidden=1
Special3Icon5RegularSquareBase=255,255,255
Special3Icon5RegularSquareBaseHidden=0

; ============================================================
; ============================================================

Special4Icon1CategoryRegularSquareNo1=Blank
Special4Icon1CategoryRegularSquareNo2=Blank
Special4Icon1CategoryRegularSquareNo3=Blank
Special4Icon1CategoryRegularSquareNo4=Blank

Special4Icon2CategoryRegularSquareNo1=Blank
Special4Icon2CategoryRegularSquareNo2=Blank
Special4Icon2CategoryRegularSquareNo3=Blank
Special4Icon2CategoryRegularSquareNo4=Blank

Special4Icon3CategoryRegularSquareNo1=Blank
Special4Icon3CategoryRegularSquareNo2=Blank
Special4Icon3CategoryRegularSquareNo3=Blank
Special4Icon3CategoryRegularSquareNo4=Blank

Special4Icon4CategoryRegularSquareNo1=Blank
Special4Icon4CategoryRegularSquareNo2=Blank
Special4Icon4CategoryRegularSquareNo3=Blank
Special4Icon4CategoryRegularSquareNo4=Blank

Special4Icon5CategoryRegularSquareNo1=Blank
Special4Icon5CategoryRegularSquareNo2=Blank
Special4Icon5CategoryRegularSquareNo3=Blank
Special4Icon5CategoryRegularSquareNo4=Blank

Special4Icon1RegularSquareNo1=Blank
Special4Icon1RegularSquareNo2=Blank
Special4Icon1RegularSquareNo3=Blank
Special4Icon1RegularSquareNo4=Blank

Special4Icon2RegularSquareNo1=Blank
Special4Icon2RegularSquareNo2=Blank
Special4Icon2RegularSquareNo3=Blank
Special4Icon2RegularSquareNo4=Blank

Special4Icon3RegularSquareNo1=Blank
Special4Icon3RegularSquareNo2=Blank
Special4Icon3RegularSquareNo3=Blank
Special4Icon3RegularSquareNo4=Blank

Special4Icon4RegularSquareNo1=Blank
Special4Icon4RegularSquareNo2=Blank
Special4Icon4RegularSquareNo3=Blank
Special4Icon4RegularSquareNo4=Blank

Special4Icon5RegularSquareNo1=Blank
Special4Icon5RegularSquareNo2=Blank
Special4Icon5RegularSquareNo3=Blank
Special4Icon5RegularSquareNo4=Blank

Special4Icon1URLRegularSquareNo1=Blank
Special4Icon1URLRegularSquareNo2=Blank
Special4Icon1URLRegularSquareNo3=Blank
Special4Icon1URLRegularSquareNo4=Blank

Special4Icon2URLRegularSquareNo1=Blank
Special4Icon2URLRegularSquareNo2=Blank
Special4Icon2URLRegularSquareNo3=Blank
Special4Icon2URLRegularSquareNo4=Blank

Special4Icon3URLRegularSquareNo1=Blank
Special4Icon3URLRegularSquareNo2=Blank
Special4Icon3URLRegularSquareNo3=Blank
Special4Icon3URLRegularSquareNo4=Blank

Special4Icon4URLRegularSquareNo1=Blank
Special4Icon4URLRegularSquareNo2=Blank
Special4Icon4URLRegularSquareNo3=Blank
Special4Icon4URLRegularSquareNo4=Blank

Special4Icon5URLRegularSquareNo1=Blank
Special4Icon5URLRegularSquareNo2=Blank
Special4Icon5URLRegularSquareNo3=Blank
Special4Icon5URLRegularSquareNo4=Blank

Special4Icon1RegularSquareCode=Base
Special4Icon1RegularSquareColorType=Base
Special4Icon1RegularSquareChameleonName=Foreground 1
Special4Icon1RegularSquareChameleonHidden=1
Special4Icon1RegularSquareBase=255,255,255
Special4Icon1RegularSquareBaseHidden=0

Special4Icon2RegularSquareCode=Base
Special4Icon2RegularSquareColorType=Base
Special4Icon2RegularSquareChameleonName=Foreground 1
Special4Icon2RegularSquareChameleonHidden=1
Special4Icon2RegularSquareBase=255,255,255
Special4Icon2RegularSquareBaseHidden=0

Special4Icon3RegularSquareCode=Base
Special4Icon3RegularSquareColorType=Base
Special4Icon3RegularSquareChameleonName=Foreground 1
Special4Icon3RegularSquareChameleonHidden=1
Special4Icon3RegularSquareBase=255,255,255
Special4Icon3RegularSquareBaseHidden=0

Special4Icon4RegularSquareCode=Base
Special4Icon4RegularSquareColorType=Base
Special4Icon4RegularSquareChameleonName=Foreground 1
Special4Icon4RegularSquareChameleonHidden=1
Special4Icon4RegularSquareBase=255,255,255
Special4Icon4RegularSquareBaseHidden=0

Special4Icon5RegularSquareCode=Base
Special4Icon5RegularSquareColorType=Base
Special4Icon5RegularSquareChameleonName=Foreground 1
Special4Icon5RegularSquareChameleonHidden=1
Special4Icon5RegularSquareBase=255,255,255
Special4Icon5RegularSquareBaseHidden=0

; ============================================================
; ============================================================

Special5Icon1CategoryRegularSquareNo1=Blank
Special5Icon1CategoryRegularSquareNo2=Blank
Special5Icon1CategoryRegularSquareNo3=Blank
Special5Icon1CategoryRegularSquareNo4=Blank
Special5Icon1CategoryRegularSquareNo5=Blank

Special5Icon2CategoryRegularSquareNo1=Blank
Special5Icon2CategoryRegularSquareNo2=Blank
Special5Icon2CategoryRegularSquareNo3=Blank
Special5Icon2CategoryRegularSquareNo4=Blank
Special5Icon2CategoryRegularSquareNo5=Blank

Special5Icon3CategoryRegularSquareNo1=Blank
Special5Icon3CategoryRegularSquareNo2=Blank
Special5Icon3CategoryRegularSquareNo3=Blank
Special5Icon3CategoryRegularSquareNo4=Blank
Special5Icon3CategoryRegularSquareNo5=Blank

Special5Icon4CategoryRegularSquareNo1=Blank
Special5Icon4CategoryRegularSquareNo2=Blank
Special5Icon4CategoryRegularSquareNo3=Blank
Special5Icon4CategoryRegularSquareNo4=Blank
Special5Icon4CategoryRegularSquareNo5=Blank

Special5Icon5CategoryRegularSquareNo1=Blank
Special5Icon5CategoryRegularSquareNo2=Blank
Special5Icon5CategoryRegularSquareNo3=Blank
Special5Icon5CategoryRegularSquareNo4=Blank
Special5Icon5CategoryRegularSquareNo5=Blank

Special5Icon1RegularSquareNo1=Blank
Special5Icon1RegularSquareNo2=Blank
Special5Icon1RegularSquareNo3=Blank
Special5Icon1RegularSquareNo4=Blank
Special5Icon1RegularSquareNo5=Blank

Special5Icon2RegularSquareNo1=Blank
Special5Icon2RegularSquareNo2=Blank
Special5Icon2RegularSquareNo3=Blank
Special5Icon2RegularSquareNo4=Blank
Special5Icon2RegularSquareNo5=Blank

Special5Icon3RegularSquareNo1=Blank
Special5Icon3RegularSquareNo2=Blank
Special5Icon3RegularSquareNo3=Blank
Special5Icon3RegularSquareNo4=Blank
Special5Icon3RegularSquareNo5=Blank

Special5Icon4RegularSquareNo1=Blank
Special5Icon4RegularSquareNo2=Blank
Special5Icon4RegularSquareNo3=Blank
Special5Icon4RegularSquareNo4=Blank
Special5Icon4RegularSquareNo5=Blank

Special5Icon5RegularSquareNo1=Blank
Special5Icon5RegularSquareNo2=Blank
Special5Icon5RegularSquareNo3=Blank
Special5Icon5RegularSquareNo4=Blank
Special5Icon5RegularSquareNo5=Blank

Special5Icon1URLRegularSquareNo1=Blank
Special5Icon1URLRegularSquareNo2=Blank
Special5Icon1URLRegularSquareNo3=Blank
Special5Icon1URLRegularSquareNo4=Blank
Special5Icon1URLRegularSquareNo5=Blank

Special5Icon2URLRegularSquareNo1=Blank
Special5Icon2URLRegularSquareNo2=Blank
Special5Icon2URLRegularSquareNo3=Blank
Special5Icon2URLRegularSquareNo4=Blank
Special5Icon2URLRegularSquareNo5=Blank

Special5Icon3URLRegularSquareNo1=Blank
Special5Icon3URLRegularSquareNo2=Blank
Special5Icon3URLRegularSquareNo3=Blank
Special5Icon3URLRegularSquareNo4=Blank
Special5Icon3URLRegularSquareNo5=Blank

Special5Icon4URLRegularSquareNo1=Blank
Special5Icon4URLRegularSquareNo2=Blank
Special5Icon4URLRegularSquareNo3=Blank
Special5Icon4URLRegularSquareNo4=Blank
Special5Icon4URLRegularSquareNo5=Blank

Special5Icon5URLRegularSquareNo1=Blank
Special5Icon5URLRegularSquareNo2=Blank
Special5Icon5URLRegularSquareNo3=Blank
Special5Icon5URLRegularSquareNo4=Blank
Special5Icon5URLRegularSquareNo5=Blank

Special5Icon1RegularSquareCode=Base
Special5Icon1RegularSquareColorType=Base
Special5Icon1RegularSquareChameleonName=Foreground 1
Special5Icon1RegularSquareChameleonHidden=1
Special5Icon1RegularSquareBase=255,255,255
Special5Icon1RegularSquareBaseHidden=0

Special5Icon2RegularSquareCode=Base
Special5Icon2RegularSquareColorType=Base
Special5Icon2RegularSquareChameleonName=Foreground 1
Special5Icon2RegularSquareChameleonHidden=1
Special5Icon2RegularSquareBase=255,255,255
Special5Icon2RegularSquareBaseHidden=0

Special5Icon3RegularSquareCode=Base
Special5Icon3RegularSquareColorType=Base
Special5Icon3RegularSquareChameleonName=Foreground 1
Special5Icon3RegularSquareChameleonHidden=1
Special5Icon3RegularSquareBase=255,255,255
Special5Icon3RegularSquareBaseHidden=0

Special5Icon4RegularSquareCode=Base
Special5Icon4RegularSquareColorType=Base
Special5Icon4RegularSquareChameleonName=Foreground 1
Special5Icon4RegularSquareChameleonHidden=1
Special5Icon4RegularSquareBase=255,255,255
Special5Icon4RegularSquareBaseHidden=0

Special5Icon5RegularSquareCode=Base
Special5Icon5RegularSquareColorType=Base
Special5Icon5RegularSquareChameleonName=Foreground 1
Special5Icon5RegularSquareChameleonHidden=1
Special5Icon5RegularSquareBase=255,255,255
Special5Icon5RegularSquareBaseHidden=0
SpecSetIconShape=1

; ============================================================
; ============================================================
; ============================================================
; ============================================================
