[MeterMask1]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType#DashedHexagon#Special7Icon4DashedHexagonCode#Style
X=237
Y=74

[MeterMask2]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType#DashedHexagon#Special7Icon4DashedHexagonCode#Style
X=313
Y=74

[MeterMask3]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType#DashedHexagon#Special7Icon4DashedHexagonCode#Style
X=199
Y=139

[MeterMask4]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType#DashedHexagon#Special7Icon4DashedHexagonCode#Style
X=275
Y=139

[MeterMask5]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType#DashedHexagon#Special7Icon4DashedHexagonCode#Style
X=351
Y=139

[MeterMask6]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType#DashedHexagon#Special7Icon4DashedHexagonCode#Style
X=237
Y=204

[MeterMask7]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType#DashedHexagon#Special7Icon4DashedHexagonCode#Style
X=313
Y=204

[MeterIcon1Base]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType##Special7Icon4CategoryDashedHexagonNo1##Special7Icon4DashedHexagonCode#Style
ImageName=#Special7Icon4DashedHexagonNo1#.png
ImageTint=#Special7Icon4DashedHexagonBase#
Container=MeterMask1
Hidden=#Special7Icon4DashedHexagonBaseHidden#

[MeterIcon2Base]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType##Special7Icon4CategoryDashedHexagonNo2##Special7Icon4DashedHexagonCode#Style
ImageName=#Special7Icon4DashedHexagonNo2#.png
ImageTint=#Special7Icon4DashedHexagonBase#
Container=MeterMask2
Hidden=#Special7Icon4DashedHexagonBaseHidden#

[MeterIcon3Base]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType##Special7Icon4CategoryDashedHexagonNo3##Special7Icon4DashedHexagonCode#Style
ImageName=#Special7Icon4DashedHexagonNo3#.png
ImageTint=#Special7Icon4DashedHexagonBase#
Container=MeterMask3
Hidden=#Special7Icon4DashedHexagonBaseHidden#

[MeterIcon4Base]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType##Special7Icon4CategoryDashedHexagonNo4##Special7Icon4DashedHexagonCode#Style
ImageName=#Special7Icon4DashedHexagonNo4#.png
ImageTint=#Special7Icon4DashedHexagonBase#
Container=MeterMask4
Hidden=#Special7Icon4DashedHexagonBaseHidden#

[MeterIcon5Base]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType##Special7Icon4CategoryDashedHexagonNo5##Special7Icon4DashedHexagonCode#Style
ImageName=#Special7Icon4DashedHexagonNo5#.png
ImageTint=#Special7Icon4DashedHexagonBase#
Container=MeterMask5
Hidden=#Special7Icon4DashedHexagonBaseHidden#

[MeterIcon6Base]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType##Special7Icon4CategoryDashedHexagonNo6##Special7Icon4DashedHexagonCode#Style
ImageName=#Special7Icon4DashedHexagonNo6#.png
ImageTint=#Special7Icon4DashedHexagonBase#
Container=MeterMask6
Hidden=#Special7Icon4DashedHexagonBaseHidden#

[MeterIcon7Base]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType##Special7Icon4CategoryDashedHexagonNo7##Special7Icon4DashedHexagonCode#Style
ImageName=#Special7Icon4DashedHexagonNo7#.png
ImageTint=#Special7Icon4DashedHexagonBase#
Container=MeterMask7
Hidden=#Special7Icon4DashedHexagonBaseHidden#

[MeterIcon1Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType##Special7Icon4CategoryDashedHexagonNo1##Special7Icon4DashedHexagonCode#Style
ImageName=#Special7Icon4DashedHexagonNo1#.png
ImageTint=[Desktop#Special7Icon4DashedHexagonCode#]
Container=MeterMask1
Hidden=#Special7Icon4DashedHexagonChameleonHidden#

[MeterIcon2Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType##Special7Icon4CategoryDashedHexagonNo2##Special7Icon4DashedHexagonCode#Style
ImageName=#Special7Icon4DashedHexagonNo2#.png
ImageTint=[Desktop#Special7Icon4DashedHexagonCode#]
Container=MeterMask2
Hidden=#Special7Icon4DashedHexagonChameleonHidden#

[MeterIcon3Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType##Special7Icon4CategoryDashedHexagonNo3##Special7Icon4DashedHexagonCode#Style
ImageName=#Special7Icon4DashedHexagonNo3#.png
ImageTint=[Desktop#Special7Icon4DashedHexagonCode#]
Container=MeterMask3
Hidden=#Special7Icon4DashedHexagonChameleonHidden#

[MeterIcon4Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType##Special7Icon4CategoryDashedHexagonNo4##Special7Icon4DashedHexagonCode#Style
ImageName=#Special7Icon4DashedHexagonNo4#.png
ImageTint=[Desktop#Special7Icon4DashedHexagonCode#]
Container=MeterMask4
Hidden=#Special7Icon4DashedHexagonChameleonHidden#

[MeterIcon5Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType##Special7Icon4CategoryDashedHexagonNo5##Special7Icon4DashedHexagonCode#Style
ImageName=#Special7Icon4DashedHexagonNo5#.png
ImageTint=[Desktop#Special7Icon4DashedHexagonCode#]
Container=MeterMask5
Hidden=#Special7Icon4DashedHexagonChameleonHidden#

[MeterIcon6Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType##Special7Icon4CategoryDashedHexagonNo6##Special7Icon4DashedHexagonCode#Style
ImageName=#Special7Icon4DashedHexagonNo6#.png
ImageTint=[Desktop#Special7Icon4DashedHexagonCode#]
Container=MeterMask6
Hidden=#Special7Icon4DashedHexagonChameleonHidden#

[MeterIcon7Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon4DashedHexagonColorType##Special7Icon4CategoryDashedHexagonNo7##Special7Icon4DashedHexagonCode#Style
ImageName=#Special7Icon4DashedHexagonNo7#.png
ImageTint=[Desktop#Special7Icon4DashedHexagonCode#]
Container=MeterMask7
Hidden=#Special7Icon4DashedHexagonChameleonHidden#

[MeterSetIcon1Text]
Meter=String
MeterStyle=SpecailSetIconText
X=750
Y=170
Text="Icon 1:"

[MeterSetIcon2Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 2:"

[MeterSetIcon3Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 3:"

[MeterSetIcon4Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 4:"

[MeterSetIcon5Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 5:"

[MeterSetIcon6Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 6:"

[MeterSetIcon7Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 7:"

[MeterSetIcon1Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=775
Y=[MeterSetIcon1Text:Y]
Text=#Special7Icon4DashedHexagonNo1#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Dashed Hexagon\7 Icons\Icon #4" "Set Icon #1.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "1" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon1('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon4DashedHexagonOver1()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon1('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon4DashedHexagonLeave1()"]

[MeterSetIcon2Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon4DashedHexagonNo2#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Dashed Hexagon\7 Icons\Icon #4" "Set Icon #2.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "2" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon2('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon4DashedHexagonOver2()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon2('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon4DashedHexagonLeave2()"]

[MeterSetIcon3Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon4DashedHexagonNo3#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Dashed Hexagon\7 Icons\Icon #4" "Set Icon #3.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "3" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon3('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon4DashedHexagonOver3()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon3('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon4DashedHexagonLeave3()"]

[MeterSetIcon4Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon4DashedHexagonNo4#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Dashed Hexagon\7 Icons\Icon #4" "Set Icon #4.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "4" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon4('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon4DashedHexagonOver4()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon4('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon4DashedHexagonLeave4()"]

[MeterSetIcon5Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon4DashedHexagonNo5#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Dashed Hexagon\7 Icons\Icon #4" "Set Icon #5.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "5" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon5('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon4DashedHexagonOver5()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon5('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon4DashedHexagonLeave5()"]

[MeterSetIcon6Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon4DashedHexagonNo6#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Dashed Hexagon\7 Icons\Icon #4" "Set Icon #6.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "6" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon6('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon4DashedHexagonOver6()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon6('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon4DashedHexagonLeave6()"]

[MeterSetIcon7Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon4DashedHexagonNo7#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Dashed Hexagon\7 Icons\Icon #4" "Set Icon #7.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "7" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon7('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon4DashedHexagonOver7()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon7('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon4DashedHexagonLeave7()"]

; ============================================================

[MeterColor]
Meter=String
MeterStyle=IconText
X=200
Y=460
Text=Color Tint

[MeterColorActive]
Meter=String
MeterStyle=IconActive
X=0r
Y=5R
Text=#Special7Icon4DashedHexagonBase#
LeftMouseUpAction=[!CommandMeasure LuaSpecial "setSpecial7Icon4DashedHexagonBase()"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialBase('Over')"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialBase('Leave')"]

[MeterChameleon]
Meter=String
MeterStyle=IconText
X=440
Y=460
Text=Chameleon Tint

[MeterChameleonActive]
Meter=String
MeterStyle=IconActive
X=0r
Y=5R
Text=#Special7Icon4DashedHexagonChameleonName#
LeftMouseUpAction=[!ToggleConfig "#ROOTCONFIG#\Context\Special\Chameleon\Dashed Hexagon\7 Icons" "Icon #1.ini"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialChameleon('Over')"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialChameleon('Leave')"]

; ============================================================
; ============================================================

[MeterSkinSpecial7Icon4DashedHexagonBase]
Measure=Plugin
Plugin=InputText
StringAlign=Center
FontFace=Segoe UI
FontSize=15
X=132
Y=480
W=140
H=30
AntiAlias=1
FocusDismiss=1
Command1=[!WriteKeyValue Variables Special7Icon4DashedHexagonBase "$UserInput$" "#@#Special Variables.inc"][!RefreshGroup ShapeSettings]
DefaultValue="#Special7Icon4DashedHexagonBase#"
