[MeterMask1]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType#AlterHexagon#Special7Icon2AlterHexagonCode#Style
X=237
Y=74

[MeterMask2]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType#AlterHexagon#Special7Icon2AlterHexagonCode#Style
X=313
Y=74

[MeterMask3]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType#AlterHexagon#Special7Icon2AlterHexagonCode#Style
X=199
Y=139

[MeterMask4]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType#AlterHexagon#Special7Icon2AlterHexagonCode#Style
X=275
Y=139

[MeterMask5]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType#AlterHexagon#Special7Icon2AlterHexagonCode#Style
X=351
Y=139

[MeterMask6]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType#AlterHexagon#Special7Icon2AlterHexagonCode#Style
X=237
Y=204

[MeterMask7]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType#AlterHexagon#Special7Icon2AlterHexagonCode#Style
X=313
Y=204

[MeterIcon1Base]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType##Special7Icon2CategoryAlterHexagonNo1##Special7Icon2AlterHexagonCode#Style
ImageName=#Special7Icon2AlterHexagonNo1#.png
ImageTint=#Special7Icon2AlterHexagonBase#
Container=MeterMask1
Hidden=#Special7Icon2AlterHexagonBaseHidden#

[MeterIcon2Base]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType##Special7Icon2CategoryAlterHexagonNo2##Special7Icon2AlterHexagonCode#Style
ImageName=#Special7Icon2AlterHexagonNo2#.png
ImageTint=#Special7Icon2AlterHexagonBase#
Container=MeterMask2
Hidden=#Special7Icon2AlterHexagonBaseHidden#

[MeterIcon3Base]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType##Special7Icon2CategoryAlterHexagonNo3##Special7Icon2AlterHexagonCode#Style
ImageName=#Special7Icon2AlterHexagonNo3#.png
ImageTint=#Special7Icon2AlterHexagonBase#
Container=MeterMask3
Hidden=#Special7Icon2AlterHexagonBaseHidden#

[MeterIcon4Base]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType##Special7Icon2CategoryAlterHexagonNo4##Special7Icon2AlterHexagonCode#Style
ImageName=#Special7Icon2AlterHexagonNo4#.png
ImageTint=#Special7Icon2AlterHexagonBase#
Container=MeterMask4
Hidden=#Special7Icon2AlterHexagonBaseHidden#

[MeterIcon5Base]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType##Special7Icon2CategoryAlterHexagonNo5##Special7Icon2AlterHexagonCode#Style
ImageName=#Special7Icon2AlterHexagonNo5#.png
ImageTint=#Special7Icon2AlterHexagonBase#
Container=MeterMask5
Hidden=#Special7Icon2AlterHexagonBaseHidden#

[MeterIcon6Base]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType##Special7Icon2CategoryAlterHexagonNo6##Special7Icon2AlterHexagonCode#Style
ImageName=#Special7Icon2AlterHexagonNo6#.png
ImageTint=#Special7Icon2AlterHexagonBase#
Container=MeterMask6
Hidden=#Special7Icon2AlterHexagonBaseHidden#

[MeterIcon7Base]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType##Special7Icon2CategoryAlterHexagonNo7##Special7Icon2AlterHexagonCode#Style
ImageName=#Special7Icon2AlterHexagonNo7#.png
ImageTint=#Special7Icon2AlterHexagonBase#
Container=MeterMask7
Hidden=#Special7Icon2AlterHexagonBaseHidden#

[MeterIcon1Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType##Special7Icon2CategoryAlterHexagonNo1##Special7Icon2AlterHexagonCode#Style
ImageName=#Special7Icon2AlterHexagonNo1#.png
ImageTint=[Desktop#Special7Icon2AlterHexagonCode#]
Container=MeterMask1
Hidden=#Special7Icon2AlterHexagonChameleonHidden#

[MeterIcon2Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType##Special7Icon2CategoryAlterHexagonNo2##Special7Icon2AlterHexagonCode#Style
ImageName=#Special7Icon2AlterHexagonNo2#.png
ImageTint=[Desktop#Special7Icon2AlterHexagonCode#]
Container=MeterMask2
Hidden=#Special7Icon2AlterHexagonChameleonHidden#

[MeterIcon3Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType##Special7Icon2CategoryAlterHexagonNo3##Special7Icon2AlterHexagonCode#Style
ImageName=#Special7Icon2AlterHexagonNo3#.png
ImageTint=[Desktop#Special7Icon2AlterHexagonCode#]
Container=MeterMask3
Hidden=#Special7Icon2AlterHexagonChameleonHidden#

[MeterIcon4Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType##Special7Icon2CategoryAlterHexagonNo4##Special7Icon2AlterHexagonCode#Style
ImageName=#Special7Icon2AlterHexagonNo4#.png
ImageTint=[Desktop#Special7Icon2AlterHexagonCode#]
Container=MeterMask4
Hidden=#Special7Icon2AlterHexagonChameleonHidden#

[MeterIcon5Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType##Special7Icon2CategoryAlterHexagonNo5##Special7Icon2AlterHexagonCode#Style
ImageName=#Special7Icon2AlterHexagonNo5#.png
ImageTint=[Desktop#Special7Icon2AlterHexagonCode#]
Container=MeterMask5
Hidden=#Special7Icon2AlterHexagonChameleonHidden#

[MeterIcon6Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType##Special7Icon2CategoryAlterHexagonNo6##Special7Icon2AlterHexagonCode#Style
ImageName=#Special7Icon2AlterHexagonNo6#.png
ImageTint=[Desktop#Special7Icon2AlterHexagonCode#]
Container=MeterMask6
Hidden=#Special7Icon2AlterHexagonChameleonHidden#

[MeterIcon7Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon2AlterHexagonColorType##Special7Icon2CategoryAlterHexagonNo7##Special7Icon2AlterHexagonCode#Style
ImageName=#Special7Icon2AlterHexagonNo7#.png
ImageTint=[Desktop#Special7Icon2AlterHexagonCode#]
Container=MeterMask7
Hidden=#Special7Icon2AlterHexagonChameleonHidden#

[MeterSetIcon1Text]
Meter=String
MeterStyle=SpecailSetIconText
X=750
Y=170
Text="Icon 1:"

[MeterSetIcon2Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 2:"

[MeterSetIcon3Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 3:"

[MeterSetIcon4Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 4:"

[MeterSetIcon5Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 5:"

[MeterSetIcon6Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 6:"

[MeterSetIcon7Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 7:"

[MeterSetIcon1Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=775
Y=[MeterSetIcon1Text:Y]
Text=#Special7Icon2AlterHexagonNo1#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Alter Hexagon\7 Icons\Icon #2" "Set Icon #1.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "1" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon1('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2AlterHexagonOver1()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon1('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2AlterHexagonLeave1()"]

[MeterSetIcon2Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon2AlterHexagonNo2#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Alter Hexagon\7 Icons\Icon #2" "Set Icon #2.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "2" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon2('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2AlterHexagonOver2()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon2('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2AlterHexagonLeave2()"]

[MeterSetIcon3Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon2AlterHexagonNo3#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Alter Hexagon\7 Icons\Icon #2" "Set Icon #3.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "3" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon3('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2AlterHexagonOver3()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon3('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2AlterHexagonLeave3()"]

[MeterSetIcon4Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon2AlterHexagonNo4#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Alter Hexagon\7 Icons\Icon #2" "Set Icon #4.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "4" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon4('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2AlterHexagonOver4()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon4('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2AlterHexagonLeave4()"]

[MeterSetIcon5Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon2AlterHexagonNo5#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Alter Hexagon\7 Icons\Icon #2" "Set Icon #5.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "5" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon5('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2AlterHexagonOver5()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon5('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2AlterHexagonLeave5()"]

[MeterSetIcon6Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon2AlterHexagonNo6#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Alter Hexagon\7 Icons\Icon #2" "Set Icon #6.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "6" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon6('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2AlterHexagonOver6()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon6('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2AlterHexagonLeave6()"]

[MeterSetIcon7Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon2AlterHexagonNo7#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Alter Hexagon\7 Icons\Icon #2" "Set Icon #7.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "7" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon7('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2AlterHexagonOver7()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon7('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2AlterHexagonLeave7()"]

; ============================================================

[MeterColor]
Meter=String
MeterStyle=IconText
X=200
Y=460
Text=Color Tint

[MeterColorActive]
Meter=String
MeterStyle=IconActive
X=0r
Y=5R
Text=#Special7Icon2AlterHexagonBase#
LeftMouseUpAction=[!CommandMeasure LuaSpecial "setSpecial7Icon2AlterHexagonBase()"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialBase('Over')"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialBase('Leave')"]

[MeterChameleon]
Meter=String
MeterStyle=IconText
X=440
Y=460
Text=Chameleon Tint

[MeterChameleonActive]
Meter=String
MeterStyle=IconActive
X=0r
Y=5R
Text=#Special7Icon2AlterHexagonChameleonName#
LeftMouseUpAction=[!ToggleConfig "#ROOTCONFIG#\Context\Special\Chameleon\Alter Hexagon\7 Icons" "Icon #2.ini"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialChameleon('Over')"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialChameleon('Leave')"]

; ============================================================
; ============================================================

[MeterSkinSpecial7Icon2AlterHexagonBase]
Measure=Plugin
Plugin=InputText
StringAlign=Center
FontFace=Segoe UI
FontSize=15
X=132
Y=480
W=140
H=30
AntiAlias=1
FocusDismiss=1
Command1=[!WriteKeyValue Variables Special7Icon2AlterHexagonBase "$UserInput$" "#@#Special Variables.inc"][!RefreshGroup ShapeSettings]
DefaultValue="#Special7Icon2AlterHexagonBase#"
