[MeterMask1]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType#AlterHexagon#Special7Icon5AlterHexagonCode#Style
X=237
Y=74

[MeterMask2]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType#AlterHexagon#Special7Icon5AlterHexagonCode#Style
X=313
Y=74

[MeterMask3]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType#AlterHexagon#Special7Icon5AlterHexagonCode#Style
X=199
Y=139

[MeterMask4]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType#AlterHexagon#Special7Icon5AlterHexagonCode#Style
X=275
Y=139

[MeterMask5]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType#AlterHexagon#Special7Icon5AlterHexagonCode#Style
X=351
Y=139

[MeterMask6]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType#AlterHexagon#Special7Icon5AlterHexagonCode#Style
X=237
Y=204

[MeterMask7]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType#AlterHexagon#Special7Icon5AlterHexagonCode#Style
X=313
Y=204

[MeterIcon1Base]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType##Special7Icon5CategoryAlterHexagonNo1##Special7Icon5AlterHexagonCode#Style
ImageName=#Special7Icon5AlterHexagonNo1#.png
ImageTint=#Special7Icon5AlterHexagonBase#
Container=MeterMask1
Hidden=#Special7Icon5AlterHexagonBaseHidden#

[MeterIcon2Base]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType##Special7Icon5CategoryAlterHexagonNo2##Special7Icon5AlterHexagonCode#Style
ImageName=#Special7Icon5AlterHexagonNo2#.png
ImageTint=#Special7Icon5AlterHexagonBase#
Container=MeterMask2
Hidden=#Special7Icon5AlterHexagonBaseHidden#

[MeterIcon3Base]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType##Special7Icon5CategoryAlterHexagonNo3##Special7Icon5AlterHexagonCode#Style
ImageName=#Special7Icon5AlterHexagonNo3#.png
ImageTint=#Special7Icon5AlterHexagonBase#
Container=MeterMask3
Hidden=#Special7Icon5AlterHexagonBaseHidden#

[MeterIcon4Base]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType##Special7Icon5CategoryAlterHexagonNo4##Special7Icon5AlterHexagonCode#Style
ImageName=#Special7Icon5AlterHexagonNo4#.png
ImageTint=#Special7Icon5AlterHexagonBase#
Container=MeterMask4
Hidden=#Special7Icon5AlterHexagonBaseHidden#

[MeterIcon5Base]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType##Special7Icon5CategoryAlterHexagonNo5##Special7Icon5AlterHexagonCode#Style
ImageName=#Special7Icon5AlterHexagonNo5#.png
ImageTint=#Special7Icon5AlterHexagonBase#
Container=MeterMask5
Hidden=#Special7Icon5AlterHexagonBaseHidden#

[MeterIcon6Base]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType##Special7Icon5CategoryAlterHexagonNo6##Special7Icon5AlterHexagonCode#Style
ImageName=#Special7Icon5AlterHexagonNo6#.png
ImageTint=#Special7Icon5AlterHexagonBase#
Container=MeterMask6
Hidden=#Special7Icon5AlterHexagonBaseHidden#

[MeterIcon7Base]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType##Special7Icon5CategoryAlterHexagonNo7##Special7Icon5AlterHexagonCode#Style
ImageName=#Special7Icon5AlterHexagonNo7#.png
ImageTint=#Special7Icon5AlterHexagonBase#
Container=MeterMask7
Hidden=#Special7Icon5AlterHexagonBaseHidden#

[MeterIcon1Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType##Special7Icon5CategoryAlterHexagonNo1##Special7Icon5AlterHexagonCode#Style
ImageName=#Special7Icon5AlterHexagonNo1#.png
ImageTint=[Desktop#Special7Icon5AlterHexagonCode#]
Container=MeterMask1
Hidden=#Special7Icon5AlterHexagonChameleonHidden#

[MeterIcon2Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType##Special7Icon5CategoryAlterHexagonNo2##Special7Icon5AlterHexagonCode#Style
ImageName=#Special7Icon5AlterHexagonNo2#.png
ImageTint=[Desktop#Special7Icon5AlterHexagonCode#]
Container=MeterMask2
Hidden=#Special7Icon5AlterHexagonChameleonHidden#

[MeterIcon3Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType##Special7Icon5CategoryAlterHexagonNo3##Special7Icon5AlterHexagonCode#Style
ImageName=#Special7Icon5AlterHexagonNo3#.png
ImageTint=[Desktop#Special7Icon5AlterHexagonCode#]
Container=MeterMask3
Hidden=#Special7Icon5AlterHexagonChameleonHidden#

[MeterIcon4Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType##Special7Icon5CategoryAlterHexagonNo4##Special7Icon5AlterHexagonCode#Style
ImageName=#Special7Icon5AlterHexagonNo4#.png
ImageTint=[Desktop#Special7Icon5AlterHexagonCode#]
Container=MeterMask4
Hidden=#Special7Icon5AlterHexagonChameleonHidden#

[MeterIcon5Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType##Special7Icon5CategoryAlterHexagonNo5##Special7Icon5AlterHexagonCode#Style
ImageName=#Special7Icon5AlterHexagonNo5#.png
ImageTint=[Desktop#Special7Icon5AlterHexagonCode#]
Container=MeterMask5
Hidden=#Special7Icon5AlterHexagonChameleonHidden#

[MeterIcon6Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType##Special7Icon5CategoryAlterHexagonNo6##Special7Icon5AlterHexagonCode#Style
ImageName=#Special7Icon5AlterHexagonNo6#.png
ImageTint=[Desktop#Special7Icon5AlterHexagonCode#]
Container=MeterMask6
Hidden=#Special7Icon5AlterHexagonChameleonHidden#

[MeterIcon7Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon5AlterHexagonColorType##Special7Icon5CategoryAlterHexagonNo7##Special7Icon5AlterHexagonCode#Style
ImageName=#Special7Icon5AlterHexagonNo7#.png
ImageTint=[Desktop#Special7Icon5AlterHexagonCode#]
Container=MeterMask7
Hidden=#Special7Icon5AlterHexagonChameleonHidden#

[MeterSetIcon1Text]
Meter=String
MeterStyle=SpecailSetIconText
X=750
Y=170
Text="Icon 1:"

[MeterSetIcon2Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 2:"

[MeterSetIcon3Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 3:"

[MeterSetIcon4Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 4:"

[MeterSetIcon5Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 5:"

[MeterSetIcon6Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 6:"

[MeterSetIcon7Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 7:"

[MeterSetIcon1Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=775
Y=[MeterSetIcon1Text:Y]
Text=#Special7Icon5AlterHexagonNo1#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Alter Hexagon\7 Icons\Icon #5" "Set Icon #1.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "1" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon1('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon5AlterHexagonOver1()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon1('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon5AlterHexagonLeave1()"]

[MeterSetIcon2Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon5AlterHexagonNo2#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Alter Hexagon\7 Icons\Icon #5" "Set Icon #2.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "2" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon2('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon5AlterHexagonOver2()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon2('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon5AlterHexagonLeave2()"]

[MeterSetIcon3Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon5AlterHexagonNo3#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Alter Hexagon\7 Icons\Icon #5" "Set Icon #3.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "3" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon3('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon5AlterHexagonOver3()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon3('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon5AlterHexagonLeave3()"]

[MeterSetIcon4Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon5AlterHexagonNo4#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Alter Hexagon\7 Icons\Icon #5" "Set Icon #4.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "4" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon4('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon5AlterHexagonOver4()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon4('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon5AlterHexagonLeave4()"]

[MeterSetIcon5Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon5AlterHexagonNo5#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Alter Hexagon\7 Icons\Icon #5" "Set Icon #5.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "5" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon5('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon5AlterHexagonOver5()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon5('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon5AlterHexagonLeave5()"]

[MeterSetIcon6Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon5AlterHexagonNo6#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Alter Hexagon\7 Icons\Icon #5" "Set Icon #6.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "6" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon6('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon5AlterHexagonOver6()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon6('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon5AlterHexagonLeave6()"]

[MeterSetIcon7Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon5AlterHexagonNo7#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Alter Hexagon\7 Icons\Icon #5" "Set Icon #7.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "7" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon7('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon5AlterHexagonOver7()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon7('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon5AlterHexagonLeave7()"]

; ============================================================

[MeterColor]
Meter=String
MeterStyle=IconText
X=200
Y=460
Text=Color Tint

[MeterColorActive]
Meter=String
MeterStyle=IconActive
X=0r
Y=5R
Text=#Special7Icon5AlterHexagonBase#
LeftMouseUpAction=[!CommandMeasure LuaSpecial "setSpecial7Icon5AlterHexagonBase()"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialBase('Over')"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialBase('Leave')"]

[MeterChameleon]
Meter=String
MeterStyle=IconText
X=440
Y=460
Text=Chameleon Tint

[MeterChameleonActive]
Meter=String
MeterStyle=IconActive
X=0r
Y=5R
Text=#Special7Icon5AlterHexagonChameleonName#
LeftMouseUpAction=[!ToggleConfig "#ROOTCONFIG#\Context\Special\Chameleon\Alter Hexagon\7 Icons" "Icon #1.ini"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialChameleon('Over')"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialChameleon('Leave')"]

; ============================================================
; ============================================================

[MeterSkinSpecial7Icon5AlterHexagonBase]
Measure=Plugin
Plugin=InputText
StringAlign=Center
FontFace=Segoe UI
FontSize=15
X=132
Y=480
W=140
H=30
AntiAlias=1
FocusDismiss=1
Command1=[!WriteKeyValue Variables Special7Icon5AlterHexagonBase "$UserInput$" "#@#Special Variables.inc"][!RefreshGroup ShapeSettings]
DefaultValue="#Special7Icon5AlterHexagonBase#"
