[MeterMask1]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType#RegularHexagon#Special7Icon2RegularHexagonCode#Style
X=237
Y=74

[MeterMask2]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType#RegularHexagon#Special7Icon2RegularHexagonCode#Style
X=313
Y=74

[MeterMask3]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType#RegularHexagon#Special7Icon2RegularHexagonCode#Style
X=199
Y=139

[MeterMask4]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType#RegularHexagon#Special7Icon2RegularHexagonCode#Style
X=275
Y=139

[MeterMask5]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType#RegularHexagon#Special7Icon2RegularHexagonCode#Style
X=351
Y=139

[MeterMask6]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType#RegularHexagon#Special7Icon2RegularHexagonCode#Style
X=237
Y=204

[MeterMask7]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType#RegularHexagon#Special7Icon2RegularHexagonCode#Style
X=313
Y=204

[MeterIcon1Base]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType##Special7Icon2CategoryRegularHexagonNo1##Special7Icon2RegularHexagonCode#Style
ImageName=#Special7Icon2RegularHexagonNo1#.png
ImageTint=#Special7Icon2RegularHexagonBase#
Container=MeterMask1
Hidden=#Special7Icon2RegularHexagonBaseHidden#

[MeterIcon2Base]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType##Special7Icon2CategoryRegularHexagonNo2##Special7Icon2RegularHexagonCode#Style
ImageName=#Special7Icon2RegularHexagonNo2#.png
ImageTint=#Special7Icon2RegularHexagonBase#
Container=MeterMask2
Hidden=#Special7Icon2RegularHexagonBaseHidden#

[MeterIcon3Base]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType##Special7Icon2CategoryRegularHexagonNo3##Special7Icon2RegularHexagonCode#Style
ImageName=#Special7Icon2RegularHexagonNo3#.png
ImageTint=#Special7Icon2RegularHexagonBase#
Container=MeterMask3
Hidden=#Special7Icon2RegularHexagonBaseHidden#

[MeterIcon4Base]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType##Special7Icon2CategoryRegularHexagonNo4##Special7Icon2RegularHexagonCode#Style
ImageName=#Special7Icon2RegularHexagonNo4#.png
ImageTint=#Special7Icon2RegularHexagonBase#
Container=MeterMask4
Hidden=#Special7Icon2RegularHexagonBaseHidden#

[MeterIcon5Base]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType##Special7Icon2CategoryRegularHexagonNo5##Special7Icon2RegularHexagonCode#Style
ImageName=#Special7Icon2RegularHexagonNo5#.png
ImageTint=#Special7Icon2RegularHexagonBase#
Container=MeterMask5
Hidden=#Special7Icon2RegularHexagonBaseHidden#

[MeterIcon6Base]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType##Special7Icon2CategoryRegularHexagonNo6##Special7Icon2RegularHexagonCode#Style
ImageName=#Special7Icon2RegularHexagonNo6#.png
ImageTint=#Special7Icon2RegularHexagonBase#
Container=MeterMask6
Hidden=#Special7Icon2RegularHexagonBaseHidden#

[MeterIcon7Base]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType##Special7Icon2CategoryRegularHexagonNo7##Special7Icon2RegularHexagonCode#Style
ImageName=#Special7Icon2RegularHexagonNo7#.png
ImageTint=#Special7Icon2RegularHexagonBase#
Container=MeterMask7
Hidden=#Special7Icon2RegularHexagonBaseHidden#

[MeterIcon1Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType##Special7Icon2CategoryRegularHexagonNo1##Special7Icon2RegularHexagonCode#Style
ImageName=#Special7Icon2RegularHexagonNo1#.png
ImageTint=[Desktop#Special7Icon2RegularHexagonCode#]
Container=MeterMask1
Hidden=#Special7Icon2RegularHexagonChameleonHidden#

[MeterIcon2Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType##Special7Icon2CategoryRegularHexagonNo2##Special7Icon2RegularHexagonCode#Style
ImageName=#Special7Icon2RegularHexagonNo2#.png
ImageTint=[Desktop#Special7Icon2RegularHexagonCode#]
Container=MeterMask2
Hidden=#Special7Icon2RegularHexagonChameleonHidden#

[MeterIcon3Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType##Special7Icon2CategoryRegularHexagonNo3##Special7Icon2RegularHexagonCode#Style
ImageName=#Special7Icon2RegularHexagonNo3#.png
ImageTint=[Desktop#Special7Icon2RegularHexagonCode#]
Container=MeterMask3
Hidden=#Special7Icon2RegularHexagonChameleonHidden#

[MeterIcon4Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType##Special7Icon2CategoryRegularHexagonNo4##Special7Icon2RegularHexagonCode#Style
ImageName=#Special7Icon2RegularHexagonNo4#.png
ImageTint=[Desktop#Special7Icon2RegularHexagonCode#]
Container=MeterMask4
Hidden=#Special7Icon2RegularHexagonChameleonHidden#

[MeterIcon5Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType##Special7Icon2CategoryRegularHexagonNo5##Special7Icon2RegularHexagonCode#Style
ImageName=#Special7Icon2RegularHexagonNo5#.png
ImageTint=[Desktop#Special7Icon2RegularHexagonCode#]
Container=MeterMask5
Hidden=#Special7Icon2RegularHexagonChameleonHidden#

[MeterIcon6Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType##Special7Icon2CategoryRegularHexagonNo6##Special7Icon2RegularHexagonCode#Style
ImageName=#Special7Icon2RegularHexagonNo6#.png
ImageTint=[Desktop#Special7Icon2RegularHexagonCode#]
Container=MeterMask6
Hidden=#Special7Icon2RegularHexagonChameleonHidden#

[MeterIcon7Chameleon]
Meter=Image
MeterStyle=Special#Special7Icon2RegularHexagonColorType##Special7Icon2CategoryRegularHexagonNo7##Special7Icon2RegularHexagonCode#Style
ImageName=#Special7Icon2RegularHexagonNo7#.png
ImageTint=[Desktop#Special7Icon2RegularHexagonCode#]
Container=MeterMask7
Hidden=#Special7Icon2RegularHexagonChameleonHidden#

[MeterSetIcon1Text]
Meter=String
MeterStyle=SpecailSetIconText
X=750
Y=170
Text="Icon 1:"

[MeterSetIcon2Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 2:"

[MeterSetIcon3Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 3:"

[MeterSetIcon4Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 4:"

[MeterSetIcon5Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 5:"

[MeterSetIcon6Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 6:"

[MeterSetIcon7Text]
Meter=String
MeterStyle=SpecailSetIconText
X=0r
Y=15R
Text="Icon 7:"

[MeterSetIcon1Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=775
Y=[MeterSetIcon1Text:Y]
Text=#Special7Icon2RegularHexagonNo1#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Regular Hexagon\7 Icons\Icon #2" "Set Icon #1.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "1" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon1('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2RegularHexagonOver1()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon1('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2RegularHexagonLeave1()"]

[MeterSetIcon2Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon2RegularHexagonNo2#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Regular Hexagon\7 Icons\Icon #2" "Set Icon #2.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "2" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon2('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2RegularHexagonOver2()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon2('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2RegularHexagonLeave2()"]

[MeterSetIcon3Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon2RegularHexagonNo3#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Regular Hexagon\7 Icons\Icon #2" "Set Icon #3.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "3" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon3('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2RegularHexagonOver3()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon3('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2RegularHexagonLeave3()"]

[MeterSetIcon4Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon2RegularHexagonNo4#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Regular Hexagon\7 Icons\Icon #2" "Set Icon #4.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "4" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon4('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2RegularHexagonOver4()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon4('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2RegularHexagonLeave4()"]

[MeterSetIcon5Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon2RegularHexagonNo5#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Regular Hexagon\7 Icons\Icon #2" "Set Icon #5.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "5" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon5('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2RegularHexagonOver5()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon5('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2RegularHexagonLeave5()"]

[MeterSetIcon6Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon2RegularHexagonNo6#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Regular Hexagon\7 Icons\Icon #2" "Set Icon #6.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "6" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon6('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2RegularHexagonOver6()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon6('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2RegularHexagonLeave6()"]

[MeterSetIcon7Active]
Meter=String
MeterStyle=SpecailSetIconTextActive
X=0r
Y=15R
Text=#Special7Icon2RegularHexagonNo7#
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Context\Special\Set Icon\Regular Hexagon\7 Icons\Icon #2" "Set Icon #7.ini"][!WriteKeyValue Variables SpecSetIconShapeNum "7" "#@#Special Variables.inc"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialIcon7('Over')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2RegularHexagonOver7()"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialIcon7('Leave')"][!CommandMeasure LuaSpecial "setSpecialMask7Icon2RegularHexagonLeave7()"]

; ============================================================

[MeterColor]
Meter=String
MeterStyle=IconText
X=200
Y=460
Text=Color Tint

[MeterColorActive]
Meter=String
MeterStyle=IconActive
X=0r
Y=5R
Text=#Special7Icon2RegularHexagonBase#
LeftMouseUpAction=[!CommandMeasure LuaSpecial "setSpecial7Icon2RegularHexagonBase()"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialBase('Over')"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialBase('Leave')"]

[MeterChameleon]
Meter=String
MeterStyle=IconText
X=440
Y=460
Text=Chameleon Tint

[MeterChameleonActive]
Meter=String
MeterStyle=IconActive
X=0r
Y=5R
Text=#Special7Icon2RegularHexagonChameleonName#
LeftMouseUpAction=[!ToggleConfig "#ROOTCONFIG#\Context\Special\Chameleon\Regular Hexagon\7 Icons" "Icon #2.ini"]
MouseOverAction=[!CommandMeasure LuaSpecial "setSpecialChameleon('Over')"]
MouseLeaveAction=[!CommandMeasure LuaSpecial "setSpecialChameleon('Leave')"]

; ============================================================
; ============================================================

[MeterSkinSpecial7Icon2RegularHexagonBase]
Measure=Plugin
Plugin=InputText
StringAlign=Center
FontFace=Segoe UI
FontSize=15
X=132
Y=480
W=140
H=30
AntiAlias=1
FocusDismiss=1
Command1=[!WriteKeyValue Variables Special7Icon2RegularHexagonBase "$UserInput$" "#@#Special Variables.inc"][!RefreshGroup ShapeSettings]
DefaultValue="#Special7Icon2RegularHexagonBase#"
