[MeterPageAfterEffectsText]
Meter=String
MeterStyle=IconTextPageName
Group=AdobePage1
Text=After Effects
X=320
Y=100
MouseOverAction=[!SetOption MeterPageAfterEffectsText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageAfterEffectsText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextAdobe#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('After Effects')"]
Hidden=0

[MeterPageAnimateText]
Meter=String
MeterStyle=IconTextPageName
Group=AdobePage1
Text=Animate
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageAnimateText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageAnimateText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextAdobe#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Animate')"]
Hidden=0

[MeterPageAuditionText]
Meter=String
MeterStyle=IconTextPageName
Group=AdobePage1
Text=Audition
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageAuditionText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageAuditionText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextAdobe#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Audition')"]
Hidden=0

[MeterPageBridgeText]
Meter=String
MeterStyle=IconTextPageName
Group=AdobePage1
Text=Bridge
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageBridgeText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageBridgeText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextAdobe#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Bridge')"]
Hidden=0

[MeterPageCreativeCloudText]
Meter=String
MeterStyle=IconTextPageName
Group=AdobePage1
Text=Creative Cloud
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageCreativeCloudText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageCreativeCloudText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextAdobe#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Creative Cloud')"]
Hidden=0

[MeterPageDreamweaverText]
Meter=String
MeterStyle=IconTextPageName
Group=AdobePage1
Text=Dreamweaver
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageDreamweaverText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageDreamweaverText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextAdobe#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Dreamweaver')"]
Hidden=0

[MeterPageFramemakerText]
Meter=String
MeterStyle=IconTextPageName
Group=AdobePage1
Text=Framemaker
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageFramemakerText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageFramemakerText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextAdobe#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Framemaker')"]
Hidden=0

[MeterPageIllustratorText]
Meter=String
MeterStyle=IconTextPageName
Group=AdobePage1
Text=Illustrator
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageIllustratorText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageIllustratorText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextAdobe#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Illustrator')"]
Hidden=0

[MeterPageInDesignText]
Meter=String
MeterStyle=IconTextPageName
Group=AdobePage2
Text=InDesign
X=320
Y=100
MouseOverAction=[!SetOption MeterPageInDesignText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageInDesignText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextAdobe#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('InDesign')"]
Hidden=1

[MeterPageLightroomText]
Meter=String
MeterStyle=IconTextPageName
Group=AdobePage2
Text=Lightroom
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageLightroomText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageLightroomText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextAdobe#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Lightroom')"]
Hidden=1

[MeterPagePhotoshopText]
Meter=String
MeterStyle=IconTextPageName
Group=AdobePage2
Text=Photoshop
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPagePhotoshopText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPagePhotoshopText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextAdobe#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Photoshop')"]
Hidden=1

[MeterPagePremiereProText]
Meter=String
MeterStyle=IconTextPageName
Group=AdobePage2
Text=Premiere Pro
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPagePremiereProText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPagePremiereProText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextAdobe#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Premiere Pro')"]
Hidden=1

[MeterPageXDText]
Meter=String
MeterStyle=IconTextPageName
Group=AdobePage2
Text=XD
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageXDText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageXDText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextAdobe#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('XD')"]
Hidden=1

; ============================================================
; ============================================================

[MeterPage1Text]
Meter=String
MeterStyle=IconPageText
X=300
Y=500
Text=1
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextAdobePage1()"]
MouseOverAction=[!CommandMeasure LuaContext "setHoverContextAdobePage1('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverContextAdobePage1('Leave')"]

[MeterPage2Text]
Meter=String
MeterStyle=IconPageText
X=340
Y=0r
Text=2
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextAdobePage2()"]
MouseOverAction=[!CommandMeasure LuaContext "setHoverContextAdobePage2('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverContextAdobePage2('Leave')"]
