[MeterPageSafariText]
Meter=String
MeterStyle=IconTextPageName
Text=Apple Safari
X=320
Y=100
MouseOverAction=[!SetOption MeterPageSafariText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageSafariText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextBrowsing#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Safari')"]

[MeterPageBraveText]
Meter=String
MeterStyle=IconTextPageName
Text=Brave Browser
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageBraveText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageBraveText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextBrowsing#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Brave Browser')"]

[MeterPageChromeText]
Meter=String
MeterStyle=IconTextPageName
Text=Google Chrome
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageChromeText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageChromeText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextBrowsing#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Chrome')"]

[MeterPageEdgeText]
Meter=String
MeterStyle=IconTextPageName
Text=Microsoft Edge
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageEdgeText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageEdgeText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextBrowsing#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Microsoft Edge')"]

[MeterPageFirefoxText]
Meter=String
MeterStyle=IconTextPageName
Text=Mozilla Firefox
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageFirefoxText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageFirefoxText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextBrowsing#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Firefox')"]

[MeterPageOperaText]
Meter=String
MeterStyle=IconTextPageName
Text=Opera Browser
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageOperaText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageOperaText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextBrowsing#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Opera')"]

[MeterPageOperaGXText]
Meter=String
MeterStyle=IconTextPageName
Text=Opera GX
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageOperaGXText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageOperaGXText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextBrowsing#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Opera GX')"]

[MeterPageVivaldiText]
Meter=String
MeterStyle=IconTextPageName
Text=Vivaldi Browser
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageVivaldiText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageVivaldiText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextBrowsing#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Vivaldi Browser')"]
