[MeterSelectCategory]
Meter=String
MeterStyle=IconContext
Text="Select Category"
X=320
Y=80

[MeterSpecialPage1Active]
Meter=String
MeterStyle=IconCategoryContext
Text=Adobe
X=320
Y=25R
MouseOverAction=[!CommandMeasure LuaContext "setHoverSpecialCategoryPage1('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverSpecialCategoryPage1('Leave')"]
LeftMouseUpAction=[!CommandMeasure LuaContext "setSpecialCategory('Adobe')"]

[MeterSpecialPage2Active]
Meter=String
MeterStyle=IconCategoryContext
X=0r
Y=25R
Text=Browsing
MouseOverAction=[!CommandMeasure LuaContext "setHoverSpecialCategoryPage2('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverSpecialCategoryPage2('Leave')"]
LeftMouseUpAction=[!CommandMeasure LuaContext "setSpecialCategory('Browsing')"]

[MeterSpecialPage3Active]
Meter=String
MeterStyle=IconCategoryContext
X=0r
Y=25R
Text=Emulator
MouseOverAction=[!CommandMeasure LuaContext "setHoverSpecialCategoryPage3('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverSpecialCategoryPage3('Leave')"]
LeftMouseUpAction=[!CommandMeasure LuaContext "setSpecialCategory('Emulator')"]

[MeterSpecialPage4Active]
Meter=String
MeterStyle=IconCategoryContext
X=0r
Y=25R
Text=Gaming
MouseOverAction=[!CommandMeasure LuaContext "setHoverSpecialCategoryPage4('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverSpecialCategoryPage4('Leave')"]
LeftMouseUpAction=[!CommandMeasure LuaContext "setSpecialCategory('Gaming')"]

[MeterSpecialPage5Active]
Meter=String
MeterStyle=IconCategoryContext
X=0r
Y=25R
Text=Media
MouseOverAction=[!CommandMeasure LuaContext "setHoverSpecialCategoryPage5('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverSpecialCategoryPage5('Leave')"]
LeftMouseUpAction=[!CommandMeasure LuaContext "setSpecialCategory('Media')"]

[MeterSpecialPage6Active]
Meter=String
MeterStyle=IconCategoryContext
X=0r
Y=25R
Text=Office
MouseOverAction=[!CommandMeasure LuaContext "setHoverSpecialCategoryPage6('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverSpecialCategoryPage6('Leave')"]
LeftMouseUpAction=[!CommandMeasure LuaContext "setSpecialCategory('Office')"]

[MeterSpecialPage7Active]
Meter=String
MeterStyle=IconCategoryContext
X=0r
Y=25R
Text=Social
MouseOverAction=[!CommandMeasure LuaContext "setHoverSpecialCategoryPage7('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverSpecialCategoryPage7('Leave')"]
LeftMouseUpAction=[!CommandMeasure LuaContext "setSpecialCategory('Social')"]

[MeterSpecialPage8Active]
Meter=String
MeterStyle=IconCategoryContext
X=0r
Y=25R
Text=Other
MouseOverAction=[!CommandMeasure LuaContext "setHoverSpecialCategoryPage8('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverSpecialCategoryPage8('Leave')"]
LeftMouseUpAction=[!CommandMeasure LuaContext "setSpecialCategory('Other')"]
