[MeterPageGameLibrariesText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage1
Text=Game Libraries
X=320
Y=100
MouseOverAction=[!SetOption MeterPageGameLibrariesText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageGameLibrariesText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Game Libraries')"]
Hidden=0

[MeterPageAmongUsText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage1
Text=Among Us
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageAmongUsText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageAmongUsText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Among Us')"]
Hidden=0

[MeterPageApexText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage1
Text=Apex Legends
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageApexText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageApexText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Apex Legends')"]
Hidden=0

[MeterPageArkText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage1
Text=ARK: Survival Evolved
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageArkText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageArkText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Ark Survival Evolved')"]
Hidden=0

[MeterPageAssettoText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage1
Text=Assetto Corsa Competizione
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageAssettoText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageAssettoText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Assetto Corsa Competizione')"]
Hidden=0

[MeterPageBadlionText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage1
Text=Badlion Client
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageBadlionText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageBadlionText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Badlion Client')"]
Hidden=0

[MeterPageBattelNetText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage1
Text=Battle.net
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageBattelNetText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageBattelNetText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Battle Net')"]
Hidden=0

[MeterPageBF1Text]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage1
Text=Battlefield 1
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageBF1Text FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageBF1Text FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Battlefield 1')"]
Hidden=0

[MeterPageBF4Text]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage2
Text=Battlefield 4
X=320
Y=100
MouseOverAction=[!SetOption MeterPageBF4Text FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageBF4Text FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Battlefield 4')"]
Hidden=1

[MeterPageBF2042Text]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage2
Text=Battlefield 2042
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageBF2042Text FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageBF2042Text FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Battlefield 2042')"]
Hidden=1

[MeterPageBFVText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage2
Text=Battlefield V
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageBFVText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageBFVText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Battlefield V')"]
Hidden=1

[MeterPageBethesdaText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage2
Text=Bethesda Launcher
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageBethesdaText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageBethesdaText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Bethesda Launcher')"]
Hidden=1

[MeterPageBDOText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage2
Text=Black Desert Online
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageBDOText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageBDOText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Black Desert Online')"]
Hidden=1

[MeterPageBTD6Text]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage2
Text=Bloons TD6
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageBTD6Text FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageBTD6Text FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Bloons TD6')"]
Hidden=1

[MeterPageCODMWText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage2
Text=Call of Duty: Modern Warfare (2019)
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageCODMWText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageCODMWText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Call of Duty: Modern Warfare (2019)')"]
Hidden=1

[MeterPageCODVanguardText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage2
Text=Call of Duty: Vanguard
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageCODVanguardText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageCODVanguardText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Call of Duty: Vanguard')"]
Hidden=1

[MeterPageCloneHeroText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage3
Text=Clone Hero
X=320
Y=100
MouseOverAction=[!SetOption MeterPageCloneHeroText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageCloneHeroText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Clone Hero')"]
Hidden=1

[MeterPageCSGOText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage3
Text=Counter-Strike: Global Offensive
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageCSGOText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageCSGOText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('CSGO')"]
Hidden=1

[MeterPageCyberpunkText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage3
Text=Cyberpunk 2077
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageCyberpunkText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageCyberpunkText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Cyberpunk 2077')"]
Hidden=1

[MeterPageDauntlessText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage3
Text=Dauntless
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageDauntlessText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageDauntlessText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Dauntless')"]
Hidden=1

[MeterPageDBDText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage3
Text=Dead by Daylight
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageDBDText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageDBDText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Dead by Daylight')"]
Hidden=1

[MeterPageDestiny2Text]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage3
Text=Destiny 2
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageDestiny2Text FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageDestiny2Text FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Destiny 2')"]
Hidden=1

[MeterPageDOOMText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage3
Text=DOOM (2016)
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageDOOMText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageDOOMText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('DOOM (2016)')"]
Hidden=1

[MeterPageDOOMEternalText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage3
Text=DOOM: Eternal
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageDOOMEternalText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageDOOMEternalText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('DOOM: Eternal')"]
Hidden=1

[MeterPageDota2Text]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage4
Text=Dota 2
X=320
Y=100
MouseOverAction=[!SetOption MeterPageDota2Text FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageDota2Text FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Dota 2')"]
Hidden=1

[MeterPageOriginText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage4
Text=EA Origin
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageOriginText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageOriginText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Origin')"]
Hidden=1

[MeterPageESOText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage4
Text=Elder Scrolls Online
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageESOText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageESOText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Elder Scrolls Online')"]
Hidden=1

[MeterPageSkyrimText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage4
Text=Elder Scrolls V: Skyrim
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageSkyrimText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageSkyrimText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Elder Scrolls V: Skyrim')"]
Hidden=1

[MeterPageEGStoreText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage4
Text=Epic Games Store
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageEGStoreText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageEGStoreText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Epic Games Store')"]
Hidden=1

[MeterPageEFTText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage4
Text=Escape From Tarkov
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageEFTText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageEFTText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Escape From Tarkov')"]
Hidden=1

[MeterPageFallGuysText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage4
Text=Fall Guys
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageFallGuysText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageFallGuysText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Fall Guys')"]
Hidden=1

[MeterPageFactorioText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage4
Text=Factorio
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageFactorioText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageFactorioText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Factorio')"]
Hidden=1

[MeterPageFFXIVText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage5
Text=Final Fantasy XIV Online
X=320
Y=100
MouseOverAction=[!SetOption MeterPageFFXIVText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageFFXIVText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Final Fantasy XIV Online')"]
Hidden=1

[MeterPageFortniteText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage5
Text=Fortnite
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageFortniteText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageFortniteText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Fortnite')"]
Hidden=1

[MeterPageFH4Text]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage5
Text=Forza Horizon 4
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageFH4Text FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageFH4Text FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Forza Horizon 4')"]
Hidden=1

[MeterPageFH5Text]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage5
Text=Forza Horizon 5
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageFH5Text FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageFH5Text FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Forza Horizon 5')"]
Hidden=1

[MeterPageFNFText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage5
Text=Friday Night Funkin'
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageFNFText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageFNFText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Friday Night Funkin')"]
Hidden=1

[MeterPageGModText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage5
Text=Garry's Mod
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageGModText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageGModText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Garrys Mod')"]
Hidden=1

[MeterPageGenshinText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage5
Text=Genshin Impact
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageGenshinText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageGenshinText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Genshin Impact')"]
Hidden=1

[MeterPageGhostrunnerText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage5
Text=Ghostrunner
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageGhostrunnerText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageGhostrunnerText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Ghostrunner')"]
Hidden=1

[MeterPageGodfallText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage6
Text=Godfall
X=320
Y=100
MouseOverAction=[!SetOption MeterPageGodfallText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageGodfallText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Godfall')"]
Hidden=1

[MeterPageGOGText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage6
Text=GOG Galaxy
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageGOGText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageGOGText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('GOG Galaxy')"]
Hidden=1

[MeterPageGTAVText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage6
Text=Grand Theft Auto V
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageGTAVText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageGTAVText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Grand Theft Auto V')"]
Hidden=1

[MeterPageGW2Text]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage6
Text=Guild Wars 2
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageGW2Text FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageGW2Text FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Guild Wars 2')"]
Hidden=1

[MeterPageGuiltyGearText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage6
Text=Guilty Gear -Strive-
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageGuiltyGearText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageGuiltyGearText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Guilty Gear Strive')"]
Hidden=1

[MeterPageHearthstoneText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage6
Text=Hearthstone
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageHearthstoneText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageHearthstoneText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Hearthstone')"]
Hidden=1

[MeterPageHOI4Text]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage6
Text=Hearts of Iron IV
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageHOI4Text FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageHOI4Text FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Hearts of Iron IV')"]
Hidden=1

[MeterPageHOTSText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage6
Text=Heroes of the Storm
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageHOTSText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageHOTSText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Heroes of the Storm')"]
Hidden=1

[MeterPageHonkaiText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage7
Text=Honkai Impact 3rd
X=320
Y=100
MouseOverAction=[!SetOption MeterPageHonkaiText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageHonkaiText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Honkai Impact 3rd')"]
Hidden=1

[MeterPageHuntShowdownText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage7
Text=Hunt: Showdown
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageHuntShowdownText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageHuntShowdownText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Hunt: Showdown')"]
Hidden=1

[MeterPageLoLText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage7
Text=League of Legends
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageLoLText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageLoLText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('League of Legends')"]
Hidden=1

[MeterPageLORText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage7
Text=Legends of Runeterra
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageLORText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageLORText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Legends of Runeterra')"]
Hidden=1

[MeterPageLunarText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage7
Text=Lunar Client
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageLunarText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageLunarText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Lunar Client')"]
Hidden=1

[MeterPageMinecraftText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage7
Text=Minecraft
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageMinecraftText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageMinecraftText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Minecraft')"]
Hidden=1

[MeterPageMHWorldText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage7
Text=Monster Hunter: World
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageMHWorldText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageMHWorldText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Monster Hunter: World')"]
Hidden=1

[MeterPageNarakaText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage7
Text=Naraka: Bladepoint
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageNarakaText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageNarakaText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Naraka: Bladepoint')"]
Hidden=1

[MeterPageNierAutomataText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage8
Text=NieR:Automata
X=320
Y=100
MouseOverAction=[!SetOption MeterPageNierAutomataText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageNierAutomataText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Nier Automata')"]
Hidden=1

[MeterPageNMSText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage8
Text=No Man's Sky
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageNMSText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageNMSText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('No Mans Sky')"]
Hidden=1

[MeterPageOriBFText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage8
Text=Ori and the Blind Forest
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageOriBFText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageOriBFText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Ori and the Blind Forest')"]
Hidden=1

[MeterPageOriWWText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage8
Text=Ori and the Will of the Wisp
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageOriWWText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageOriWWText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Ori and the Will of the Wisp')"]
Hidden=1

[MeterPageOsuText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage8
Text=Osu!
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageOsuText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageOsuText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Osu')"]
Hidden=1

[MeterPageOutridersText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage8
Text=Outriders
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageOutridersText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageOutridersText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Outriders')"]
Hidden=1

[MeterPageOverwatchText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage8
Text=Overwatch
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageOverwatchText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageOverwatchText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Overwatch')"]
Hidden=1

[MeterPagePaladinsText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage8
Text=Paladins
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPagePaladinsText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPagePaladinsText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Paladins')"]
Hidden=1

[MeterPagePOEText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage9
Text=Path of Exile
X=320
Y=100
MouseOverAction=[!SetOption MeterPagePOEText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPagePOEText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Path of Exile')"]
Hidden=1

[MeterPagePUBGText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage9
Text=PlayerUnknown's Battlegrounds
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPagePUBGText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPagePUBGText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('PlayerUnknowns Battlegrounds')"]
Hidden=1

[MeterPageRSSiegeText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage9
Text=Rainbow Six Siege
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageRSSiegeText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageRSSiegeText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Rainbow Six Siege')"]
Hidden=1

[MeterPageRecRoomText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage9
Text=Rec Room
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageRecRoomText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageRecRoomText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Rec Room')"]
Hidden=1

[MeterPageRiotText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage9
Text=Riot Client
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageRiotText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageRiotText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Riot Client')"]
Hidden=1

[MeterPageRobloxText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage9
Text=Roblox
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageRobloxText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageRobloxText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Roblox')"]
Hidden=1

[MeterPageRobloxStudioText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage9
Text=Roblox Studio
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageRobloxStudioText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageRobloxStudioText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Roblox Studio')"]
Hidden=1

[MeterPageRocketLeagueText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage9
Text=Rocket League
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageRocketLeagueText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageRocketLeagueText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Rocket League')"]
Hidden=1

[MeterPageRockstarText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage10
Text=Rockstar Games Launcher
X=320
Y=100
MouseOverAction=[!SetOption MeterPageRockstarText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageRockstarText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Rockstar Games Launcher')"]
Hidden=1

[MeterPageRSIText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage10
Text=RSI Launcher
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageRSIText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageRSIText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('RSI Launcher')"]
Hidden=1

[MeterPageRuneScapeText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage10
Text=RuneScape
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageRuneScapeText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageRuneScapeText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('RuneScape')"]
Hidden=1

[MeterPageRustText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage10
Text=Rust
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageRustText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageRustText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Rust')"]
Hidden=1

[MeterPageSatisfactoryText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage10
Text=Satisfactory
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageSatisfactoryText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageSatisfactoryText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Satisfactory')"]
Hidden=1

[MeterPageSoTText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage10
Text=Sea of Thieves
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageSoTText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageSoTText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Sea of Thieves')"]
Hidden=1

[MeterPageStSText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage10
Text=Slay the Spire
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageStSText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageStSText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Slay the Spire')"]
Hidden=1

[MeterPageSmiteText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage10
Text=Smite
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageSmiteText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageSmiteText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Smite')"]
Hidden=1

[MeterPageStarCitizenText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage11
Text=Star Citizen
X=320
Y=100
MouseOverAction=[!SetOption MeterPageStarCitizenText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageStarCitizenText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Star Citizen')"]
Hidden=1

[MeterPageSteamText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage11
Text=Steam
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageSteamText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageSteamText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Steam')"]
Hidden=1

[MeterPageTF2Text]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage11
Text=Team Fortress 2
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageTF2Text FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageTF2Text FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Team Fortress 2')"]
Hidden=1

[MeterPageTW3Text]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage11
Text=The Witcher 3: Wild Hunt
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageTW3Text FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageTW3Text FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('The Witcher 3: Wild Hunt')"]
Hidden=1

[MeterPageUbisoftText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage11
Text=Ubisoft Connect
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageUbisoftText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageUbisoftText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Ubisoft Connect')"]
Hidden=1

[MeterPageValorantText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage11
Text=Valorant
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageValorantText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageValorantText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Valorant')"]
Hidden=1

[MeterPageVortexText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage11
Text=Vortex
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageVortexText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageVortexText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Vortex')"]
Hidden=1

[MeterPageWarThunderText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage11
Text=War Thunder
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageWarThunderText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageWarThunderText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('War Thunder')"]
Hidden=1

[MeterPageWarframeText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage12
Text=Warframe
X=320
Y=100
MouseOverAction=[!SetOption MeterPageWarframeText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageWarframeText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Warframe')"]
Hidden=1

[MeterPageWOTanksText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage12
Text=World of Tanks
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageWOTanksText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageWOTanksText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('World of Tanks')"]
Hidden=1

[MeterPageWOWText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage12
Text=World of Warcraft
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageWOWText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageWOWText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('World of Warcraft')"]
Hidden=1

[MeterPageWOWarshipsText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage12
Text=World of Warships
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageWOWarshipsText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageWOWarshipsText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('World of Warships')"]
Hidden=1

[MeterPageXboxText]
Meter=String
MeterStyle=IconTextPageName
Group=GamingPage12
Text=Xbox
X=0r
Y=25R
MouseOverAction=[!SetOption MeterPageXboxText FontColor "255,215,0"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption MeterPageXboxText FontColor "255,255,255"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGaming#SpecNumShape#Icon#SpecIconNum##SpecNameShape#No#SpecSetIconShapeNum#('Xbox')"]
Hidden=1

; ============================================================
; ============================================================

[MeterPage1Text]
Meter=String
MeterStyle=IconPageText
X=100
Y=500
Text=1
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGamingPage1()"]
MouseOverAction=[!CommandMeasure LuaContext "setHoverContextGamingPage1('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverContextGamingPage1('Leave')"]

[MeterPage2Text]
Meter=String
MeterStyle=IconPageText
X=40r
Y=0r
Text=2
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGamingPage2()"]
MouseOverAction=[!CommandMeasure LuaContext "setHoverContextGamingPage2('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverContextGamingPage2('Leave')"]

[MeterPage3Text]
Meter=String
MeterStyle=IconPageText
X=40r
Y=0r
Text=3
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGamingPage3()"]
MouseOverAction=[!CommandMeasure LuaContext "setHoverContextGamingPage3('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverContextGamingPage3('Leave')"]

[MeterPage4Text]
Meter=String
MeterStyle=IconPageText
X=40r
Y=0r
Text=4
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGamingPage4()"]
MouseOverAction=[!CommandMeasure LuaContext "setHoverContextGamingPage4('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverContextGamingPage4('Leave')"]

[MeterPage5Text]
Meter=String
MeterStyle=IconPageText
X=40r
Y=0r
Text=5
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGamingPage5()"]
MouseOverAction=[!CommandMeasure LuaContext "setHoverContextGamingPage5('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverContextGamingPage5('Leave')"]

[MeterPage6Text]
Meter=String
MeterStyle=IconPageText
X=40r
Y=0r
Text=6
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGamingPage6()"]
MouseOverAction=[!CommandMeasure LuaContext "setHoverContextGamingPage6('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverContextGamingPage6('Leave')"]

[MeterPage7Text]
Meter=String
MeterStyle=IconPageText
X=40r
Y=0r
Text=7
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGamingPage7()"]
MouseOverAction=[!CommandMeasure LuaContext "setHoverContextGamingPage7('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverContextGamingPage7('Leave')"]

[MeterPage8Text]
Meter=String
MeterStyle=IconPageText
X=40r
Y=0r
Text=8
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGamingPage8()"]
MouseOverAction=[!CommandMeasure LuaContext "setHoverContextGamingPage8('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverContextGamingPage8('Leave')"]

[MeterPage9Text]
Meter=String
MeterStyle=IconPageText
X=40r
Y=0r
Text=9
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGamingPage9()"]
MouseOverAction=[!CommandMeasure LuaContext "setHoverContextGamingPage9('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverContextGamingPage9('Leave')"]

[MeterPage10Text]
Meter=String
MeterStyle=IconPageText
X=40r
Y=0r
Text=10
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGamingPage10()"]
MouseOverAction=[!CommandMeasure LuaContext "setHoverContextGamingPage10('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverContextGamingPage10('Leave')"]

[MeterPage11Text]
Meter=String
MeterStyle=IconPageText
X=40r
Y=0r
Text=11
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGamingPage11()"]
MouseOverAction=[!CommandMeasure LuaContext "setHoverContextGamingPage11('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverContextGamingPage11('Leave')"]

[MeterPage12Text]
Meter=String
MeterStyle=IconPageText
X=40r
Y=0r
Text=12
LeftMouseUpAction=[!CommandMeasure LuaContext "setContextGamingPage12()"]
MouseOverAction=[!CommandMeasure LuaContext "setHoverContextGamingPage12('Over')"]
MouseLeaveAction=[!CommandMeasure LuaContext "setHoverContextGamingPage12('Leave')"]
